In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_columns', 500)

In [2]:
dir_folder_path = r"..\..\[IN USE] Rookie Directors\[1] Director Level\director_wrangle_output"
import_folder_path = "car_output2"
output_folder_path = "car_output3"
supporting_folder_path = "supporting_datafiles"

## Data Reading

### Company Keys

In [3]:
# companyKeys = pd.read_excel("Prowess IQ - Indicators.xlsx").rename({"Company Name":"CompanyName", "Prowess company code":"ProwessCode", "NSE symbol":"Symbol"}, axis = 1 )

In [4]:
# companyKeys

### Director Level Data

In [5]:
dirLevel = pd.read_pickle(rf"{dir_folder_path}\Main_Director_COMPLETE.pkl").rename({"Company Name":"CompanyName"}, axis = 1)

In [6]:
dirLevel

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence
0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN
2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,NaN,<NA>,<NA>,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,NaT,U,1988-03-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,7672.0,0.0,0.0,7307.0,0.0,0.0,7307.0,7672.0,0.0,0.0,7672.0,7307.0,0.0,0.0,7307.0,7672.0,0.0,0.0,7672.0,7667,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,79,0.000000,21.019178,21.005479,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...",POST GRADUATE: M.SC.-CHEMISTRY,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'operations', 'legal/...",1,1,<NA>,11,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,False,False,True,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254835,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00114429,MR.,JITENDRA,KUMAR,PAL,1971-07-08,M,INDIA,NONE,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...","GRADUATE: LL.B.,UTKAL UNIVERSITY,BHUBANESWAR",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,U,2012-09-30,2018-03-31,2017-03-31,NaT,1,0.0,0.0,2.0,0,0.0,0.0,0.0,365.0,0.0,0.0,1643.0,0.0,0.0,1643.0,2008.0,0.0,0.0,2008.0,3165.0,0.0,0.0,3165.0,3530.0,0.0,0.0,3530.0,3528,"((ZYLOG, U),)","{(ZYLOG, U)}","{(ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,54,0.000000,9.671233,9.665753,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
254836,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00080494,MS.,KAMALA,NaN,R.,NaT,F,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2016-11-23,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,128.0,0.0,128.0,0.0,493.0,0.0,493.0,0.0,128.0,0.0,128.0,0.0,493.0,0.0,493.0,493,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y), (ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,<NA>,1.350685,1.350685,1.350685,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

In [7]:
dirDate = dirLevel.reset_index().melt(id_vars = "index", value_vars = [
    "Appointment Date", "Cessation Date", "Date of Demise"], var_name = "date_source",
                                       value_name = "Date of Study").dropna(subset = "Date of Study")
dirLevel2 = dirLevel.reset_index().merge(dirDate, on = ["index"])

In [8]:
dirLevel2

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{fast moving consumer goods, marketing, leader...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{11011, 62013}","{11011, 62013}","{11011, 62013}","{11011, 62013}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25

## 120 CAR

In [9]:
output120CAR = pd.read_pickle(rf"{import_folder_path}\output120CAR_2.pkl")

In [10]:
output120CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS120_intercept', 'OLS120_RMRF',
       'OLS120_SMB', 'OLS120_HML', 'OLS120_r_squared',
       'OLS120_adjusted_r_squared', 'OLS120_f_p_value', 'pct_cen3sum',
       'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum', 'HML_cen3sum',
       'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum', 'SMB_cen5sum',
       'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum', 'RMRF_cen7sum',
       'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum', 'RF_cen11sum',
       'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum', '120CAR3', '120CAR5',
       '120CAR7', '120CAR11'],
      dtype='object')

In [11]:
colDrop = output120CAR.columns[[2, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                      28, 29, 30, 31, 32, 33, 34, 35, 36, 37]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum',
       'HML_cen3sum', 'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum',
       'SMB_cen5sum', 'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum',
       'RF_cen11sum', 'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum'],
      dtype='object')

In [12]:
output120CAR2 = output120CAR.drop(labels = colDrop, axis = 1)
output120CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11
0,20 Microns Ltd.,11.0,2009-07-29,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.017647,0.005552,0.012183,0.009481,0.149680,0.127689,0.000288,-0.040906,0.031116,0.005558,-0.005077
1,20 Microns Ltd.,11.0,2009-07-30,12.50,-0.007937,0.008824,0.606603,0.615428,-0.050968,0.076723,-0.016498,0.005772,0.013185,0.009805,0.170255,0.148796,0.000074,0.030317,-0.040692,0.029223,-0.042542
2,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.013787,0.004889,0.011979,0.005721,0.127494,0.104929,0.001196,-0.046090,0.001445,0.049908,0.187838
3,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027096,0.010449,0.015732,-0.002440,0.176213,0.154908,0.000049,0.163401,0.074130,0.027549,-0.095063
4,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.035800,0.010683,0.006169,0.001164,0.121640,0.098924,0.001726,0.020884,-0.055292,-0.141493,-0.282114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34561,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034650,0.004784,-0.007787,0.006894,0.045213,0.020521,0.145370,-0.106933,-0.262065,-0.339525,-0.419573
34562,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.025512,-0.001175,-0.000664,0.005110,0.016047,-0.009400,0.596696,0.094435,0.004753,-0.060387,-0.194113
34563,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.028918,-0.000405,-0.002380,0.003763,0.013945,-0.011556,0.651255,-0.085160,-0.136289,-0.150080,-0.288341
34564,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.028118,0.000909,-0.002034,0.008051,0.057325,0.032945,0.075918,0.009463,-0.119328,-0.207848,-0.081765
34565,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.021431,0.005628,0.003575,0.002313,0.020592,-0.004738,0.489197,0.048258,0.039317,-0.017125,-0.127470

In [13]:
dir120CAR = dirLevel2.merge(output120CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [14]:
dir120CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{fast moving consumer goods, marketing, leader...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{11011, 62013}","{11011, 62013}","{11011, 62013}","{11011, 62013}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
dir120CAR.to_pickle(rf"{output_folder_path}\dir120CAR_2.pkl")

In [16]:
del output120CAR
del output120CAR2
del dir120CAR

## 150 CAR

In [17]:
output150CAR = pd.read_pickle(rf"{import_folder_path}\output150CAR_2.pkl")

In [18]:
output150CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS150_intercept', 'OLS150_RMRF',
       'OLS150_SMB', 'OLS150_HML', 'OLS150_r_squared',
       'OLS150_adjusted_r_squared', 'OLS150_f_p_value', 'pct_cen3sum',
       'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum', 'HML_cen3sum',
       'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum', 'SMB_cen5sum',
       'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum', 'RMRF_cen7sum',
       'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum', 'RF_cen11sum',
       'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum', '150CAR3', '150CAR5',
       '150CAR7', '150CAR11'],
      dtype='object')

In [19]:
colDrop = output150CAR.columns[[2, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                      28, 29, 30, 31, 32, 33, 34, 35, 36, 37]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum',
       'HML_cen3sum', 'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum',
       'SMB_cen5sum', 'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum',
       'RF_cen11sum', 'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum'],
      dtype='object')

In [20]:
output150CAR2 = output150CAR.drop(labels = colDrop, axis = 1)
output150CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11
0,20 Microns Ltd.,11.0,2009-07-29,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.018884,0.007822,0.012183,0.011318,0.181844,0.165033,0.000002,-0.036358,0.032253,-0.004294,-0.021468
1,20 Microns Ltd.,11.0,2009-07-30,12.50,-0.007937,0.008824,0.606603,0.615428,-0.050968,0.076723,-0.017772,0.007442,0.011800,0.008235,0.158646,0.141357,0.000013,0.032478,-0.039550,0.034055,-0.036511
2,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.017060,0.006434,0.011588,0.008780,0.163067,0.145870,0.000009,-0.042477,0.002045,0.054302,0.191216
3,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.025992,0.008764,0.012305,0.002310,0.158002,0.140700,0.000014,0.148246,0.060988,0.009841,-0.110733
4,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.035619,0.008433,0.006457,0.001327,0.084912,0.066109,0.004638,0.019308,-0.057342,-0.145741,-0.284504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34393,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034041,0.006057,-0.003198,0.008756,0.079905,0.060999,0.006729,-0.108517,-0.259477,-0.335944,-0.410390
34394,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.027929,0.000399,0.000096,0.003071,0.007924,-0.012461,0.761294,0.102376,0.012937,-0.049250,-0.189788
34395,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.025870,-0.001230,-0.001257,0.006396,0.025822,0.005804,0.280130,-0.092785,-0.145167,-0.157975,-0.298391
34396,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.029026,0.001455,-0.002229,0.005384,0.035742,0.015929,0.149041,0.020077,-0.111642,-0.202270,-0.076821
34397,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.022639,0.005990,0.001212,0.004337,0.029050,0.009099,0.229036,0.052862,0.040714,-0.012842,-0.122747

In [21]:
dir150CAR = dirLevel2.merge(output150CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [22]:
dir150CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{fast moving consumer goods, marketing, leader...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{11011, 62013}","{11011, 62013}","{11011, 62013}","{11011, 62013}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
dir150CAR.to_pickle(rf"{output_folder_path}\dir150CAR_2.pkl")

In [24]:
del output150CAR
del output150CAR2
del dir150CAR

## 180 CAR

In [25]:
output180CAR = pd.read_pickle(rf"{import_folder_path}\output180CAR_2.pkl")

In [26]:
output180CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS180_intercept', 'OLS180_RMRF',
       'OLS180_SMB', 'OLS180_HML', 'OLS180_r_squared',
       'OLS180_adjusted_r_squared', 'OLS180_f_p_value', 'pct_cen3sum',
       'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum', 'HML_cen3sum',
       'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum', 'SMB_cen5sum',
       'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum', 'RMRF_cen7sum',
       'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum', 'RF_cen11sum',
       'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum', '180CAR3', '180CAR5',
       '180CAR7', '180CAR11'],
      dtype='object')

In [27]:
colDrop = output180CAR.columns[[2, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                      28, 29, 30, 31, 32, 33, 34, 35, 36, 37]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum',
       'HML_cen3sum', 'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum',
       'SMB_cen5sum', 'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum',
       'RF_cen11sum', 'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum'],
      dtype='object')

In [28]:
output180CAR2 = output180CAR.drop(labels = colDrop, axis = 1)
output180CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.019523,0.008528,0.010563,0.007012,0.162659,0.148386,7.238692e-07,-0.035395,0.013419,0.061457,0.192774
1,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.023910,0.008059,0.012570,0.004786,0.128802,0.113952,2.125338e-05,0.139034,0.052771,0.000425,-0.119776
2,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.035592,0.008052,0.006294,0.002610,0.076637,0.060898,2.808170e-03,0.018383,-0.057725,-0.144865,-0.280436
3,20 Microns Ltd.,11.0,2015-02-05,38.50,-0.020356,0.021755,-0.625772,-0.604017,0.012769,-1.213916,-0.035151,0.007464,0.003937,-0.002033,0.042711,0.026393,5.254045e-02,0.058303,-0.048021,-0.137637,-0.297664
4,20 Microns Ltd.,11.0,2017-05-04,43.70,0.016279,0.016554,0.046274,0.062828,0.831535,-0.581499,-0.023958,0.016109,0.010135,0.001335,0.219310,0.206003,1.752317e-09,0.001120,-0.132678,-0.183787,-0.283439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34082,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.033714,0.005668,-0.003566,0.012798,0.106314,0.091081,1.833697e-04,-0.108131,-0.253083,-0.327043,-0.398804
34083,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.029250,0.003714,-0.001238,0.002913,0.026072,0.009471,1.982265e-01,0.096045,0.004526,-0.054684,-0.186557
34084,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.027848,0.000326,-0.000422,0.004325,0.014731,-0.002063,4.541101e-01,-0.084829,-0.134955,-0.150529,-0.291787
34085,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.030886,0.002208,-0.003777,0.004163,0.031962,0.015461,1.253331e-01,0.028403,-0.105864,-0.197091,-0.072749
34086,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.023642,0.003510,0.003016,0.005124,0.022382,0.005718,2.619858e-01,0.058100,0.046779,-0.009005,-0.117912

In [29]:
dir180CAR = dirLevel2.merge(output180CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [30]:
dir180CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{fast moving consumer goods, marketing, leader...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{11011, 62013}","{11011, 62013}","{11011, 62013}","{11011, 62013}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
dir180CAR.to_pickle(rf"{output_folder_path}\dir180CAR_2.pkl")

In [32]:
del output180CAR
del output180CAR2
del dir180CAR

## 210 CAR

In [33]:
output210CAR = pd.read_pickle(rf"{import_folder_path}\output210CAR_2.pkl")

In [40]:
output210CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS210_intercept', 'OLS210_RMRF',
       'OLS210_SMB', 'OLS210_HML', 'OLS210_r_squared',
       'OLS210_adjusted_r_squared', 'OLS210_f_p_value', 'pct_cen3sum',
       'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum', 'HML_cen3sum',
       'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum', 'SMB_cen5sum',
       'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum', 'RMRF_cen7sum',
       'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum', 'RF_cen11sum',
       'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum', '210CAR3', '210CAR5',
       '210CAR7', '210CAR11'],
      dtype='object')

In [35]:
colDrop = output210CAR.columns[[2, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                      28, 29, 30, 31, 32, 33, 34, 35, 36, 37]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'SMB_cen3sum',
       'HML_cen3sum', 'pct_cen5sum', 'RF_cen5sum', 'RMRF_cen5sum',
       'SMB_cen5sum', 'HML_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'SMB_cen7sum', 'HML_cen7sum', 'pct_cen11sum',
       'RF_cen11sum', 'RMRF_cen11sum', 'SMB_cen11sum', 'HML_cen11sum'],
      dtype='object')

In [36]:
output210CAR2 = output210CAR.drop(labels = colDrop, axis = 1)
output210CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.022830,0.009052,0.012831,0.002836,0.131758,0.119114,2.058205e-06,0.139681,0.053503,0.002506,-0.117960
1,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.036365,0.006364,0.006151,0.003198,0.065439,0.051829,2.939000e-03,0.020019,-0.056337,-0.144163,-0.277777
2,20 Microns Ltd.,11.0,2015-02-05,38.50,-0.020356,0.021755,-0.625772,-0.604017,0.012769,-1.213916,-0.035407,0.007727,0.003104,-0.001389,0.044002,0.030080,2.564648e-02,0.058810,-0.046110,-0.134653,-0.297360
3,20 Microns Ltd.,11.0,2017-05-04,43.70,0.016279,0.016554,0.046274,0.062828,0.831535,-0.581499,-0.024819,0.014223,0.010697,0.003037,0.206107,0.194546,2.516556e-10,0.005364,-0.128143,-0.181674,-0.279592
4,20 Microns Ltd.,11.0,2019-05-28,41.00,-0.016787,0.016873,0.367905,0.384778,-0.177790,0.292518,-0.024276,0.015716,0.012604,0.001488,0.334962,0.325277,3.803786e-18,0.018415,0.009655,-0.017933,-0.122470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33898,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034644,0.006125,0.000900,0.012578,0.116788,0.103926,1.131949e-05,-0.105282,-0.250236,-0.324769,-0.395281
33899,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.028389,0.004898,0.001269,0.005712,0.051949,0.038142,1.164031e-02,0.085732,-0.012006,-0.082900,-0.204769
33900,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.029012,0.003331,-0.001272,0.004015,0.031630,0.017528,8.440892e-02,-0.083260,-0.129692,-0.144996,-0.288929
33901,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.027645,0.001205,-0.002831,0.004653,0.025289,0.011094,1.518053e-01,0.018937,-0.114226,-0.204689,-0.079244
33902,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.025254,0.004525,0.001875,0.003494,0.019630,0.005353,2.514974e-01,0.060207,0.049020,-0.007970,-0.114533

In [37]:
dir210CAR = dirLevel2.merge(output210CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [38]:
dir210CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, leadership/management, operations,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{29, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, marketing, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{marketing, operations, legal/compliance, acco...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{financial services, marketing, operations, fi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{fast moving consumer goods, marketing, leader...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{11011, 62013}","{11011, 62013}","{11011, 62013}","{11011, 62013}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
dir210CAR.to_pickle(rf"{output_folder_path}\dir210CAR_2.pkl")