In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_columns', 500)

In [2]:
dir_folder_path = r"..\..\[IN USE] Rookie Directors\[1] Director Level\director_wrangle_output"
import_folder_path = "car_output2"
output_folder_path = "car_output3"
supporting_folder_path = "supporting_datafiles"

## Data Reading

### Company Keys

In [3]:
# companyKeys = pd.read_excel("Prowess IQ - Indicators.xlsx").rename({"Company Name":"CompanyName", "Prowess company code":"ProwessCode", "NSE symbol":"Symbol"}, axis = 1 )

In [4]:
# companyKeys

### Director Level Data

In [5]:
dirLevel = pd.read_pickle(rf"{dir_folder_path}\Main_Director_COMPLETE.pkl").rename({"Company Name":"CompanyName"}, axis = 1)

In [6]:
dirLevel

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence
0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(BANCOINDIA, U), (20MICRONS, U), (MUNJALAU, U)}","{(BANCOINDIA, U), (20MICRONS, U), (MUNJALAU, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{human resources, information technology, fina...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN
2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{information technology, finance, marketing, c...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, services, financial servi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,NaN,<NA>,<NA>,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,NaT,U,1988-03-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,7672.0,0.0,0.0,7307.0,0.0,0.0,7307.0,7672.0,0.0,0.0,7672.0,7307.0,0.0,0.0,7307.0,7672.0,0.0,0.0,7672.0,7667,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,79,0.000000,21.019178,21.005479,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{information technology, finance, marketing, c...",POST GRADUATE: M.SC.-CHEMISTRY,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'operations', 'legal/...",1,1,<NA>,11,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,False,False,True,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254835,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00114429,MR.,JITENDRA,KUMAR,PAL,1971-07-08,M,INDIA,NONE,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...","GRADUATE: LL.B.,UTKAL UNIVERSITY,BHUBANESWAR",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,U,2012-09-30,2018-03-31,2017-03-31,NaT,1,0.0,0.0,2.0,0,0.0,0.0,0.0,365.0,0.0,0.0,1643.0,0.0,0.0,1643.0,2008.0,0.0,0.0,2008.0,3165.0,0.0,0.0,3165.0,3530.0,0.0,0.0,3530.0,3528,"((ZYLOG, U),)","{(ZYLOG, U)}","{(ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,54,0.000000,9.671233,9.665753,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
254836,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00080494,MS.,KAMALA,NaN,R.,NaT,F,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2016-11-23,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,128.0,0.0,128.0,0.0,493.0,0.0,493.0,0.0,128.0,0.0,128.0,0.0,493.0,0.0,493.0,493,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y), (ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,<NA>,1.350685,1.350685,1.350685,1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

In [7]:
dirDate = dirLevel.reset_index().melt(id_vars = "index", value_vars = [
    "Appointment Date", "Cessation Date", "Date of Demise"], var_name = "date_source",
                                       value_name = "Date of Study").dropna(subset = "Date of Study")
dirLevel2 = dirLevel.reset_index().merge(dirDate, on = ["index"])

In [8]:
dirLevel2

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(BANCOINDIA, U), (20MICRONS, U), (MUNJALAU, U)}","{(BANCOINDIA, U), (20MICRONS, U), (MUNJALAU, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{human resources, information technology, fina...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, operations}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{information technology, finance, marketing, c...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, services, financial servi...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(ZYLOG, Y), (RKDL, Y), (RKDL, U)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{human resources, information technology, fina...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{62013, 11011}","{62013, 11011}","{62013, 11011}","{62013, 11011}","{11, 62}","{11, 62}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25

## 120 CAR

In [9]:
output120CAR = pd.read_pickle(rf"{import_folder_path}\output120CAR_2.pkl")

In [10]:
output120CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS120_intercept', 'OLS120_RMRF',
       'OLS120_r_squared', 'OLS120_adjusted_r_squared', 'OLS120_f_p_value',
       'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum',
       '120CAR3', '120CAR5', '120CAR7', '120CAR11'],
      dtype='object')

In [11]:
colDrop = output120CAR.columns[[2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum'],
      dtype='object')

In [12]:
output120CAR2 = output120CAR.drop(labels = colDrop, axis = 1)
output120CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11
0,20 Microns Ltd.,11.0,2009-07-29,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.016130,0.003310,0.028601,0.020369,0.064814,-0.034268,0.044935,0.047310,0.078687
1,20 Microns Ltd.,11.0,2009-07-30,12.50,-0.007937,0.008824,0.606603,0.615428,-0.050968,0.076723,-0.015122,0.003345,0.029881,0.021660,0.059023,0.018321,-0.028993,0.070992,0.040831
2,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.012672,0.002374,0.016580,0.008245,0.161037,-0.014266,0.064480,0.116737,0.257054
3,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027709,0.010815,0.109751,0.102207,0.000219,0.142262,0.059733,0.003581,-0.112165
4,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.034611,0.011129,0.088050,0.080322,0.000998,0.025785,-0.053622,-0.132788,-0.287699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34561,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034858,0.007051,0.027495,0.019253,0.070302,-0.108911,-0.272803,-0.354960,-0.434712
34562,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.025075,0.002161,0.002523,-0.005930,0.585868,0.095600,0.008034,-0.047072,-0.196916
34563,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.028892,0.001915,0.002487,-0.005967,0.588591,-0.079827,-0.127416,-0.147103,-0.286999
34564,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.028364,0.006545,0.020030,0.011725,0.123099,0.025903,-0.107993,-0.208582,-0.086900
34565,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.021262,0.007799,0.018200,0.009880,0.141807,0.042647,0.032314,-0.025294,-0.130340

In [15]:
dir120CAR = dirLevel2.merge(output120CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [17]:
dir120CAR.loc[ ~pd.isnull(dir120CAR["RF"])]

,index,Symbol_x,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,Symbol_y,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,pct_cen3sum,RF_cen3sum,RMRF_cen3sum,pct_cen5sum,RF_cen5sum,RMRF_cen5sum,pct_cen7sum,RF_cen7sum,RMRF_cen7sum,pct_cen11sum,RF_cen11sum,RMRF_cen11sum,120CAR3,120CAR5,120CAR7,120CAR11
19,18,20MICRONS,20 MICRONS LTD.,2010-03-31,2010,INE144J01027,P00031581,MR.,ATUL,HARI,PATEL,1950-12-20,M,INDIA,NONE,NaN,<NA>,<NA>,"GRADUATE: B.E.-TEXTILE,VEERMATA JIJABAI TECHNO...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,COMMODITIES,CORPORATE ...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. ATUL H. PATEL JOINED THE INDUSTRY AFTER OB...,NaT,NaT,U,2009-08-27,NaT,NaT,2011-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,216.0,0.0,0.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,216.0,0.0,0.0,0.0,0.0,216.0,0.0,0.0,216.0,216,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,74,0.000000,0.591781,0.591781,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{information technology, finance, marketing, c...","GRADUATE: B.E.-TEXTILE,VEERMATA JIJABAI TECHNO...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{operations},"{'corporate governance', 'operations', 'legal/...",1,1,<NA>,15,0,0,0,1,0,0,0,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,NaN,NaN,NaN,Appointment Date,2009-08-27,11.0,20MICRONS,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.012672,0.002374,0.016580,0.008245,0.161037,-0.020051,0.027229,2.106517,0.095158,0.063718,2.095520,0.186179,0.099990,3.145210,0.367888,0.136368,5.257233,-0.014266,0.064480,0.116737,0.257054
22,20,20MICRONS,20 MICRONS LTD.,2010-03-31,2010,INE144J01027,P00027663,MR.,HARISH,KIRTIKANT,SHETH,1947-09-11,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.SC.-MECHANICAL,UNIVERSITY OF MICHI...","POST GRADUATE: M.B.A.-FINANCE,COLUMBIA UNIVERS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CONSUMER DISCRETIONARY,CORPORATE GOVERNANCE,FI...",<NA>,RESIGNED (NO REASON STATED),NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.HARISH SHETH IS A B.SC. IN MECHANICAL ENGIN...,NaT,NaT,U,2007-12-10,2009-07-30,2009-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,121.0,0.0,0.0,233.0,0.0,0.0,233.0,598.0,0.0,0.0,598.0,233.0,0.0,0.0,233.0,598.0,0.0,0.0,598.0,10185,"((20MICRONS, U),)","{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,77,0.000000,1.638356,27.904110,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{human resources, finance, consumer discretion...","GRADUATE: B.SC.-MECHANICAL,UNIVERSITY OF MICHI...",1,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'legal/compliance', '...",0,1,{20MICRONS},11,1,1,0,1,0,0,1,False,False,False,False,True,False,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,1,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,NaN,NaN,NaN,Cessation Date,2009-07-30,11.0,20MICRONS,12.50,-0.007937,0.008824,0.606603,0.615428,-0.050968,0.076723,-0.015122,0.003345,0.029881,0.021660,0.059023,0.000503,0.026365,0.353815,-0.004746,0.061340,2.473169,0.130467,0.096531,2.484330,0.143027,0.131612,4.768098,0.018321,-0.028993,0.070992,0.040831
26,23,20MICRONS,20 MICRONS LTD.,2010-03-31,2010,INE144J01027,P00027669,LATE MR.,VISHNU,RAJARAM,VARSHNEY,1947-04-11,M,NaN,NaN,NaN,<NA>,<NA>,POST GRADUATE: M.E.-ELECTRICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.VISHNU VARSHNEY HOLDS BACHELOR'S DEGREE OF ...,NaT,2009-07-29,U,2000-04-10,2009-07-29,2009-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,120.0,0.0,0.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3395,"((20MICRONS, U),)","{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,78,0.000000,9.306849,9.301370,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},POST GRADUATE: M.E.-ELECTRICAL,0,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{20MICRONS},0,1,1,0,1,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-07-29,11.0,20MICRONS,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.016130,0.003310,0.028601,0.020369,0.064814,-0.056087,0.026473,0.029619,0.062901,0.061664,1.417488,0.109739,0.096639,4.283657,0.181963,0.131720,6.025389,-0.034268,0.044935,0.047310,0.078687
27,23,20MICRONS,20 MICRONS LTD.,2010-03-31,2010,INE144J01027,P00027669,LATE MR.,VISHNU,RAJARAM,VARSHNEY,1947-04-11,M,NaN,NaN,NaN,<NA>,<NA>,POST GRADUATE: M.E.-ELECTRICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.VISHNU VARSHNEY HOLDS BACHELOR'S DEGREE OF ...,NaT,2009-07-29,U,2000-04-10,2009-07-29,2009-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,120.0,0.0,0.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3395,"((20MICRONS, U),)","{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,78,0.000000,9.306849,9.301370,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},POST GRADUATE: M.E.-ELECTRICAL,0,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{20MICRONS},0,1,1,0,1,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Date of Demise,2009-07-29,11.0,20MICRONS,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.016130,0.003310,0.028601,0.020369,0.064814,-0.056087,0.026473,0.029619,0.062901,0.061664,1.417488,0.109739,0.096639,4.283657,0.181963,0.131720,6.025389,-0.034268,0.044935,0.047310,0.078687
34,30,20MICRONS,20 MICRONS LTD.,2011-03-31,2011,INE144J01027,P00031581,MR.,ATUL,HARI,PATEL,1950-12-20,M,INDIA,NONE,NaN,<NA>,<NA>,"GRADUATE: B.E.-TEXTILE,VEERMATA JIJABAI TECHNO...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,COMMODITIES,CORPORATE ...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. ATUL H. PATEL JOINED THE INDUSTRY AFTER OB...,NaT,NaT,U,2009-08-27,NaT,2010-03-31,2012-03-31,0,0.0,0.0,1.0,0,0.0,0.0,0.0,365.0,0.0,0.0,216.0,0.0,0.0,216.0,581.0,0.0,0.0,581.0,216.0,0.0,0.0,216.0,581.0,0.0,0.0,581.0,581,"((20MICRONS, U),)","{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,74,0.000000,1.591781,1.591781,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{information technology, finance, marketing, c...","GRADUATE: B.E.-TEXTILE,VEERMATA JIJABAI TECHNO...",1,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{operations},"{'corporate governance', 'operations', 'legal/...",1,1,{20MICRONS},15,1,1,0,1,0,0,1,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,NaN,NaN,NaN,Appointment Date,2009-08-27,11.0,20MICRONS,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.012672,0.002374,0.016580,0.008245,0.161037,-0.020051,0.027229,2.106517,0.095158,0.063718,2.095520,0.186179,0.099990,3.145210,0.367888,0.136368,5.257233,-0.014266,0.064480,0.116737,0.257054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303224,254831,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067112,MR.,SRIKANTH,NaN,GOPALAN,NaT,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,N,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,863.0,0.0,0.0,1228.0,1228.0,0.0,0.0,863.0,863.0,0.0,0.0,1228.0,1228.0,1227,"((ZYLOG, N),)","{(ZYLOG, N)}","{(ZYLOG, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,<NA>,0.000000,3.364384,3.361644,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2014-11-19,275793.0,ZYLOG,7.70,-0.025316,0.021860,-0.741569,-0.719709,0.280029,-0.546563,-0.037219,0.014717,0.059441,0.051470,0.007287,-0.166621,0.065476,-0.584795,-0.128630,0.152826,0.041803,-0.054409,0.239965,0.676165,-0.144981,0.327195,-0.398142,-0.111834,-0.170415,-0.192669,-0.354660
303226,254832,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00073179,MR.,SIVAKUMAR,NaN,KANDASAMY,NaT,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,N,2015-08-14,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,595.0,595.0,0.0,0.0,960.0,960.0,0.0,0.0,595.0,595.0,0.0,0.0,960.0,960.0,960,"((ZYLOG, N),)","{(ZYLOG, N)}","{(ZYLOG, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,<NA>,0.000000,2.630137,2.630137,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2015-08-14,275793.0,ZYLOG,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034858,0.007051,0.027495,0.019253,0.070302,-0.113635,0.096076,0.535057,-0.246220,0.134926,-0.534668,-0.291712,0.173777,-0.844522,-0.274151,0.291613,-3.755096,-0.108911,-0.272803,-0.354960,-0.434712

In [15]:
dir120CAR.to_pickle(rf"{output_folder_path}\dir120CAR_2.pkl")

In [16]:
del output120CAR
del output120CAR2
del dir120CAR

## 150 CAR

In [17]:
output150CAR = pd.read_pickle(rf"{import_folder_path}\output150CAR_2.pkl")

In [18]:
output150CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS150_intercept', 'OLS150_RMRF',
       'OLS150_r_squared', 'OLS150_adjusted_r_squared', 'OLS150_f_p_value',
       'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum',
       '150CAR3', '150CAR5', '150CAR7', '150CAR11'],
      dtype='object')

In [19]:
colDrop = output150CAR.columns[[2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum'],
      dtype='object')

In [20]:
output150CAR2 = output150CAR.drop(labels = colDrop, axis = 1)
output150CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11
0,20 Microns Ltd.,11.0,2009-07-29,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.018705,0.005061,0.064182,0.057859,0.001760,-0.026594,0.050179,0.047536,0.075864
1,20 Microns Ltd.,11.0,2009-07-30,12.50,-0.007937,0.008824,0.606603,0.615428,-0.050968,0.076723,-0.017426,0.004621,0.055583,0.049202,0.003680,0.024780,-0.025239,0.074731,0.041656
2,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.016317,0.004135,0.048609,0.042181,0.006706,-0.007040,0.071726,0.122134,0.258731
3,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.026340,0.010345,0.100758,0.094682,0.000076,0.137190,0.053622,-0.002689,-0.118655
4,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.034378,0.008381,0.050199,0.043781,0.005847,0.024399,-0.055854,-0.137471,-0.291262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34393,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034571,0.010030,0.061262,0.054919,0.002261,-0.111364,-0.272070,-0.353304,-0.424385
34394,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.027604,0.002431,0.002971,-0.003765,0.507632,0.102407,0.014577,-0.040544,-0.189821
34395,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.025477,0.002946,0.004509,-0.002217,0.414249,-0.090198,-0.136508,-0.156335,-0.297482
34396,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.029032,0.004966,0.013618,0.006953,0.154986,0.031027,-0.103373,-0.202336,-0.079376
34397,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.022281,0.008887,0.024759,0.018170,0.054476,0.045621,0.035374,-0.020473,-0.127947

In [21]:
dir150CAR = dirLevel2.merge(output150CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [22]:
dir150CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, personal values, cons...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, operations, marketing}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, risk management, mark...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, financial services, opera...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(RKDL, U), (ZYLOG, Y), (RKDL, Y)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{public policy, risk management, marketing, st...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{62013, 11011}","{62013, 11011}","{62013, 11011}","{62013, 11011}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
dir150CAR.to_pickle(rf"{output_folder_path}\dir150CAR_2.pkl")

In [24]:
del output150CAR
del output150CAR2
del dir150CAR

## 180 CAR

In [25]:
output180CAR = pd.read_pickle(rf"{import_folder_path}\output180CAR_2.pkl")

In [26]:
output180CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS180_intercept', 'OLS180_RMRF',
       'OLS180_r_squared', 'OLS180_adjusted_r_squared', 'OLS180_f_p_value',
       'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum',
       '180CAR3', '180CAR5', '180CAR7', '180CAR11'],
      dtype='object')

In [27]:
colDrop = output180CAR.columns[[2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum'],
      dtype='object')

In [28]:
output180CAR2 = output180CAR.drop(labels = colDrop, axis = 1)
output180CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20 Microns Ltd.,11.0,2009-08-27,15.78,0.000000,0.009040,0.358959,0.368000,0.741064,0.945923,-0.019785,0.006153,0.095433,0.090351,2.449373e-05,-0.000888,0.077900,0.126189,0.258523
1,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.024022,0.010026,0.072412,0.067200,2.594653e-04,0.129581,0.045305,-0.011114,-0.127230
2,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.034278,0.008417,0.042347,0.036967,5.581963e-03,0.024108,-0.056134,-0.137719,-0.291525
3,20 Microns Ltd.,11.0,2015-02-05,38.50,-0.020356,0.021755,-0.625772,-0.604017,0.012769,-1.213916,-0.034440,0.006402,0.034724,0.029301,1.225873e-02,0.051002,-0.053362,-0.137931,-0.302848
4,20 Microns Ltd.,11.0,2017-05-04,43.70,0.016279,0.016554,0.046274,0.062828,0.831535,-0.581499,-0.024020,0.018310,0.186137,0.181564,1.480156e-09,0.016897,-0.111592,-0.163628,-0.275287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34082,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.034362,0.011860,0.071526,0.066310,2.840090e-04,-0.112971,-0.271720,-0.352387,-0.418144
34083,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.028974,0.005380,0.020708,0.015206,5.395059e-02,0.098004,0.007288,-0.047994,-0.191085
34084,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.027501,0.003164,0.004900,-0.000691,3.504521e-01,-0.084153,-0.130193,-0.150050,-0.291461
34085,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.030786,0.004640,0.014079,0.008541,1.126326e-01,0.036935,-0.097569,-0.196195,-0.072971
34086,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.023243,0.006936,0.015210,0.009678,9.906091e-02,0.048657,0.038255,-0.020749,-0.123870

In [29]:
dir180CAR = dirLevel2.merge(output180CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [30]:
dir180CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, personal values, cons...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, operations, marketing}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, risk management, mark...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, financial services, opera...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(RKDL, U), (ZYLOG, Y), (RKDL, Y)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{public policy, risk management, marketing, st...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{62013, 11011}","{62013, 11011}","{62013, 11011}","{62013, 11011}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
dir180CAR.to_pickle(rf"{output_folder_path}\dir180CAR_2.pkl")

In [32]:
del output180CAR
del output180CAR2
del dir180CAR

## 210 CAR

In [33]:
output210CAR = pd.read_pickle(rf"{import_folder_path}\output210CAR_2.pkl")

In [34]:
output210CAR.columns

Index(['CompanyName', 'ProwessCode', 'Symbol', 'AsOnDate', 'ACP', 'pct', 'RF',
       'RMRF', 'MF', 'SMB', 'HML', 'OLS210_intercept', 'OLS210_RMRF',
       'OLS210_r_squared', 'OLS210_adjusted_r_squared', 'OLS210_f_p_value',
       'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum',
       '210CAR3', '210CAR5', '210CAR7', '210CAR11'],
      dtype='object')

In [35]:
colDrop = output210CAR.columns[[2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]

colDrop

Index(['Symbol', 'pct_cen3sum', 'RF_cen3sum', 'RMRF_cen3sum', 'pct_cen5sum',
       'RF_cen5sum', 'RMRF_cen5sum', 'pct_cen7sum', 'RF_cen7sum',
       'RMRF_cen7sum', 'pct_cen11sum', 'RF_cen11sum', 'RMRF_cen11sum'],
      dtype='object')

In [36]:
output210CAR2 = output210CAR.drop(labels = colDrop, axis = 1)
output210CAR2

,CompanyName,ProwessCode,AsOnDate,ACP,pct,RF,RMRF,MF,SMB,HML,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,20 Microns Ltd.,11.0,2011-04-29,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.023121,0.009385,0.073740,0.069287,6.696283e-05,0.125561,0.039867,-0.016769,-0.133185
1,20 Microns Ltd.,11.0,2014-08-06,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.035117,0.005551,0.026592,0.021912,1.803598e-02,0.025908,-0.055217,-0.139358,-0.291996
2,20 Microns Ltd.,11.0,2015-02-05,38.50,-0.020356,0.021755,-0.625772,-0.604017,0.012769,-1.213916,-0.034893,0.006952,0.038823,0.034202,4.151230e-03,0.053314,-0.050453,-0.135060,-0.301011
3,20 Microns Ltd.,11.0,2017-05-04,43.70,0.016279,0.016554,0.046274,0.062828,0.831535,-0.581499,-0.024740,0.017188,0.166374,0.162366,7.998804e-10,0.017940,-0.110223,-0.161819,-0.272828
4,20 Microns Ltd.,11.0,2019-05-28,41.00,-0.016787,0.016873,0.367905,0.384778,-0.177790,0.292518,-0.025401,0.017863,0.233449,0.229763,1.106707e-13,0.041646,0.042037,0.003702,-0.102033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33898,Zylog Systems Ltd.,275793.0,2015-08-14,5.40,0.018868,0.019213,1.546309,1.565522,-0.064032,1.416502,-0.035294,0.013010,0.077200,0.072764,4.444277e-05,-0.110791,-0.268309,-0.348619,-0.411028
33899,Zylog Systems Ltd.,275793.0,2016-06-30,3.90,0.040000,0.017832,1.065921,1.083753,-0.809196,1.214423,-0.027771,0.008411,0.038518,0.033895,4.304770e-03,0.085644,-0.008037,-0.063485,-0.200219
33900,Zylog Systems Ltd.,275793.0,2016-08-12,3.15,-0.045455,0.017406,0.290292,0.307698,-0.979555,0.368906,-0.028711,0.005695,0.022120,0.017419,3.120744e-02,-0.080831,-0.123732,-0.143932,-0.288414
33901,Zylog Systems Ltd.,275793.0,2016-11-23,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.027389,0.004182,0.010090,0.005331,1.468822e-01,0.027651,-0.106999,-0.205153,-0.081559
33902,Zylog Systems Ltd.,275793.0,2017-02-10,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.024955,0.006593,0.015668,0.010935,7.026674e-02,0.053818,0.043389,-0.016170,-0.118526

In [37]:
dir210CAR = dirLevel2.merge(output210CAR2, how = "left", left_on = ["CompanyName", "Date of Study"], right_on = ["CompanyName", "AsOnDate"]).drop("AsOnDate_y", axis = 1).rename({"AsOnDate_x":"AsOnDate"}, axis = 1)

In [38]:
dir210CAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, personal values, cons...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{08, 29301, 29209}","{08, 29301, 29209}","{08, 29301, 29209}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{finance, operations, marketing}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{international business, risk management, mark...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, finance, financial services, opera...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303238,254838,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00036956,MR.,KUNJURI SATYA NARAYANA MURTY,SARVOTHAMA,RAO,1947-08-01,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: A.I.B.,LONDON",GRADUATE: B.COM.,GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE OF IN...,GRADUATE: LL.B.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,RAVIKUMAR DISTILLERIES LTD.,ZYLOG SYSTEMS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. K S M. RAO WAS ASSOCIATED WITH MANY REPUTE...,NaT,NaT,Y,2015-11-25,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,0.0,492.0,0.0,492.0,0.0,857.0,0.0,857.0,3795,"((RKDL, Y), (ZYLOG, Y), (RKDL, U))","{(ZYLOG, Y), (RKDL, Y)}","{(RKDL, U), (ZYLOG, Y), (RKDL, Y)}","((RKDL, U),)",(),1,0,0,1,0,0,0,0,0,2,0,2,1,2,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77,2.347945,2.347945,10.397260,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,"{public policy, risk management, marketing, st...","GRADUATE: A.I.B.,LONDON GRADUATE: B.COM. GRADU...",0,0,"{62013, 11011}","{62013, 11011}","{62013, 11011}","{62013, 11011}","{62, 11}","{62, 11}",0,1,1,0,0,0,0,0,0,0,0,{},{},{risk management},"{'corporate governance', 'legal/compliance', '...",1,1,"{ZYLOG, RKDL}",12,2,2,0,0,0,0,1,False,False,False,False,False,True,True,True,True,False,True,True,True,True,False,True,False,0,False,False,False,False,True,True,True,False,False,True,False,False,False,True,False,False,False,NaN,False,False,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2015-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
dir210CAR.to_pickle(rf"{output_folder_path}\dir210CAR_2.pkl")