In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
import_folder_path = "car_output3"
output_folder_path = "car_output4"
filtering_folder_path = rf"..\..\[IN USE] Rookie Directors\[4] FF3 CAR\car_filtering"
supporting_folder_path = "supporting_datafiles"

## Data Reading

In [3]:
dir120CAR = pd.read_pickle(rf"{import_folder_path}\dir120CAR_2.pkl")
dir150CAR = pd.read_pickle(rf"{import_folder_path}\dir150CAR_2.pkl")
dir180CAR = pd.read_pickle(rf"{import_folder_path}\dir180CAR_2.pkl")
dir210CAR = pd.read_pickle(rf"{import_folder_path}\dir210CAR_2.pkl")

In [4]:
dir180CAR.columns.to_list()

['index',
 'Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Date of Demise',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'TenureInYearsTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsZeroYear',
 'IsZeroYearIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Ownership group code',
 'Prowess company code',
 'CompanyName',
 'govtdummy',
 'findummy',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllPastDirectNIC_2Digit',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'SkillsInBriefProfile',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills_gai',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'Academic',
 'Outside Board',
 'Company Business',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Manufacturing_NIC_not used',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'skill_committee_sustainability',
 'combined_entrepreneurial',
 'skill_committee_entrepreneurial',
 'combined_compensation',
 'skill_committee_compensation',
 'combined_conglomerate_experience',
 'skill_committee_conglomerate_experience',
 'combined_hr',
 'skill_committee_hr',
 'combined_technology',
 'skill_committee_technology',
 'combined_finance_accounting',
 'skill_committee_finance_accounting',
 'combined_governance',
 'skill_committee_governance',
 'combined_government_policy',
 'skill_committee_government_policy',
 'combined_international',
 'skill_committee_international',
 'combined_leadership',
 'skill_committee_leadership',
 'combined_legal',
 'skill_committee_legal',
 'combined_marketing',
 'skill_committee_marketing',
 'combined_risk_management',
 'skill_committee_risk_management',
 'combined_scientific',
 'skill_committee_scientific',
 'combined_strategic_planning',
 'skill_committee_strategic_planning',
 'combined_manufacturing_supply_chain',
 'skill_committee_manufacturing_supply_chain',
 'skill_committee_leadership_outside_board',
 'combined_leadership_outside_board',
 'board_corporate governance',
 'board_international business',
 'board_industrials',
 'board_utilities',
 'board_finance',
 'board_telecommunication',
 'board_accounts/audit/taxation',
 'board_public policy',
 'board_risk management',
 'board_research & development',
 'board_legal/compliance',
 'board_services',
 'board_marketing',
 'board_healthcare',
 'board_strategy',
 'board_commodities',
 'board_operations',
 'board_diversity',
 'board_diversified',
 'board_corporate social responsibility',
 'board_human resources',
 'board_fast moving consumer goods',
 'board_economics',
 'board_leadership/management',
 'board_energy',
 'board_financial services',
 'board_information technology',
 'board_personal values',
 'board_consumer discretionary',
 'board_supply chain management',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'date_source',
 'Date of Study',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11']

In [5]:
comCol = list(dir150CAR.columns[0:135])
comCol

['index',
 'Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Date of Demise',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'TenureInYearsTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsZeroYear',
 'IsZeroYearIndep',
 'IsOneYear']

In [6]:
dirCAR = pd.concat([dir120CAR, dir150CAR, dir180CAR, dir210CAR], axis = 1)
dirCAR = dirCAR.loc[:, ~dirCAR.columns.duplicated()].copy()
dirCAR

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(20MICRONS, U), (MUNJALAU, U), (BANCOINDIA, U)}","{(20MICRONS, U), (MUNJALAU, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{research & development, corporate governance,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, operations, finance}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{research & development, corporate governance,...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{services, finance, financial services, market...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303237,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dirCAR.columns.to_list()

['index',
 'Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Date of Demise',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'TenureInYearsTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsZeroYear',
 'IsZeroYearIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Ownership group code',
 'Prowess company code',
 'CompanyName',
 'govtdummy',
 'findummy',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllPastDirectNIC_2Digit',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'SkillsInBriefProfile',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills_gai',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'Academic',
 'Outside Board',
 'Company Business',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Manufacturing_NIC_not used',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'skill_committee_sustainability',
 'combined_entrepreneurial',
 'skill_committee_entrepreneurial',
 'combined_compensation',
 'skill_committee_compensation',
 'combined_conglomerate_experience',
 'skill_committee_conglomerate_experience',
 'combined_hr',
 'skill_committee_hr',
 'combined_technology',
 'skill_committee_technology',
 'combined_finance_accounting',
 'skill_committee_finance_accounting',
 'combined_governance',
 'skill_committee_governance',
 'combined_government_policy',
 'skill_committee_government_policy',
 'combined_international',
 'skill_committee_international',
 'combined_leadership',
 'skill_committee_leadership',
 'combined_legal',
 'skill_committee_legal',
 'combined_marketing',
 'skill_committee_marketing',
 'combined_risk_management',
 'skill_committee_risk_management',
 'combined_scientific',
 'skill_committee_scientific',
 'combined_strategic_planning',
 'skill_committee_strategic_planning',
 'combined_manufacturing_supply_chain',
 'skill_committee_manufacturing_supply_chain',
 'skill_committee_leadership_outside_board',
 'combined_leadership_outside_board',
 'board_corporate governance',
 'board_international business',
 'board_industrials',
 'board_utilities',
 'board_finance',
 'board_telecommunication',
 'board_accounts/audit/taxation',
 'board_public policy',
 'board_risk management',
 'board_research & development',
 'board_legal/compliance',
 'board_services',
 'board_marketing',
 'board_healthcare',
 'board_strategy',
 'board_commodities',
 'board_operations',
 'board_diversity',
 'board_diversified',
 'board_corporate social responsibility',
 'board_human resources',
 'board_fast moving consumer goods',
 'board_economics',
 'board_leadership/management',
 'board_energy',
 'board_financial services',
 'board_information technology',
 'board_personal values',
 'board_consumer discretionary',
 'board_supply chain management',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'date_source',
 'Date of Study',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11',
 'OLS210_intercept',
 'OLS210_RMRF',
 'OLS210_r_squared',
 'OLS210_adjusted_r_squared',
 'OLS210_f_p_value',
 '210CAR3',
 '210CAR5',
 '210CAR7',
 '210CAR11']

In [8]:
dirCAR.loc[ (dirCAR["Person Code"] == "P00000256") & (dirCAR["AsOnDate"] == "2006-03-31") ]

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
2898,2458,ACC,ACC LTD.,2006-03-31,2006,INE012A01025,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.TARUN DAS, AS DIRECTOR GENERAL OF THE CONFE...",NaT,NaT,U,2000-04-26,2006-01-01,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,2076.0,0.0,0.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,2164,(),"{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}","{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,5.687671,5.928767,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,ACC,23941,Public Ltd.,Adani Group,2.010102e+10,23354.0,A C C Ltd.,0,0,{},GRADUATE: B.A.(HONS.)-ECONOMICS,0,0,{},"{23941, 64300, 6020}","{23941, 64300, 6020}","{23941, 64300, 6020}",{},"{64, 60, 23}",0,0,0,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,1,False,False,False,False,True,True,True,False,True,True,True,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2000-04-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2899,2458,ACC,ACC LTD.,2006-03-31,2006,INE012A01025,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.TARUN DAS, AS DIRECTOR GENERAL OF THE CONFE...",NaT,NaT,U,2000-04-26,2006-01-01,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,2076.0,0.0,0.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,2164,(),"{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}","{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,5.687671,5.928767,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,ACC,23941,Public Ltd.,Adani Group,2.010102e+10,23354.0,A C C Ltd.,0,0,{},GRADUATE: B.A.(HONS.)-ECONOMICS,0,0,{},"{23941, 64300, 6020}","{23941, 64300, 6020}","{23941, 64300, 6020}",{},"{64, 60, 23}",0,0,0,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,1,False,False,False,False,True,True,True,False,True,True,True,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2006-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29189,24722,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,HE HAS SPENT HIS ENTIRE WORKING CAREER IN INDU...,NaT,NaT,U,2004-09-15,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,562.0,0.0,0.0,197.0,0.0,0.0,197.0,562.0,0.0,0.0,562.0,197.0,0.0,0.0,197.0,562.0,0.0,0.0,562.0,2164,(),"{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}","{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,1.539726,5.928767,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,BAJAJHLDNG,64300,Public Ltd.,Bajaj Group,2.010101e+10,28899.0,Bajaj Holdings & Invst. Ltd.,0,1,{},GRADUATE: B.A.(HONS.)-ECONOMICS,0,0,{},"{23941, 64300, 6020}","{23941, 64300, 6020}","{23941, 64300, 6020}",{},"{64, 60, 23}",0,0,0,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,True,True,True,False,True,True,True,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2004-09-15,28899.0,1.4,-0.066667,0.012454,-0.201723,-0.189269,-0.599788,-0.057796,-0.015254,0.003666,0.009104,0.000707,0.299889,-0.118986,-0.209977,-0.232322,-0.037078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185845,156406,NDTV,NEW DELHI TELEVISION LTD.,2006-03-31,2006,INE155G01029,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.TARUN DAS IS THE CHIEF MENTOR OF CONFEDERAT...,NaT,NaT,U,2004-05-14,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,686.0,0.0,0.0,321.0,0.0,0.0,321.0,686.0,0.0,0.0,686.0,321.0,0.0,0.0,321.0,686.0,0.0,0.0,686.0,2164,(),"{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}","{(NDTV, U), (ACC, U), (BAJAJHLDNG, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,1.879452,5.928767,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NDTV,6020,Public Ltd.,Adani Group,2.010102e+10,158295.0,New Delhi Television Ltd.,0,0,{},GRADUATE: B.A.(HONS.)-ECONOMICS,0,0,{},"{23941, 64300, 6020}","{23941, 64300, 6020}","{23941, 64300, 6020}",{},"{64, 60, 23}",0,0,0,0,0,0,0,0,0,0,0,{},{},{economics},{'economics'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,True,True,True,False,True,True,True,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2004-05-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Importing CAR filters and Filtering

In [9]:
CARs = [120, 150, 180, 210]

insuffDataLong = []
for i,CAR in enumerate(CARs):
    frame = pd.read_pickle(rf"{filtering_folder_path}\Insufficient Data for {CAR}CAR.pkl")
    dirCAR = dirCAR.merge(frame,
                          right_on = ["CompanyName", "AsOnDate"],
                          left_on = ["CompanyName", "Appointment Date"],
                          how = "left")
    dirCAR.drop(["AsOnDate_y"], axis = 1, inplace = True)
    dirCAR.rename({"insufficient_data_dummy":f"insufficient_data_dummy_{CAR}", "AsOnDate_x":"AsOnDate", "na_trading_days":f"na_trading_days_{CAR}"},
                  axis = 1, inplace = True)
    dirCAR[f"insufficient_data_dummy_{CAR}"] = dirCAR[f"insufficient_data_dummy_{CAR}"].fillna(0)

    event_periods = [3, 5, 7, 11]
    for event_period in event_periods:
        dirCAR.loc[ dirCAR[f"insufficient_data_dummy_{CAR}"] == 1, f"{CAR}CAR{event_period}"] = pd.NA

## Filtered Data Points

In [10]:
filter_row_list = [
    dirCAR.loc[ (dirCAR["Person Code"] == "P00093327") & 
    (dirCAR["Symbol"] == "ATNINTER") & (dirCAR["AsOnDate"] == "2020-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00095015") & 
    (dirCAR["Symbol"] == "HNDFDS") & (dirCAR["AsOnDate"] == "2024-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00100475") & 
    (dirCAR["Symbol"] == "ROUTE") & (dirCAR["AsOnDate"] == "2021-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00013751") & 
    (dirCAR["Symbol"] == "LLOYDSME") & (dirCAR["AsOnDate"] == "2024-03-31")]
]

filter_df = pd.concat(filter_row_list, axis = 0)

In [11]:
dirCAR2 = dirCAR.iloc[ dirCAR.index.difference(filter_df.index)  ].reset_index(drop = True)

In [12]:
dirCAR2.to_pickle(rf"{output_folder_path}\Director Level_MF_CAR.pkl")

In [13]:
# dirCAR.to_pickle(rf"{output_folder_path}\Director Level_MF_CAR.pkl")

In [14]:
dirCAR2

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210
0,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2005-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,<NA>,<NA>,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NOMINATION ENDED,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,NaT,U,2005-04-29,2009-03-02,NaT,NaT,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.000000,3.843836,3.841096,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},GRADUATE: B.SC.,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{risk management},{'risk management'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,0,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2009-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,<NA>,<NA>,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(20MICRONS, U), (MUNJALAU, U), (BANCOINDIA, U)}","{(20MICRONS, U), (MUNJALAU, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.000000,1.465753,7.668493,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{research & development, corporate governance,...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}",{29},"{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{marketing, operations, finance}","{'corporate governance', 'operations', 'legal/...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,False,False,False,False,True,True,True,True,False,True,True,True,True,True,False,True,True,0,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,NaN,NaN,NaN,Appointment Date,2007-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,2,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,48,0.000000,1.605479,1.605479,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},{'corporate governance'},0,0,<NA>,1,0,0,0,1,0,0,0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,True,True,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Appointment Date,2007-08-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,3,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,NaN,<NA>,<NA>,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,NaT,U,2001-01-29,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,2983.0,0.0,0.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2618.0,0.0,0.0,2618.0,2983.0,0.0,0.0,2983.0,2981,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,47,0.000000,8.172603,8.167123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{research & development, corporate governance,...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},"{services, finance, financial services, market...","{'corporate governance', 'operations', 'servic...",1,1,<NA>,13,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Appointment Date,2001-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303231,254837,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,0.0,863.0,0.0,863.0,0.0,1228.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.364384,3.364384,3.361644,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),2.010200e+10,275793.0,Zylog Systems Ltd.,0,0,{},,0,0,{62013},{62013},{62013},{62013},{62},{62},0,1,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cessation Date,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN