# Director Skill Sets Table 7 - Appointments only

In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import mpl_toolkits as mplot3d
%matplotlib inline
import seaborn as sns

import scipy.stats as stats
from scipy.stats.mstats import winsorize
from scipy.spatial.distance import cdist


from sklearn.neighbors import NearestNeighbors

import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
import_folder_path = rf"../../../../[IN USE] Rookie Directors/[4] FF3 CAR/car_output4"
output_folder_path = "analysis_outputs"
# pca_input_folder_path = rf"..\..\..\[IN USE] Rookie Directors\[1.5] Director Skills PCA\director_skills_pca"
supporting_folder_path = "supporting_datafiles"

In [3]:
dirFirm = pd.read_pickle(rf"{import_folder_path}/Director Level_FF3_CAR.pkl")
dirFirm = dirFirm.loc[ dirFirm["date_source"] == "Appointment Date"].reset_index(drop = True)

# pca = pd.read_pickle(rf"{pca_input_folder_path}\Main_Director_COMPLETE_PCA.pkl")

# pca_col = [
#     "Person Code", "AsOnDate", "Symbol",
#     "SkillsetIndex", "SkillsetGeneralistDummy",
#     "PC1_FactorScore", "PC1_FactorScore_Standardised"
# ]

# pca2 = pca[pca_col].copy()
# dirFirm = dirFirm0.merge(pca2, on = ["Person Code", "AsOnDate", "Symbol"], how = "left")

In [4]:
# dirFirm data wrangling if any:
dirFirm["Year of Study"] = [x.year for x in dirFirm["Date of Study"]]

dirFirm = dirFirm.drop_duplicates(subset = ["Person Code", "Company", "Date of Study"]).reset_index(drop = True)

dirFirm["ln_dirage"] = np.log(dirFirm["Age"] + 1).astype("float")
dirFirm["ln_directorships"] = np.log(dirFirm["CompCountOtherPastTotalAB"] + 1).astype("float")

In [5]:
dirFirm.describe()

,index,AsOnDate,AsOnYear,Date of Birth,Tenure Valid till,Date of Demise,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,Ownership group code,Prowess company code,govtdummy,findummy,IsMBA,IsPhD,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,HasTechSkill,HasFinanceSkill,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,Manufacturing_NIC_not used,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships
count,47218.000000,47218,47218.00000,41389,9257,64,47218,7093,803,40269,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.0,47218.0,47218.0,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.00000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,41389.0,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.0,47218.000000,47218.000000,47218.000000,47218.000000,47218.0,47218.000000,4.685300e+04,46853.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.0,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,47218.000000,23817.000000,23817.000000,23815.000000,47218,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,24590.000000,2.459000e+04,22779.000000,22769.000000,22764.000000,22747.000000,24441.000000,24441.000000,24441.000000,24441.000000,24441.000000,24441.000000,2.444100e+04,22625.000000,22615.000000,22611.000000,22594.000000,24148.000000,24148.000000,24148.000000,24148.000000,24148.000000,24148.000000,2.414800e+04,22332.000000,22322.000000,22318.000000,22301.000000,24025.000000,24025.000000,24025.000000,24025.000000,24025.000000,24025.000000,2.402500e+04,22197.000000,22187.000000,22183.000000,22166.000000,47218.000000,1811.000000,47218.000000,1816.000000,47218.000000,1816.000000,47218.000000,1828.000000,47218.000000,41389.000000,47218.000000
mean,127936.994600,2015-04-30 10:13:26.641534976,2015.08232,1959-08-09 10:05:28.956969280,2027-07-20 11:47:19.321594368,2014-10-18 19:30:00,2011-10-26 07:27:25.152272640,2020-07-22 02:36:19.388129280,2016-02-07 18:13:53.872976384,2015-05-22 05:06:51.145049600,0.150218,0.016964,0.999958,1.017133,0.617773,0.0,0.0,0.0,727.393854,171.887543,373.641704,614.455208,101.716866,304.359947,1020.532022,727.393854,171.897603,373.641704,1272.933161,634.418061,106.619615,313.093375,1054.131052,747.777924,177.598501,383.725020,1309.101444,2060.00413,0.252870,0.081071,0.064912,0.398852,0.224109,0.081071,0.064912,0.370092,0.682070,0.531704,0.393176,1.606951,1.245860,0.531704,0.393176,2.170740,0.312042,0.687958,0.570566,0.429434,0.048668,0.036236,0.093248,0.034542,0.096933,0.049663,0.061756,0.057902,0.066055,0.024652,0.024482,0.016138,0.009996,0.194333,0.376234,0.117709,0.311724,0.145411,65.442291,0.486571,3.586579,5.643847,0.798085,0.287094,0.003261,0.001588,0.390635,0.130776,0.514634,0.179550,0.570566,0.194333,0.027722,0.0,0.110424,0.139057,0.150218,0.004066,0.0,0.062900,1.882614e+10,206453.122511,0.127473,0.150875,0.247448,0.063895,0.082299,0.023360,0.072811,0.046423,0.070037,0.013639,0.053327,0.052819,0.000042,0.052904,0.000106,0.256173,0.568300,5.924224,0.597886,0.562328,0.034711,0.669279,0.063895,0.139650,0.072811,0.478737,0.233047,0.218010,0.267483,0.114723,0.192723,0.168389,0.025181,0.0,0.424965,0.196302,0.889830,0.555763,0.852959,0.685141,0.506459,0.490999,0.297450,0.173324,0.348977,0.162904,0.526452,0.496844,0.391800,0.361028,0.501461,0.485747,0.384557,0.383710,0.049219,0.000275,0.455462,0.443899,0.494049,0.370198,0.528760,0.555466,0.419141,0.153395,0.098395,0.016561,0.477487,0.008853,0.276441,0.155894,0.346012,0.132873,0.360625,0.026092,0.298530,0.036914,0.421068,0.083167,0.244907,0.081155,0.001885,0.124868,0.256597,0.037909,0.113135,0.496823,0.013088,0.083252,0.245902,0.195646,0.137151,0.037719,8.111013,4.698073,0.429204,2011-10-26 07:27:25.152272640,185081.199715,338.150492,0.001846,0.024832,0.022440,0.047271,0.000876,-0.003008,-0.023391,0.009331,0.005554,0.001711,0.166707,0.145156,1.048139e-01,-0.002152,-0.051659,-0.100071,-0.195908,-0.023036,0.009656,0.005920,0.002245,0.163687,0.146503,9.083014e-02,-0.004368,-0.054039,-0.101908,-0.197984,-0.023170,0.009662,0.005930,0.002374,0.160341,0.146029,8.327125e-02,-0.004178,-0.053825,-0.101770,-0.197832,-0.023269,0.009609,0.005938,0.002350,0.158497,0.146242,7.537677e-02,-0.003465,-0.052980,-0.101043,-0.196852,0.038354,118.420210,0.038460,147.529736,0.038460,176.478524,0.038714,204.577681,2011.322737,4.172367,0.158531
min,0.000000,2006-03-31 00:00:00,2006.00000,1911-11-11 00:00:00,2025-02-14 00:00:00,2006-01-02 00:00:00,1940-08-23 00:00:00,2006-01-01 00:00:00,2007-03-31 00:00:00,2007-03-31 00:00:00,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,-96.000000,-158.000000,-122.000000,0.000000,0.000000,0.000000,0.000000,-96.000000,-158.000000,-122.000000,-158.000000,0.000000,0.000000,0.000000,0.000000,-96.000000,0.000000,-122.000000,-96.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,0.000000,-0.263014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.010000e+10,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.500000,1940-08-23 00:00:00,11.000000,0.050000,-0.905898,0.007905,-10.824149,-10.785401,-5.329015,-4.724853,-0.049294,-0.808750,-1.746015,-1.438630,0.000050,-0.025810,1.232648e-38,-5.881178,-7.810134,-8.022797,-13.315398,-0.050355,-1.062931,-1.425225,-1.287548,0.000049,-0.020498,5.695104e-44,-20.068527,-23.083874,-18.363488,-19.380329,-0.047755,-0.869967,-1.284674,-1.141087,0.000068,-0.016976,3.460710e-49,-17.038145,-19.928152,-17.021014,-17.768450,-0.045535,-0.743163,-1.068946,-0.937069,0.000205,-0.014355,8.147145e-55,-12.509249,-15.234707,-12.097492,-13.219807,0.000000,60.000000,0.000000,75.000000,0.000000,90.000000,0.000000,105.000000,1940.000000,3.044522,0.000000
25%,64094.250000,2009-03-31 00:00:00,2009.00000,1950-07-22 00:00:00,2026-06-26 00:00:00,2008-07-18 18:00:00,2006-08-26 00:00:00,2017-09-14 00:00:00,2013-03-31 00:00:00,2009-03-31 00:00:00,0.000000,0.000000,1.000000,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,154.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,154.000000,242.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,57.0,0.000000,0.421918,0.663014,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2.010101e+10,86729.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.111111,2006-08-26 00:00:00,83019.750000,24.110000,-0.013883,0.015807,-0.507297,-0.477828,-0.461883,-0.530267,-0.029228,0.004984,0.000670,-0.001966,0.058042,0.033681,3.672450e-07,-0.035363,-0.091517,-0.152113,-0.267172,-0.029199,0.005305,0.000873,-0.001591,0.055786,0.036384,9.512427e-09,-0.035434,-0.091632,-0.153108,-0.267947,-0.029182,0.005428,0.001015,-0.001361,0.054630,0.038515,2.645132e-10,-0.035650,-0.092321,-0.152941,-0.268645,-0.029207,0.005687,0.001157,-0.001268,0.054590,0.040822,5.933159e-12,-0.035758,-0.091966,-0.152990,-0.268068,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2006.000000,4.060443,0.000000
50%,129497.500000,2015-03-31 00:00:00,2015.00000,1958-12-03 00:00:00,2027-07-24 00:00:00,2015-03-28 00:00:00,2013-10-29 00:00:00,2024-03-31 00:00:00,2016-03-31 00:00:00,2016-03-31 00:00:00,0.000000,0.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,304.000000,650.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,66.0,0.000000,0.832877,1.780822,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2.010103e+10,164832.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,4.000000,0.428571,2013-10-29 00:00:00,155471.000000,74.525000,0.000000,0.018788,0.109106,0.131495,0.048463,-0.009574,-0.024747,0.009346,0.004995,0.001275,0.137663,0.115361,6.267681e-04,-0.004611,-0.053583,-0.102295,-0.202407,-0.024793,0.009479,0.005100,0.001388,0.136882,0.119147,8.036557e-05,-0.004639,-0.053978,-0.102550,-0.202616,-0.024811,0.009536,0.005179,0.001476,0.135161,0.120420,1.140554e-05,-0.004632,-0.054032,-0.102707,-0.202888,-0.024774,0.009529,0.005260,0.001495,0.135434,0.122843,1.346824e-06,-0.004246,-0.053961,-0.102374,-0.202586,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2013.000000,4.204693,0.000000

# PSM

## Verifying and removing those rows with no control data points

In [6]:
# Sample constraints ---> govtdummy==0 & findummy==0 & asonyear>2012
dirFirm.columns.to_list()

['index',
 'Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Date of Demise',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'TenureInYearsTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsZeroYear',
 'IsZeroYearIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Ownership group code',
 'Prowess company code',
 'CompanyName',
 'govtdummy',
 'findummy',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllPastDirectNIC_2Digit',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'SkillsInBriefProfile',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills_gai',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'Academic',
 'Outside Board',
 'Company Business',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Manufacturing_NIC_not used',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'skill_committee_sustainability',
 'combined_entrepreneurial',
 'skill_committee_entrepreneurial',
 'combined_compensation',
 'skill_committee_compensation',
 'combined_conglomerate_experience',
 'skill_committee_conglomerate_experience',
 'combined_hr',
 'skill_committee_hr',
 'combined_technology',
 'skill_committee_technology',
 'combined_finance_accounting',
 'skill_committee_finance_accounting',
 'combined_governance',
 'skill_committee_governance',
 'combined_government_policy',
 'skill_committee_government_policy',
 'combined_international',
 'skill_committee_international',
 'combined_leadership',
 'skill_committee_leadership',
 'combined_legal',
 'skill_committee_legal',
 'combined_marketing',
 'skill_committee_marketing',
 'combined_risk_management',
 'skill_committee_risk_management',
 'combined_scientific',
 'skill_committee_scientific',
 'combined_strategic_planning',
 'skill_committee_strategic_planning',
 'combined_manufacturing_supply_chain',
 'skill_committee_manufacturing_supply_chain',
 'skill_committee_leadership_outside_board',
 'combined_leadership_outside_board',
 'board_corporate governance',
 'board_international business',
 'board_industrials',
 'board_utilities',
 'board_finance',
 'board_telecommunication',
 'board_accounts/audit/taxation',
 'board_public policy',
 'board_risk management',
 'board_research & development',
 'board_legal/compliance',
 'board_services',
 'board_marketing',
 'board_healthcare',
 'board_strategy',
 'board_commodities',
 'board_operations',
 'board_diversity',
 'board_diversified',
 'board_corporate social responsibility',
 'board_human resources',
 'board_fast moving consumer goods',
 'board_economics',
 'board_leadership/management',
 'board_energy',
 'board_financial services',
 'board_information technology',
 'board_personal values',
 'board_consumer discretionary',
 'board_supply chain management',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'date_source',
 'Date of Study',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_SMB',
 'OLS120_HML',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_SMB',
 'OLS150_HML',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_SMB',
 'OLS180_HML',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11',
 'OLS210_intercept',
 'OLS210_RMRF',
 'OLS210_SMB',
 'OLS210_HML',
 'OLS210_r_squared',
 'OLS210_adjusted_r_squared',
 'OLS210_f_p_value',
 '210CAR3',
 '210CAR5',
 '210CAR7',
 '210CAR11',
 'insufficient_data_dummy_120',
 'na_trading_days_120',
 'insufficient_data_dummy_150',
 'na_trading_days_150',
 'insufficient_data_dummy_180',
 'na_trading_days_180',
 'insufficient_data_dummy_210',
 'na_trading_days_210',
 'Year of Study',
 'ln_dirage',
 'ln_directorships']

In [7]:
dirFirm["IsDualityChairmanMD"] = dirFirm["IsDualityChairmanMD"].astype(int)


# dirFirm["NIC_2digit"] = dirFirm["NIC code"].dropna().apply(lambda x: x[0:2])
# dirFirm["NIC_2digit"] = dirFirm["NIC_2digit"]

psmSample = dirFirm.loc[ (dirFirm["Year of Study"] >= 2013)].copy()
# \
# & (dirFirm["govtdummy"] == 0) & (dirFirm["findummy"] == 0) ].copy()
#.dropna(subset = controlVars).dropna(subset = dependentVar).copy()

psmSample["DummySum"] = psmSample["IsRookie"] + psmSample["IsNonRookie"]
psmSample["DummySumIndep"] = psmSample["IsRookieIndep"] + psmSample["IsNonRookieIndep"]

psmSampleAll = psmSample.loc[ psmSample["DummySum"] == 1 ].reset_index(drop = True)
#psmSampleAll = psmSampleAll.loc[ ~psmSampleAll.duplicated(subset = ["AsOnDate", "Symbol", "Appointment Date"], keep = False)]

psmSampleIndep = psmSample.loc[ psmSample["DummySumIndep"] == 1 ].reset_index(drop = True)
#psmSampleIndep = psmSampleIndep.loc[ ~psmSampleIndep.duplicated(subset = ["AsOnDate", "Symbol", "Appointment Date"], keep = False)]

## CAR windsorization

In [8]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

from scipy.stats.mstats import winsorize

def winsorize_output(sample, variable, limits = [0, 0]):
    sample[f"nonwinsorised_{variable}"] = sample[variable]
    sample[f"winsorised_{variable}"] = winsorize(np.array(sample[f"nonwinsorised_{variable}"]), limits = limits, inclusive = [False, False])
    sample[[f"nonwinsorised_{variable}", f"winsorised_{variable}"]].describe()
    print(sample[[f"winsorised_{variable}", f"nonwinsorised_{variable}"]].describe())
    print("\n\nTop values and their count: ", (sample[f"nonwinsorised_{variable}"].value_counts().sort_index().tail(n=10)))
    print("\n\n")
    
    # Graphs
    fig, axes = plt.subplots(1, 2, figsize = (12, 6))
    sns.kdeplot(data = sample[f"nonwinsorised_{variable}"].replace([np.inf, -np.inf], np.nan), ax = axes[0])
    axes[0].set_title(f'Nonwinsorised {variable}')
    sns.kdeplot(data = sample[f"winsorised_{variable}"].replace([np.inf, -np.inf], np.nan), ax = axes[1])
    axes[1].set_title(f'Winsorized {variable}')
    plt.tight_layout()
    plt.show()

    sample[variable] = sample[f"winsorised_{variable}"]
    return sample[variable]

# for car in carCol:
#     psmSampleIndep[car] = winsorize_output(psmSampleIndep, car, [0.01, 0.01])

In [9]:
# dirFirm2 = dirFirm.copy()
# psmSampleIndep2 = psmSampleIndep.copy()

# listCol = [
#     "FirstYearPCodeList", "TwoYearPCodeList", "ThreeYearPCodeList", "PCodeList",
#     "FirstYearIndepPCodeList", "TwoYearIndepPCodeList", "ThreeYearIndepPCodeList", "IndepPCodeList",
#     "OtherFirstYearIndepPCode", "OtherTwoYearIndepPCode", "OtherThreeYearIndepPCode", "TotalIndepPCode",
#     "OtherFirstYearPCode", "OtherTwoYearPCode", "OtherThreeYearPCode", "TotalPCode",
#     "OtherFirstYearPCodeIndepExcl","OtherTwoYearPCodeIndepExcl", "OtherThreeYearPCodeIndepExcl", "TotalPCodeIndepExcl",
#     "OtherFirstYearPCodeExcl", "OtherTwoYearPCodeExcl", "OtherThreeYearPCodeExcl", "TotalPCodeExcl"
# ]

# dirFirm2 = dirFirm2.drop(listCol, axis = 1)
# psmSampleIndep2 = psmSampleIndep2.drop(listCol, axis = 1)


# dirFirm2.to_csv("Main_Firm_PSM Ready_no filter v040425.csv")
# psmSampleIndep2.to_csv("Main_Firm_PSM Ready_filter-Indep_gov_fin v040425.csv")


# # # psmSampleAll --> 2101 rows 
# # psmSampleIndep --> 1561 rows

## PSM --> RookieAppoints as Treatment, NonRookieAppoints as Control

In [10]:
def LogitReg(sample, endog_var, exog_var):
    
    # Logit Regression
    endog = sample[endog_var]
    exog = sample[exog_var]
    
    scaler = StandardScaler()
    exog_standardised = pd.DataFrame(scaler.fit_transform(exog), columns=exog.columns)

    exog_standardised = sm.add_constant(exog_standardised)
    
    log_reg = sm.Logit(endog, exog_standardised).fit()

    propensityScores = log_reg.predict(exog_standardised)
    
    return propensityScores

In [11]:
def MeanDiffTtest(sample, endog_var, exog_var, car, depVar, dirFirm):

    sample[car] = winsorize(sample[car], limits = [0.01, 0.01])
    if depVar != None:
        dirFirm = dirFirm.rename( {depVar:f"{depVar}_2"}, axis = 1)
    
        colsAdd = []
        for i in range(-1, 4):
            if i != 0:
                colsAdd.append(f"AsOnYear_T+{i}")
                colsAdd.append(f"{depVar}T+{i}")
                if i>0 :
                    colsAdd.append(depVar+f"(T+{i}) - (T-1)")
    
        newFrame= pd.DataFrame(columns = colsAdd, data = 0, index = sample.index, dtype = "float")
        sample = pd.concat([sample, newFrame], axis = 1)
        sample = sample.copy()
        
        for i in range(-1, 4):
            if i != 0:
                sample.loc[:, f"AsOnYear_T+{i}"] = sample["AsOnYear"] + i
    
        for i in range(-1, 4):
            if i != 0:
                sample.loc[:, f"{depVar}T+{i}"] = sample.merge(dirFirm[["Symbol", "AsOnYear", f"{depVar}_2"]].copy(), left_on = ["Symbol", f"AsOnYear_T+{i}"],
                                                              right_on = ["Symbol", "AsOnYear"], how = "left")[f"{depVar}_2"]
        
        for i in range(1, 4):
            if i != 0:
                sample.loc[:, depVar+f"(T+{i}) - (T-1)"] = sample[f"{depVar}T+{i}"] - sample[f"{depVar}T+-1"]
    
            
        sample = sample.copy()
    
    group1 = sample.loc[ sample[endog_var] == 1].copy()
    group2 = sample.loc[ sample[endog_var] == 0].copy()
    
    t_stat, p_value = stats.ttest_ind(group1[car], group2[car], equal_var=False)  # Welch’s t-test (default)

    print("\n")
    print(car, ":")
    print("\n")
    print("T Statistic:", t_stat, " P Value:",p_value)
    print("Treated Mean:", group1[car].mean(), " Control Mean:", group2[car].mean(), " Diff:", group1[car].mean() - group2[car].mean())
    print("Treated Median:", group1[car].median(), " Control Median:", group2[car].median(), " Diff:", group1[car].median() - group2[car].median())
    print("Treated N:", len(group1[car]), "; Control N:", len(group2[car]))
    print("[treated unique = ", len(group1.loc[ :, ["Person Code", "Symbol", "AsOnDate"]].drop_duplicates()), "]",\
          "[control unique = ", len(group2.loc[ :, ["Person Code", "Symbol", "AsOnDate"]].drop_duplicates()), "]"
         )
    print("\n")

    # -----------------------------------------------------------------------------------------------------------------
    
    if exog_var != None:
        print("━"*120)
        print(f'{"Matching Variable":<40} {"Treatment Firms":<20} {"Control Firms":<20} {"Test of Diff (p value)":<20}')
        print(f'{" ":<40} {"N = " + str(len(group1[car])):<20} {"N = " + str(len(group2[car])):<20}')
        print("-"*120)

        for var in exog_var:
            treatMean = group1[var].mean()
            controlMean = group2[var].mean()
            p_value = stats.ttest_ind(group1[var], group2[var], equal_var=False)[1]
            print(f'{var:<40} {treatMean:<20.4f} {controlMean:<20.4f} {p_value:<20.4f}')
    
        print("━"*120, "\n")
    
    # -----------------------------------------------------------------------------------------------------------------


    if depVar != None:
        print(depVar, " across years:\n")
        for i in range(1,4):
            sample = sample.dropna(subset = [depVar+f'(T+{i}) - (T-1)'])
    
        group1 = sample.loc[ sample[endog_var] == 1].copy()
        group2 = sample.loc[ sample[endog_var] == 0].copy()

        print("━"*150, "\n")
        print(f'{depVar:<40}{" ":<20}{"Treatment":<20}{"Control":<20}{"Difference":<20}{"Test of Diff":<20}{"Test of Diff"}')
        print(f'{" ":<120}{"(t stat)":<20}{"(p value)":<20}')
    
        print("─"*150, "\n")
    
        for i in range(1,4):
            t_stat2, p_value2 = stats.ttest_ind(group1[depVar+f'(T+{i}) - (T-1)'], group2[depVar+f'(T+{i}) - (T-1)'], equal_var=False)  # Welch’s t-test (default)
            
            treatedMean = group1[depVar+f'(T+{i}) - (T-1)'].mean()
            controlMean = group2[depVar+f'(T+{i}) - (T-1)'].mean()
            diffMean = treatedMean - controlMean
    
            treatedMedian = group1[depVar+f'(T+{i}) - (T-1)'].median()
            controlMedian = group2[depVar+f'(T+{i}) - (T-1)'].median()
            diffMedian = treatedMedian - controlMedian
    
            print(f'{"Year_T+" + str(i) +" - Year_T-1":<40}{"<MEAN>":<20}{treatedMean:<20.4f}{controlMean:<20.4f}{diffMean:<20.4f}{t_stat2:<20.4f}{p_value2:<20.10f}')
    
            label1 = "Treated N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
            label2 = "Control N: " + str(len(group2[depVar+f'(T+{i}) - (T-1)']))
            
            print(f'{label1 + " "*5 + label2:<40}{"<MEDIAN>":<20}{treatedMedian:<20.4f}{controlMedian:<20.4f}{diffMedian:<20.4f}')
            
            print("-"*150, "\n")
            
        print("━"*150, "\n")

    return

In [12]:
def OneSampleTtest(sample, endog_var, exog_var, car, depVar, dirFirm):

    # if depVar != None:
    #     dirFirm = dirFirm.rename( {depVar:f"{depVar}_2"}, axis = 1)
    
    #     colsAdd = []
    #     for i in range(-1, 4):
    #         if i != 0:
    #             colsAdd.append(f"AsOnYear_T+{i}")
    #             colsAdd.append(f"{depVar}T+{i}")
    #             if i>0 :
    #                 colsAdd.append(depVar+f"(T+{i}) - (T-1)")
    
    #     newFrame= pd.DataFrame(columns = colsAdd, data = 0, index = sample.index, dtype = "int")
    #     sample = pd.concat([sample, newFrame], axis = 1)
    #     sample = sample.copy()
        
    #     for i in range(-1, 4):
    #         if i != 0:
    #             sample.loc[:, f"AsOnYear_T+{i}"] = sample["AsOnYear"] + i
    
    #     for i in range(-1, 4):
    #         if i != 0:
    #             sample.loc[:, f"{depVar}T+{i}"] = sample.merge(dirFirm[["Symbol", "AsOnYear", f"{depVar}_2"]].copy(), left_on = ["Symbol", f"AsOnYear_T+{i}"],
    #                                                           right_on = ["Symbol", "AsOnYear"], how = "left")[f"{depVar}_2"]
        
    #     for i in range(1, 4):
    #         if i != 0:
    #             sample.loc[:, depVar+f"(T+{i}) - (T-1)"] = sample[f"{depVar}T+{i}"] - sample[f"{depVar}T+-1"]
    
            
    #     sample = sample.copy()
    sample[car] = winsorize(sample[car], limits = [0.01, 0.01])
    group1 = sample.copy()
    
    t_stat, p_value = stats.ttest_1samp(group1[car], 0)  # Welch’s t-test (default)
    
    print("\n")
    print(car, ":")
    print("\n")
    print("T Statistic:", t_stat, " P Value:",p_value)
    print("Mean:", group1[car].mean())
    print("Median:", group1[car].median())
    print("N:", len(group1[car]))

    print("\n")

    # -----------------------------------------------------------------------------------------------------------------




    # if exog_var != None:
    #     print("━"*120)
    #     print(f'{"Matching Variable":<40} {"Treatment Firms":<20} {"Control Firms":<20} {"Test of Diff (p value)":<20}')
    #     print(f'{" ":<40} {"N = " + str(len(group1[car])):<20} {"N = " + str(len(group2[car])):<20}')
    #     print("-"*120)

    #     for var in exog_var:
    #         treatMean = group1[var].mean()
    #         controlMean = group2[var].mean()
    #         p_value = stats.ttest_ind(group1[var], group2[var], equal_var=False)[1]
    #         print(f'{var:<40} {treatMean:<20.4f} {controlMean:<20.4f} {p_value:<20.4f}')
    
    #     print("━"*120, "\n")
    
    # -----------------------------------------------------------------------------------------------------------------


    # if depVar != None:
    #     print(depVar, " across years:\n")
    #     for i in range(1,4):
    #         sample = sample.dropna(subset = [depVar+f'(T+{i}) - (T-1)'])
    
    #     group1 = sample.loc[ sample[endog_var] == 1].copy()
    #     group2 = sample.loc[ sample[endog_var] == 0].copy()

    #     print("━"*150, "\n")
    #     print(f'{depVar:<40}{" ":<20}{"Treatment Firms":<20}{"Control Firms":<20}{"Difference":<20}{"Test of Diff":<20}{"Test of Diff"}')
    #     print(f'{" ":<120}{"(t stat)":<20}{"(p value)":<20}')
    
    #     print("─"*150, "\n")
    
    #     for i in range(1,4):
    #         t_stat2, p_value2 = stats.ttest_ind(group1[depVar+f'(T+{i}) - (T-1)'], group2[depVar+f'(T+{i}) - (T-1)'], equal_var=False)  # Welch’s t-test (default)
            
    #         treatedMean = group1[depVar+f'(T+{i}) - (T-1)'].mean()
    #         controlMean = group2[depVar+f'(T+{i}) - (T-1)'].mean()
    #         diffMean = treatedMean - controlMean
    
    #         treatedMedian = group1[depVar+f'(T+{i}) - (T-1)'].median()
    #         controlMedian = group2[depVar+f'(T+{i}) - (T-1)'].median()
    #         diffMedian = treatedMedian - controlMedian
    
    #         print(f'{"Year_T+" + str(i) +" - Year_T-1":<40}{"<MEAN>":<20}{treatedMean:<20.4f}{controlMean:<20.4f}{diffMean:<20.4f}{t_stat2:<20.4f}{p_value2:<20.10f}')
    
    #         label1 = "Treated N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
    #         label2 = "Control N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
            
    #         print(f'{label1 + " "*5 + label2:<40}{"<MEDIAN>":<20}{treatedMedian:<20.4f}{controlMedian:<20.4f}{diffMedian:<20.4f}')
            
    #         print("-"*150, "\n")
            
    #print("━"*150, "\n")

    return

In [13]:
def PsmReplac(sample, endog_var, exog_var, car, depVar, dirFirm):

    # Logit Regression
    sample.loc[:, "propensityScore"] = LogitReg(sample, endog_var, exog_var)

    treated = sample.loc[ sample[endog_var] == 1].copy()
    control = sample.loc[ sample[endog_var] == 0].copy()

    # Nearest Neighbours
    nn = NearestNeighbors(n_neighbors = 1, metric = "euclidean")
    nn.fit(control[["propensityScore"]])

    distances, indices = nn.kneighbors(treated[["propensityScore"]])
    
    matchedControl = control.iloc[indices.flatten()].copy()
    
    matched = pd.concat([treated, matchedControl])
    matched.reset_index(drop=True, inplace=True)

    MeanDiffTtest(matched, endog_var, exog_var, car, depVar, dirFirm)

    return

In [14]:
# Func PSM non replacement
def PsmNonReplac(sample, endog_var, exog_var, car, depVar, dirFirm):

    # Logit Regression
    sample.loc[:, "propensityScore"] = LogitReg(sample, endog_var, exog_var)

    # Separate treated and control groups
    treated = sample[sample[endog_var] == 1].copy()
    control = sample[sample[endog_var] == 0].copy()
    
    # Compute pairwise distances (absolute difference in propensity scores)
    dist_matrix = cdist(treated[['propensityScore']], control[['propensityScore']], metric='euclidean')
    
    # Match without replacement
    treated_indices = []
    matched_indices = []
    used_control_indices = set()
    
    for i in range(len(treated)):
        if len(used_control_indices) >= len(control):  # Stop if no controls left
            print("Warning: Not enough control units to match all treated units.")
            break
        
        # Get nearest control unit index that hasn't been used
        match_idx = np.argmin(dist_matrix[i])
        
        while match_idx in used_control_indices:  # Ensure it's not already matched
            dist_matrix[i, match_idx] = np.inf  # Temporarily set distance to infinity

            if np.all(dist_matrix[i] == np.inf):  # If all controls are exhausted
                print(f"No available control for treated unit {i}, skipping.")
                match_idx = None
                break
            
            match_idx = np.argmin(dist_matrix[i])
        
        used_control_indices.add(match_idx)
        matched_indices.append(match_idx)
        treated_indices.append(i)
    
    # Retrieve matched units
    matched_control = control.iloc[matched_indices].copy()
    matched_treated = treated.iloc[treated_indices].copy()
    
    # Combine matched treated and control units
    matched_data = pd.concat([matched_treated.reset_index(drop=True), matched_control.reset_index(drop=True)])
    
    # Reset index
    matched_data.reset_index(drop=True, inplace=True)


    # Mean difference and T Test
    MeanDiffTtest(matched_data, endog_var, exog_var, car, depVar, dirFirm)

    return

In [15]:
psmSampleIndep

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships,DummySum,DummySumIndep
0,62,20MICRONS,20 MICRONS LTD.,2015-03-31,2015,INE144J01027,P00064917,MS.,DARSHA,RAJESH,KIKANI,1957-09-01,F,INDIA,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: LL.B.,"POST GRADUATE: COMPANY SECRETARY,INSTITUTE OF ...","POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF COMP...","POST GRADUATE: M.B.A.,GUJARAT UNIVERSITY,AHMED...","POST GRADUATE: MEMBER,INSTITUTE OF CHARTERED S...","POST GRADUATE: P.G.PROGRAM-EXECUTIVE,INDIAN IN...",NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,20 MICRONS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MRS. DARSHA R. KIKANI, THE INDEPENDENT DIRECTO...",NaT,NaT,Y,2014-08-06,NaT,NaT,2016-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,0.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,237.0,0.0,237.0,0.0,0.0,0.0,0.0,0.0,237.0,0.0,237.0,237,(),"{(20MICRONS, Y)}","{(20MICRONS, Y), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,67,0.649315,0.649315,0.649315,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{corporate governance, industrials, finance, p...",GRADUATE: LL.B. POST GRADUATE: COMPANY SECRETA...,1,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{corporate governance},"{'corporate governance', 'industrials', 'opera...",0,1,<NA>,12,0,0,0,1,0,0,0,False,False,False,False,True,True,True,True,False,False,True,True,True,True,False,True,True,0,False,True,False,False,False,True,True,True,False,False,False,True,True,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,6.0,3.0,0.500000,Appointment Date,2014-08-06,11.0,31.15,-0.011111,0.022705,-0.690542,-0.667837,1.023324,-0.182707,-0.035800,0.010683,0.006169,0.001164,0.121640,0.098924,1.725805e-03,0.020884,-0.055292,-0.141493,-0.282114,-0.035619,0.008433,0.006457,0.001327,0.084912,0.066109,4.638373e-03,0.019308,-0.057342,-0.145741,-0.284504,-0.035592,0.008052,0.006294,0.002610,0.076637,0.060898,2.808170e-03,0.018383,-0.057725,-0.144865,-0.280436,-0.036365,0.006364,0.006151,0.003198,0.065439,0.051829,2.939000e-03,0.020019,-0.056337,-0.144163,-0.277777,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2014,4.219508,0.000000,1,1
1,69,20MICRONS,20 MICRONS LTD.,2015-03-31,2015,INE144J01027,P00066605,DR.(MR.),AJAY,ISHWARLAL,RANKA,1956-10-24,M,INDIA,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,DOCTORATE: PH.D.-POLYMER SCIENCE & ENGINEERING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,20 MICRONS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,POLYMER CHEMISTRY & NANOTECHNOLOGY.,NaT,NaT,Y,2014-09-27,NaT,NaT,2016-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,0.0,185.0,0.0,0.0,0.0,0.0,0.0,0.0,185.0,0.0,185.0,0.0,0.0,0.0,0.0,0.0,185.0,0.0,185.0,185,(),"{(20MICRONS, Y)}","{(20MICRONS, Y), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,68,0.506849,0.506849,0.506849,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{corporate governance, research & development,...",DOCTORATE: PH.D.-POLYMER SCIENCE & ENGINEERING,0,1,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'operations', 'legal/...",1,1,<NA>,11,0,0,0,1,1,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,6.0,1.0,0.833333,Appointment Date,2014-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2014,4.234107,0.000000,1,1
2,115,20MICRONS,20 MICRONS LTD.,2020-03-31,2020,INE144J01027,P00093936,MR.,JAIDEEP,BHANUSHANKAR,VERMA,1967-11-02,M,INDIA,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.S.L.,"GRADUATE: DIPLOMA-CONSUMER PROTECTION LAWS,SAV...","GRADUATE: LL.B.,SYMBIOSIS LAW SCHOOL,PUNE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,<NA>,20 MICRONS LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR. JAIDEEP VERMA, HAS BAGGED BSL, LLB DEGREES...",2029-05-27,NaT,Y,2019-05-28,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,0.0,308.0,0.0,0.0,0.0,0.0,0.0,0.0,308.0,0.0,308.0,0.0,0.0,0.0,0.0,0.0,308.0,0.0,308.0,308,(),"{(20MICRONS, Y)}","{(20MICRONS, Y), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,57,0.843836,0.843836,0.843836,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{corporate governance, research & development,...",GRADUATE: B.S.L. GRADUATE: DIPLOMA-CONSUMER PR...,0,0,{},{08},{08},{08},{},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'operations', 'legal/...",1,1,<NA>,11,0,0,0,1,0,0,0,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,True,False,False,True,True,True,False,True,False,False,True,False,False,False,False,False,[nomination & remuneration committee],False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,1,1,0,0,1,0,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,5.0,4.0,0.200000,Appointment Date,2019-05-28,11.0,41.00,-0.016787,0.016873,0.367905,0.384778,-0.177790,0.292518,-0.025666,0.014600,0.013163,0.003634,0.308224,0.290333,2.555217e-09,0.022322,0.014419,-0.011471,-0.115625,-0.025053,0.015349,0.011943,0.002961,0.361151,0.348024,3.667411e-14,0.022079,0.014219,-0.012937,-0.117117,-0.023995,0.016299,0.012980,0.002108,0.329361,0.317930,3.320964e-15,0.016598,0.006196,-0.020455,-0.124292,-0.024276,0.015716,0.012604,0.001488,0.334962,0.325277,3.803786e-18,0.018415,0.009655,-0.017933,-0.122470,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2019,4.060443,0.000000,1,1
3,145,20MICRONS,20 MICRONS LTD.,2024-03-31,2024,INE144J01027,P00004449,DR.(MR.),SIVARAM,NaN,SWAMINATHAN,1946-11-04,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.SC.-CHEMISTRY,MADRAS CHRISTIAN COL...","POST GRADUATE: M.SC.-CHEMISTRY,INDIAN INSTITUT...","DOCTORATE: D.SC.-HC,PURDUE UNIVERSITY,WEST LAF...","DOCTORATE: PH.D.-CHEMISTRY,PURDUE UNIVERSITY,W...","DOCTORATE: PH.D.-HONORIS CAUSA,PURDUE UNIVERSI...",NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,COMMODITIES,CONSUMER D...",SCIENTIST,<NA>,20 MICRONS LTD.,APCOTEX INDUSTRIES LTD.,SUPREME PETROCHEM LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,DR. SIVARAM SWAMINATHAN HE HAS TOTAL EXPERIENC...,2028-08-09,NaT,Y,2023-05-16,2024-03-31,NaT,NaT,1,0.0,1.0,1.0,1,0.0,0.0,0.0,0.0,320.0,0.0,0.0,0.0,0.0,0.0,0.0,320.0,0.0,320.0,0.0,0.0,0.0,0.0,0.0,320.0,0.0,320.0,10224,"((APCOTEXIND, U), (ASIANPAINT, Y), (GMMPFAUDLR...","{(20MICRONS, Y), (APCOTEXIND, Y), (SPLPETRO, Y)}","{(20MICRONS, Y), (20MICRONS, U), (APCOTEXIND, ...","((APCOTEXIND, U), (ASIANPAINT, Y), (GMMPFAUDLR...","((APCOTEXIND, U), (ASIANPAINT, Y), (GMMPFAUDLR...",2,3,0,5,2,3,0,5,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,78,0.876712,0.876712,28.010959,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{public policy, corporate governance, industri...","GRADUATE: B.SC.-CHEMISTRY,MADRAS CHRISTIAN COL...",0,1,"{20221, 20132, 20119, 20131, 28230}","{20132, 20131, 08}","{20132, 20131, 08}","{20221, 20132, 08, 20119, 20131, 28230}","{20, 28}","{20, 28, 08}",0,0,0,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'industrials', 'commo...",1,1,"{ASIANPAINT, SPLPETRO, APCOTEXIND, DEEPAKNTR, ...",18,5,5,0,1,1,1,0,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,True,True,False,False,False,True,False,False,NaN,False,False,True,False,False,True,True,False,False,False,False,False,False,True,False,False,False,0,0,0,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,0,1,0,1,1,1,0,0,0,1,0,0,1,0,0,1,1,1,0,5.0,5.0,0.000000,Appointment Date,2023-05-16,11.0,82.20,-0.000608,0.018393,-0.219663,-0.201270,0.165950,0.576497,-0.025381,0.016867,0.011721,-0.002704,0.340604,0.323551,1.661638e-10,-0.036008,-0.053042,-0.091451,-0.178843,-0.025469,0.016218,0.013162,0.000602,0.344839,0.331377,2.259487e-13,-0.039284,-0.057280,-0.093892,-0.174149,-0.023337,0.016367,0.013252,0.001910,0.250587,0.237812,5.112479e-11,-0.046524,-0.063954,-0.099904,-0.178706,-0.023586,0.014998,0.013664,0.007173,0.313242,0.303240,1.008558e-16,-0.050052,-0.067146,-0.099406,-0.169350,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2023,4.369448,1.791759,1,1
4,149,360ONE,360 ONE WAM LTD.,2020-03-31,2020,INE466L01038,P00049804,MS.,GEETA,NaN,MATHUR,1966-11-21,F,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.(HONS.),SHRI RAM COLLEGE OF CO...",POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),"POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),INST...",POST GRADUATE: F.C.A.(FELLOW CHARTERED ACCOUNT...,"POST GRADUATE: MEMBER,INSTITUTE OF CHARTERED A...",NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",<NA>,<NA>,360 ONE WAM LTD.,IIFL FINANCE LTD.,INFO EDGE (INDIA) LTD.,JTEKT INDIA LTD.,NIIT LTD.,SAMVARDHANA MOTHERSON INTERNATIONAL LTD.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,GEETA MATHUR IS AN INDEPENDENT DIRECTOR ON THE...,2025-03-02,NaT,Y,2015-03-03,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,0.0,1855.0,0.0,0.0,1490.0,0.0,1490.0,0.0,1855.0,0.0,1855.0,0.0,1490.0,0.0,1490.0,0.0,1855.0,0.0,1855.0,2249,"((RSWM, Y), (NIITLTD, Y), (MOTHERSON, Y), (MAR...","{(MOTHERSON, Y), (NIITLTD, Y), (IIFL, Y), (JTE...","{(MOTHERSON, Y), (NIITLTD, Y), (NIITLTD, U), (...","((RSWM, Y), (MARALOVER, Y), (VARDHACRLC, Y))","((RSWM, Y), (MARALOVER, Y), (VARDHACRLC, Y))",0,3,0,3,0,3,0,3,0,8,0,8,1,8,0,9,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,58,5.082192,5.082192,6.161644,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,360ONE,64300,Public Ltd.,IIFL Group,2.010103e+10,384392.0,360 One Wam Ltd.,0,1,"{public policy, international business, consum...","GRADUATE: B.COM.(HONS.),SHRI RAM COLLEGE OF CO...",0,0,"{20302, 13131, 29301, 62013, 29304, 13111, 64191}","{82990, 29301, 64300, 62013, 29304, 2710, 6419...","{82990, 29301, 64300, 62013, 29304, 2710, nan,...","{13131, 20302, 82990, 29301, nan, 64300, 62013...","{29, 20, 13, 64, 62}","{29, 20, 82, 27, 13, 64, 62}",1,1,1,0,0,0,1,1,0,1,0,{},{},"{risk management, finance}","{'corporate governance', 'finance', 'research ...",1,1,"{IIFL, MARALOVER, VARDHACRLC, JTEKTINDIA, MOTH...",22,7,7,0,1,0,1,1,True,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,True,0,True,True,False,False,True,True,True,True,True,True,True,False,True,True,False,True,True,"[nomination & remuneration committee, risk man...",True,True,True,False,False,True,True,True,False,False,False,False,False,True,False,False,False,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,1,0,1,1,0,1,1,1,1,0,9.0,8.0,0.111111,Appointment Date,2015-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2015,4.077537,1.386294,1,1

# CAR Plots

### Total Sample

In [16]:
test = psmSampleIndep.copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Date of Study"]].plot(kind = "scatter", x="Date of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

### RID

In [17]:
test = psmSampleIndep.loc[ psmSampleIndep["IsRookieIndep"] == 1 ].copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Date of Study"]].plot(kind = "scatter", x="Date of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

In [18]:
# test.describe()

### Non RID

In [19]:
test = psmSampleIndep.loc[ psmSampleIndep["IsRookieIndep"] == 0 ].copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Date of Study"]].plot(kind = "scatter", x="Date of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

## Panel A: Whole Sample

### Mean Difference

In [20]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    sample = psmSampleIndep.dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

120CAR3 :


T Statistic: -0.486175496047491  P Value: 0.6268634022433054
Treated Mean: -0.0013234874789001861  Control Mean: -0.0006255537192905486  Diff: -0.0006979337596096375
Treated Median: -0.004346557679585403  Control Median: -0.003439614781977386  Diff: -0.0009069428976080166
Treated N: 5851 ; Control N: 2522
[treated unique =  5851 ] [control unique =  2522 ]




120CAR5 :


T Statistic: -1.1309948444317472  P Value: 0.25810862492772335
Treated Mean: -0.05091081051252594  Control Mean: -0.04889777742148409  Diff: -0.002013033091041852
Treated Median: -0.05290124491400665  Control Median: -0.05181485356787635  Diff: -0.001086391346130297
Treated N: 5849 ; Control N: 2520
[treated unique =  5849 ] [control unique =  2520 ]




120CAR7 :


T Statistic: -1.496433651764629  P Value: 0.13460030762647787
Treated Mean: -0.09993503524119154  Control Mean: -0.09672327744239095  Diff: -0.0032117577988005908
Treated Median: -0.0998726914488782  Control Median: -0.09800070562237295  Diff: -0.0018719858265052458
Treated N: 5847 ; Control N: 2518
[treated unique =  5847 ] [control unique =  2518 ]




120CAR11 :


T Statistic: -1.8652405682799886  P Value: 0.062201494762196156
Treated Mean: -0.1946497234530044  Control Mean: -0.1894615925020029  Diff: -0.005188130951001513
Treated Median: -0.19937281348381794  Control Median: -0.19393332205037905  Diff: -0.005439491433438887
Treated N: 5840 ; Control N: 2515
[treated unique =  5840 ] [control unique =  2515 ]




150CAR3 :


T Statistic: -0.43453496699406974  P Value: 0.6639182746465442
Treated Mean: -0.0011690329866115982  Control Mean: -0.0005453316840128637  Diff: -0.0006237013025987344
Treated Median: -0.004047237877553955  Control Median: -0.0031931828677723654  Diff: -0.0008540550097815899
Treated N: 5829 ; Control N: 2510
[treated unique =  5829 ] [control unique =  2510 ]




150CAR5 :


T Statistic: -1.1061066761827738  P Value: 0.2687308894075804
Treated Mean: -0.05094853512873217  Control Mean: -0.048984872054065993  Diff: -0.0019636630746661735
Treated Median: -0.05333764968322023  Control Median: -0.05179004197886029  Diff: -0.0015476077043599379
Treated N: 5827 ; Control N: 2508
[treated unique =  5827 ] [control unique =  2508 ]




150CAR7 :


T Statistic: -1.38903854052815  P Value: 0.16487980588849116
Treated Mean: -0.09977773506623776  Control Mean: -0.09679524897170551  Diff: -0.0029824860945322496
Treated Median: -0.10123541790551616  Control Median: -0.09814936586074718  Diff: -0.003086052044768972
Treated N: 5826 ; Control N: 2506
[treated unique =  5826 ] [control unique =  2506 ]




150CAR11 :


T Statistic: -1.8046365743403763  P Value: 0.07118702711205382
Treated Mean: -0.1944424194638916  Control Mean: -0.18940701541478372  Diff: -0.005035404049107878
Treated Median: -0.198822719290225  Control Median: -0.19285751719138897  Diff: -0.0059652020988360255
Treated N: 5819 ; Control N: 2503
[treated unique =  5819 ] [control unique =  2503 ]




180CAR3 :


T Statistic: -0.5150503227267904  P Value: 0.6065401187331148
Treated Mean: -0.0013484031546994672  Control Mean: -0.0006100392847631412  Diff: -0.000738363869936326
Treated Median: -0.003980319747193636  Control Median: -0.002964193603639989  Diff: -0.0010161261435536473
Treated N: 5792 ; Control N: 2499
[treated unique =  5792 ] [control unique =  2499 ]




180CAR5 :


T Statistic: -1.1794154582987204  P Value: 0.23828613961873307
Treated Mean: -0.05116633960924566  Control Mean: -0.04906295435766724  Diff: -0.002103385251578417
Treated Median: -0.05341455034418338  Control Median: -0.052087810204666435  Diff: -0.0013267401395169465
Treated N: 5790 ; Control N: 2497
[treated unique =  5790 ] [control unique =  2497 ]




180CAR7 :


T Statistic: -1.5042272856360206  P Value: 0.1325830191538561
Treated Mean: -0.09990768952715388  Control Mean: -0.09666456207302344  Diff: -0.00324312745413044
Treated Median: -0.10140829635514159  Control Median: -0.09771279124364424  Diff: -0.0036955051114973547
Treated N: 5789 ; Control N: 2495
[treated unique =  5789 ] [control unique =  2495 ]




180CAR11 :


T Statistic: -1.7879299201815353  P Value: 0.07384356701972081
Treated Mean: -0.19440088601811117  Control Mean: -0.1893862228081137  Diff: -0.005014663209997466
Treated Median: -0.1981288657731039  Control Median: -0.19452271945683847  Diff: -0.003606146316265435
Treated N: 5782 ; Control N: 2492
[treated unique =  5782 ] [control unique =  2492 ]




210CAR3 :


T Statistic: -0.4318265079100103  P Value: 0.6658857356888521
Treated Mean: -0.0010433094078770811  Control Mean: -0.00042504783544515545  Diff: -0.0006182615724319257
Treated Median: -0.003285969603807115  Control Median: -0.0028091757686475455  Diff: -0.00047679383515956963
Treated N: 5767 ; Control N: 2488
[treated unique =  5767 ] [control unique =  2488 ]




210CAR5 :


T Statistic: -1.042203450608614  P Value: 0.2973656757006715
Treated Mean: -0.05071105228790161  Control Mean: -0.0488499406295153  Diff: -0.0018611116583863094
Treated Median: -0.05305057355913748  Control Median: -0.05197853651423228  Diff: -0.0010720370449052025
Treated N: 5765 ; Control N: 2486
[treated unique =  5765 ] [control unique =  2486 ]




210CAR7 :


T Statistic: -1.3340759211724964  P Value: 0.18223720387787865
Treated Mean: -0.09934206541908007  Control Mean: -0.09646955963425323  Diff: -0.00287250578482684
Treated Median: -0.10135977193319501  Control Median: -0.09753370193290858  Diff: -0.0038260700002864245
Treated N: 5764 ; Control N: 2484
[treated unique =  5764 ] [control unique =  2484 ]




210CAR11 :


T Statistic: -1.530292466149847  P Value: 0.12600358890109084
Treated Mean: -0.19373527911496966  Control Mean: -0.18943184035770652  Diff: -0.004303438757263134
Treated Median: -0.1984230368840691  Control Median: -0.1938227304695539  Diff: -0.004600306414515198
Treated N: 5757 ; Control N: 2481
[treated unique =  5757 ] [control unique =  2481 ]

In [21]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)

In [22]:
psmSampleIndep["Person Code"].nunique()

10145

### One Sample T Test

In [23]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsIndep"] == 1].copy()
    print("All Independent Directors:")
    sample = sample1.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsIndep", exog_var, car, depVar, dirFirm)
    
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors:")
    sample = sample1.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors:")
    sample = sample2.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

All Independent Directors:


120CAR3 :


T Statistic: -1.6365122610757261  P Value: 0.10177000885080854
Mean: -0.0011132654626890904
Median: -0.00396743040244113
N: 8373


Rookie Independent Directors:


120CAR3 :


T Statistic: -1.600659863874034  P Value: 0.10950627183557417
Mean: -0.0013398569755964814
Median: -0.004346557679585403
N: 5851

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Non Rookie Independent Directors:


120CAR3 :


T Statistic: -0.48325112304427364  P Value: 0.6289594055597285
Mean: -0.0005588479775951244
Median: -0.003439614781977386
N: 2522


All Independent Directors:


120CAR5 :


T Statistic: -59.036163304003246  P Value: 0.0
Mean: -0.05030466361451835
Median: -0.052521655062125666
N: 8369

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors:


120CAR5 :


T Statistic: -48.169267512255864  P Value: 0.0
Mean: -0.05088141809905922
Median: -0.05290124491400665
N: 5849


Non Rookie Independent Directors:


120CAR5 :


T Statistic: -34.672626009263524  P Value: 1.0452583997221248e-215
Mean: -0.048957433642003244
Median: -0.05181485356787635
N: 2520


All Independent Directors:


120CAR7 :


T Statistic: -96.18773352394473  P Value: 0.0
Mean: -0.09896824431024355
Median: -0.09922864851237534
N: 8365


Rookie Independent Directors:


120CAR7 :


T Statistic: -77.99064034663081  P Value: 0.0
Mean: -0.0997499234970998
Median: -0.0998726914488782
N: 5847


Non Rookie Independent Directors:


120CAR7 :


T Statistic: -57.17451140841131  P Value: 0.0
Mean: -0.09690051871030902
Median: -0.09800070562237295
N: 2518

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

All Independent Directors:


120CAR11 :


T Statistic: -143.12174309268212  P Value: 0.0
Mean: -0.19308800599737677
Median: -0.19811658040842217
N: 8355


Rookie Independent Directors:


120CAR11 :


T Statistic: -114.80084966871134  P Value: 0.0
Mean: -0.19433986156109337
Median: -0.19937281348381794
N: 5840


Non Rookie Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR11 :


T Statistic: -87.35114189819723  P Value: 0.0
Mean: -0.18972857655875952
Median: -0.19393332205037905
N: 2515


All Independent Directors:


150CAR3 :


T Statistic: -1.4426875693638144  P Value: 0.14914606551865567
Mean: -0.000981301811467957
Median: -0.0038355214991585285
N: 8339


Rookie Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR3 :


T Statistic: -1.4688022500307691  P Value: 0.14194040525057902
Mean: -0.0012270434072968737
Median: -0.004047237877553955
N: 5829


Non Rookie Independent Directors:


150CAR3 :


T Statistic: -0.468964065183694  P Value: 0.639136066563263
Mean: -0.0005408987946048264
Median: -0.0031931828677723654
N: 2510


All Independent Directors:


150CAR5 :


T Statistic: -59.20747317973906  P Value: 0.0
Mean: -0.05035766926295379
Median: -0.05279047263393177
N: 8335

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors:


150CAR5 :


T Statistic: -48.12873958877103  P Value: 0.0
Mean: -0.05094591559198056
Median: -0.05333764968322023
N: 5827


Non Rookie Independent Directors:


150CAR5 :


T Statistic: -34.851589866659644  P Value: 2.3470439235751494e-217
Mean: -0.04894271200848243
Median: -0.05179004197886029
N: 2508


All Independent Directors:


150CAR7 :


T Statistic: -96.10473248352517  P Value: 0.0
Mean: -0.09888069832201093
Median: -0.10046250773139853
N: 8332


Rookie Independent Directors:


150CAR7 :


T Statistic: -77.75607008761067  P Value: 0.0
Mean: -0.09953693389840197
Median: -0.10123541790551616
N: 5826


Non Rookie Independent Directors:


150CAR7 :


T Statistic: -57.23475600137749  P Value: 0.0
Mean: -0.09693427179004994
Median: -0.09814936586074718
N: 2506


All Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR11 :


T Statistic: -142.4522853254148  P Value: 0.0
Mean: -0.19292792579230822
Median: -0.197855870336143
N: 8322


Rookie Independent Directors:


150CAR11 :


T Statistic: -114.05610626354803  P Value: 0.0
Mean: -0.19413505614329848
Median: -0.198822719290225
N: 5819


Non Rookie Independent Directors:


150CAR11 :


T Statistic: -87.08999104050187  P Value: 0.0
Mean: -0.18960847749259396
Median: -0.19285751719138897
N: 2503

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

All Independent Directors:


180CAR3 :


T Statistic: -1.6567855983490396  P Value: 0.09760067189856204
Mean: -0.0011258520377086484
Median: -0.003590150974166567
N: 8291


Rookie Independent Directors:


180CAR3 :


T Statistic: -1.6383637781242566  P Value: 0.1014001558255794
Mean: -0.0013694352472754347
Median: -0.003980319747193636
N: 5792


Non Rookie Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR3 :


T Statistic: -0.4597065286076375  P Value: 0.6457668878593483
Mean: -0.0005322373286701839
Median: -0.002964193603639989
N: 2499


All Independent Directors:


180CAR5 :


T Statistic: -59.06384983931382  P Value: 0.0
Mean: -0.05053255742351001
Median: -0.05303581561323166
N: 8287


Rookie Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR5 :


T Statistic: -48.13639950878858  P Value: 0.0
Mean: -0.0511772597915109
Median: -0.05341455034418338
N: 5790


Non Rookie Independent Directors:


180CAR5 :


T Statistic: -34.81719231023445  P Value: 7.690294338956022e-217
Mean: -0.04908415065606385
Median: -0.052087810204666435
N: 2497


All Independent Directors:


180CAR7 :


T Statistic: -95.68503079789022  P Value: 0.0
Mean: -0.0989309146601747
Median: -0.10046419115739205
N: 8284


Rookie Independent Directors:


180CAR7 :


T Statistic: -77.5808941580033  P Value: 0.0
Mean: -0.09973315202283833
Median: -0.10140829635514159
N: 5789


Non Rookie Independent Directors:


180CAR7 :


T Statistic: -56.76290892469342  P Value: 0.0
Mean: -0.09677145346315413
Median: -0.09771279124364424
N: 2495

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

All Independent Directors:


180CAR11 :


T Statistic: -141.8843615168635  P Value: 0.0
Mean: -0.1928905475216991
Median: -0.19733234972573382
N: 8274


Rookie Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR11 :


T Statistic: -113.74451579384073  P Value: 0.0
Mean: -0.1940858590615014
Median: -0.1981288657731039
N: 5782


Non Rookie Independent Directors:


180CAR11 :


T Statistic: -86.66721867529935  P Value: 0.0
Mean: -0.18973643276421573
Median: -0.19452271945683847
N: 2492


All Independent Directors:


210CAR3 :


T Statistic: -1.2608947096684713  P Value: 0.20738242330831252
Mean: -0.0008569696389842126
Median: -0.0031359241445890196
N: 8255


Rookie Independent Directors:


210CAR3 :


T Statistic: -1.2254234097584915  P Value: 0.22046578277647738
Mean: -0.001026408541516705
Median: -0.003285969603807115
N: 5767


Non Rookie Independent Directors:


210CAR3 :


T Statistic: -0.2765524721827554  P Value: 0.7821467437892936
Mean: -0.0003189967844822851
Median: -0.0028091757686475455
N: 2488

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

All Independent Directors:


210CAR5 :


T Statistic: -58.635677828910225  P Value: 0.0
Mean: -0.05015030527750913
Median: -0.05257817342610711
N: 8251


Rookie Independent Directors:


210CAR5 :


T Statistic: -47.815371919276174  P Value: 0.0
Mean: -0.05071046340384537
Median: -0.05305057355913748
N: 5765

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Non Rookie Independent Directors:


210CAR5 :


T Statistic: -34.6704817895112  P Value: 3.4892342658257383e-215
Mean: -0.04891969629105116
Median: -0.05197853651423228
N: 2486


All Independent Directors:


210CAR7 :


T Statistic: -95.43753197183189  P Value: 0.0
Mean: -0.09847697032093386
Median: -0.10023196702983755
N: 8248

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors:


210CAR7 :


T Statistic: -77.25867663337216  P Value: 0.0
Mean: -0.09925909771997832
Median: -0.10135977193319501
N: 5764


Non Rookie Independent Directors:


210CAR7 :


T Statistic: -56.73789068115166  P Value: 0.0
Mean: -0.09663033705647882
Median: -0.09753370193290858
N: 2484

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

All Independent Directors:


210CAR11 :


T Statistic: -141.37208874129234  P Value: 0.0
Mean: -0.19243923255551712
Median: -0.1979060977168538
N: 8238


Rookie Independent Directors:


210CAR11 :


T Statistic: -113.41470234962647  P Value: 0.0
Mean: -0.1934132075664638
Median: -0.1984230368840691
N: 5757


Non Rookie Independent Directors:


210CAR11 :


T Statistic: -86.07504107920747  P Value: 0.0
Mean: -0.18974961406053142
Median: -0.1938227304695539
N: 2481

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

## Panel B: Unique skills dummy

### Mean Difference: RID vs NRID

In [23]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    print("No unique skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

No unique skills:


120CAR3 :


T Statistic: -0.6604880327736614  P Value: 0.5100524926188369
Treated Mean: -0.0032722305073784705  Control Mean: 0.0005797359310105517  Diff: -0.003851966438389022
Treated Median: -0.004585595133571499  Control Median: 0.0023617468228735727  Diff: -0.006947341956445072
Treated N: 1019 ; Control N: 103
[treated unique =  1019 ] [control unique =  103 ]


At least one unique skill:


120CAR3 :


T Statistic: -0.17082612970368952  P Value: 0.8643672282014322
Treated Mean: -0.0009281505192169388  Control Mean: -0.0006722995436929593  Diff: -0.0002558509755239796
Treated Median: -0.004192524835961171  Control Median: -0.0037774340493796216  Diff: -0.0004150907865815498
Treated N: 4832 ; Control N: 2419
[treated unique =  4832 ] [control unique =  2419 ]


No unique skills:


120CAR5 :


T Statistic: 0.7716252167835593  P Value: 0.4416490635009558
Treated Mean: -0.06321951397757535  Control Mean: -0.06906266545613754  Diff: 0.005843151478562195
Treated Median: -0.06237857706929871  Control Median: -0.06475830346483366  Diff: 0.0023797263955349507
Treated N: 1019 ; Control N: 103
[treated unique =  1019 ] [control unique =  103 ]


At least one unique skill:


120CAR5 :


T Statistic: -0.17563551415463322  P Value: 0.8605871410023119
Treated Mean: -0.04832432438792153  Control Mean: -0.048001592219291685  Diff: -0.0003227321686298454
Treated Median: -0.051277095724333185  Control Median: -0.051261449611979065  Diff: -1.5646112354120167e-05
Treated N: 4830 ; Control N: 2417
[treated unique =  4830 ] [control unique =  2417 ]


No unique skills:


120CAR7 :


T Statistic: 1.2548423965485902  P Value: 0.21166305955214923
Treated Mean: -0.11933306354767428  Control Mean: -0.13107951870502932  Diff: 0.011746455157355035
Treated Median: -0.11845993379436442  Control Median: -0.12664919700132177  Diff: 0.008189263206957342
Treated N: 1019 ; Control N: 103
[treated unique =  1019 ] [control unique =  103 ]


At least one unique skill:


120CAR7 :


T Statistic: -0.3272519543028345  P Value: 0.7434905310146436
Treated Mean: -0.09593628620997986  Control Mean: -0.09521584390191401  Diff: -0.0007204423080658523
Treated Median: -0.09688240179738684  Control Median: -0.09751944170788968  Diff: 0.0006370399105028318
Treated N: 4828 ; Control N: 2415
[treated unique =  4828 ] [control unique =  2415 ]


No unique skills:


120CAR11 :


T Statistic: 0.9901527131460202  P Value: 0.3237901456856094
Treated Mean: -0.22808418143280879  Control Mean: -0.2400940514656484  Diff: 0.012009870032839626
Treated Median: -0.23169520097690635  Control Median: -0.24120833699337013  Diff: 0.00951313601646378
Treated N: 1018 ; Control N: 103
[treated unique =  1018 ] [control unique =  103 ]


At least one unique skill:


120CAR11 :


T Statistic: -0.06266244417321831  P Value: 0.9500376537253473
Treated Mean: -0.18731174015443006  Control Mean: -0.18713330581679252  Diff: -0.00017843433763753414
Treated Median: -0.1924758589556249  Control Median: -0.1919126337628324  Diff: -0.0005632251927925047
Treated N: 4822 ; Control N: 2412
[treated unique =  4822 ] [control unique =  2412 ]


No unique skills:


150CAR3 :


T Statistic: -0.6669415989424772  P Value: 0.5059251961957008
Treated Mean: -0.0030662962021857335  Control Mean: 0.0007268828937681615  Diff: -0.003793179095953895
Treated Median: -0.005074685213181093  Control Median: 0.00017156078765075133  Diff: -0.0052462460008318446
Treated N: 1015 ; Control N: 103
[treated unique =  1015 ] [control unique =  103 ]


At least one unique skill:


150CAR3 :


T Statistic: -0.11411149999864476  P Value: 0.9091538934708953
Treated Mean: -0.0008061714296179811  Control Mean: -0.0006354630494064615  Diff: -0.0001707083802115196
Treated Median: -0.00385243688727192  Control Median: -0.003545777694073833  Diff: -0.0003066591931980868
Treated N: 4814 ; Control N: 2407
[treated unique =  4814 ] [control unique =  2407 ]


No unique skills:


150CAR5 :


T Statistic: 0.8075792453027628  P Value: 0.4207086600010198
Treated Mean: -0.06304610953408217  Control Mean: -0.06906743668396047  Diff: 0.006021327149878297
Treated Median: -0.06182044332045783  Control Median: -0.06711552314128695  Diff: 0.005295079820829121
Treated N: 1015 ; Control N: 103
[treated unique =  1015 ] [control unique =  103 ]


At least one unique skill:


150CAR5 :


T Statistic: -0.12187328879714816  P Value: 0.903004088913653
Treated Mean: -0.04832420534226552  Control Mean: -0.048099990911869  Diff: -0.0002242144303965174
Treated Median: -0.05127729451785877  Control Median: -0.0514641486263307  Diff: 0.00018685410847192607
Treated N: 4812 ; Control N: 2405
[treated unique =  4812 ] [control unique =  2405 ]


No unique skills:


150CAR7 :


T Statistic: 1.3034144209866376  P Value: 0.19458397818162676
Treated Mean: -0.11888783245211064  Control Mean: -0.13086687606071234  Diff: 0.011979043608601705
Treated Median: -0.11691066436683752  Control Median: -0.12782557859951335  Diff: 0.010914914232675835
Treated N: 1015 ; Control N: 103
[treated unique =  1015 ] [control unique =  103 ]


At least one unique skill:


150CAR7 :


T Statistic: -0.23956447867282973  P Value: 0.81067741589274
Treated Mean: -0.0958432505537865  Control Mean: -0.0953150296059928  Diff: -0.0005282209477937005
Treated Median: -0.09802295272811565  Control Median: -0.0971291711232069  Diff: -0.0008937816049087444
Treated N: 4811 ; Control N: 2403
[treated unique =  4811 ] [control unique =  2403 ]


No unique skills:


150CAR11 :


T Statistic: 1.0260825397988325  P Value: 0.30659398599516996
Treated Mean: -0.22715788908118753  Control Mean: -0.23961882050247016  Diff: 0.012460931421282628
Treated Median: -0.23047413376197648  Control Median: -0.24131007354315753  Diff: 0.010835939781181053
Treated N: 1014 ; Control N: 103
[treated unique =  1014 ] [control unique =  103 ]


At least one unique skill:


150CAR11 :


T Statistic: -0.04778445996477134  P Value: 0.9618898185458125
Treated Mean: -0.18725629839961233  Control Mean: -0.18711956376095695  Diff: -0.00013673463865537805
Treated Median: -0.19209250288266966  Control Median: -0.19145634812151427  Diff: -0.0006361547611553886
Treated N: 4805 ; Control N: 2400
[treated unique =  4805 ] [control unique =  2400 ]


No unique skills:


180CAR3 :


T Statistic: -0.6011317330554186  P Value: 0.5487411210653133
Treated Mean: -0.003506300944313055  Control Mean: -8.104188550501426e-05  Diff: -0.0034252590588080404
Treated Median: -0.0044699616494608685  Control Median: -0.0011323893468706756  Diff: -0.003337572302590193
Treated N: 1011 ; Control N: 103
[treated unique =  1011 ] [control unique =  103 ]


At least one unique skill:


180CAR3 :


T Statistic: -0.16959809786878327  P Value: 0.8653329639633173
Treated Mean: -0.0009117868049630602  Control Mean: -0.000658201789162158  Diff: -0.0002535850158009022
Treated Median: -0.00390118009922992  Control Median: -0.0029953361415193443  Diff: -0.0009058439577105757
Treated N: 4781 ; Control N: 2396
[treated unique =  4781 ] [control unique =  2396 ]


No unique skills:


180CAR5 :


T Statistic: 0.8685675181258706  P Value: 0.3865694619666651
Treated Mean: -0.06379608930979963  Control Mean: -0.07024454809557638  Diff: 0.006448458785776753
Treated Median: -0.06240864324051776  Control Median: -0.06897806234884883  Diff: 0.006569419108331073
Treated N: 1011 ; Control N: 103
[treated unique =  1011 ] [control unique =  103 ]


At least one unique skill:


180CAR5 :


T Statistic: -0.18028260640775257  P Value: 0.8569377667710362
Treated Mean: -0.048458633845464824  Control Mean: -0.04812599026470288  Diff: -0.000332643580761946
Treated Median: -0.05180832107621397  Control Median: -0.05164692596082056  Diff: -0.00016139511539341178
Treated N: 4779 ; Control N: 2394
[treated unique =  4779 ] [control unique =  2394 ]


No unique skills:


180CAR7 :


T Statistic: 1.3908384301391374  P Value: 0.16648457198993313
Treated Mean: -0.1192992325945275  Control Mean: -0.13200561449671785  Diff: 0.012706381902190353
Treated Median: -0.11855727487887413  Control Median: -0.12980135378388963  Diff: 0.011244078905015498
Treated N: 1011 ; Control N: 103
[treated unique =  1011 ] [control unique =  103 ]


At least one unique skill:


180CAR7 :


T Statistic: -0.3474092982541307  P Value: 0.7282980499539707
Treated Mean: -0.09591356726878668  Control Mean: -0.09514224689980083  Diff: -0.0007713203689858478
Treated Median: -0.09786225611880112  Control Median: -0.09657701507927527  Diff: -0.0012852410395258473
Treated N: 4778 ; Control N: 2392
[treated unique =  4778 ] [control unique =  2392 ]


No unique skills:


180CAR11 :


T Statistic: 1.152798916555399  P Value: 0.2509177407833062
Treated Mean: -0.22742115249429387  Control Mean: -0.24136574915476847  Diff: 0.013944596660474595
Treated Median: -0.23255811317849  Control Median: -0.23307341997877162  Diff: 0.0005153068002816119
Treated N: 1010 ; Control N: 103
[treated unique =  1010 ] [control unique =  103 ]


At least one unique skill:


180CAR11 :


T Statistic: -0.05081148584527902  P Value: 0.9594776646608537
Treated Mean: -0.1871553367652202  Control Mean: -0.18700910750390942  Diff: -0.0001462292613107763
Treated Median: -0.19276379853247572  Control Median: -0.19248888184274218  Diff: -0.0002749166897335342
Treated N: 4772 ; Control N: 2389
[treated unique =  4772 ] [control unique =  2389 ]


No unique skills:


210CAR3 :


T Statistic: -0.6681245399420843  P Value: 0.5051671572660152
Treated Mean: -0.0030537838817892727  Control Mean: 0.0007509967166611533  Diff: -0.003804780598450426
Treated Median: -0.004123331412642314  Control Median: -0.0008085309924912021  Diff: -0.0033148004201511115
Treated N: 1008 ; Control N: 103
[treated unique =  1008 ] [control unique =  103 ]


At least one unique skill:


210CAR3 :


T Statistic: -0.07677676643291753  P Value: 0.9388041583359911
Treated Mean: -0.000597942085424298  Control Mean: -0.0004832952096920014  Diff: -0.00011464687573229662
Treated Median: -0.0031754915433972464  Control Median: -0.0028156150997710044  Diff: -0.00035987644362624194
Treated N: 4759 ; Control N: 2385
[treated unique =  4759 ] [control unique =  2385 ]


No unique skills:


210CAR5 :


T Statistic: 0.8181319197866191  P Value: 0.4146646691081143
Treated Mean: -0.06308145069048869  Control Mean: -0.06908238885899334  Diff: 0.006000938168504652
Treated Median: -0.06118053727890058  Control Median: -0.0662408492533128  Diff: 0.005060311974412222
Treated N: 1008 ; Control N: 103
[treated unique =  1008 ] [control unique =  103 ]


At least one unique skill:


210CAR5 :


T Statistic: -0.03307895331616887  P Value: 0.9736129110246845
Treated Mean: -0.047974139171272016  Control Mean: -0.04791297979597682  Diff: -6.115937529519583e-05
Treated Median: -0.051052852701958945  Control Median: -0.05148111425065577  Diff: 0.0004282615486968233
Treated N: 4757 ; Control N: 2383
[treated unique =  4757 ] [control unique =  2383 ]


No unique skills:


210CAR7 :


T Statistic: 1.3018956231748295  P Value: 0.19507956284140035
Treated Mean: -0.1187175884486346  Control Mean: -0.13045950811502258  Diff: 0.011741919666387976
Treated Median: -0.11887549897121041  Control Median: -0.12713773546769108  Diff: 0.008262236496480668
Treated N: 1008 ; Control N: 103
[treated unique =  1008 ] [control unique =  103 ]


At least one unique skill:


210CAR7 :


T Statistic: -0.14821359947522758  P Value: 0.8821800339861638
Treated Mean: -0.09533021303350331  Control Mean: -0.09500075469238753  Diff: -0.0003294583411157792
Treated Median: -0.09727143632788512  Control Median: -0.09670341111172942  Diff: -0.0005680252161557042
Treated N: 4756 ; Control N: 2381
[treated unique =  4756 ] [control unique =  2381 ]


No unique skills:


210CAR11 :


T Statistic: 1.117282249229718  P Value: 0.2657392286106421
Treated Mean: -0.22666138681812134  Control Mean: -0.24009741278659802  Diff: 0.013436025968476678
Treated Median: -0.23132858680883717  Control Median: -0.2307591940668609  Diff: -0.0005693927419762601
Treated N: 1007 ; Control N: 103
[treated unique =  1007 ] [control unique =  103 ]


At least one unique skill:


210CAR11 :


T Statistic: 0.2022947146988719  P Value: 0.8396942013578734
Treated Mean: -0.18644387810189053  Control Mean: -0.18702711502887087  Diff: 0.0005832369269803406
Treated Median: -0.19256670137796955  Control Median: -0.19278361413172734  Diff: 0.00021691275375779195
Treated N: 4750 ; Control N: 2378
[treated unique =  4750 ] [control unique =  2378 ]

### Mean Difference: within RID/NRID: WIP

In [24]:
# carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
#           "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
#           "180CAR3", "180CAR5", "180CAR7", "180CAR11",
#           "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# exog_var = None
# depVar = None
# controlVars = None

# for car in carCol:
#     print("No unique skills:")
#     sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
#     MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

#     print("At least one unique skill:")
#     sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
#     MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

### One Sample T Test

In [25]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors\nNo unique skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = sample1.loc[sample1["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors\nNo unique skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = sample2.loc[sample2["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

Rookie Independent Directors
No unique skills:


120CAR3 :


T Statistic: -1.4003029083783842  P Value: 0.1617273320289205
Mean: -0.0030541875412564514
Median: -0.004585595133571499
N: 1019


At least one unique skill:


120CAR3 :


T Statistic: -1.0554925999758706  P Value: 0.2912528730805362
Mean: -0.0009531809381539055
Median: -0.004192524835961171
N: 4832


Non Rookie Independent Directors
No unique skills:


120CAR3 :


T Statistic: 0.260511302841984  P Value: 0.7949945919203114
Mean: 0.0013461383560544637
Median: 0.0023617468228735727
N: 103


At least one unique skill:


120CAR3 :


T Statistic: -0.49103981249477785  P Value: 0.6234428516924722
Mean: -0.0005829861922042172
Median: -0.0037774340493796216
N: 2419


Rookie Independent Directors
No unique skills:


120CAR5 :


T Statistic: -21.96312341822861  P Value: 7.958377816462652e-88
Mean: -0.06316391440868917
Median: -0.06237857706929871
N: 1019


At least one unique skill:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR5 :


T Statistic: -42.84721867088302  P Value: 0.0
Mean: -0.048216549522872125
Median: -0.051277095724333185
N: 4830


Non Rookie Independent Directors
No unique skills:


120CAR5 :


T Statistic: -10.122175435233755  P Value: 4.368095535348474e-17
Mean: -0.06836908463763797
Median: -0.06475830346483366
N: 103


At least one unique skill:


120CAR5 :


T Statistic: -33.3165228793851  P Value: 1.337781175017229e-200
Mean: -0.04808838124887803
Median: -0.051261449611979065
N: 2417


Rookie Independent Directors
No unique skills:


120CAR7 :


T Statistic: -33.885159868241914  P Value: 4.0556925861102995e-169
Mean: -0.11944579651457266
Median: -0.11845993379436442
N: 1019


At least one unique skill:


120CAR7 :


T Statistic: -70.73688070333957  P Value: 0.0
Mean: -0.09566378010992733
Median: -0.09688240179738684
N: 4828


Non Rookie Independent Directors
No unique skills:


120CAR7 :


T Statistic: -15.379350926765524  P Value: 2.5244527903561663e-28
Mean: -0.13045966320155725
Median: -0.12664919700132177
N: 103


At least one unique skill:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR7 :


T Statistic: -55.18387383524197  P Value: 0.0
Mean: -0.09537243916381007
Median: -0.09751944170788968
N: 2415


Rookie Independent Directors
No unique skills:


120CAR11 :


T Statistic: -48.13895077712822  P Value: 1.7698813914566011e-264
Mean: -0.22817397100173545
Median: -0.23169520097690635
N: 1018


At least one unique skill:


120CAR11 :


T Statistic: -105.25126465337651  P Value: 0.0
Mean: -0.1870719845686467
Median: -0.1924758589556249
N: 4822


Non Rookie Independent Directors
No unique skills:


120CAR11 :


T Statistic: -21.75056189750101  P Value: 4.268505834125909e-40
Mean: -0.24043838407119922
Median: -0.24120833699337013
N: 103


At least one unique skill:


120CAR11 :


T Statistic: -85.00405621162909  P Value: 0.0
Mean: -0.18744281990866757
Median: -0.1919126337628324
N: 2412


Rookie Independent Directors
No unique skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR3 :


T Statistic: -1.3641460571745347  P Value: 0.17282429947195402
Mean: -0.0029277047939958393
Median: -0.005074685213181093
N: 1015


At least one unique skill:


150CAR3 :


T Statistic: -0.9586446512760224  P Value: 0.3377859426163897
Mean: -0.000864786176210247
Median: -0.00385243688727192
N: 4814


Non Rookie Independent Directors
No unique skills:


150CAR3 :


T Statistic: 0.2758090989683899  P Value: 0.7832527027987352
Mean: 0.001382524141836465
Median: 0.00017156078765075133
N: 103


At least one unique skill:


150CAR3 :


T Statistic: -0.40110768076372155  P Value: 0.6883764644860999
Mean: -0.0004777111595563608
Median: -0.003545777694073833
N: 2407


Rookie Independent Directors
No unique skills:


150CAR5 :


T Statistic: -22.099656711155134  P Value: 1.184820058044387e-88
Mean: -0.0630231123289029
Median: -0.06182044332045783
N: 1015


At least one unique skill:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR5 :


T Statistic: -42.77337839834466  P Value: 0.0
Mean: -0.04828320801501249
Median: -0.05127729451785877
N: 4812


Non Rookie Independent Directors
No unique skills:


150CAR5 :


T Statistic: -10.318054137489714  P Value: 1.609860154565144e-17
Mean: -0.06852800726944941
Median: -0.06711552314128695
N: 103


At least one unique skill:


150CAR5 :


T Statistic: -33.54752706916064  P Value: 1.001362626547737e-202
Mean: -0.04810516732854783
Median: -0.0514641486263307
N: 2405


Rookie Independent Directors
No unique skills:


150CAR7 :


T Statistic: -33.869628877917  P Value: 8.161745077965321e-169
Mean: -0.11896806910301366
Median: -0.11691066436683752
N: 1015


At least one unique skill:


150CAR7 :


T Statistic: -70.53197829694608  P Value: 0.0
Mean: -0.09556860617503675
Median: -0.09802295272811565
N: 4811

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Non Rookie Independent Directors
No unique skills:


150CAR7 :


T Statistic: -15.909349249235689  P Value: 2.1812181087697683e-29
Mean: -0.13067421676050867
Median: -0.12782557859951335
N: 103


At least one unique skill:


150CAR7 :


T Statistic: -55.06600378765676  P Value: 0.0
Mean: -0.09535635233383463
Median: -0.0971291711232069
N: 2403


Rookie Independent Directors
No unique skills:


150CAR11 :


T Statistic: -47.55281541920748  P Value: 2.5995372572007743e-260
Mean: -0.22715788908118753
Median: -0.23047413376197648
N: 1014


At least one unique skill:


150CAR11 :


T Statistic: -104.56166987244286  P Value: 0.0
Mean: -0.18708786268035907
Median: -0.19209250288266966
N: 4805


Non Rookie Independent Directors
No unique skills:


150CAR11 :


T Statistic: -21.644379415146055  P Value: 6.439104434276357e-40
Mean: -0.23982434690548193
Median: -0.24131007354315753
N: 103


At least one unique skill:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR11 :


T Statistic: -84.77622305036833  P Value: 0.0
Mean: -0.18741320649062979
Median: -0.19145634812151427
N: 2400


Rookie Independent Directors
No unique skills:


180CAR3 :


T Statistic: -1.6044305187472088  P Value: 0.10893181261741226
Mean: -0.0034348161824281757
Median: -0.0044699616494608685
N: 1011


At least one unique skill:


180CAR3 :


T Statistic: -1.049262486030559  P Value: 0.2941103735692243
Mean: -0.0009477839266428913
Median: -0.00390118009922992
N: 4781


Non Rookie Independent Directors
No unique skills:


180CAR3 :


T Statistic: 0.10729844998643313  P Value: 0.914762980675394
Mean: 0.0005391445974833382
Median: -0.0011323893468706756
N: 103


At least one unique skill:


180CAR3 :


T Statistic: -0.4390253040453764  P Value: 0.6606828046632898
Mean: -0.0005223657831583808
Median: -0.0029953361415193443
N: 2396

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors
No unique skills:


180CAR5 :


T Statistic: -22.298982885658138  P Value: 6.9041883348606495e-90
Mean: -0.06379656618442062
Median: -0.06240864324051776
N: 1011


At least one unique skill:


180CAR5 :


T Statistic: -42.68380858271875  P Value: 0.0
Mean: -0.04840706190328967
Median: -0.05180832107621397
N: 4779


Non Rookie Independent Directors
No unique skills:


180CAR5 :


T Statistic: -10.528894542947404  P Value: 5.502174073932426e-18
Mean: -0.06979389244817916
Median: -0.06897806234884883
N: 103


At least one unique skill:


180CAR5 :


T Statistic: -33.482498237028175  P Value: 6.335390350707386e-202
Mean: -0.048193935663871194
Median: -0.05164692596082056
N: 2394


Rookie Independent Directors
No unique skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR7 :


T Statistic: -33.915161387645476  P Value: 6.239078139521029e-169
Mean: -0.1193253735840664
Median: -0.11855727487887413
N: 1011


At least one unique skill:


180CAR7 :


T Statistic: -70.15778434063213  P Value: 0.0
Mean: -0.09572534796491693
Median: -0.09786225611880112
N: 4778


Non Rookie Independent Directors
No unique skills:


180CAR7 :


T Statistic: -16.113481830442154  P Value: 8.573289123798925e-30
Mean: -0.1320000937943348
Median: -0.12980135378388963
N: 103


At least one unique skill:


180CAR7 :


T Statistic: -54.90622481538517  P Value: 0.0
Mean: -0.09526324913312491
Median: -0.09657701507927527
N: 2392


Rookie Independent Directors
No unique skills:


180CAR11 :


T Statistic: -47.497581909009355  P Value: 1.5403919363385253e-259
Mean: -0.22743626405762643
Median: -0.23255811317849
N: 1010


At least one unique skill:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR11 :


T Statistic: -104.14997599349701  P Value: 0.0
Mean: -0.18693850339108734
Median: -0.19276379853247572
N: 4772


Non Rookie Independent Directors
No unique skills:


180CAR11 :


T Statistic: -22.004001326697793  P Value: 1.6083804265321292e-40
Mean: -0.24149965010631935
Median: -0.23307341997877162
N: 103


At least one unique skill:


180CAR11 :


T Statistic: -84.29717980879093  P Value: 0.0
Mean: -0.18744367121226693
Median: -0.19248888184274218
N: 2389


Rookie Independent Directors
No unique skills:


210CAR3 :


T Statistic: -1.367938816823082  P Value: 0.17163639921556073
Mean: -0.002955212512219673
Median: -0.004123331412642314
N: 1008


At least one unique skill:


210CAR3 :


T Statistic: -0.7173633623802226  P Value: 0.47318513531977424
Mean: -0.0006491586566423428
Median: -0.0031754915433972464
N: 4759

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Non Rookie Independent Directors
No unique skills:


210CAR3 :


T Statistic: 0.2696156528065666  P Value: 0.7880006434333705
Mean: 0.001346571037814882
Median: -0.0008085309924912021
N: 103


At least one unique skill:


210CAR3 :


T Statistic: -0.2877857163512873  P Value: 0.7735357861982227
Mean: -0.0003411657424972912
Median: -0.0028156150997710044
N: 2385


Rookie Independent Directors
No unique skills:


210CAR5 :


T Statistic: -22.106074347721634  P Value: 1.3696774078677207e-88
Mean: -0.06312735187973582
Median: -0.06118053727890058
N: 1008


At least one unique skill:


210CAR5 :


T Statistic: -42.34756418158831  P Value: 0.0
Mean: -0.04797151165794959
Median: -0.051052852701958945
N: 4757


Non Rookie Independent Directors
No unique skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

210CAR5 :


T Statistic: -10.45642767472372  P Value: 7.956737774537865e-18
Mean: -0.06873767082847768
Median: -0.0662408492533128
N: 103


At least one unique skill:


210CAR5 :


T Statistic: -33.14049668892474  P Value: 2.171475376942131e-198
Mean: -0.04796627196656193
Median: -0.05148111425065577
N: 2383


Rookie Independent Directors
No unique skills:


210CAR7 :


T Statistic: -33.898958627359136  P Value: 1.1366984290034493e-168
Mean: -0.11865656333804639
Median: -0.11887549897121041
N: 1008


At least one unique skill:


210CAR7 :


T Statistic: -69.96669365798674  P Value: 0.0
Mean: -0.09523477705308477
Median: -0.09727143632788512
N: 4756


Non Rookie Independent Directors
No unique skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

210CAR7 :


T Statistic: -16.14477319193486  P Value: 7.433292256316887e-30
Mean: -0.13057201483158512
Median: -0.12713773546769108
N: 103


At least one unique skill:


210CAR7 :


T Statistic: -54.84569644802965  P Value: 0.0
Mean: -0.09516277250935494
Median: -0.09670341111172942
N: 2381


Rookie Independent Directors
No unique skills:


210CAR11 :


T Statistic: -47.25569460908824  P Value: 1.107605589309008e-257
Mean: -0.2267160984233088
Median: -0.23132858680883717
N: 1007


At least one unique skill:


210CAR11 :


T Statistic: -103.77680391596274  P Value: 0.0
Mean: -0.18627246452778726
Median: -0.19256670137796955
N: 4750


Non Rookie Independent Directors
No unique skills:


210CAR11 :


T Statistic: -22.026421378994446  P Value: 1.4758574907546814e-40
Mean: -0.24040818164761713
Median: -0.2307591940668609
N: 103


At least one unique skill:


210CAR11 :


T Statistic: -83.78774633846993  P Value: 0.0
Mean: -0.18740371680220344
Median: -0.19278361413172734
N: 2378

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

In [26]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)

## Panel C: Number of Skills

### Mean Difference

In [27]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

num_skills_median = psmSampleIndep.drop_duplicates(subset = ["AsOnDate", "Person Code"])["NumSkills_gai"].median()
for car in carCol:
    print("Less than median no. skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

Less than median no. skills:


120CAR3 :


T Statistic: -0.9725233146647255  P Value: 0.33121784661851184
Treated Mean: -0.0023172761156445747  Control Mean: 0.0008048108040660466  Diff: -0.0031220869197106215
Treated Median: -0.005169410972389363  Control Median: -0.00010747346534108193  Diff: -0.005061937507048281
Treated N: 3147 ; Control N: 419
[treated unique =  3147 ] [control unique =  419 ]


Greater than median no. skills:


120CAR3 :


T Statistic: 0.5689930690010324  P Value: 0.5693903405145284
Treated Mean: 0.0003455469681746879  Control Mean: -0.0006992522965263488  Diff: 0.0010447992647010366
Treated Median: -0.002402639819990157  Control Median: -0.004034838162761109  Diff: 0.0016321983427709519
Treated N: 2353 ; Control N: 2009
[treated unique =  2353 ] [control unique =  2009 ]


Less than median no. skills:


120CAR5 :


T Statistic: 0.3984999096066665  P Value: 0.690413311484527
Treated Mean: -0.056355352215917205  Control Mean: -0.05794724279635861  Diff: 0.0015918905804414019
Treated Median: -0.05694459232992993  Control Median: -0.060978528693769476  Diff: 0.004033936363839544
Treated N: 3147 ; Control N: 419
[treated unique =  3147 ] [control unique =  419 ]


Greater than median no. skills:


120CAR5 :


T Statistic: 1.009112623629507  P Value: 0.3129769845690676
Treated Mean: -0.044731226635308124  Control Mean: -0.04699993144423952  Diff: 0.0022687048089313974
Treated Median: -0.0478607701921724  Control Median: -0.05027291495418852  Diff: 0.002412144762016122
Treated N: 2351 ; Control N: 2007
[treated unique =  2351 ] [control unique =  2007 ]


Less than median no. skills:


120CAR7 :


T Statistic: 0.5903023635662666  P Value: 0.555227001863776
Treated Mean: -0.10726894472567816  Control Mean: -0.11014392180375986  Diff: 0.0028749770780816947
Treated Median: -0.10610569829553844  Control Median: -0.10607594952034335  Diff: -2.9748775195084787e-05
Treated N: 3147 ; Control N: 419
[treated unique =  3147 ] [control unique =  419 ]


Greater than median no. skills:


120CAR7 :


T Statistic: 1.1709824842404393  P Value: 0.2416702568923303
Treated Mean: -0.09134521507296164  Control Mean: -0.09448806199237078  Diff: 0.003142846919409137
Treated Median: -0.09343032494473358  Control Median: -0.09646062270205857  Diff: 0.0030302977573249956
Treated N: 2350 ; Control N: 2005
[treated unique =  2350 ] [control unique =  2005 ]


Less than median no. skills:


120CAR11 :


T Statistic: 1.546386230346733  P Value: 0.12254617275389515
Treated Mean: -0.20638825972524444  Control Mean: -0.21558272636241238  Diff: 0.009194466637167942
Treated Median: -0.2082773414282721  Control Median: -0.22174349944799043  Diff: 0.013466158019718344
Treated N: 3144 ; Control N: 418
[treated unique =  3144 ] [control unique =  418 ]


Greater than median no. skills:


120CAR11 :


T Statistic: 0.8407706886008391  P Value: 0.4005227814279737
Treated Mean: -0.18182488788592172  Control Mean: -0.18476168733011097  Diff: 0.0029367994441892586
Treated Median: -0.18820647402675872  Control Median: -0.18852306978768935  Diff: 0.0003165957609306269
Treated N: 2346 ; Control N: 2003
[treated unique =  2346 ] [control unique =  2003 ]


Less than median no. skills:


150CAR3 :


T Statistic: -0.9673162114026296  P Value: 0.3338137470870114
Treated Mean: -0.002059429318114883  Control Mean: 0.0010439120686938496  Diff: -0.0031033413868087325
Treated Median: -0.005178524749622215  Control Median: -0.0012684606152124495  Diff: -0.003910064134409766
Treated N: 3135 ; Control N: 417
[treated unique =  3135 ] [control unique =  417 ]


Greater than median no. skills:


150CAR3 :


T Statistic: 0.48240242816023954  P Value: 0.6295445417673091
Treated Mean: 0.00029028647091338566  Control Mean: -0.0005923396464038229  Diff: 0.0008826261173172085
Treated Median: -0.0022970313216678535  Control Median: -0.004110453092502339  Diff: 0.0018134217708344856
Treated N: 2346 ; Control N: 2001
[treated unique =  2346 ] [control unique =  2001 ]


Less than median no. skills:


150CAR5 :


T Statistic: 0.3976006760613971  P Value: 0.6910762100863522
Treated Mean: -0.0562078212617401  Control Mean: -0.0577876823452582  Diff: 0.001579861083518097
Treated Median: -0.057103631436664894  Control Median: -0.060126635923189814  Diff: 0.0030230044865249203
Treated N: 3135 ; Control N: 417
[treated unique =  3135 ] [control unique =  417 ]


Greater than median no. skills:


150CAR5 :


T Statistic: 0.9632603739718215  P Value: 0.33547081023775005
Treated Mean: -0.04476797057278156  Control Mean: -0.046925461089497286  Diff: 0.0021574905167157238
Treated Median: -0.04819149469081087  Control Median: -0.050091998625381065  Diff: 0.0019005039345701968
Treated N: 2344 ; Control N: 1999
[treated unique =  2344 ] [control unique =  1999 ]


Less than median no. skills:


150CAR7 :


T Statistic: 0.47656871945614016  P Value: 0.6338581245244468
Treated Mean: -0.10684071758048475  Control Mean: -0.10918829460108984  Diff: 0.0023475770206050905
Treated Median: -0.10620606754251488  Control Median: -0.10696255950730582  Diff: 0.0007564919647909396
Treated N: 3135 ; Control N: 417
[treated unique =  3135 ] [control unique =  417 ]


Greater than median no. skills:


150CAR7 :


T Statistic: 1.166967270086736  P Value: 0.24328806053585394
Treated Mean: -0.0914076639736529  Control Mean: -0.09452445307030637  Diff: 0.0031167890966534717
Treated Median: -0.09598533836183208  Control Median: -0.09557873865626615  Diff: -0.0004065997055659326
Treated N: 2343 ; Control N: 1997
[treated unique =  2343 ] [control unique =  1997 ]


Less than median no. skills:


150CAR11 :


T Statistic: 1.3105589103571158  P Value: 0.19052188674381754
Treated Mean: -0.20544588549914933  Control Mean: -0.21342967429817306  Diff: 0.007983788799023728
Treated Median: -0.20853265491577677  Control Median: -0.21868943718620082  Diff: 0.010156782270424047
Treated N: 3132 ; Control N: 416
[treated unique =  3132 ] [control unique =  416 ]


Greater than median no. skills:


150CAR11 :


T Statistic: 0.8713084965864804  P Value: 0.38363410909098705
Treated Mean: -0.18162247210837656  Control Mean: -0.18467013060105014  Diff: 0.0030476584926735772
Treated Median: -0.18872862598693513  Control Median: -0.18887429049064358  Diff: 0.00014566450370845363
Treated N: 2339 ; Control N: 1995
[treated unique =  2339 ] [control unique =  1995 ]


Less than median no. skills:


180CAR3 :


T Statistic: -0.815391499526326  P Value: 0.41520390583333067
Treated Mean: -0.0022097899010565677  Control Mean: 0.00039451030794789623  Diff: -0.002604300209004464
Treated Median: -0.004832090728751723  Control Median: -0.0026322307813737567  Diff: -0.002199859947377966
Treated N: 3111 ; Control N: 415
[treated unique =  3111 ] [control unique =  415 ]


Greater than median no. skills:


180CAR3 :


T Statistic: 0.39285244167216604  P Value: 0.6944479386767576
Treated Mean: 0.00021738553469428335  Control Mean: -0.0004999415999368478  Diff: 0.0007173271346311311
Treated Median: -0.00209623397773084  Control Median: -0.003216748998231961  Diff: 0.0011205150205011206
Treated N: 2336 ; Control N: 1993
[treated unique =  2336 ] [control unique =  1993 ]


Less than median no. skills:


180CAR5 :


T Statistic: 0.5596025329459475  P Value: 0.5759754591150592
Treated Mean: -0.05652946558533202  Control Mean: -0.058770963879545245  Diff: 0.0022414982942132247
Treated Median: -0.05771496635124426  Control Median: -0.06035814141362804  Diff: 0.0026431750623837763
Treated N: 3111 ; Control N: 415
[treated unique =  3111 ] [control unique =  415 ]


Greater than median no. skills:


180CAR5 :


T Statistic: 0.8805554033096518  P Value: 0.37860770641634955
Treated Mean: -0.04482446108087088  Control Mean: -0.04679626812069437  Diff: 0.0019718070398234908
Treated Median: -0.049258580185164214  Control Median: -0.049921518279981425  Diff: 0.0006629380948172114
Treated N: 2334 ; Control N: 1991
[treated unique =  2334 ] [control unique =  1991 ]


Less than median no. skills:


180CAR7 :


T Statistic: 0.5148113128764132  P Value: 0.6068918539300685
Treated Mean: -0.10707736489037065  Control Mean: -0.10962006917164634  Diff: 0.00254270428127569
Treated Median: -0.10680513490723254  Control Median: -0.10893024639401822  Diff: 0.00212511148678568
Treated N: 3111 ; Control N: 415
[treated unique =  3111 ] [control unique =  415 ]


Greater than median no. skills:


180CAR7 :


T Statistic: 1.0697949942746043  P Value: 0.2847716638677221
Treated Mean: -0.09135030470414059  Control Mean: -0.09421779017491741  Diff: 0.0028674854707768233
Treated Median: -0.09502233741633603  Control Median: -0.09598033409149612  Diff: 0.0009579966751600832
Treated N: 2333 ; Control N: 1989
[treated unique =  2333 ] [control unique =  1989 ]


Less than median no. skills:


180CAR11 :


T Statistic: 1.3940808848626731  P Value: 0.1638272153314001
Treated Mean: -0.20557640334722896  Control Mean: -0.21410890195294058  Diff: 0.00853249860571162
Treated Median: -0.2090886882456958  Control Median: -0.21860301917050923  Diff: 0.009514330924813436
Treated N: 3108 ; Control N: 414
[treated unique =  3108 ] [control unique =  414 ]


Greater than median no. skills:


180CAR11 :


T Statistic: 0.8101178352484347  P Value: 0.4179172343354327
Treated Mean: -0.18162417480961934  Control Mean: -0.18447444179823858  Diff: 0.0028502669886192322
Treated Median: -0.18789267876675242  Control Median: -0.18950880375161008  Diff: 0.0016161249848576642
Treated N: 2329 ; Control N: 1987
[treated unique =  2329 ] [control unique =  1987 ]


Less than median no. skills:


210CAR3 :


T Statistic: -0.9050826987628419  P Value: 0.3658215171352728
Treated Mean: -0.001985341284164729  Control Mean: 0.0008900206872822933  Diff: -0.002875361971447022
Treated Median: -0.004226458377428723  Control Median: -0.0014509282570572685  Diff: -0.002775530120371454
Treated N: 3101 ; Control N: 413
[treated unique =  3101 ] [control unique =  413 ]


Greater than median no. skills:


210CAR3 :


T Statistic: 0.580102618092939  P Value: 0.5618759257295141
Treated Mean: 0.0006408071169642838  Control Mean: -0.00041736838075766286  Diff: 0.0010581754977219467
Treated Median: -0.0016417049703723041  Control Median: -0.002997660537585045  Diff: 0.001355955567212741
Treated N: 2325 ; Control N: 1985
[treated unique =  2325 ] [control unique =  1985 ]


Less than median no. skills:


210CAR5 :


T Statistic: 0.44811079025135564  P Value: 0.6542480809378164
Treated Mean: -0.05598737563840206  Control Mean: -0.05776939424063069  Diff: 0.0017820186022286313
Treated Median: -0.056840952316300236  Control Median: -0.06108671872207108  Diff: 0.0042457664057708455
Treated N: 3101 ; Control N: 413
[treated unique =  3101 ] [control unique =  413 ]


Greater than median no. skills:


210CAR5 :


T Statistic: 1.1293433320202368  P Value: 0.25881632567274054
Treated Mean: -0.04424428915170156  Control Mean: -0.04678398314778134  Diff: 0.002539693996079777
Treated Median: -0.047643399114914206  Control Median: -0.05018083154937148  Diff: 0.002537432434457275
Treated N: 2323 ; Control N: 1983
[treated unique =  2323 ] [control unique =  1983 ]


Less than median no. skills:


210CAR7 :


T Statistic: 0.4486983181966192  P Value: 0.6538267988574503
Treated Mean: -0.10647695323167432  Control Mean: -0.10868830149696448  Diff: 0.0022113482652901667
Treated Median: -0.1061857698547766  Control Median: -0.10595736387163497  Diff: -0.00022840598314162464
Treated N: 3101 ; Control N: 413
[treated unique =  3101 ] [control unique =  413 ]


Greater than median no. skills:


210CAR7 :


T Statistic: 1.3346094816670167  P Value: 0.18207519812151987
Treated Mean: -0.0906943714392089  Control Mean: -0.09428953471822425  Diff: 0.003595163279015351
Treated Median: -0.09417461036129526  Control Median: -0.09616634438924315  Diff: 0.001991734027947889
Treated N: 2322 ; Control N: 1981
[treated unique =  2322 ] [control unique =  1981 ]


Less than median no. skills:


210CAR11 :


T Statistic: 1.3937853658679322  P Value: 0.1639188446255079
Treated Mean: -0.20487317909654884  Control Mean: -0.21341407986637975  Diff: 0.008540900769830911
Treated Median: -0.20739241908741346  Control Median: -0.2173059032542738  Diff: 0.009913484166860331
Treated N: 3098 ; Control N: 412
[treated unique =  3098 ] [control unique =  412 ]


Greater than median no. skills:


210CAR11 :


T Statistic: 1.0426911862345867  P Value: 0.29715017122140197
Treated Mean: -0.18101868159655307  Control Mean: -0.1847091797791384  Diff: 0.0036904981825853223
Treated Median: -0.18798091103573344  Control Median: -0.18943627929361406  Diff: 0.0014553682578806182
Treated N: 2318 ; Control N: 1979
[treated unique =  2318 ] [control unique =  1979 ]

### One Sample T Test

In [28]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

num_skills_median = psmSampleIndep.drop_duplicates(subset = ["AsOnDate", "Person Code"])["NumSkills_gai"].median()
for car in carCol:
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors\nLess than median no. skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors\nLess than median no. skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

Rookie Independent Directors
Less than median no. skills:


120CAR3 :


T Statistic: -1.944006193793995  P Value: 0.051983744067008106
Mean: -0.002250578856325277
Median: -0.005169410972389363
N: 3147


Greater than median no. skills:


120CAR3 :


T Statistic: -1.944006193793995  P Value: 0.051983744067008106
Mean: -0.002250578856325277
Median: -0.005169410972389363
N: 3147


Non Rookie Independent Directors
Less than median no. skills:


120CAR3 :


T Statistic: -0.472401055700424  P Value: 0.6366918866893856
Mean: -0.0006086980267347143
Median: -0.004034838162761109
N: 2009


Greater than median no. skills:


120CAR3 :


T Statistic: -0.472401055700424  P Value: 0.6366918866893856
Mean: -0.0006086980267347143
Median: -0.004034838162761109
N: 2009


Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR5 :


T Statistic: -37.80862176315087  P Value: 3.2446887412715597e-258
Mean: -0.056300064403705545
Median: -0.05694459232992993
N: 3147


Greater than median no. skills:


120CAR5 :


T Statistic: -37.80862176315087  P Value: 3.2446887412715597e-258
Mean: -0.056300064403705545
Median: -0.05694459232992993
N: 3147


Non Rookie Independent Directors
Less than median no. skills:


120CAR5 :


T Statistic: -29.98602800864166  P Value: 1.5239814016216538e-163
Mean: -0.047102087664747716
Median: -0.05027291495418852
N: 2007


Greater than median no. skills:


120CAR5 :


T Statistic: -29.98602800864166  P Value: 1.5239814016216538e-163
Mean: -0.047102087664747716
Median: -0.05027291495418852
N: 2007


Rookie Independent Directors
Less than median no. skills:


120CAR7 :


T Statistic: -59.56703504972766  P Value: 0.0
Mean: -0.10710457359849027
Median: -0.10610569829553844
N: 3147


Greater than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR7 :


T Statistic: -59.56703504972766  P Value: 0.0
Mean: -0.10710457359849027
Median: -0.10610569829553844
N: 3147


Non Rookie Independent Directors
Less than median no. skills:


120CAR7 :


T Statistic: -50.980283425115736  P Value: 0.0
Mean: -0.09465244869274722
Median: -0.09646062270205857
N: 2005


Greater than median no. skills:


120CAR7 :


T Statistic: -50.980283425115736  P Value: 0.0
Mean: -0.09465244869274722
Median: -0.09646062270205857
N: 2005


Rookie Independent Directors
Less than median no. skills:


120CAR11 :


T Statistic: -85.29076705027953  P Value: 0.0
Mean: -0.20606515252751254
Median: -0.2082773414282721
N: 3144


Greater than median no. skills:


120CAR11 :


T Statistic: -85.29076705027953  P Value: 0.0
Mean: -0.20606515252751254
Median: -0.2082773414282721
N: 3144


Non Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

120CAR11 :


T Statistic: -76.66543374125047  P Value: 0.0
Mean: -0.18509141756313313
Median: -0.18852306978768935
N: 2003


Greater than median no. skills:


120CAR11 :


T Statistic: -76.66543374125047  P Value: 0.0
Mean: -0.18509141756313313
Median: -0.18852306978768935
N: 2003


Rookie Independent Directors
Less than median no. skills:


150CAR3 :


T Statistic: -1.7474290899063578  P Value: 0.08066087364126316
Mean: -0.00201551549173988
Median: -0.005178524749622215
N: 3135


Greater than median no. skills:


150CAR3 :


T Statistic: -1.7474290899063578  P Value: 0.08066087364126316
Mean: -0.00201551549173988
Median: -0.005178524749622215
N: 3135


Non Rookie Independent Directors
Less than median no. skills:


150CAR3 :


T Statistic: -0.3516414958613866  P Value: 0.7251441836499047
Mean: -0.0004511825266534805
Median: -0.004110453092502339
N: 2001


Greater than median no. skills:


150CAR3 :


T Statistic: -0.3516414958613866  P Value: 0.7251441836499047
Mean: -0.0004511825266534805
Median: -0.004110453092502339
N: 2001

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors
Less than median no. skills:


150CAR5 :


T Statistic: -37.83542928174144  P Value: 2.351487170733966e-258
Mean: -0.0561708088270937
Median: -0.057103631436664894
N: 3135


Greater than median no. skills:


150CAR5 :


T Statistic: -37.83542928174144  P Value: 2.351487170733966e-258
Mean: -0.0561708088270937
Median: -0.057103631436664894
N: 3135


Non Rookie Independent Directors
Less than median no. skills:


150CAR5 :


T Statistic: -30.101410467109382  P Value: 1.782880727690734e-164
Mean: -0.046986173543726265
Median: -0.050091998625381065
N: 1999


Greater than median no. skills:


150CAR5 :


T Statistic: -30.101410467109382  P Value: 1.782880727690734e-164
Mean: -0.046986173543726265
Median: -0.050091998625381065
N: 1999


Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR7 :


T Statistic: -59.24282339111682  P Value: 0.0
Mean: -0.10669572182659828
Median: -0.10620606754251488
N: 3135


Greater than median no. skills:


150CAR7 :


T Statistic: -59.24282339111682  P Value: 0.0
Mean: -0.10669572182659828
Median: -0.10620606754251488
N: 3135


Non Rookie Independent Directors
Less than median no. skills:


150CAR7 :


T Statistic: -50.892846965364036  P Value: 0.0
Mean: -0.09454336716090625
Median: -0.09557873865626615
N: 1997


Greater than median no. skills:


150CAR7 :


T Statistic: -50.892846965364036  P Value: 0.0
Mean: -0.09454336716090625
Median: -0.09557873865626615
N: 1997


Rookie Independent Directors
Less than median no. skills:


150CAR11 :


T Statistic: -84.17343086131245  P Value: 0.0
Mean: -0.2053051399660255
Median: -0.20853265491577677
N: 3132


Greater than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR11 :


T Statistic: -84.17343086131245  P Value: 0.0
Mean: -0.2053051399660255
Median: -0.20853265491577677
N: 3132


Non Rookie Independent Directors
Less than median no. skills:


150CAR11 :


T Statistic: -76.7403487635796  P Value: 0.0
Mean: -0.18502041151895973
Median: -0.18887429049064358
N: 1995


Greater than median no. skills:


150CAR11 :


T Statistic: -76.7403487635796  P Value: 0.0
Mean: -0.18502041151895973
Median: -0.18887429049064358
N: 1995


Rookie Independent Directors
Less than median no. skills:


180CAR3 :


T Statistic: -1.872598902475763  P Value: 0.06121754728109338
Mean: -0.002162343982099191
Median: -0.004832090728751723
N: 3111


Greater than median no. skills:


180CAR3 :


T Statistic: -1.872598902475763  P Value: 0.06121754728109338
Mean: -0.002162343982099191
Median: -0.004832090728751723
N: 3111


Non Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR3 :


T Statistic: -0.2672223166103386  P Value: 0.7893256565443852
Mean: -0.0003434188201168575
Median: -0.003216748998231961
N: 1993


Greater than median no. skills:


180CAR3 :


T Statistic: -0.2672223166103386  P Value: 0.7893256565443852
Mean: -0.0003434188201168575
Median: -0.003216748998231961
N: 1993


Rookie Independent Directors
Less than median no. skills:


180CAR5 :


T Statistic: -37.75417699189329  P Value: 4.121069805441575e-257
Mean: -0.05647393854722064
Median: -0.05771496635124426
N: 3111


Greater than median no. skills:


180CAR5 :


T Statistic: -37.75417699189329  P Value: 4.121069805441575e-257
Mean: -0.05647393854722064
Median: -0.05771496635124426
N: 3111


Non Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR5 :


T Statistic: -30.043124980686184  P Value: 7.644316722233529e-164
Mean: -0.04690721833148166
Median: -0.049921518279981425
N: 1991


Greater than median no. skills:


180CAR5 :


T Statistic: -30.043124980686184  P Value: 7.644316722233529e-164
Mean: -0.04690721833148166
Median: -0.049921518279981425
N: 1991


Rookie Independent Directors
Less than median no. skills:


180CAR7 :


T Statistic: -59.10100581272701  P Value: 0.0
Mean: -0.10697856882949196
Median: -0.10680513490723254
N: 3111


Greater than median no. skills:


180CAR7 :


T Statistic: -59.10100581272701  P Value: 0.0
Mean: -0.10697856882949196
Median: -0.10680513490723254
N: 3111


Non Rookie Independent Directors
Less than median no. skills:


180CAR7 :


T Statistic: -50.763837630332766  P Value: 0.0
Mean: -0.0942841073258206
Median: -0.09598033409149612
N: 1989


Greater than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

180CAR7 :


T Statistic: -50.763837630332766  P Value: 0.0
Mean: -0.0942841073258206
Median: -0.09598033409149612
N: 1989


Rookie Independent Directors
Less than median no. skills:


180CAR11 :


T Statistic: -84.05906264497354  P Value: 0.0
Mean: -0.205405365734233
Median: -0.2090886882456958
N: 3108


Greater than median no. skills:


180CAR11 :


T Statistic: -84.05906264497354  P Value: 0.0
Mean: -0.205405365734233
Median: -0.2090886882456958
N: 3108


Non Rookie Independent Directors
Less than median no. skills:


180CAR11 :


T Statistic: -76.51731435864038  P Value: 0.0
Mean: -0.18502401885559205
Median: -0.18950880375161008
N: 1987


Greater than median no. skills:


180CAR11 :


T Statistic: -76.51731435864038  P Value: 0.0
Mean: -0.18502401885559205
Median: -0.18950880375161008
N: 1987

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Rookie Independent Directors
Less than median no. skills:


210CAR3 :


T Statistic: -1.6460847316743776  P Value: 0.09984768394521952
Mean: -0.0019054472828128023
Median: -0.004226458377428723
N: 3101


Greater than median no. skills:


210CAR3 :


T Statistic: -1.6460847316743776  P Value: 0.09984768394521952
Mean: -0.0019054472828128023
Median: -0.004226458377428723
N: 3101


Non Rookie Independent Directors
Less than median no. skills:


210CAR3 :


T Statistic: -0.18577155550112778  P Value: 0.852642901889643
Mean: -0.00023859092010042045
Median: -0.002997660537585045
N: 1985


Greater than median no. skills:


210CAR3 :


T Statistic: -0.18577155550112778  P Value: 0.852642901889643
Mean: -0.00023859092010042045
Median: -0.002997660537585045
N: 1985


Rookie Independent Directors
Less than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

210CAR5 :


T Statistic: -37.495048564788995  P Value: 4.583984897173807e-254
Mean: -0.05592469312113248
Median: -0.056840952316300236
N: 3101


Greater than median no. skills:


210CAR5 :


T Statistic: -37.495048564788995  P Value: 4.583984897173807e-254
Mean: -0.05592469312113248
Median: -0.056840952316300236
N: 3101


Non Rookie Independent Directors
Less than median no. skills:


210CAR5 :


T Statistic: -29.782311542415332  P Value: 2.1310004953703413e-161
Mean: -0.04684689827161603
Median: -0.05018083154937148
N: 1983


Greater than median no. skills:


210CAR5 :


T Statistic: -29.782311542415332  P Value: 2.1310004953703413e-161
Mean: -0.04684689827161603
Median: -0.05018083154937148
N: 1983


Rookie Independent Directors
Less than median no. skills:


210CAR7 :


T Statistic: -58.795373698078215  P Value: 0.0
Mean: -0.10638498169653644
Median: -0.1061857698547766
N: 3101


Greater than median no. skills:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

210CAR7 :


T Statistic: -58.795373698078215  P Value: 0.0
Mean: -0.10638498169653644
Median: -0.1061857698547766
N: 3101


Non Rookie Independent Directors
Less than median no. skills:


210CAR7 :


T Statistic: -50.73224283170815  P Value: 0.0
Mean: -0.09446344021514086
Median: -0.09616634438924315
N: 1981


Greater than median no. skills:


210CAR7 :


T Statistic: -50.73224283170815  P Value: 0.0
Mean: -0.09446344021514086
Median: -0.09616634438924315
N: 1981


Rookie Independent Directors
Less than median no. skills:


210CAR11 :


T Statistic: -83.73896852031146  P Value: 0.0
Mean: -0.2047428713472602
Median: -0.20739241908741346
N: 3098


Greater than median no. skills:


210CAR11 :


T Statistic: -83.73896852031146  P Value: 0.0
Mean: -0.2047428713472602
Median: -0.20739241908741346
N: 3098


Non Rookie Independent Directors
Less than median no. skills:


210CAR11 :


T Statistic: -76.06755358118505  P Value: 0.0
Mean: -0.1851408583827517
Median: -0.18943627929361406
N: 1979


Greater than median no. skills:


210CAR11 :


T Statistic: -76.06755358118505  P Value: 0.0
Mean: -0.1851408583827517
Median: -0.18943627929361406
N: 1979

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

In [29]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)