In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import numpy as np
import datetime as dt
import math as math
pd.set_option("display.max_columns", None)
from pandas.tseries.offsets import MonthEnd

In [2]:
import_folder_path = r"..\firm_calc1_output"
output_folder_path = "firm_fin_output"
supporting_folder_path = "supporting_datafiles"

### Identifiers: Prowess Company Code x NSE Symbol [Done later]

In [3]:
compCodeNse = pd.read_excel(rf"{supporting_folder_path}\Prowess Code_NSE Symbol.xlsx")
compCodeNse

                               Company Name  Prowess company code NSE symbol
0          'K' Steamship Agencies Pvt. Ltd.                     3        NaN
1      'X'Clusive Business Centre Pvt. Ltd.                307865        NaN
2                 1 To 1 Help.Net Pvt. Ltd.                591675        NaN
3              10C India Internet Pvt. Ltd.                556976        NaN
4           10I Commerce Services Pvt. Ltd.                560502        NaN
...                                     ...                   ...        ...
55307                    Zylog Systems Ltd.                275793      ZYLOG
55308       Zyma Laboratories Ltd. [Merged]                275794        NaN
55309      Zyphar'S Pharmaceutics Pvt. Ltd.                565342        NaN
55310                   Zytel Agencies Ltd.                275795        NaN
55311      Zyxel Technology India Pvt. Ltd.                432445        NaN

[55312 rows x 3 columns]

### READING ALL DATA FILES

#### 16 Ownership Data

In [4]:
own1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Ownership Data.xlsx", sheet_name = 0, header = [0,1])
own2 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Ownership Data.xlsx", sheet_name = 1, header = [0,1])

In [5]:
own11 = own1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
own12 = own11.unstack().unstack(level = 1).reset_index()
own13 = own12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
own13["AsOnDate"] = pd.to_datetime(own13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

own21 = own2.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
own22 = own21.unstack().unstack(level = 1).reset_index()
own23 = own22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
own23["AsOnDate"] = pd.to_datetime(own23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [6]:
own = pd.concat([own13, own23], axis = 0).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop= True).drop_duplicates()
own

,AsOnDate,Company Name,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,2005-03-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005-06-30,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005-09-30,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005-12-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-03-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
297487,2023-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297488,2023-06-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297489,2023-09-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297490,2023-12-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297491,2024-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 1 Financial Data

In [7]:
fin1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Financial Data.xlsx", sheet_name = 0, header = [0,1])

fin2 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Financial Data.xlsx", sheet_name = 1, header = [0,1])

In [8]:
# fin1 = fin_identifiers.drop(fin_identifiers.columns[[1,3,4,5,6,7,8,9,10,11,12,13]], axis = 1)

In [9]:
fin11 = fin1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
fin12 = fin11.unstack().unstack(level = 1).reset_index()
fin13 = fin12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
fin13["AsOnDate"] = pd.to_datetime(fin13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

fin21 = fin2.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
fin22 = fin21.unstack().unstack(level = 1).reset_index()
fin23 = fin22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
fin23["AsOnDate"] = pd.to_datetime(fin23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [10]:
fin = pd.concat([fin13, fin23], axis = 0).sort_values(by = ["Company Name", "AsOnDate"])\
.reset_index(drop= True).drop_duplicates()\
.drop(["Cash (outflow) due to purchase of fixed assets", "Cash inflow due to sale of fixed assets",
       "Cash flow due to purchase of fixed assets",
       "Net cash inflow or (outflow) from investing activities"], axis = 1)

fin

,AsOnDate,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)
0,2005-03-31,20 Microns Ltd.,578.3,-63.2,70.0,-8.78,698.5,66.3,2.3,2.08,NaN,NaN,389.1,70.6,NaN,NaN,NaN,NaN,NaN,68.2,NaN,NaN
1,2006-03-31,20 Microns Ltd.,720.8,18.0,83.1,2.58,742.9,80.0,9.4,1.98,NaN,NaN,399.6,57.7,NaN,NaN,NaN,NaN,0.9,53.8,1.9,NaN
2,2007-03-31,20 Microns Ltd.,933.6,35.7,125.2,4.51,845.1,121.5,45.1,1.78,NaN,NaN,423.6,70.6,NaN,NaN,NaN,NaN,2.5,61.9,6.3,NaN
3,2008-03-31,20 Microns Ltd.,1147.9,45.9,164.9,4.11,978.4,152.9,64.4,1.64,NaN,NaN,466.0,98.2,NaN,NaN,NaN,NaN,12.1,69.0,5.5,NaN
4,2009-03-31,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,3.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80089,2020-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80090,2021-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80091,2022-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80092,2023-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80093,2024-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 4 BVPS

In [11]:
bvps1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - BVPS.xlsx", sheet_name = 0, header = [0,1])
bvps2 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - BVPS.xlsx", sheet_name = 1, header = [0,1])

In [12]:
bvps11 = bvps1.set_index([("Unnamed: 0_level_0","Company Name")])
bvps12 = bvps11.unstack().unstack(level = 1).reset_index()
bvps13 = bvps12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
bvps13["AsOnDate"] = pd.to_datetime(bvps13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
bvps14 = bvps13.merge(compCodeNse, on = ["Company Name"], how = "left")

bvps21 = bvps2.set_index([("Unnamed: 0_level_0","Company Name")])
bvps22 = bvps21.unstack().unstack(level = 1).reset_index()
bvps23 = bvps22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
bvps23["AsOnDate"] = pd.to_datetime(bvps23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
bvps24 = bvps23.merge(compCodeNse, on = ["Company Name"], how = "left")

In [13]:
bvps = pd.concat([bvps14, bvps24], axis = 0).sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
bvps = bvps[ bvps.columns[[1,0,2]]].dropna(subset = ["BV per Share "]).reset_index(drop = True).rename({"BV per Share ":"BVPS"}, axis = 1).drop_duplicates()
bvps

                    Company Name   AsOnDate   BVPS
0                20 Microns Ltd. 2009-03-31  25.19
1                20 Microns Ltd. 2010-03-31  29.03
2                20 Microns Ltd. 2011-03-31  31.12
3                20 Microns Ltd. 2012-03-31  36.38
4                20 Microns Ltd. 2013-03-31  20.92
...                          ...        ...    ...
54469    Shree Karni Fabcom Ltd. 2024-03-31   0.00
54470  Pratham Epc Projects Ltd. 2024-03-31   0.00
54471     Signoria Creation Ltd. 2024-03-31  32.18
54472      Enfuse Solutions Ltd. 2024-03-31  35.07
54473  Enser Communications Ltd. 2024-03-31  26.59

[51977 rows x 3 columns]

#### 2 Deferred Tax Liability

In [14]:
defTaxLia1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Deferred Tax Liability.xlsx", sheet_name = 0, header = [0,1])

In [15]:
defTaxLia11 = defTaxLia1.set_index([("Unnamed: 0_level_0","Company Name")])
defTaxLia12 = defTaxLia11.unstack().unstack(level = 1).reset_index()
defTaxLia13 = defTaxLia12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
defTaxLia13["AsOnDate"] = pd.to_datetime(defTaxLia13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
defTaxLia14 = defTaxLia13.merge(compCodeNse, on = ["Company Name"], how = "left")

In [16]:
defTaxLia = defTaxLia14.sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop([ "NSE symbol"], axis =1)
defTaxLia = defTaxLia[ defTaxLia.columns[[1,0,2]]].dropna(subset = ["Deferred tax liability"]).reset_index( drop = True).drop_duplicates()
defTaxLia

                             Company Name   AsOnDate  Deferred tax liability
0        'K' Steamship Agencies Pvt. Ltd. 2011-03-31                     7.3
1        'K' Steamship Agencies Pvt. Ltd. 2012-03-31                     9.6
2        'K' Steamship Agencies Pvt. Ltd. 2013-03-31                     0.6
3        'K' Steamship Agencies Pvt. Ltd. 2014-03-31                     0.4
4        'K' Steamship Agencies Pvt. Ltd. 2015-03-31                     0.3
...                                   ...        ...                     ...
204869      Economist Communications Ltd. 2023-03-31                     0.4
204870                P V R Pictures Ltd. 2023-03-31                    35.8
204871  Pankaj Piyush Trade & Invst. Ltd. 2023-03-31                     0.2
204872   R D C Concrete (India) Pvt. Ltd. 2023-03-31                     1.7
204873                S M C Comtrade Ltd. 2023-03-31                     1.3

[204874 rows x 3 columns]

#### 3 Net Deferred Tax Liabilties

In [17]:
netDefTaxLia1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Net Deferred Tax Liability.xlsx", sheet_name = 0, header = [0,1])

In [18]:
netDefTaxLia11 = netDefTaxLia1.set_index([("Unnamed: 0_level_0","Company Name")])
netDefTaxLia12 = netDefTaxLia11.unstack().unstack(level = 1).reset_index()
netDefTaxLia13 = netDefTaxLia12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
netDefTaxLia13["AsOnDate"] = pd.to_datetime(netDefTaxLia13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
netDefTaxLia14 = netDefTaxLia13.merge(compCodeNse, on = ["Company Name"], how = "left")

In [19]:
netDefTaxLia = netDefTaxLia14.sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
netDefTaxLia = netDefTaxLia[ netDefTaxLia.columns[[1,0,2]]].dropna(subset = ["Net deferred tax liabilities"]).reset_index( drop = True).drop_duplicates()
netDefTaxLia

,Company Name,AsOnDate,Net deferred tax liabilities
0,'K' Steamship Agencies Pvt. Ltd.,2011-03-31,6.1
1,'K' Steamship Agencies Pvt. Ltd.,2012-03-31,8.1
2,'K' Steamship Agencies Pvt. Ltd.,2013-03-31,-0.4
3,'K' Steamship Agencies Pvt. Ltd.,2014-03-31,-0.8
4,'K' Steamship Agencies Pvt. Ltd.,2015-03-31,-3.3
...,...,...,...
314437,Paras Healthcare Pvt. Ltd.,2023-03-31,-36.3
314438,R D C Concrete (India) Pvt. Ltd.,2023-03-31,-209.7
314439,S M C Comtrade Ltd.,2023-03-31,-6.1
314440,Shyama Infosys Ltd.,2023-03-31,-0.5
314441,T S R Darashaw Ltd.,2023-03-31,-3.5

#### 5 Shares Outstanding

In [20]:
sharesOut1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Shares Outstanding.xlsx", sheet_name = 0, header = [0,1])
sharesOut2 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Shares Outstanding.xlsx", sheet_name = 1, header = [0,1])

In [21]:
sharesOut11 = sharesOut1.set_index([("Unnamed: 0_level_0","Company Name")])
sharesOut12 = sharesOut11.unstack().unstack(level = 1).reset_index()
sharesOut13 = sharesOut12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
sharesOut13["AsOnDate"] = pd.to_datetime(sharesOut13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
sharesOut14 = sharesOut13.merge(compCodeNse, on = ["Company Name"], how = "left")

sharesOut21 = sharesOut2.set_index([("Unnamed: 0_level_0","Company Name")])
sharesOut22 = sharesOut21.unstack().unstack(level = 1).reset_index()
sharesOut23 = sharesOut22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
sharesOut23["AsOnDate"] = pd.to_datetime(sharesOut23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
sharesOut24 = sharesOut23.merge(compCodeNse, on = ["Company Name"], how = "left")

In [22]:
sharesOut = pd.concat([sharesOut14, sharesOut24], axis = 0).sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
sharesOut = sharesOut[ sharesOut.columns[[1,0,2]]].dropna(subset = ["Shares Outstanding "]).reset_index( drop = True).rename({"Shares Oustanding ":"Shares Oustanding"}, axis = 1).drop_duplicates()
sharesOut

                    Company Name   AsOnDate  Shares Outstanding
0                20 Microns Ltd. 2009-03-31           14205248.0
1                20 Microns Ltd. 2010-03-31           14331028.0
2                20 Microns Ltd. 2011-03-31           14331028.0
3                20 Microns Ltd. 2012-03-31           14331028.0
4                20 Microns Ltd. 2013-03-31           31662056.0
...                          ...        ...                  ...
54469    Shree Karni Fabcom Ltd. 2024-03-31            7072000.0
54470  Pratham Epc Projects Ltd. 2024-03-31           17760000.0
54471     Signoria Creation Ltd. 2024-03-31            4758000.0
54472      Enfuse Solutions Ltd. 2024-03-31            8847600.0
54473  Enser Communications Ltd. 2024-03-31            8716059.0

[51977 rows x 3 columns]

#### 6 Market Data

In [23]:
market1 = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Market Data.xlsx", sheet_name = 0, header = [0,1])

In [24]:
market11 = market1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
market12 = market11.unstack().unstack(level = 1).reset_index()
market13 = market12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
market13["AsOnDate"] = pd.to_datetime(market13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [25]:
market = market13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Market Capitalisation", "Total Returns", "P/B ", "Market Capitalisation / Enterprise Value"], how = "all").reset_index(drop= True).drop_duplicates()
market

,AsOnDate,Company Name,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value
0,2008-12-31,20 Microns Ltd.,220.98,2.62,0.42,0.33
1,2009-03-31,20 Microns Ltd.,214.50,0.67,0.60,0.28
2,2009-06-30,20 Microns Ltd.,328.85,-1.49,0.84,0.38
3,2009-09-30,20 Microns Ltd.,599.75,-1.99,1.47,0.52
4,2009-12-31,20 Microns Ltd.,659.94,-1.07,1.57,0.55
...,...,...,...,...,...,...
199881,2023-03-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199882,2023-06-30,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199883,2023-09-30,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199884,2023-12-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199885,2024-03-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00

#### 7 Net Cash from investing activities

In [26]:
netCashInvest1 = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Net Cash Investing activities.csv", header = [0,1])

In [27]:
netCashInvest11 = netCashInvest1.set_index([("Unnamed: 0_level_0","Company Name")])
netCashInvest12 = netCashInvest11.unstack().unstack(level = 1).reset_index()
netCashInvest13 = netCashInvest12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
netCashInvest13["AsOnDate"] = pd.to_datetime(netCashInvest13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [28]:
netCashInvest = netCashInvest13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Net cash inflow or (outflow) from investing activities"], how = "all").reset_index(drop= True).drop_duplicates()
netCashInvest

,AsOnDate,Company Name,Net cash inflow or (outflow) from investing activities
0,2014-03-31,'K' Steamship Agencies Pvt. Ltd.,-96.3
1,2015-03-31,'K' Steamship Agencies Pvt. Ltd.,-181.9
2,2016-03-31,'K' Steamship Agencies Pvt. Ltd.,29.3
3,2017-03-31,'K' Steamship Agencies Pvt. Ltd.,-122.0
4,2018-03-31,'K' Steamship Agencies Pvt. Ltd.,-80.4
...,...,...,...
297232,2019-03-31,Zyxel Technology India Pvt. Ltd.,-0.2
297233,2020-03-31,Zyxel Technology India Pvt. Ltd.,-0.3
297234,2021-03-31,Zyxel Technology India Pvt. Ltd.,-0.2
297235,2022-03-31,Zyxel Technology India Pvt. Ltd.,-0.1
297236,2023-03-31,Zyxel Technology India Pvt. Ltd.,-0.2

#### 8 Cash inflow from sale of fixed assets

In [29]:
inCashSaleFixed1 = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Cash inflow from sale of fixed assets.csv", header = [0,1])

In [30]:
inCashSaleFixed11 = inCashSaleFixed1.set_index([("Unnamed: 0_level_0","Company Name")])
inCashSaleFixed12 = inCashSaleFixed11.unstack().unstack(level = 1).reset_index()
inCashSaleFixed13 = inCashSaleFixed12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
inCashSaleFixed13["AsOnDate"] = pd.to_datetime(inCashSaleFixed13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [31]:
inCashSaleFixed = inCashSaleFixed13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash inflow due to sale of fixed assets"], how = "all").reset_index(drop= True).drop_duplicates()
inCashSaleFixed

,AsOnDate,Company Name,Cash inflow due to sale of fixed assets
0,2005-03-31,20 Microns Ltd.,0.3
1,2006-03-31,20 Microns Ltd.,0.4
2,2007-03-31,20 Microns Ltd.,0.9
3,2008-03-31,20 Microns Ltd.,2.8
4,2009-03-31,20 Microns Ltd.,4.2
...,...,...,...
91910,2019-03-31,Zydus Wellness Products Ltd.,995.3
91911,2020-03-31,Zydus Wellness Products Ltd.,0.5
91912,2021-03-31,Zydus Wellness Products Ltd.,20.1
91913,2022-03-31,Zydus Wellness Products Ltd.,6.2
91914,2023-03-31,Zydus Wellness Products Ltd.,4.1

#### 9 Cash outflow from Purchase of Fixed assets

In [32]:
outCashPurchaseFixed1 = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Cash outflow from Purchase of Fixed assets.csv", header = [0,1])

In [33]:
outCashPurchaseFixed11 = outCashPurchaseFixed1.set_index([("Unnamed: 0_level_0","Company Name")])
outCashPurchaseFixed12 = outCashPurchaseFixed11.unstack().unstack(level = 1).reset_index()
outCashPurchaseFixed13 = outCashPurchaseFixed12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
outCashPurchaseFixed13["AsOnDate"] = pd.to_datetime(outCashPurchaseFixed13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [34]:
outCashPurchaseFixed = outCashPurchaseFixed13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash (outflow) due to purchase of fixed assets"], how = "all").reset_index(drop= True).drop_duplicates()
outCashPurchaseFixed

,AsOnDate,Company Name,Cash (outflow) due to purchase of fixed assets
0,2014-03-31,'K' Steamship Agencies Pvt. Ltd.,-7.6
1,2015-03-31,'K' Steamship Agencies Pvt. Ltd.,-117.1
2,2016-03-31,'K' Steamship Agencies Pvt. Ltd.,-9.4
3,2017-03-31,'K' Steamship Agencies Pvt. Ltd.,-16.8
4,2018-03-31,'K' Steamship Agencies Pvt. Ltd.,-4.4
...,...,...,...
211570,2019-03-31,Zyxel Technology India Pvt. Ltd.,-0.2
211571,2020-03-31,Zyxel Technology India Pvt. Ltd.,-0.3
211572,2021-03-31,Zyxel Technology India Pvt. Ltd.,-0.3
211573,2022-03-31,Zyxel Technology India Pvt. Ltd.,-0.1
211574,2023-03-31,Zyxel Technology India Pvt. Ltd.,-0.2

#### 10 Cash inflow from sale of intangible assets

In [35]:
inCashSaleIntangible1 = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Cash inflow from sale of intangible assets.csv", header = [0,1])

In [36]:
inCashSaleIntangible11 = inCashSaleIntangible1.set_index([("Unnamed: 0_level_0","Company Name")])
inCashSaleIntangible12 = inCashSaleIntangible11.unstack().unstack(level = 1).reset_index()
inCashSaleIntangible13 = inCashSaleIntangible12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
inCashSaleIntangible13["AsOnDate"] = pd.to_datetime(inCashSaleIntangible13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [37]:
inCashSaleIntangible = inCashSaleIntangible13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash inflow due to sale of Intangible assets"], how = "all").reset_index(drop= True).drop_duplicates()
inCashSaleIntangible

,AsOnDate,Company Name,Cash inflow due to sale of Intangible assets
0,2022-03-31,A B A Builders Ltd. [Merged],0.5
1,2019-03-31,A L M Infotech City Pvt. Ltd.,17.0
2,2016-03-31,Aarti International Ltd.,34.8
3,2021-03-31,Aarti International Ltd.,25.6
4,2023-03-31,Aarti International Ltd.,11.5
...,...,...,...
502,2016-03-31,Zydus Hospira Oncology Pvt. Ltd.,1018.7
503,2021-03-31,Zydus Hospira Oncology Pvt. Ltd.,0.4
504,2022-03-31,Zydus Hospira Oncology Pvt. Ltd.,0.5
505,2023-03-31,Zydus Hospira Oncology Pvt. Ltd.,0.3
506,2024-03-31,Zydus Hospira Oncology Pvt. Ltd.,3.2

#### 11 Cash outflow from Purchase of intangible assets

In [38]:
outCashPurchaseIntangible1 = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Cash outflow from Purchase of intangible assets.csv", header = [0,1])

In [39]:
outCashPurchaseIntangible11 = outCashPurchaseIntangible1.set_index([("Unnamed: 0_level_0","Company Name")])
outCashPurchaseIntangible12 = outCashPurchaseIntangible11.unstack().unstack(level = 1).reset_index()
outCashPurchaseIntangible13 = outCashPurchaseIntangible12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
outCashPurchaseIntangible13["AsOnDate"] = pd.to_datetime(outCashPurchaseIntangible13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [40]:
outCashPurchaseIntangible = outCashPurchaseIntangible13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash (outflow) due to purchase of Intangible assets"], how = "all").reset_index(drop= True).drop_duplicates()
outCashPurchaseIntangible

,AsOnDate,Company Name,Cash (outflow) due to purchase of Intangible assets
0,2024-03-31,360 One Prime Ltd.,-22.7
1,2017-03-31,3D Future Technologies Pvt. Ltd.,-1.7
2,2023-03-31,3D Future Technologies Pvt. Ltd.,-1.2
3,2023-03-31,7Seas Entertainment Ltd.,-5.5
4,2024-03-31,7Seas Entertainment Ltd.,-13.6
...,...,...,...
3969,2020-03-31,Zydus Hospira Oncology Pvt. Ltd.,-0.8
3970,2021-03-31,Zydus Hospira Oncology Pvt. Ltd.,-2.6
3971,2022-03-31,Zydus Hospira Oncology Pvt. Ltd.,-9.2
3972,2023-03-31,Zydus Hospira Oncology Pvt. Ltd.,-19.2
3973,2024-03-31,Zydus Hospira Oncology Pvt. Ltd.,-8.4

#### 12 Net change in cash and equivalents

In [41]:
netCashEquiv1 = pd.read_csv(rf"{supporting_folder_path}\CMIE - Net change in cash and equivalents.csv", header = [0,1])

In [42]:
netCashEquiv11 = netCashEquiv1.set_index([("Unnamed: 0_level_0","Company Name")])
netCashEquiv12 = netCashEquiv11.unstack().unstack(level = 1).reset_index()
netCashEquiv13 = netCashEquiv12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
netCashEquiv13["AsOnDate"] = pd.to_datetime(netCashEquiv13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [43]:
netCashEquiv = netCashEquiv13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Net change in cash and cash equivalents"], how = "all").reset_index(drop= True).drop_duplicates()
netCashEquiv

,AsOnDate,Company Name,Net change in cash and cash equivalents
0,2022-03-31,1 Finance Pvt. Ltd.,3.00700
1,2023-03-31,1 Finance Pvt. Ltd.,164.62600
2,2024-03-31,1 Finance Pvt. Ltd.,-147.77300
3,2021-03-31,102 Mother Child Services (U P),-587.67300
4,2022-03-31,102 Mother Child Services (U P),75.21800
...,...,...,...
465199,2020-03-31,Zyxel Technology India Pvt. Ltd.,-1.34685
465200,2021-03-31,Zyxel Technology India Pvt. Ltd.,6.04053
465201,2022-03-31,Zyxel Technology India Pvt. Ltd.,-2.50261
465202,2023-03-31,Zyxel Technology India Pvt. Ltd.,39.68986
465203,2024-03-31,Zyxel Technology India Pvt. Ltd.,-15.08072

#### 13 Cash and cash equivalents as at the end of the year

In [44]:
cashEquivEndYear1 = pd.read_csv(rf"{supporting_folder_path}\CMIE - Cash and equivalents as at the end of the year.csv", header = [0,1])

In [45]:
cashEquivEndYear11 = cashEquivEndYear1.set_index([("Unnamed: 0_level_0","Company Name")])
cashEquivEndYear12 = cashEquivEndYear11.unstack().unstack(level = 1).reset_index()
cashEquivEndYear13 = cashEquivEndYear12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
cashEquivEndYear13["AsOnDate"] = pd.to_datetime(cashEquivEndYear13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [46]:
cashEquivEndYear = cashEquivEndYear13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash and cash equivalents as at the end of the year"], how = "all").reset_index(drop= True).drop_duplicates()
cashEquivEndYear

,AsOnDate,Company Name,Cash and cash equivalents as at the end of the year
0,2022-03-31,1 Finance Pvt. Ltd.,3.00700
1,2023-03-31,1 Finance Pvt. Ltd.,167.63300
2,2024-03-31,1 Finance Pvt. Ltd.,19.86000
3,2014-03-31,10C India Internet Pvt. Ltd.,68.24976
4,2015-03-31,10C India Internet Pvt. Ltd.,170.68583
...,...,...,...
442006,2020-03-31,Zyxel Technology India Pvt. Ltd.,0.25544
442007,2021-03-31,Zyxel Technology India Pvt. Ltd.,6.29597
442008,2022-03-31,Zyxel Technology India Pvt. Ltd.,3.79335
442009,2023-03-31,Zyxel Technology India Pvt. Ltd.,43.48322
442010,2024-03-31,Zyxel Technology India Pvt. Ltd.,28.40249

#### 14 Cash outflow from Purchase of intangible assets

In [47]:
cashEquivBegYear1 = pd.read_csv(rf"{supporting_folder_path}\CMIE - Cash at the beginning of the year.csv", header = [0,1])

In [48]:
cashEquivBegYear11 = cashEquivBegYear1.set_index([("Unnamed: 0_level_0","Company Name")])
cashEquivBegYear12 = cashEquivBegYear11.unstack().unstack(level = 1).reset_index()
cashEquivBegYear13 = cashEquivBegYear12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
cashEquivBegYear13["AsOnDate"] = pd.to_datetime(cashEquivBegYear13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [49]:
cashEquivBegYear = cashEquivBegYear13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Cash and cash equivalents as at the beginning of the year"], how = "all").reset_index(drop= True).drop_duplicates()
cashEquivBegYear

,AsOnDate,Company Name,Cash and cash equivalents as at the beginning of the year
0,2022-03-31,1 Finance Pvt. Ltd.,0.00000
1,2023-03-31,1 Finance Pvt. Ltd.,3.00700
2,2024-03-31,1 Finance Pvt. Ltd.,167.63300
3,2021-03-31,102 Mother Child Services (U P),587.67300
4,2022-03-31,102 Mother Child Services (U P),-75.21800
...,...,...,...
467241,2020-03-31,Zyxel Technology India Pvt. Ltd.,1.60230
467242,2021-03-31,Zyxel Technology India Pvt. Ltd.,0.25544
467243,2022-03-31,Zyxel Technology India Pvt. Ltd.,6.29597
467244,2023-03-31,Zyxel Technology India Pvt. Ltd.,3.79335
467245,2024-03-31,Zyxel Technology India Pvt. Ltd.,43.48322

## Intercorporate loans

#### 15 Current portion of long term inter-corporate loans

In [50]:
currLongInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Current portion of long term inter-corporate loans.csv", header = [0,1])

In [51]:
currLongInterCorpLoans11 = currLongInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
currLongInterCorpLoans12 = currLongInterCorpLoans11.unstack().unstack(level = 1).reset_index()
currLongInterCorpLoans13 = currLongInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
currLongInterCorpLoans13["AsOnDate"] = pd.to_datetime(currLongInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [52]:
currLongInterCorpLoans = currLongInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Current portion of long term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
currLongInterCorpLoans

,AsOnDate,Company Name,Current portion of long term inter-corporate loans
0,2011-03-31,20 Microns Ltd.,3.0
1,2012-03-31,20 Microns Ltd.,3.6
2,2013-03-31,20 Microns Ltd.,0.7
3,2014-03-31,20 Microns Ltd.,3.1
4,2015-03-31,20 Microns Ltd.,6.7
...,...,...,...
1423,2012-03-31,Zydus Technologies Ltd. [Merged],66.7
1424,2014-03-31,Zydus Technologies Ltd. [Merged],0.0
1425,2015-03-31,Zydus Technologies Ltd. [Merged],114.7
1426,2018-03-31,Zydus Technologies Ltd. [Merged],1886.2
1427,2019-03-31,Zydus Technologies Ltd. [Merged],1152.5

#### 16 Inter-corporate loans & borrowings (as per nbfc norms)

In [53]:
nbfcInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Inter-corporate loans & borrowings (as per nbfc norms).csv", header = [0,1])

In [54]:
nbfcInterCorpLoans11 = nbfcInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
nbfcInterCorpLoans12 = nbfcInterCorpLoans11.unstack().unstack(level = 1).reset_index()
nbfcInterCorpLoans13 = nbfcInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
nbfcInterCorpLoans13["AsOnDate"] = pd.to_datetime(nbfcInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [55]:
nbfcInterCorpLoans = nbfcInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Inter-corporate loans & borrowings (as per nbfc norms)"], how = "all").reset_index(drop= True).drop_duplicates()
nbfcInterCorpLoans

,AsOnDate,Company Name,Inter-corporate loans & borrowings (as per nbfc norms)
0,2008-03-31,A C T Fininvest Ltd.,0.0
1,2009-03-31,A C T Fininvest Ltd.,1994.7
2,2016-03-31,A C T Fininvest Ltd.,558.5
3,2017-03-31,A C T Fininvest Ltd.,558.7
4,2018-03-31,A C T Fininvest Ltd.,2415.0
...,...,...,...
2275,2020-03-31,Zenith Credit Pvt. Ltd.,17.7
2276,2021-03-31,Zenith Credit Pvt. Ltd.,17.8
2277,2022-03-31,Zenith Credit Pvt. Ltd.,17.1
2278,2023-03-31,Zenith Credit Pvt. Ltd.,34.0
2279,2023-03-31,Zodiac Consultants Ltd.,23.8

#### 17 Inter-corporate loans (Old Sch. VI)

In [56]:
oldSchInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Inter-corporate loans (Old Sch. VI).csv", header = [0,1])

In [57]:
oldSchInterCorpLoans11 = oldSchInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
oldSchInterCorpLoans12 = oldSchInterCorpLoans11.unstack().unstack(level = 1).reset_index()
oldSchInterCorpLoans13 = oldSchInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
oldSchInterCorpLoans13["AsOnDate"] = pd.to_datetime(oldSchInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [58]:
oldSchInterCorpLoans = oldSchInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Inter-corporate loans (Old Sch. VI)"], how = "all").reset_index(drop= True).drop_duplicates()
oldSchInterCorpLoans

,AsOnDate,Company Name,Inter-corporate loans (Old Sch. VI)
0,2016-03-31,2 X 2 Logistics Pvt. Ltd.,186.5
1,2017-03-31,2 X 2 Logistics Pvt. Ltd.,211.4
2,2023-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
3,2024-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
4,2011-03-31,20 Microns Ltd.,7.3
...,...,...,...
107767,2020-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,33.6
107768,2021-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,6.3
107769,2022-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,30.2
107770,2023-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,23.2
107771,2024-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,28.2

#### 18 Long term inter-corporate loans

In [59]:
longInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Long term inter-corporate loans.csv", header = [0,1])

In [60]:
longInterCorpLoans11 = longInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
longInterCorpLoans12 = longInterCorpLoans11.unstack().unstack(level = 1).reset_index()
longInterCorpLoans13 = longInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
longInterCorpLoans13["AsOnDate"] = pd.to_datetime(longInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [61]:
longInterCorpLoans = longInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Long term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
longInterCorpLoans

,AsOnDate,Company Name,Long term inter-corporate loans
0,2016-03-31,2 X 2 Logistics Pvt. Ltd.,186.5
1,2017-03-31,2 X 2 Logistics Pvt. Ltd.,211.4
2,2023-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
3,2024-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
4,2011-03-31,20 Microns Ltd.,7.3
...,...,...,...
43762,2020-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,33.6
43763,2021-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,6.3
43764,2022-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,30.2
43765,2023-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,23.2
43766,2024-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,28.2

#### 19 Secured inter-corporate loans (Old Sch. VI)

In [62]:
oldSchSecuredInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Secured inter-corporate loans (Old Sch. VI).csv", header = [0,1])

In [63]:
oldSchSecuredInterCorpLoans11 = oldSchSecuredInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
oldSchSecuredInterCorpLoans12 = oldSchSecuredInterCorpLoans11.unstack().unstack(level = 1).reset_index()
oldSchSecuredInterCorpLoans13 = oldSchSecuredInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
oldSchSecuredInterCorpLoans13["AsOnDate"] = pd.to_datetime(oldSchSecuredInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [64]:
oldSchSecuredInterCorpLoans = oldSchSecuredInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Secured inter-corporate loans (Old Sch. VI)"], how = "all").reset_index(drop= True).drop_duplicates()
oldSchSecuredInterCorpLoans

,AsOnDate,Company Name,Secured inter-corporate loans (Old Sch. VI)
0,2022-03-31,20Cube Warehousing & Distribution Pvt. Ltd. [M...,29.2
1,2011-03-31,A 1 Century Trades Ltd.,21.5
2,2012-03-31,A 1 Century Trades Ltd.,13.0
3,2013-03-31,A 1 Century Trades Ltd.,13.0
4,2019-03-31,A 1 Century Trades Ltd.,61.9
...,...,...,...
4111,2020-03-31,Zuari International Ltd.,390.0
4112,2021-03-31,Zuari International Ltd.,1110.0
4113,2022-03-31,Zuari International Ltd.,150.0
4114,2023-03-31,Zuari International Ltd.,390.0
4115,2024-03-31,Zuari International Ltd.,190.0

#### 20 Secured long term inter-corporate loans

In [65]:
securedLongInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Secured long term inter-corporate loans.csv", header = [0,1])

In [66]:
securedLongInterCorpLoans11 = securedLongInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
securedLongInterCorpLoans12 = securedLongInterCorpLoans11.unstack().unstack(level = 1).reset_index()
securedLongInterCorpLoans13 = securedLongInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
securedLongInterCorpLoans13["AsOnDate"] = pd.to_datetime(securedLongInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [67]:
securedLongInterCorpLoans = securedLongInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Secured long term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
securedLongInterCorpLoans

,AsOnDate,Company Name,Secured long term inter-corporate loans
0,2022-03-31,20Cube Warehousing & Distribution Pvt. Ltd. [M...,23.0
1,2011-03-31,A 1 Century Trades Ltd.,21.5
2,2012-03-31,A 1 Century Trades Ltd.,13.0
3,2013-03-31,A 1 Century Trades Ltd.,13.0
4,2019-03-31,A 1 Century Trades Ltd.,61.9
...,...,...,...
5349,2024-03-31,York Exports Ltd.,12.2
5350,2020-03-31,Zar Jewels Pvt. Ltd.,35.9
5351,2021-03-31,Zar Jewels Pvt. Ltd.,37.5
5352,2022-03-31,Zar Jewels Pvt. Ltd.,34.7
5353,2023-03-31,Zar Jewels Pvt. Ltd.,34.7

#### 21 Secured short term inter-corporate loans

In [68]:
securedShortInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Secured short term inter-corporate loans.csv", header = [0,1])

In [69]:
securedShortInterCorpLoans11 = securedShortInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
securedShortInterCorpLoans12 = securedShortInterCorpLoans11.unstack().unstack(level = 1).reset_index()
securedShortInterCorpLoans13 = securedShortInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
securedShortInterCorpLoans13["AsOnDate"] = pd.to_datetime(securedShortInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [70]:
securedShortInterCorpLoans = securedShortInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Secured short term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
securedShortInterCorpLoans

,AsOnDate,Company Name,Secured short term inter-corporate loans
0,2022-03-31,20Cube Warehousing & Distribution Pvt. Ltd. [M...,6.2
1,2020-03-31,A A Infraproperties Pvt. Ltd. [Merged],4927.2
2,2021-03-31,A A Infraproperties Pvt. Ltd. [Merged],6461.3
3,2022-03-31,A A Infraproperties Pvt. Ltd. [Merged],7124.4
4,2023-03-31,A A Infraproperties Pvt. Ltd. [Merged],7169.2
...,...,...,...
1059,2020-03-31,Zuari International Ltd.,390.0
1060,2021-03-31,Zuari International Ltd.,1110.0
1061,2022-03-31,Zuari International Ltd.,150.0
1062,2023-03-31,Zuari International Ltd.,390.0
1063,2024-03-31,Zuari International Ltd.,190.0

#### 22 Short term inter-corporate loans

In [71]:
shortInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Short term inter-corporate loans.csv", header = [0,1])

In [72]:
shortInterCorpLoans11 = shortInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
shortInterCorpLoans12 = shortInterCorpLoans11.unstack().unstack(level = 1).reset_index()
shortInterCorpLoans13 = shortInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
shortInterCorpLoans13["AsOnDate"] = pd.to_datetime(shortInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [73]:
shortInterCorpLoans = shortInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Short term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
shortInterCorpLoans

        AsOnDate        Company Name  Short term inter-corporate loans
0     2012-03-31     20 Microns Ltd.                              15.3
1     2013-03-31     20 Microns Ltd.                               6.8
2     2015-03-31     20 Microns Ltd.                              18.4
3     2017-03-31     20 Microns Ltd.                               3.6
4     2024-03-31     20 Microns Ltd.                               0.3
...          ...                 ...                               ...
35149 2012-03-31  Zylog Systems Ltd.                             195.2
35150 2013-03-31  Zylog Systems Ltd.                             957.2
35151 2014-03-31  Zylog Systems Ltd.                             964.7
35152 2015-03-31  Zylog Systems Ltd.                             985.1
35153 2016-03-31  Zylog Systems Ltd.                              42.1

[35154 rows x 3 columns]

#### 23 Unsecured inter-corporate loans (Old Sch. VI)

In [74]:
oldUnsecuredInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Unsecured inter-corporate loans (Old Sch. VI).csv", header = [0,1])

In [75]:
oldUnsecuredInterCorpLoans11 = oldUnsecuredInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
oldUnsecuredInterCorpLoans12 = oldUnsecuredInterCorpLoans11.unstack().unstack(level = 1).reset_index()
oldUnsecuredInterCorpLoans13 = oldUnsecuredInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
oldUnsecuredInterCorpLoans13["AsOnDate"] = pd.to_datetime(oldUnsecuredInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [76]:
oldUnsecuredInterCorpLoans = oldUnsecuredInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Unsecured inter-corporate loans (Old Sch. VI)"], how = "all").reset_index(drop= True).drop_duplicates()
oldUnsecuredInterCorpLoans

,AsOnDate,Company Name,Unsecured inter-corporate loans (Old Sch. VI)
0,2023-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
1,2024-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
2,2011-03-31,20 Microns Ltd.,7.3
3,2012-03-31,20 Microns Ltd.,22.7
4,2013-03-31,20 Microns Ltd.,37.0
...,...,...,...
101246,2020-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,33.6
101247,2021-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,6.3
101248,2022-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,30.2
101249,2023-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,23.2
101250,2024-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,28.2

#### 24 Unsecured long term inter-corporate loans

In [77]:
unsecuredLongInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Unsecured long term inter-corporate loans.csv", header = [0,1])

In [78]:
unsecuredLongInterCorpLoans11 = unsecuredLongInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
unsecuredLongInterCorpLoans12 = unsecuredLongInterCorpLoans11.unstack().unstack(level = 1).reset_index()
unsecuredLongInterCorpLoans13 = unsecuredLongInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
unsecuredLongInterCorpLoans13["AsOnDate"] = pd.to_datetime(unsecuredLongInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [79]:
unsecuredLongInterCorpLoans = unsecuredLongInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Unsecured long term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
unsecuredLongInterCorpLoans

,AsOnDate,Company Name,Unsecured long term inter-corporate loans
0,2023-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
1,2024-03-31,2 X 2 Logistics Pvt. Ltd.,80.0
2,2011-03-31,20 Microns Ltd.,7.3
3,2012-03-31,20 Microns Ltd.,7.4
4,2013-03-31,20 Microns Ltd.,30.2
...,...,...,...
41729,2020-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,33.6
41730,2021-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,6.3
41731,2022-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,30.2
41732,2023-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,23.2
41733,2024-03-31,Zyphar'S Pharmaceutics Pvt. Ltd.,28.2

#### 25 Unsecured short term inter-corporate loans

In [80]:
unsecuredShortInterCorpLoans1 = pd.read_csv(rf"{supporting_folder_path}\Intercorporate Loans\CMIE - Unsecured short term inter-corporate loans.csv", header = [0,1])

In [81]:
unsecuredShortInterCorpLoans11 = unsecuredShortInterCorpLoans1.set_index([("Unnamed: 0_level_0","Company Name")])
unsecuredShortInterCorpLoans12 = unsecuredShortInterCorpLoans11.unstack().unstack(level = 1).reset_index()
unsecuredShortInterCorpLoans13 = unsecuredShortInterCorpLoans12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
unsecuredShortInterCorpLoans13["AsOnDate"] = pd.to_datetime(unsecuredShortInterCorpLoans13["AsOnDate"], format = "%b-%y" ) + MonthEnd(0)

In [82]:
unsecuredShortInterCorpLoans = unsecuredShortInterCorpLoans13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Unsecured short term inter-corporate loans"], how = "all").reset_index(drop= True).drop_duplicates()
unsecuredShortInterCorpLoans

,AsOnDate,Company Name,Unsecured short term inter-corporate loans
0,2011-03-31,20 Microns Ltd.,0.0
1,2012-03-31,20 Microns Ltd.,15.3
2,2013-03-31,20 Microns Ltd.,6.8
3,2014-03-31,20 Microns Ltd.,0.0
4,2015-03-31,20 Microns Ltd.,18.4
...,...,...,...
34462,2012-03-31,Zylog Systems Ltd.,195.2
34463,2013-03-31,Zylog Systems Ltd.,957.2
34464,2014-03-31,Zylog Systems Ltd.,964.7
34465,2015-03-31,Zylog Systems Ltd.,985.1
34466,2016-03-31,Zylog Systems Ltd.,42.1

#### 26 Entity ID and stuff

In [83]:
# iden = fin_identifiers[fin_identifiers.columns[[0,1,2,3,4,5,6,7,8,9,10,11,12,13]]].droplevel( 0, axis =1)

In [84]:
# iden

In [85]:
iden = pd.read_csv(rf"{supporting_folder_path}\Prowess IQ - Indicators 2.txt", sep="|", dtype = {"NIC code":str})

In [86]:
iden

,Company Name,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address
0,'K' Steamship Agencies Pvt. Ltd.,3,Private Ltd.,10203010000,1971.0,Diversified,1.100000e+14,Diversified,34,20102000000,Private (Indian),Between 1951 and 1971,NaN,NaN
1,'X'Clusive Business Centre Pvt. Ltd.,307865,Private Ltd.,10203010000,1996.0,Diversified financial services,1.022000e+14,"Other financial service activities, except ins...",649,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
2,1 To 1 Help.Net Pvt. Ltd.,591675,Private Ltd.,10203010000,2001.0,Business services & consultancy,1.010415e+14,Management consultancy activities,70200,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
3,10C India Internet Pvt. Ltd.,556976,Private Ltd.,10203010000,2012.0,Telecommunication services,1.010406e+14,Other telecommunications activities,61900,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
4,10I Commerce Services Pvt. Ltd.,560502,Private Ltd.,10203010000,2015.0,Wholesale trading,1.010404e+14,"Wholesale of radio, television and other consu...",46522,20102000000,Private (Indian),After 2014,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55316,Zylog Systems Ltd.,275793,Public Ltd.,10203020000,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013,20102000000,Private (Indian),Between 1991 and 2013,ZYLOG,NaN
55317,Zyma Laboratories Ltd. [Merged],275794,Public Ltd.,10203020000,1970.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,20102000000,Private (Indian),Between 1951 and 1971,NaN,NaN
55318,Zyphar'S Pharmaceutics Pvt. Ltd.,565342,Private Ltd.,10203010000,2006.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
55319,Zytel Agencies Ltd.,275795,Public Ltd.,10203020000,1984.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,20102000000,Private (Indian),Between 1972 and 1985,NaN,NaN
55320,Zyxel Technology India Pvt. Ltd.,432445,Private Ltd.,10203010000,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN

### Merging all the raw Data together before merging with main

In [87]:
# 1 fin
# 2 defTaxLia
# 3 netDefTaxLia

# 4 bvps
# 5 sharesOut

# 6 market

# 7 netCashInvest
# 8 inCashSaleFixed
# 9 outCashPurchaseFixed
# 10 inCashSaleIntangible
# 11 outCashPurchaseIntangible

# 12 netCashEquiv
# 13 cashEquivEndYear
# 14 cashEquivBegYear

# 15 currLongInterCorpLoans
# 16 nbfcInterCorpLoans
# 17 oldSchInterCorpLoans
# 18 longInterCorpLoans
# 19 oldSchSecuredInterCorpLoans
# 20 securedLongInterCorpLoans
# 21 securedShortInterCorpLoans
# 22 shortInterCorpLoans
# 23 oldUnsecuredInterCorpLoans
# 24 unsecuredLongInterCorpLoans
# 25 unsecuredShortInterCorpLoans

# 26 iden
# 27 own

In [88]:
# raw1 = compCodeNse.merge(fin, on = ["Company Name"], how = "outer")
raw2 = fin.merge(defTaxLia, on = ["Company Name", "AsOnDate"], how = "outer")
raw3 = raw2.merge(netDefTaxLia, on = ["Company Name", "AsOnDate"], how = "outer")

In [89]:
raw4 = raw3.merge(bvps, on = ["Company Name", "AsOnDate"], how = "outer")
raw5 = raw4.merge(sharesOut, on = ["Company Name", "AsOnDate"], how = "outer")

raw6 = raw5.merge(market, on = ["Company Name", "AsOnDate"], how = "outer")

raw7 = raw6.merge(netCashInvest, on = ["Company Name", "AsOnDate"], how = "outer")

raw8 = raw7.merge(inCashSaleFixed, on = ["Company Name", "AsOnDate"], how = "outer")
raw9 = raw8.merge(outCashPurchaseFixed, on = ["Company Name", "AsOnDate"], how = "outer")

raw10 = raw9.merge(inCashSaleIntangible, on = ["Company Name", "AsOnDate"], how = "outer")
raw11 = raw10.merge(outCashPurchaseIntangible, on = ["Company Name", "AsOnDate"], how = "outer")

raw12 = raw11.merge(netCashEquiv, on = ["Company Name", "AsOnDate"], how = "outer")
raw13 = raw12.merge(cashEquivEndYear, on = ["Company Name", "AsOnDate"], how = "outer")
raw14 = raw13.merge(cashEquivBegYear, on = ["Company Name", "AsOnDate"], how = "outer")

raw15 = raw14.merge(currLongInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw16 = raw15.merge(nbfcInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw17 = raw16.merge(oldSchInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw18 = raw17.merge(longInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw19 = raw18.merge(oldSchSecuredInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw20 = raw19.merge(securedLongInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw21 = raw20.merge(securedShortInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw22 = raw21.merge(shortInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw23 = raw22.merge(oldUnsecuredInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw24 = raw23.merge(unsecuredLongInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")
raw25 = raw24.merge(unsecuredShortInterCorpLoans, on = ["Company Name", "AsOnDate"], how = "outer")

raw25 = raw24.merge(iden, on = ["Company Name"], how = "outer")
raw26 = raw25.merge(own, on = ["Company Name", "AsOnDate"], how = "outer")

In [90]:
raw26

,AsOnDate,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or (outflow) from investing activities,Cash inflow due to sale of fixed assets,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash (outflow) due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings (as per nbfc norms),Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans (Old Sch. VI),Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans (Old Sch. VI),Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,2011-03-31,'K' Steamship Agencies Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.3,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Private Ltd.,1.020301e+10,1971.0,Diversified,1.100000e+14,Diversified,34,2.010200e+10,Private (Indian),Between 1951 and 1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-03-31,'K' Steamship Agencies Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.6,8.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Private Ltd.,1.020301e+10,1971.0,Diversified,1.100000e+14,Diversified,34,2.010200e+10,Private (Indian),Between 1951 and 1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-31,'K' Steamship Agencies Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6,-0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Private Ltd.,1.020301e+10,1971.0,Diversified,1.100000e+14,Diversified,34,2.010200e+10,Private (Indian),Between 1951 and 1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-03-31,'K' Steamship Agencies Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,-0.8,NaN,NaN,NaN,NaN,NaN,NaN,-96.3,NaN,-7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Private Ltd.,1.020301e+10,1971.0,Diversified,1.100000e+14,Diversified,34,2.010200e+10,Private (Indian),Between 1951 and 1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-03-31,'K' Steamship Agencies Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,-3.3,NaN,NaN,NaN,NaN,NaN,NaN,-181.9,NaN,-117.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Private Ltd.,1.020301e+10,1971.0,Diversified,1.100000e+14,Diversified,34,2.010200e+10,Private (Indian),Between 1951 and 1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950177,2020-03-31,Zyxel Technology India Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.3,NaN,-0.3,NaN,NaN,-1.34685,0.25544,1.60230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432445.0,Private Ltd.,1.020301e+10,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,2.010200e+10,Private (Indian),Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950178,2021-03-31,Zyxel Technology India Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.2,NaN,-0.3,NaN,NaN,6.04053,6.29597,0.25544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432445.0,Private Ltd.,1.020301e+10,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,2.010200e+10,Private (Indian),Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950179,2022-03-31,Zyxel Technology India Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,NaN,-0.1,NaN,NaN,-2.50261,3.79335,6.29597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432445.0,Private Ltd.,1.020301e+10,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,2.010200e+10,Private (Indian),Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950180,2023-03-31,Zyxel Technology India Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.2,NaN,-0.2,NaN,NaN,39.68986,43.48322,3.79335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432445.0,Private Ltd.,1.020301e+10,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,2.010200e+10,Private (Indian),Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
950181,2024-03-31,Zyxel Technology India Pvt. Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.08072,28.40249,43.48322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432445.0,Private Ltd.,1.020301e+10,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411,2.010200e+10,Private (Indian),Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
finance_data = raw26.copy()
finance_data.to_pickle(rf"{output_folder_path}\Finance_data_merged_06_24.pkl")

In [92]:
main = pd.read_pickle(rf"{import_folder_path}\Main_Firm_No Loc_No Fin.pkl")
main

,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted
0,20MICRONS,2009-03-31,12,2009,2.484907,0,0.000000,0,69.916667,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,1,1,6.412557,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,5,0.416667,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.666667,0,0.000000,0,0.0,4,0.333333,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,NaN,NaN,12,0,"{information technology, accounts/audit/taxati...",16,0,0.0,[],1,0.083333,1,0.083333,0,0.000000,0,0.000000,[],[P00032270],"[P00027664, P00032270]","[P00027664, P00027665, P00032270]","[P00027662, P00027633, P00027664, P00029006, P...",[],[],[],[],[],NaN,0.000,0.000000,0.0,0.166667,0.000000,0.000,0.333333,0.916667,0.916667,0.500000,0.166667,0.333333,0.166667,0.666667,0.416667,0.500000,0.083333,0.416667,0.583333,0.166667,0.0,0.0,0.000000,0.0,0.166667,0.333333,0.750000,0.500000,0.083333,0.333333,0.166667,0.416667,0.416667,0.500000,0.0,0.416667,0.333333,0.166667,0.166667,0.333333,0.416667,0.0,0.0,0.000000,0.416667,0.0,0.0,0.0,0.166667,0.416667,0.0,0.0,0.166667,0.0,0.0,0.166667,0.0,0.416667,0.333333,0.333333,0.0,0.000000,0.0,0.416667,0.333333,0.333333,0.416667,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,2010-03-31,12,2010,2.484907,0,0.000000,0,70.333333,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,2,1,6.946575,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,6,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,9,0.750000,0,0.000000,0,0.0,5,0.416667,0,0.000000,0,0.0,11,0.916667,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,1.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],2,0.166667,2,0.166667,0,0.000000,0,0.000000,[],[P00031581],"[P00031581, P00032270]","[P00027664, P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,0.916667,0.0,0.166667,0.000000,0.000,0.416667,0.916667,0.916667,0.583333,0.250000,0.416667,0.250000,0.750000,0.500000,0.500000,0.083333,0.500000,0.583333,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.416667,0.750000,0.583333,0.166667,0.416667,0.250000,0.500000,0.500000,0.500000,0.0,0.500000,0.416667,0.250000,0.166667,0.416667,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.250000,0.500000,0.0,0.0,0.250000,0.0,0.0,0.166667,0.0,0.500000,0.416667,0.416667,0.0,0.083333,0.0,0.500000,0.416667,0.416667,0.500000,0.166667,1.0,0.000000,1.0,0.083333,0.0,0.0,0.000000
2,20MICRONS,2011-03-31,10,2011,2.302585,0,0.000000,0,68.9,2,1,8,0,0.000000,10,0,2,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,0,0,8.241370,0.000000,0.000000,0.000000,0.200000,0.800000,0.200000,0.800000,0,0,0,5,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.800000,0,0.000000,0,0.0,5,0.500000,0,0.000000,0,0.0,10,1.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,2.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00031581],"[P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,1.000000,0.0,0.100000,0.000000,0.000,0.400000,0.900000,0.900000,0.600000,0.200000,0.500000,0.200000,0.800000,0.500000,0.500000,0.100000,0.500000,0.500000,0.200000,0.0,0.0,0.000000,0.0,0.200000,0.500000,0.800000,0.600000,0.100000,0.500000,0.200000,0.500000,0.500000,0.500000,0.0,0.500000,0.500000,0.200000,0.100000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.200000,0.500000,0.0,0.0,0.200000,0.0,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.500000,0.100000,2.0,0.000000,2.0,0.166667,0.0,0.0,0.000000
3,20MICRONS,2012-03-31,11,2012,2.397895,0,0.000000,0,68.9,3,1,8,0,0.000000,11,0,3,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,3,1,8.323537,0.000000,0.000000,0.000000,0.272727,0.727273,0.272727,0.727273,0,0,0,5,0.454545,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.727273,0,0.000000,0,0.0,5,0.454545,0,0.000000,0,0.0,10,0.909091,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,0.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],3,0.272727,3,0.272727,0,0.000000,0,0.000000,[],[P00042601],[P00042601],"[P00042601, P00031581, P00032270]","[P00027633, P00027664, P00042601, P00029006, P...",[],[],[],[],[],NaN,0.000,0.909091,0.0,0.090909,0.000000,0.000,0.363636,0.818182,0.818182,0.545455,0.181818,0.454545,0.181818,0.727273,0.454545,0.454545,0.090909,0.454545,0.454545,0.181818,0.0,0.0,0.000000,0.0,0.181818,0.454545,0.727273,0.545455,0.090909,0.454545,0.181818,0.454545,0.454545,0.454545,0.0,0.454545,0.454545,0.181818,0.090909,0.454545,0.454545,0.0,0.0,0.000000,0.454545,0.0,0.0,0.0,0.181818,0.454545,0.0,0.0,0.181818,0.0,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.454545,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
4,20MICRONS,2013-03-31,8,2013,2.079442,0,0.000000,0,69.285714,1,1,7,3,0.375000,5,0,1,3,4,4,1,0.333333,1,1,1,1,1,1,1,1,2,1,0.333333,0,0,10.322260,0.375000,0.000000,0.375000,0.125000,0.500000,0.125000,0.875000,0,0,0,4,0.500000,2,0.666667,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,7,0.875000,3,1.000000,0,0.0,5,0.625000,2,0.666667,0,0.0,8,1.000000,3,1.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,3.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00042601],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",[],[],[],[],"[P00027633, P00031581, P00027665]",NaN,0.000,1.000000,0.0,0.000000,0.000000,0.000,0.500000,0.875000,0.875000,0.625000,0.125000,0.625000,0.250000,0.750000,0.625000,0.625000,0.125000,0.625000,0.625000,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.625000,0.875000,0.625000,0.125000,0.625000,0.250000,0.625000,0.625000,0.625000,0.0,0.625000,0.625000,0.250000,0.125000,0.625000,0.625000,0.0,0.0,0.000000,0.625000,0.0,0.0,0.0,0.250000,0.625000,0.0,0.0,0.250000,0.0,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.625000,0.125000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28904,ZYLOG,2014-03-31,8,2014,2.079442,0,0.000000,0,65.75,2,1,6,3,0.375000,5,1,1,2,4,1,1,0.333333,1,1,1,1,1,1,0,0,3,2,0.666667,3,1,7.815411,0.404110,0.333333,0.250000,0.125000,0.500000,0.250000,0.750000,0,1,0,0,0.000000,0,0.000000,0,0.0,1,0.125,0,0.0,0,0.0,1,0.125,1,0.333333,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,1,0.333333,0,0.0,0,0.000000,0,0.000000,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,0,0.0,0,0.0,2,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,1.0,2,1,"{accounts/audit/taxation, leadership/managemen...",7,0,0.0,[],3,0.375000,3,0.375000,1,0.333333,1,0.333333,[],"[P00048642, P00062851]","[P00048642, P00062851]","[P00048642, P00062851]","[P00027508, P00007571, P00114429, P00027510, P...",[],[P00062851],[P00062851],[P00062851],"[P00027508, P00007571, P00062851]",NaN,0.125,0.750000,0.0,0.125000,0.125000,0.125,0.125000,0.750000,0.625000,0.375000,0.000000,0.125000,0.125000,0.375000,0.375000,0.125000,0.000000,0.250000,0.500000,0.250000,0.0,0.0,0.000000,0.0,0.000000,0.750000,0.250000,0.125000,0.000000,0.000000,0.125000,0.125000,0.375000,0.125000,0.0,0.125000,0.250000,0.250000,0.000000,0.000000,0.125000,0.0,0.0,0.000000,0.125000,0.0,0.0,0.0,0.000000,0.125000,0.0,0.0,0.125000,0.0,0.0,0.000000,0.0,0.125000,0.125000,0.000000,0.0,0.000000,0.0,0.125000,0.000000,0.000000,0.000000,0.000000,3.0,0.400000,3.0,0.333333,2.0,2.0,0.400000
28905,ZYLOG,2015-03-31,7,2015,1.945910,0,0.000000,0,64.4,3,1,4,3,0.428571,4,2,1,1,3,1,0,0.000000,0,1,1,1,0,1,0,0,3,2,0.666667,1,1,8.549511,0.571429,0.666667,0.142857,0.142857,0.428571,0.428571,0.571429,1,0,1,0,0.000000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,5,0.714286,2,0.666667,1,0.500000,1,0.142857,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.0,5,0.714286,2,0.666667,1,0.500000,2,0.285714,0,0.0,0,0.0,2,0.285714,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.142857,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,0.0,2,1,{},0,0,0.0,[],1,0.142857,1,0.142857,0,0.000000,0,0.000000,[],"[P00067112, P00067111]","[P00067112, P00067111, P00062851]","[P00067112, P00067111, P00062851]","[P00027508, P00067112, P00114429, P00067111, P...",[],[P00067111],"[P00067111, P00062851]","[P00067111, P00062851]","[P00027508, P00067111, P00062851]",0.416667,0.000,0.714286,0.0,0.000000,0.000000,0.000,0.000000,0.714286,0.428571,0.142857,0.000000,0.142857,0.000000,0.142857,0.142857,0.000000,0.000000,0.142857,0.285714,0.142857,0.0,0.0,0.000000,0.0,0.000000,0.714286,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.0,0.000000,0.285714,0.142857,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,0.333333,3.0,0.375000,1.0,1.0,0.333333
28906,ZYLOG,2016-03-31,11,2016,2.397895,0,0.000000,0,62.5,7,1,4,7,0.636364,4,5,2,2,2,1,0,0.000000,0,1,0,1,0,1,0,0,8,6,0.857143,1,1,4.365878,0.637111,0.714286,0.181818,0.181818,0.181818,0.636364,0.363636,1,0,1,0,0.000000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,6,0.545455,3,0.428571,2,0.400000,3,0.272727,2,0.285714,0,0.0,1,0.090909,1,0.142857,0,0.0,6,0.545455,3,0.428571,2,0.400000,1,0.090909,0,0.0,0,0.0,1,0.090909,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,4,3,1,1,1,1,1,1,1.0,0.0,5,3,"{fast moving consumer goods, accounts/audit/ta...",12,0,0.0,[],1,0.090909,1,0.090909,0,0.000000,0,0.000000,[],"[P00073179, P00075400, P00075399, P00075398]","[P00067112, P00073179, P00075400, P00067111, P...","[P00067112, P00073179, P00075400, P00067111, P...","[P00027508, P00067112, P00073179, P00075400, P...",[],"[P00075400, P00075399, P00075398]","[P00075400, P00067111, P00075399, P00075398]","[P00075400, P00067111, P00075399, P00062851, P...","[P00027508, P00075400, P00067111, P00036956, P...",0.698413,0.000,0.545455,0.0,0.090909,0.181818,0.000,0.181818,0.909091,0.636364,0.272727,0.090909,0.181818,0.090909,0.181818,0.272727,0.090909,0.000000,0.090909,0.181818,0.181818,0.0,0.0,0.181818,0.0,0.000000,0.636364,0.454545,0.272727,0.090909,0.000000,0.090909,0.090909,0.272727,0.090909,0.0,0.090909,0.181818,0.181818,0.000000,0.000000,0.090909,0.0,0.0,0.090909,0.090909,0.0,0.0,0.0,0.000000,0.090909,0.0,0.0,0.090909,0.0,0.0,0.090909,0.0,0.090909,0.090909,0.000000,0.0,0.000000,0.0,0.090909,0.000000,0.090909,0.090909,0.090909,1.0,0.000000,1.0,0.142857,0.0,0.0,0.000000
28907,ZYLOG,2017-03-31,12,2017,2.484907,1,0.083333,1,63.0,9,1,3,9,0.750000,3,7,2,2,1,0,0,0.000000,0,0,0,0,0,0,0,0,10,8,0.888889,3,1,3.075799,0.989498,0.777778,0.166667,0.166667,0.083333,0.750000,0.250000,1,0,1,0,0.000000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,10,0.833333,7,0.777778,5,0.714286,2,0.166667,2,0.222222,0,0.0,1,0.083333,1,0.111111,0,0.0,10,0.833333,7,0.777778,5,0.714286,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,2,0,0,1,1,0,0,1.0,0.0,2,2,"{fast moving consumer goods, accounts/audit/ta...",12,0,0.0,[],3,0.250000,3,0.250000,3,0.333333,3,0.333333,[],"[P00081419, P00080494, P00075398]","[P00073179, P00075400, P00081419, P00080494, P...","[P00067112, P00073179, P00075400, P00081419, P...","[P00027508, P00067112, P00073179, P00075400, P...",[],"[P00081419, P00080494, P00075398]","[P00075400, P00081419, P00080494, P00075399, P...","[P00075400, P00081419, P00080494, P00067111, P...","[P00027508, P00075400, P00081419, P00080494, P...",NaN,0.000,0.833333,0.0,0.083333,0.250000,0.000,0.166667,0.833333,0.500000,0.333333,0.083333,0.083333,0.083333,0.166667,0.250000,0.083333,0.000000,0.083333,0.083333,0.166667,0.0,0.0,0.250000,0.0,0.000000,0.833333,0.250000,0.250000,0.083333,0.000000,0.083333,0.083333,0.250000,0.083333,0.0,0.083333,0.083333,0.166667,0.000000,0.000000,0.083333,0.0,0.0,0.083333,0.083333,0.0,0.0,0.0,0.000000,0.083333,0.0,0.0,0.083333,0.0,0.0,0.083333,0.0,0.083333,0.083333,0.000000,0.0,0.000000,0.0,0.083333,0.000000,0.083333,0.083333,0.083333,1.0,0.000000,1.0,0.090909,0.0,0.0,0.000000

In [93]:
merged = main.merge(finance_data, left_on = ["Symbol", "AsOnDate"], right_on = ["NSE symbol", "AsOnDate"], how = "left")

In [94]:
FirmID = merged.Symbol.drop_duplicates().reset_index(drop = True).reset_index().rename({"index":"FirmID"}, axis = 1)
FirmID

      FirmID      Symbol
0          0   20MICRONS
1          1  21STCENMGM
2          2      360ONE
3          3   3IINFOLTD
4          4     3MINDIA
...      ...         ...
2775    2775       ZUARI
2776    2776    ZUARIIND
2777    2777   ZYDUSLIFE
2778    2778   ZYDUSWELL
2779    2779       ZYLOG

[2780 rows x 2 columns]

In [95]:
merged2 = FirmID.merge(merged, on = "Symbol", how = "inner")
merged2

,FirmID,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or (outflow) from investing activities,Cash inflow due to sale of fixed assets,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash (outflow) due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings (as per nbfc norms),Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans (Old Sch. VI),Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans (Old Sch. VI),Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,0,20MICRONS,2009-03-31,12,2009,2.484907,0,0.000000,0,69.916667,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,1,1,6.412557,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,5,0.416667,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.666667,0,0.000000,0,0.0,4,0.333333,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,NaN,NaN,12,0,"{information technology, accounts/audit/taxati...",16,0,0.0,[],1,0.083333,1,0.083333,0,0.000000,0,0.000000,[],[P00032270],"[P00027664, P00032270]","[P00027664, P00027665, P00032270]","[P00027662, P00027633, P00027664, P00029006, P...",[],[],[],[],[],NaN,0.000,0.000000,0.0,0.166667,0.000000,0.000,0.333333,0.916667,0.916667,0.500000,0.166667,0.333333,0.166667,0.666667,0.416667,0.500000,0.083333,0.416667,0.583333,0.166667,0.0,0.0,0.000000,0.0,0.166667,0.333333,0.750000,0.500000,0.083333,0.333333,0.166667,0.416667,0.416667,0.500000,0.0,0.416667,0.333333,0.166667,0.166667,0.333333,0.416667,0.0,0.0,0.000000,0.416667,0.0,0.0,0.0,0.166667,0.416667,0.0,0.0,0.166667,0.0,0.0,0.166667,0.0,0.416667,0.333333,0.333333,0.0,0.000000,0.0,0.416667,0.333333,0.333333,0.416667,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,-89.9,4.2,-94.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90
1,0,20MICRONS,2010-03-31,12,2010,2.484907,0,0.000000,0,70.333333,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,2,1,6.946575,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,6,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,9,0.750000,0,0.000000,0,0.0,5,0.416667,0,0.000000,0,0.0,11,0.916667,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,1.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],2,0.166667,2,0.166667,0,0.000000,0,0.000000,[],[P00031581],"[P00031581, P00032270]","[P00027664, P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,0.916667,0.0,0.166667,0.000000,0.000,0.416667,0.916667,0.916667,0.583333,0.250000,0.416667,0.250000,0.750000,0.500000,0.500000,0.083333,0.500000,0.583333,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.416667,0.750000,0.583333,0.166667,0.416667,0.250000,0.500000,0.500000,0.500000,0.0,0.500000,0.416667,0.250000,0.166667,0.416667,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.250000,0.500000,0.0,0.0,0.250000,0.0,0.0,0.166667,0.0,0.500000,0.416667,0.416667,0.0,0.083333,0.0,0.500000,0.416667,0.416667,0.500000,0.166667,1.0,0.000000,1.0,0.083333,0.0,0.0,0.000000,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,-196.5,28.1,-164.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30
2,0,20MICRONS,2011-03-31,10,2011,2.302585,0,0.000000,0,68.9,2,1,8,0,0.000000,10,0,2,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,0,0,8.241370,0.000000,0.000000,0.000000,0.200000,0.800000,0.200000,0.800000,0,0,0,5,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.800000,0,0.000000,0,0.0,5,0.500000,0,0.000000,0,0.0,10,1.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,2.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00031581],"[P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,1.000000,0.0,0.100000,0.000000,0.000,0.400000,0.900000,0.900000,0.600000,0.200000,0.500000,0.200000,0.800000,0.500000,0.500000,0.100000,0.500000,0.500000,0.200000,0.0,0.0,0.000000,0.0,0.200000,0.500000,0.800000,0.600000,0.100000,0.500000,0.200000,0.500000,0.500000,0.500000,0.0,0.500000,0.500000,0.200000,0.100000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.200000,0.500000,0.0,0.0,0.200000,0.0,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.500000,0.100000,2.0,0.000000,2.0,0.166667,0.0,0.0,0.000000,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,-147.9,8.3,-154.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,7.3,7.3,NaN,NaN,NaN,NaN,7.3,7.3,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46
3,0,20MICRONS,2012-03-31,11,2012,2.397895,0,0.000000,0,68.9,3,1,8,0,0.000000,11,0,3,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,3,1,8.323537,0.000000,0.000000,0.000000,0.272727,0.727273,0.272727,0.727273,0,0,0,5,0.454545,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.727273,0,0.000000,0,0.0,5,0.454545,0,0.000000,0,0.0,10,0.909091,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,0.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],3,0.272727,3,0.272727,0,0.000000,0,0.000000,[],[P00042601],[P00042601],"[P00042601, P00031581, P00032270]","[P00027633, P00027664, P00042601, P00029006, P...",[],[],[],[],[],NaN,0.000,0.909091,0.0,0.090909,0.000000,0.000,0.363636,0.818182,0.818182,0.545455,0.181818,0.454545,0.181818,0.727273,0.454545,0.454545,0.090909,0.454545,0.454545,0.181818,0.0,0.0,0.000000,0.0,0.181818,0.454545,0.727273,0.545455,0.090909,0.454545,0.181818,0.454545,0.454545,0.454545,0.0,0.454545,0.454545,0.181818,0.090909,0.454545,0.454545,0.0,0.0,0.000000,0.454545,0.0,0.0,0.0,0.181818,0.454545,0.0,0.0,0.181818,0.0,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.454545,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,-397.2,15.6,-414.7,NaN,NaN,NaN,NaN,NaN,3.6,NaN,22.7,7.4,NaN,NaN,NaN,15.3,22.7,7.4,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35
4,0,20MICRONS,2013-03-31,8,2013,2.079442,0,0.000000,0,69.285714,1,1,7,3,0.375000,5,0,1,3,4,4,1,0.333333,1,1,1,1,1,1,1,1,2,1,0.333333,0,0,10.322260,0.375000,0.000000,0.375000,0.125000,0.500000,0.125000,0.875000,0,0,0,4,0.500000,2,0.666667,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,7,0.875000,3,1.000000,0,0.0,5,0.625000,2,0.666667,0,0.0,8,1.000000,3,1.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,3.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00042601],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",[],[],[],[],"[P00027633, P00031581, P00027665]",NaN,0.000,1.000000,0.0,0.000000,0.000000,0.000,0.500000,0.875000,0.875000,0.625000,0.125000,0.625000,0.250000,0.750000,0.625000,0.625000,0.125000,0.625000,0.625000,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.625000,0.875000,0.625000,0.125000,0.625000,0.250000,0.625000,0.625000,0.625000,0.0,0.625000,0.625000,0.250000,0.125000,0.625000,0.625000,0.0,0.0,0.000000,0.625000,0.0,0.0,0.0,0.250000,0.625000,0.0,0.0,0.250000,0.0,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.625000,0.125000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.000000,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,-361.2,1.9,-409.5,NaN,NaN,NaN,NaN,NaN,0.7,NaN,37.0,30.2,NaN,NaN,NaN,6.8,37.0,30.2,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28904,2779,ZYLOG,2014-03-31,8,2014,2.079442,0,0.000000,0,65.75,2,1,6,3,0.375000,5,1,1,2,4,1,1,0.333333,1,1,1,1,1,1,0,0,3,2,0.666667,3,1,7.815411,0.404110,0.333333,0.250000,0.125000,0.500000,0.250000,0.750000,0,1,0,0,0.000000,0,0.000000,0,0.0,1,0.125,0,0.0,0,0.0,1,0.125,1,0.333333,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,1,0.333333,0,0.0,0,0.000000,0,0.000000,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,0,0.0,0,0.0,2,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,1.0,2,1,"{accounts/audit/taxation, leadership/managemen...",7,0,0.0,[],3,0.375000,3,0.375000,1,0.333333,1,0.333333,[],"[P00048642, P00062851]","[P00048642, P00062851]","[P00048642, P00062851]","[P00027508, P00007571, P00114429, P00027510, P...",[],[P00062851],[P00062851],[P00062851],"[P00027508, P00007571, P00062851]",NaN,0.125,0.750000,0.0,0.125000,0.125000,0.125,0.125000,0.750000,0.625000,0.375000,0.000000,0.125000,0.125000,0.375000,0.375000,0.125000,0.000000,0.250000,0.500000,0.250000,0.0,0.0,0.000000,0.0,0.000000,0.750000,0.250000,0.125000,0.000000,0.000000,0.125000,0.125000,0.375000,0.125000,0.0,0.125000,0.250000,0.250000,0.000000,0.000000,0.125000,0.0,0.0,0.000000,0.125000,0.0,0.0,0.0,0.000000,0.125000,0.0,0.0,0.125000,0.0,0.0,0.000000,0.0,0.125000,0.125000,0.000000,0.0,0.000000,0.0,0.125000,0.000000,0.000000,0.000000,0.000000,3.0,0.400000,3.0,0.333333,2.0,2.0,0.400000,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,-1354.6,NaN,-2012.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964.7,NaN,NaN,NaN,NaN,964.7,964.7,NaN,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70

In [96]:
merged2["BVCommonStock"] = merged2["BVPS"] * merged2["Shares Outstanding "]
merged2

,FirmID,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or (outflow) from investing activities,Cash inflow due to sale of fixed assets,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash (outflow) due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings (as per nbfc norms),Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans (Old Sch. VI),Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans (Old Sch. VI),Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held,BVCommonStock
0,0,20MICRONS,2009-03-31,12,2009,2.484907,0,0.000000,0,69.916667,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,1,1,6.412557,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,5,0.416667,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.666667,0,0.000000,0,0.0,4,0.333333,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,NaN,NaN,12,0,"{information technology, accounts/audit/taxati...",16,0,0.0,[],1,0.083333,1,0.083333,0,0.000000,0,0.000000,[],[P00032270],"[P00027664, P00032270]","[P00027664, P00027665, P00032270]","[P00027662, P00027633, P00027664, P00029006, P...",[],[],[],[],[],NaN,0.000,0.000000,0.0,0.166667,0.000000,0.000,0.333333,0.916667,0.916667,0.500000,0.166667,0.333333,0.166667,0.666667,0.416667,0.500000,0.083333,0.416667,0.583333,0.166667,0.0,0.0,0.000000,0.0,0.166667,0.333333,0.750000,0.500000,0.083333,0.333333,0.166667,0.416667,0.416667,0.500000,0.0,0.416667,0.333333,0.166667,0.166667,0.333333,0.416667,0.0,0.0,0.000000,0.416667,0.0,0.0,0.0,0.166667,0.416667,0.0,0.0,0.166667,0.0,0.0,0.166667,0.0,0.416667,0.333333,0.333333,0.0,0.000000,0.0,0.416667,0.333333,0.333333,0.416667,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,-89.9,4.2,-94.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90,3.578302e+08
1,0,20MICRONS,2010-03-31,12,2010,2.484907,0,0.000000,0,70.333333,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,2,1,6.946575,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,6,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,9,0.750000,0,0.000000,0,0.0,5,0.416667,0,0.000000,0,0.0,11,0.916667,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,1.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],2,0.166667,2,0.166667,0,0.000000,0,0.000000,[],[P00031581],"[P00031581, P00032270]","[P00027664, P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,0.916667,0.0,0.166667,0.000000,0.000,0.416667,0.916667,0.916667,0.583333,0.250000,0.416667,0.250000,0.750000,0.500000,0.500000,0.083333,0.500000,0.583333,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.416667,0.750000,0.583333,0.166667,0.416667,0.250000,0.500000,0.500000,0.500000,0.0,0.500000,0.416667,0.250000,0.166667,0.416667,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.250000,0.500000,0.0,0.0,0.250000,0.0,0.0,0.166667,0.0,0.500000,0.416667,0.416667,0.0,0.083333,0.0,0.500000,0.416667,0.416667,0.500000,0.166667,1.0,0.000000,1.0,0.083333,0.0,0.0,0.000000,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,-196.5,28.1,-164.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30,4.160297e+08
2,0,20MICRONS,2011-03-31,10,2011,2.302585,0,0.000000,0,68.9,2,1,8,0,0.000000,10,0,2,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,0,0,8.241370,0.000000,0.000000,0.000000,0.200000,0.800000,0.200000,0.800000,0,0,0,5,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.800000,0,0.000000,0,0.0,5,0.500000,0,0.000000,0,0.0,10,1.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,2.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00031581],"[P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,1.000000,0.0,0.100000,0.000000,0.000,0.400000,0.900000,0.900000,0.600000,0.200000,0.500000,0.200000,0.800000,0.500000,0.500000,0.100000,0.500000,0.500000,0.200000,0.0,0.0,0.000000,0.0,0.200000,0.500000,0.800000,0.600000,0.100000,0.500000,0.200000,0.500000,0.500000,0.500000,0.0,0.500000,0.500000,0.200000,0.100000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.200000,0.500000,0.0,0.0,0.200000,0.0,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.500000,0.100000,2.0,0.000000,2.0,0.166667,0.0,0.0,0.000000,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,-147.9,8.3,-154.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,7.3,7.3,NaN,NaN,NaN,NaN,7.3,7.3,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46,4.459816e+08
3,0,20MICRONS,2012-03-31,11,2012,2.397895,0,0.000000,0,68.9,3,1,8,0,0.000000,11,0,3,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,3,1,8.323537,0.000000,0.000000,0.000000,0.272727,0.727273,0.272727,0.727273,0,0,0,5,0.454545,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.727273,0,0.000000,0,0.0,5,0.454545,0,0.000000,0,0.0,10,0.909091,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,0.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],3,0.272727,3,0.272727,0,0.000000,0,0.000000,[],[P00042601],[P00042601],"[P00042601, P00031581, P00032270]","[P00027633, P00027664, P00042601, P00029006, P...",[],[],[],[],[],NaN,0.000,0.909091,0.0,0.090909,0.000000,0.000,0.363636,0.818182,0.818182,0.545455,0.181818,0.454545,0.181818,0.727273,0.454545,0.454545,0.090909,0.454545,0.454545,0.181818,0.0,0.0,0.000000,0.0,0.181818,0.454545,0.727273,0.545455,0.090909,0.454545,0.181818,0.454545,0.454545,0.454545,0.0,0.454545,0.454545,0.181818,0.090909,0.454545,0.454545,0.0,0.0,0.000000,0.454545,0.0,0.0,0.0,0.181818,0.454545,0.0,0.0,0.181818,0.0,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.454545,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,-397.2,15.6,-414.7,NaN,NaN,NaN,NaN,NaN,3.6,NaN,22.7,7.4,NaN,NaN,NaN,15.3,22.7,7.4,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35,5.213628e+08
4,0,20MICRONS,2013-03-31,8,2013,2.079442,0,0.000000,0,69.285714,1,1,7,3,0.375000,5,0,1,3,4,4,1,0.333333,1,1,1,1,1,1,1,1,2,1,0.333333,0,0,10.322260,0.375000,0.000000,0.375000,0.125000,0.500000,0.125000,0.875000,0,0,0,4,0.500000,2,0.666667,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,7,0.875000,3,1.000000,0,0.0,5,0.625000,2,0.666667,0,0.0,8,1.000000,3,1.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,3.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00042601],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",[],[],[],[],"[P00027633, P00031581, P00027665]",NaN,0.000,1.000000,0.0,0.000000,0.000000,0.000,0.500000,0.875000,0.875000,0.625000,0.125000,0.625000,0.250000,0.750000,0.625000,0.625000,0.125000,0.625000,0.625000,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.625000,0.875000,0.625000,0.125000,0.625000,0.250000,0.625000,0.625000,0.625000,0.0,0.625000,0.625000,0.250000,0.125000,0.625000,0.625000,0.0,0.0,0.000000,0.625000,0.0,0.0,0.0,0.250000,0.625000,0.0,0.0,0.250000,0.0,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.625000,0.125000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.000000,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,-361.2,1.9,-409.5,NaN,NaN,NaN,NaN,NaN,0.7,NaN,37.0,30.2,NaN,NaN,NaN,6.8,37.0,30.2,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66,6.623702e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28904,2779,ZYLOG,2014-03-31,8,2014,2.079442,0,0.000000,0,65.75,2,1,6,3,0.375000,5,1,1,2,4,1,1,0.333333,1,1,1,1,1,1,0,0,3,2,0.666667,3,1,7.815411,0.404110,0.333333,0.250000,0.125000,0.500000,0.250000,0.750000,0,1,0,0,0.000000,0,0.000000,0,0.0,1,0.125,0,0.0,0,0.0,1,0.125,1,0.333333,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,1,0.333333,0,0.0,0,0.000000,0,0.000000,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,0,0.0,0,0.0,2,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,1.0,2,1,"{accounts/audit/taxation, leadership/managemen...",7,0,0.0,[],3,0.375000,3,0.375000,1,0.333333,1,0.333333,[],"[P00048642, P00062851]","[P00048642, P00062851]","[P00048642, P00062851]","[P00027508, P00007571, P00114429, P00027510, P...",[],[P00062851],[P00062851],[P00062851],"[P00027508, P00007571, P00062851]",NaN,0.125,0.750000,0.0,0.125000,0.125000,0.125,0.125000,0.750000,0.625000,0.375000,0.000000,0.125000,0.125000,0.375000,0.375000,0.125000,0.000000,0.250000,0.500000,0.250000,0.0,0.0,0.000000,0.0,0.000000,0.750000,0.250000,0.125000,0.000000,0.000000,0.125000,0.125000,0.375000,0.125000,0.0,0.125000,0.250000,0.250000,0.000000,0.000000,0.125000,0.0,0.0,0.000000,0.125000,0.0,0.0,0.0,0.000000,0.125000,0.0,0.0,0.125000,0.0,0.0,0.000000,0.0,0.125000,0.125000,0.000000,0.0,0.000000,0.0,0.125000,0.000000,0.000000,0.000000,0.000000,3.0,0.400000,3.0,0.333333,2.0,2.0,0.400000,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,-1354.6,NaN,-2012.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964.7,NaN,NaN,NaN,NaN,964.7,964.7,NaN,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70,5.129427e+09

## Location Data

In [97]:
loc = pd.read_excel(rf"{supporting_folder_path}\Prowess IQ - Location Data.xlsx", skiprows = 5)
loc = loc.drop( ["Registrar Address", "Company Name"], axis = 1).dropna(how = "all")
loc

     Corporate Office Head Office Registered Office  Prowess company code
0              Mumbai    Vadodara          Vadodara                    11
1              Mumbai         NaN            Mumbai                384392
2              Mumbai         NaN       Navi Mumbai                 96387
3           Bengaluru         NaN         Bengaluru                 36277
4                 NaN      Mumbai              Pune                183396
...               ...         ...               ...                   ...
2542            Surat         NaN             Surat                275663
2543        Bengaluru         NaN               Goa                397515
2544         Gurugram         NaN               Goa                275679
2545        Ahmedabad   Ahmedabad         Ahmedabad                 41246
2546        Ahmedabad         NaN         Ahmedabad                 42684

[2547 rows x 4 columns]

In [98]:
loc["Office"] = np.where( pd.isnull(loc["Head Office"]), loc["Corporate Office"], loc["Head Office"])
loc["Office"] = np.where( pd.isnull(loc["Office"]), loc["Registered Office"], loc["Office"])
loc2 = loc.drop( ["Corporate Office", "Head Office", "Registered Office"], axis = 1).dropna(how = "all")
loc2

      Prowess company code     Office
0                       11   Vadodara
1                   384392     Mumbai
2                    96387     Mumbai
3                    36277  Bengaluru
4                   183396     Mumbai
...                    ...        ...
2542                275663      Surat
2543                397515  Bengaluru
2544                275679   Gurugram
2545                 41246  Ahmedabad
2546                 42684  Ahmedabad

[2547 rows x 2 columns]

In [99]:
firmLoc = merged2.merge(loc2, on = ["Prowess company code"], how = "left")

In [100]:
firmLoc

,FirmID,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or (outflow) from investing activities,Cash inflow due to sale of fixed assets,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash (outflow) due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings (as per nbfc norms),Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans (Old Sch. VI),Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans (Old Sch. VI),Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held,BVCommonStock,Office
0,0,20MICRONS,2009-03-31,12,2009,2.484907,0,0.000000,0,69.916667,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,1,1,6.412557,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,5,0.416667,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.666667,0,0.000000,0,0.0,4,0.333333,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,NaN,NaN,12,0,"{information technology, accounts/audit/taxati...",16,0,0.0,[],1,0.083333,1,0.083333,0,0.000000,0,0.000000,[],[P00032270],"[P00027664, P00032270]","[P00027664, P00027665, P00032270]","[P00027662, P00027633, P00027664, P00029006, P...",[],[],[],[],[],NaN,0.000,0.000000,0.0,0.166667,0.000000,0.000,0.333333,0.916667,0.916667,0.500000,0.166667,0.333333,0.166667,0.666667,0.416667,0.500000,0.083333,0.416667,0.583333,0.166667,0.0,0.0,0.000000,0.0,0.166667,0.333333,0.750000,0.500000,0.083333,0.333333,0.166667,0.416667,0.416667,0.500000,0.0,0.416667,0.333333,0.166667,0.166667,0.333333,0.416667,0.0,0.0,0.000000,0.416667,0.0,0.0,0.0,0.166667,0.416667,0.0,0.0,0.166667,0.0,0.0,0.166667,0.0,0.416667,0.333333,0.333333,0.0,0.000000,0.0,0.416667,0.333333,0.333333,0.416667,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,-89.9,4.2,-94.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90,3.578302e+08,Vadodara
1,0,20MICRONS,2010-03-31,12,2010,2.484907,0,0.000000,0,70.333333,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,2,1,6.946575,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,6,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,9,0.750000,0,0.000000,0,0.0,5,0.416667,0,0.000000,0,0.0,11,0.916667,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,1.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],2,0.166667,2,0.166667,0,0.000000,0,0.000000,[],[P00031581],"[P00031581, P00032270]","[P00027664, P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,0.916667,0.0,0.166667,0.000000,0.000,0.416667,0.916667,0.916667,0.583333,0.250000,0.416667,0.250000,0.750000,0.500000,0.500000,0.083333,0.500000,0.583333,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.416667,0.750000,0.583333,0.166667,0.416667,0.250000,0.500000,0.500000,0.500000,0.0,0.500000,0.416667,0.250000,0.166667,0.416667,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.250000,0.500000,0.0,0.0,0.250000,0.0,0.0,0.166667,0.0,0.500000,0.416667,0.416667,0.0,0.083333,0.0,0.500000,0.416667,0.416667,0.500000,0.166667,1.0,0.000000,1.0,0.083333,0.0,0.0,0.000000,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,-196.5,28.1,-164.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30,4.160297e+08,Vadodara
2,0,20MICRONS,2011-03-31,10,2011,2.302585,0,0.000000,0,68.9,2,1,8,0,0.000000,10,0,2,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,0,0,8.241370,0.000000,0.000000,0.000000,0.200000,0.800000,0.200000,0.800000,0,0,0,5,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.800000,0,0.000000,0,0.0,5,0.500000,0,0.000000,0,0.0,10,1.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,2.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00031581],"[P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,1.000000,0.0,0.100000,0.000000,0.000,0.400000,0.900000,0.900000,0.600000,0.200000,0.500000,0.200000,0.800000,0.500000,0.500000,0.100000,0.500000,0.500000,0.200000,0.0,0.0,0.000000,0.0,0.200000,0.500000,0.800000,0.600000,0.100000,0.500000,0.200000,0.500000,0.500000,0.500000,0.0,0.500000,0.500000,0.200000,0.100000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.200000,0.500000,0.0,0.0,0.200000,0.0,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.500000,0.100000,2.0,0.000000,2.0,0.166667,0.0,0.0,0.000000,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,-147.9,8.3,-154.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,7.3,7.3,NaN,NaN,NaN,NaN,7.3,7.3,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46,4.459816e+08,Vadodara
3,0,20MICRONS,2012-03-31,11,2012,2.397895,0,0.000000,0,68.9,3,1,8,0,0.000000,11,0,3,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,3,1,8.323537,0.000000,0.000000,0.000000,0.272727,0.727273,0.272727,0.727273,0,0,0,5,0.454545,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.727273,0,0.000000,0,0.0,5,0.454545,0,0.000000,0,0.0,10,0.909091,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,0.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],3,0.272727,3,0.272727,0,0.000000,0,0.000000,[],[P00042601],[P00042601],"[P00042601, P00031581, P00032270]","[P00027633, P00027664, P00042601, P00029006, P...",[],[],[],[],[],NaN,0.000,0.909091,0.0,0.090909,0.000000,0.000,0.363636,0.818182,0.818182,0.545455,0.181818,0.454545,0.181818,0.727273,0.454545,0.454545,0.090909,0.454545,0.454545,0.181818,0.0,0.0,0.000000,0.0,0.181818,0.454545,0.727273,0.545455,0.090909,0.454545,0.181818,0.454545,0.454545,0.454545,0.0,0.454545,0.454545,0.181818,0.090909,0.454545,0.454545,0.0,0.0,0.000000,0.454545,0.0,0.0,0.0,0.181818,0.454545,0.0,0.0,0.181818,0.0,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.454545,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,-397.2,15.6,-414.7,NaN,NaN,NaN,NaN,NaN,3.6,NaN,22.7,7.4,NaN,NaN,NaN,15.3,22.7,7.4,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35,5.213628e+08,Vadodara
4,0,20MICRONS,2013-03-31,8,2013,2.079442,0,0.000000,0,69.285714,1,1,7,3,0.375000,5,0,1,3,4,4,1,0.333333,1,1,1,1,1,1,1,1,2,1,0.333333,0,0,10.322260,0.375000,0.000000,0.375000,0.125000,0.500000,0.125000,0.875000,0,0,0,4,0.500000,2,0.666667,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,7,0.875000,3,1.000000,0,0.0,5,0.625000,2,0.666667,0,0.0,8,1.000000,3,1.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,3.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00042601],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",[],[],[],[],"[P00027633, P00031581, P00027665]",NaN,0.000,1.000000,0.0,0.000000,0.000000,0.000,0.500000,0.875000,0.875000,0.625000,0.125000,0.625000,0.250000,0.750000,0.625000,0.625000,0.125000,0.625000,0.625000,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.625000,0.875000,0.625000,0.125000,0.625000,0.250000,0.625000,0.625000,0.625000,0.0,0.625000,0.625000,0.250000,0.125000,0.625000,0.625000,0.0,0.0,0.000000,0.625000,0.0,0.0,0.0,0.250000,0.625000,0.0,0.0,0.250000,0.0,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.625000,0.125000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.000000,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,-361.2,1.9,-409.5,NaN,NaN,NaN,NaN,NaN,0.7,NaN,37.0,30.2,NaN,NaN,NaN,6.8,37.0,30.2,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66,6.623702e+08,Vadodara
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28904,2779,ZYLOG,2014-03-31,8,2014,2.079442,0,0.000000,0,65.75,2,1,6,3,0.375000,5,1,1,2,4,1,1,0.333333,1,1,1,1,1,1,0,0,3,2,0.666667,3,1,7.815411,0.404110,0.333333,0.250000,0.125000,0.500000,0.250000,0.750000,0,1,0,0,0.000000,0,0.000000,0,0.0,1,0.125,0,0.0,0,0.0,1,0.125,1,0.333333,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,1,0.333333,0,0.0,0,0.000000,0,0.000000,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,0,0.0,0,0.0,2,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,1.0,2,1,"{accounts/audit/taxation, leadership/managemen...",7,0,0.0,[],3,0.375000,3,0.375000,1,0.333333,1,0.333333,[],"[P00048642, P00062851]","[P00048642, P00062851]","[P00048642, P00062851]","[P00027508, P00007571, P00114429, P00027510, P...",[],[P00062851],[P00062851],[P00062851],"[P00027508, P00007571, P00062851]",NaN,0.125,0.750000,0.0,0.125000,0.125000,0.125,0.125000,0.750000,0.625000,0.375000,0.000000,0.125000,0.125000,0.375000,0.375000,0.125000,0.000000,0.250000,0.500000,0.250000,0.0,0.0,0.000000,0.0,0.000000,0.750000,0.250000,0.125000,0.000000,0.000000,0.125000,0.125000,0.375000,0.125000,0.0,0.125000,0.250000,0.250000,0.000000,0.000000,0.125000,0.0,0.0,0.000000,0.125000,0.0,0.0,0.0,0.000000,0.125000,0.0,0.0,0.125000,0.0,0.0,0.000000,0.0,0.125000,0.125000,0.000000,0.0,0.000000,0.0,0.125000,0.000000,0.000000,0.000000,0.000000,3.0,0.400000,3.0,0.333333,2.0,2.0,0.400000,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,-1354.6,NaN,-2012.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964.7,NaN,NaN,NaN,NaN,964.7,964.7,NaN,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70,5.129427e+09,NaN

# Further Calc

In [101]:
firm0 = firmLoc.copy()

firm = firm0.rename({"Paid up preference capital (net of forfeited preference capital) (Old Sch. VI)":"Paid up preference capital_net of forfeited preference capital_old",
                     "Paid up preference capital (net of forfeited preference capital)":"Paid up preference capital_net of forfeited preference capital",
                     "Indian Promoters (In %) - Shares held":"Indian Promoters_percent",
                     "Total Shares (In %) - Shares held":"Total Shares_percent_Shares held",
                     "Foreign Promoters (In %) - Shares held":"Foreign Promoters_percent",
                     "Non-promoters (In %) - Shares held":"Nonpromoters_percent",
                     "Non-promoter Institutions (In %) - Shares held":"NonpromoterInstitutions_percent",
                     "Non-promoter Non-institutions (In %) - Shares held":"Nonpromoter Noninstitutions_percent",
                     "Trade payables (Old Sch. VI)":"Trade payables_old",
                     "Debt to equity ratio (times)":"Debt to equity ratio",
                     "Cash (outflow) due to purchase of fixed assets":"Cash outflow due to purchase of fixed assets",
                     "Net cash inflow or (outflow) from investing activities":"Net cash inflow or outflow from investing activities",
                     "Cash (outflow) due to purchase of Intangible assets":"Cash outflow due to purchase of Intangible assets",
                     "Research & development expenses":"Research development expenses",
                     "Inter-corporate loans (Old Sch. VI)":"Intercorporate loans_old",
                     "Promoters (In %) - Shares held":"Promoters_percent",
                     "Inter-corporate loans & borrowings (as per nbfc norms)":"Inter-corporate loans & borrowings_nbfc norms",
                     "Inter-corporate loans (Old Sch. VI)":"Inter-corporate loans_old sch",
                     "Secured inter-corporate loans (Old Sch. VI)":"Secured inter-corporate loans_old sch",
                     "Unsecured inter-corporate loans (Old Sch. VI)":"Unsecured inter-corporate loans_old sch"
                    }, axis = 1)

firm

,FirmID,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio,Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables_old,Subscribed preference capital,Paid up preference capital_net of forfeited preference capital_old,Paid up preference capital_net of forfeited preference capital,Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or outflow from investing activities,Cash inflow due to sale of fixed assets,Cash outflow due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash outflow due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings_nbfc norms,Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans_old sch,Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans_old sch,Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares_percent_Shares held,Promoters_percent,Indian Promoters_percent,Foreign Promoters_percent,Nonpromoters_percent,NonpromoterInstitutions_percent,Nonpromoter Noninstitutions_percent,BVCommonStock,Office
0,0,20MICRONS,2009-03-31,12,2009,2.484907,0,0.000000,0,69.916667,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,1,1,6.412557,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,5,0.416667,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.666667,0,0.000000,0,0.0,4,0.333333,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,NaN,NaN,12,0,"{information technology, accounts/audit/taxati...",16,0,0.0,[],1,0.083333,1,0.083333,0,0.000000,0,0.000000,[],[P00032270],"[P00027664, P00032270]","[P00027664, P00027665, P00032270]","[P00027662, P00027633, P00027664, P00029006, P...",[],[],[],[],[],NaN,0.000,0.000000,0.0,0.166667,0.000000,0.000,0.333333,0.916667,0.916667,0.500000,0.166667,0.333333,0.166667,0.666667,0.416667,0.500000,0.083333,0.416667,0.583333,0.166667,0.0,0.0,0.000000,0.0,0.166667,0.333333,0.750000,0.500000,0.083333,0.333333,0.166667,0.416667,0.416667,0.500000,0.0,0.416667,0.333333,0.166667,0.166667,0.333333,0.416667,0.0,0.0,0.000000,0.416667,0.0,0.0,0.0,0.166667,0.416667,0.0,0.0,0.166667,0.0,0.0,0.166667,0.0,0.416667,0.333333,0.333333,0.0,0.000000,0.0,0.416667,0.333333,0.333333,0.416667,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,-89.9,4.2,-94.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90,3.578302e+08,Vadodara
1,0,20MICRONS,2010-03-31,12,2010,2.484907,0,0.000000,0,70.333333,3,1,9,0,0.000000,12,0,3,0,9,0,1,0.000000,1,0,0,0,0,0,0,0,6,0,0.000000,2,1,6.946575,0.000000,0.000000,0.000000,0.250000,0.750000,0.250000,0.750000,0,0,0,6,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,9,0.750000,0,0.000000,0,0.0,5,0.416667,0,0.000000,0,0.0,11,0.916667,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,1.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],2,0.166667,2,0.166667,0,0.000000,0,0.000000,[],[P00031581],"[P00031581, P00032270]","[P00027664, P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,0.916667,0.0,0.166667,0.000000,0.000,0.416667,0.916667,0.916667,0.583333,0.250000,0.416667,0.250000,0.750000,0.500000,0.500000,0.083333,0.500000,0.583333,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.416667,0.750000,0.583333,0.166667,0.416667,0.250000,0.500000,0.500000,0.500000,0.0,0.500000,0.416667,0.250000,0.166667,0.416667,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.250000,0.500000,0.0,0.0,0.250000,0.0,0.0,0.166667,0.0,0.500000,0.416667,0.416667,0.0,0.083333,0.0,0.500000,0.416667,0.416667,0.500000,0.166667,1.0,0.000000,1.0,0.083333,0.0,0.0,0.000000,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,-196.5,28.1,-164.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30,4.160297e+08,Vadodara
2,0,20MICRONS,2011-03-31,10,2011,2.302585,0,0.000000,0,68.9,2,1,8,0,0.000000,10,0,2,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,0,0,8.241370,0.000000,0.000000,0.000000,0.200000,0.800000,0.200000,0.800000,0,0,0,5,0.500000,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.800000,0,0.000000,0,0.0,5,0.500000,0,0.000000,0,0.0,10,1.000000,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,2.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00031581],"[P00031581, P00032270]","[P00027633, P00027664, P00029006, P00027661, P...",[],[],[],[],[],NaN,0.000,1.000000,0.0,0.100000,0.000000,0.000,0.400000,0.900000,0.900000,0.600000,0.200000,0.500000,0.200000,0.800000,0.500000,0.500000,0.100000,0.500000,0.500000,0.200000,0.0,0.0,0.000000,0.0,0.200000,0.500000,0.800000,0.600000,0.100000,0.500000,0.200000,0.500000,0.500000,0.500000,0.0,0.500000,0.500000,0.200000,0.100000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.0,0.0,0.0,0.200000,0.500000,0.0,0.0,0.200000,0.0,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.0,0.100000,0.0,0.500000,0.500000,0.500000,0.500000,0.100000,2.0,0.000000,2.0,0.166667,0.0,0.0,0.000000,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,-147.9,8.3,-154.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,7.3,7.3,NaN,NaN,NaN,NaN,7.3,7.3,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46,4.459816e+08,Vadodara
3,0,20MICRONS,2012-03-31,11,2012,2.397895,0,0.000000,0,68.9,3,1,8,0,0.000000,11,0,3,0,8,0,1,0.000000,1,0,0,0,0,0,0,0,5,0,0.000000,3,1,8.323537,0.000000,0.000000,0.000000,0.272727,0.727273,0.272727,0.727273,0,0,0,5,0.454545,0,0.000000,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,8,0.727273,0,0.000000,0,0.0,5,0.454545,0,0.000000,0,0.0,10,0.909091,0,0.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,0,0,1,0,0,0,0.0,0.0,1,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],3,0.272727,3,0.272727,0,0.000000,0,0.000000,[],[P00042601],[P00042601],"[P00042601, P00031581, P00032270]","[P00027633, P00027664, P00042601, P00029006, P...",[],[],[],[],[],NaN,0.000,0.909091,0.0,0.090909,0.000000,0.000,0.363636,0.818182,0.818182,0.545455,0.181818,0.454545,0.181818,0.727273,0.454545,0.454545,0.090909,0.454545,0.454545,0.181818,0.0,0.0,0.000000,0.0,0.181818,0.454545,0.727273,0.545455,0.090909,0.454545,0.181818,0.454545,0.454545,0.454545,0.0,0.454545,0.454545,0.181818,0.090909,0.454545,0.454545,0.0,0.0,0.000000,0.454545,0.0,0.0,0.0,0.181818,0.454545,0.0,0.0,0.181818,0.0,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.0,0.090909,0.0,0.454545,0.454545,0.454545,0.454545,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,-397.2,15.6,-414.7,NaN,NaN,NaN,NaN,NaN,3.6,NaN,22.7,7.4,NaN,NaN,NaN,15.3,22.7,7.4,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35,5.213628e+08,Vadodara
4,0,20MICRONS,2013-03-31,8,2013,2.079442,0,0.000000,0,69.285714,1,1,7,3,0.375000,5,0,1,3,4,4,1,0.333333,1,1,1,1,1,1,1,1,2,1,0.333333,0,0,10.322260,0.375000,0.000000,0.375000,0.125000,0.500000,0.125000,0.875000,0,0,0,4,0.500000,2,0.666667,0,0.0,0,0.000,0,0.0,0,0.0,0,0.000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.000000,7,0.875000,3,1.000000,0,0.0,5,0.625000,2,0.666667,0,0.0,8,1.000000,3,1.000000,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,0,0,0,0,0,0,0,0,3.0,0.0,0,0,"{information technology, accounts/audit/taxati...",17,0,0.0,[],0,0.000000,0,0.000000,0,0.000000,0,0.000000,[],[],[P00042601],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",[],[],[],[],"[P00027633, P00031581, P00027665]",NaN,0.000,1.000000,0.0,0.000000,0.000000,0.000,0.500000,0.875000,0.875000,0.625000,0.125000,0.625000,0.250000,0.750000,0.625000,0.625000,0.125000,0.625000,0.625000,0.250000,0.0,0.0,0.000000,0.0,0.250000,0.625000,0.875000,0.625000,0.125000,0.625000,0.250000,0.625000,0.625000,0.625000,0.0,0.625000,0.625000,0.250000,0.125000,0.625000,0.625000,0.0,0.0,0.000000,0.625000,0.0,0.0,0.0,0.250000,0.625000,0.0,0.0,0.250000,0.0,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.0,0.125000,0.0,0.625000,0.625000,0.625000,0.625000,0.125000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.000000,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,-361.2,1.9,-409.5,NaN,NaN,NaN,NaN,NaN,0.7,NaN,37.0,30.2,NaN,NaN,NaN,6.8,37.0,30.2,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66,6.623702e+08,Vadodara
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28904,2779,ZYLOG,2014-03-31,8,2014,2.079442,0,0.000000,0,65.75,2,1,6,3,0.375000,5,1,1,2,4,1,1,0.333333,1,1,1,1,1,1,0,0,3,2,0.666667,3,1,7.815411,0.404110,0.333333,0.250000,0.125000,0.500000,0.250000,0.750000,0,1,0,0,0.000000,0,0.000000,0,0.0,1,0.125,0,0.0,0,0.0,1,0.125,1,0.333333,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,1,0.333333,0,0.0,0,0.000000,0,0.000000,0,0.0,6,0.750000,2,0.666667,0,0.000000,2,0.250000,0,0.0,0,0.0,2,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0.125000,0,0.0,0,0.0,2,1,0,0,1,1,0,0,3.0,1.0,2,1,"{accounts/audit/taxation, leadership/managemen...",7,0,0.0,[],3,0.375000,3,0.375000,1,0.333333,1,0.333333,[],"[P00048642, P00062851]","[P00048642, P00062851]","[P00048642, P00062851]","[P00027508, P00007571, P00114429, P00027510, P...",[],[P00062851],[P00062851],[P00062851],"[P00027508, P00007571, P00062851]",NaN,0.125,0.750000,0.0,0.125000,0.125000,0.125,0.125000,0.750000,0.625000,0.375000,0.000000,0.125000,0.125000,0.375000,0.375000,0.125000,0.000000,0.250000,0.500000,0.250000,0.0,0.0,0.000000,0.0,0.000000,0.750000,0.250000,0.125000,0.000000,0.000000,0.125000,0.125000,0.375000,0.125000,0.0,0.125000,0.250000,0.250000,0.000000,0.000000,0.125000,0.0,0.0,0.000000,0.125000,0.0,0.0,0.0,0.000000,0.125000,0.0,0.0,0.125000,0.0,0.0,0.000000,0.0,0.125000,0.125000,0.000000,0.0,0.000000,0.0,0.125000,0.000000,0.000000,0.000000,0.000000,3.0,0.400000,3.0,0.333333,2.0,2.0,0.400000,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,-1354.6,NaN,-2012.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964.7,NaN,NaN,NaN,NaN,964.7,964.7,NaN,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70,5.129427e+09,NaN

## Calculations

In [102]:
firm["NoFamilyControl"] = np.where( (firm["IsFamilyManaged"] == 0) & (firm["HasFamilyChairman"] == 0)
                                   & (firm["HasFamilyChairmanAndCEO"] == 0), 1, 0)

firm["PBOA_calc"] = firm["PBDITA"].fillna(0) / firm["Total assets"]
firm["ROA_calc"] = firm["Profit after tax"].fillna(0) / firm["Total assets"]
firm["ln_totalassets"] = np.log(firm["Total assets"])

firm["Book value of common stock"] = firm["BVPS"].fillna(0) * firm["Shares Outstanding "].fillna(0)

firm["TobinQ_Debt1"] = (firm["Debt"].fillna(0) + firm["Paid up preference capital_net of forfeited preference capital"].fillna(0)
                        + firm["Market Capitalisation"].fillna(0)) / firm["Total assets"]
firm["ln_TobinQ_Debt1"] = np.log(firm["TobinQ_Debt1"])

firm["TobinQ_longborrowincl2"] = (firm["Long term borrowings incl current portion"].fillna(0)
                                  + firm["Paid up preference capital_net of forfeited preference capital"].fillna(0)
                                  + firm["Market Capitalisation"].fillna(0)) / firm["Total assets"]

firm["TobinQ_longborrowexcl3"] = (firm["Long term borrowings excl current portion"].fillna(0)
                                  + firm["Paid up preference capital_net of forfeited preference capital"].fillna(0)
                                  + firm["Market Capitalisation"].fillna(0)) / firm["Total assets"]

firm["ln_TobinQ_longborrowincl2"] = np.log(firm["TobinQ_longborrowincl2"])
firm["ln_TobinQ_longborrowexcl3"] = np.log(firm["TobinQ_longborrowexcl3"])


firm["TobinQ_BVPS"] = (firm["Total assets"].fillna(0)
                       + firm["Market Capitalisation"].fillna(0)
                       - firm["Book value of common stock"].fillna(0)) / firm["Total assets"]

firm["BookLeverage"] = (firm["Long term borrowings incl current portion"].fillna(0)
                        + firm["Trade payables_old"].fillna(0)) / firm["Total assets"]

firm["Debt_TotalAssets"] = firm["Debt"].fillna(0) / firm["Total assets"]
firm["RD to Assets"] = firm["Research development expenses"].fillna(0) / firm["Total assets"]
firm["ln_rdtoassets"] = np.log(firm["RD to Assets"])

firm["ln_marcap"] = np.log(firm["Market Capitalisation"])

firm["FirmAge"] = firm["AsOnYear"].fillna(0) - firm["Incorporation year"]
firm["lnage"] = np.log(firm["FirmAge"])

firm["govtdummy"] = np.where( firm["Ownership group code"] <= 20000000000, 1, 0)

fincode = [649, 64191, 64192, 64300, 64920, 64990, 65110, 65120, 66190, 66301]
firm["findummy"] = np.where( firm["NIC code"].isin(fincode), 1, 0)

firm["promoterholding20"] = np.where( firm["Promoters_percent"] >= 20,1,0)
firm["promoterholding25"] = np.where( firm["Promoters_percent"] >= 25,1,0)
firm["promoterholding30"] = np.where( firm["Promoters_percent"] >= 30,1,0)
firm["promoterholding40"] = np.where( firm["Promoters_percent"] >= 40,1,0)
firm["promoterholding50"] = np.where( firm["Promoters_percent"] >= 50,1,0)

firm["FamilyOwnedFamilyCeoChair20"] = np.where( (firm["HasFamilyChairmanAndCEO"] == 1) & (firm["promoterholding20"] == 1),1,0)
firm["FamilyOwnedFamilyCeoChair25"] = np.where( (firm["HasFamilyChairmanAndCEO"] == 1) & (firm["promoterholding25"] == 1),1,0)
firm["FamilyOwnedFamilyCeoChair30"] = np.where( (firm["HasFamilyChairmanAndCEO"] == 1) & (firm["promoterholding30"] == 1),1,0)
firm["FamilyOwnedFamilyCeoChair40"] = np.where( (firm["HasFamilyChairmanAndCEO"] == 1) & (firm["promoterholding40"] == 1),1,0)
firm["FamilyOwnedFamilyCeoChair50"] = np.where( (firm["HasFamilyChairmanAndCEO"] == 1) & (firm["promoterholding50"] == 1),1,0)

firm["FamilyOwnedFamilyChair20"] = np.where( (firm["HasFamilyChairman"] == 1) & (firm["promoterholding20"] == 1),1,0)
firm["FamilyOwnedFamilyChair25"] = np.where( (firm["HasFamilyChairman"] == 1) & (firm["promoterholding25"] == 1),1,0)
firm["FamilyOwnedFamilyChair30"] = np.where( (firm["HasFamilyChairman"] == 1) & (firm["promoterholding30"] == 1),1,0)
firm["FamilyOwnedFamilyChair40"] = np.where( (firm["HasFamilyChairman"] == 1) & (firm["promoterholding40"] == 1),1,0)
firm["FamilyOwnedFamilyChair50"] = np.where( (firm["HasFamilyChairman"] == 1) & (firm["promoterholding50"] == 1),1,0)

firm["FamilyOwnedFamilyManaged20"] = np.where( (firm["IsFamilyManaged"] == 1) & (firm["promoterholding20"] == 1),1,0)
firm["FamilyOwnedFamilyManaged25"] = np.where( (firm["IsFamilyManaged"] == 1) & (firm["promoterholding25"] == 1),1,0)
firm["FamilyOwnedFamilyManaged30"] = np.where( (firm["IsFamilyManaged"] == 1) & (firm["promoterholding30"] == 1),1,0)
firm["FamilyOwnedFamilyManaged40"] = np.where( (firm["IsFamilyManaged"] == 1) & (firm["promoterholding40"] == 1),1,0)
firm["FamilyOwnedFamilyManaged50"] = np.where( (firm["IsFamilyManaged"] == 1) & (firm["promoterholding50"] == 1),1,0)

C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\SHIVAM\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [103]:
firm.columns.to_list()

['FirmID',
 'Symbol',
 'AsOnDate',
 'TotDirCount',
 'AsOnYear',
 'LnBoardSize',
 'FemaleDirCount',
 'PercentWomenDir',
 'Women_dummy',
 'AvgAge',
 'CountRookie',
 'Rookie_dummy',
 'CountNonRookie',
 'CountIndep',
 'PercentIndep',
 'CountNonIndep',
 'CountRookieIndep',
 'CountRookieNonIndep',
 'CountNonRookieIndep',
 'CountNonRookieNonIndep',
 'CountPromoterDir',
 'CountBusyDir',
 'PercentBusyDir',
 'Busy_dummy',
 'HasCeoMD',
 'HasChairman',
 'HasPromoterOnBoard',
 'HasDualityChairmanMD',
 'IsFamilyManaged',
 'HasFamilyChairman',
 'HasFamilyChairmanAndCEO',
 'CountFirstTermDir',
 'CountFirstTermIndepDir',
 'PercentFirstTermIndepDir',
 'CountTurnOverIndepDir',
 'HasIndepTurnOver',
 'AvgTenureInYearsinCompTotal',
 'AvgTenureInYearsinCompIndep',
 'PercentRookieIndep',
 'PercentNonRookieIndep',
 'PercentRookieNonIndep',
 'PercentNonRookieNonIndep',
 'PercentRookie',
 'PercentNonRookie',
 'IsRookieBoard',
 'JustOneRookie',
 'TwoOrMoreRookies',
 'CountMBA',
 'PercentMBA',
 'CountIndepMBA',
 'PercentIndepMBA',
 'CountRookieIndepMBA',
 'PercentRookieIndepMBA',
 'CountPhD',
 'PercentPhD',
 'CountIndepPhD',
 'PercentIndepPhD',
 'CountRookieIndepPhD',
 'PercentRookieIndepPhD',
 'CountFinanceXP',
 'PercentFinanceXP',
 'CountIndepFinanceXP',
 'PercentIndepFinanceXP',
 'CountRookieIndepFinanceXP',
 'PercentRookieIndepFinanceXP',
 'CountTechXP',
 'PercentTechXP',
 'CountIndepTechXP',
 'PercentIndepTechXP',
 'CountRookieIndepTechXP',
 'PercentRookieIndepTechXP',
 'CountFinanceSkill',
 'PercentFinanceSkill',
 'CountIndepFinanceSkill',
 'PercentIndepFinanceSkill',
 'CountRookieIndepFinanceSkill',
 'PercentRookieIndepFinanceSkill',
 'CountTechSkill',
 'PercentTechSkill',
 'CountIndepTechSkill',
 'PercentIndepTechSkill',
 'CountRookieIndepTechSkill',
 'PercentRookieIndepTechSkill',
 'CountRelatedIndustryXP',
 'PercentRelatedIndustryXP',
 'CountIndepRelatedIndustryXP',
 'PercentIndepRelatedIndustryXP',
 'CountRookieIndepRelatedIndustryXP',
 'PercentRookieIndepRelatedIndustryXP',
 'CountExecXP',
 'PercentExecXP',
 'CountIndepExecXP',
 'PercentIndepExecXP',
 'CountRookieIndepExecXP',
 'PercentRookieIndepExecXP',
 'CountPublicExecXP',
 'PercentPublicExecXP',
 'CountIndepPublicExecXP',
 'PercentIndepPublicExecXP',
 'CountRookieIndepPublicExecXP',
 'PercentRookieIndepPublicExecXP',
 'CountPrivateExecXP',
 'PercentPrivateExecXP',
 'CountIndepPrivateExecXP',
 'PercentIndepPrivateExecXP',
 'CountRookieIndepPrivateExecXP',
 'PercentRookieIndepPrivateExecXP',
 'CountCeoMDChairXP',
 'PercentCeoMDChairXP',
 'CountIndepCeoMDChairXP',
 'PercentIndepCeoMDChairXP',
 'CountRookieIndepCeoMDChairXP',
 'PercentRookieIndepCeoMDChairXP',
 'CountRookieAppoint',
 'CountRookieIndepAppoint',
 'CountNonRookieAppoint',
 'CountNonRookieIndepAppoint',
 'RookieAppointDummy',
 'RookieIndepAppointDummy',
 'NonRookieAppointDummy',
 'NonRookieIndepAppointDummy',
 'TotalDirCess',
 'TotalRookieIndepDirCess',
 'TotalDirAppoint',
 'TotalRookieIndepDirAppoint',
 'UniqueSkills',
 'CountUniqueSkills',
 'CountRetiringTermLimit',
 'PercentRetiringTermLimit',
 'TermLimitRetireesPcodeList',
 'CountDirTurnOver_exits_retire',
 'PercentDirTurnOver_exits_retire',
 'CountDirTurnOver_real_exits',
 'PercentDirTurnOver_real_exits',
 'CountIndepDirTurnOver_exits_retire',
 'PercentIndepDirTurnOver_exits_retire',
 'CountIndepDirTurnOver_real_exits',
 'PercentIndepDirTurnOver_real_exits',
 'ZeroYearPCodeList',
 'FirstYearPCodeList',
 'TwoYearPCodeList',
 'ThreeYearPCodeList',
 'PCodeList',
 'ZeroYearIndepPCodeList',
 'FirstYearIndepPCodeList',
 'TwoYearIndepPCodeList',
 'ThreeYearIndepPCodeList',
 'IndepPCodeList',
 'BoardAbsenceMean',
 'Academic_mean',
 'Company Business_mean',
 'combined_sustainability_mean',
 'combined_entrepreneurial_mean',
 'combined_compensation_mean',
 'combined_conglomerate_experience_mean',
 'combined_hr_mean',
 'combined_technology_mean',
 'combined_finance_accounting_mean',
 'combined_governance_mean',
 'combined_government_policy_mean',
 'combined_international_mean',
 'combined_leadership_mean',
 'combined_legal_mean',
 'combined_marketing_mean',
 'combined_risk_management_mean',
 'combined_scientific_mean',
 'combined_strategic_planning_mean',
 'combined_manufacturing_supply_chain_mean',
 'combined_leadership_outside_board_mean',
 'skill_committee_sustainability_mean',
 'skill_committee_entrepreneurial_mean',
 'skill_committee_compensation_mean',
 'skill_committee_conglomerate_experience_mean',
 'skill_committee_hr_mean',
 'skill_committee_technology_mean',
 'skill_committee_finance_accounting_mean',
 'skill_committee_governance_mean',
 'skill_committee_government_policy_mean',
 'skill_committee_international_mean',
 'skill_committee_leadership_mean',
 'skill_committee_legal_mean',
 'skill_committee_marketing_mean',
 'skill_committee_risk_management_mean',
 'skill_committee_scientific_mean',
 'skill_committee_strategic_planning_mean',
 'skill_committee_manufacturing_supply_chain_mean',
 'skill_committee_leadership_outside_board_mean',
 'board_consumer discretionary_mean',
 'board_research & development_mean',
 'board_legal/compliance_mean',
 'board_utilities_mean',
 'board_healthcare_mean',
 'board_fast moving consumer goods_mean',
 'board_risk management_mean',
 'board_economics_mean',
 'board_supply chain management_mean',
 'board_diversified_mean',
 'board_personal values_mean',
 'board_finance_mean',
 'board_diversity_mean',
 'board_telecommunication_mean',
 'board_leadership/management_mean',
 'board_energy_mean',
 'board_industrials_mean',
 'board_human resources_mean',
 'board_services_mean',
 'board_corporate governance_mean',
 'board_accounts/audit/taxation_mean',
 'board_operations_mean',
 'board_financial services_mean',
 'board_commodities_mean',
 'board_corporate social responsibility_mean',
 'board_strategy_mean',
 'board_international business_mean',
 'board_information technology_mean',
 'board_marketing_mean',
 'board_public policy_mean',
 'CountDirTurnOver_exits_retire_shifted',
 'PercentIndepDirTurnOver_exits_retire_shifted',
 'CountDirTurnOver_real_exits_shifted',
 'PercentDirTurnOver_real_exits_shifted',
 'CountIndepDirTurnOver_exits_retire_shifted',
 'CountIndepDirTurnOver_real_exits_shifted',
 'PercentIndepDirTurnOver_real_exits_shifted',
 'Company Name',
 'Sales',
 'Profit after tax',
 'PBDITA',
 'Return on total assets',
 'Total assets',
 'Operating  profit of non-financial companies',
 'Operating profit of financial companies',
 'Debt to equity ratio',
 'Long term borrowings incl current portion',
 'Long term borrowings excl current portion',
 'Debt',
 'Trade payables_old',
 'Subscribed preference capital',
 'Paid up preference capital_net of forfeited preference capital_old',
 'Paid up preference capital_net of forfeited preference capital',
 'Paid up preference shares',
 'Total other receivables',
 'Net cash flow from operating activities',
 'Research development expenses',
 'Inter-corporate loans (Old Sch. VI)_x',
 'Deferred tax liability',
 'Net deferred tax liabilities',
 'BVPS',
 'Shares Outstanding ',
 'Market Capitalisation',
 'Total Returns',
 'P/B ',
 'Market Capitalisation / Enterprise Value',
 'Net cash inflow or outflow from investing activities',
 'Cash inflow due to sale of fixed assets',
 'Cash outflow due to purchase of fixed assets',
 'Cash inflow due to sale of Intangible assets',
 'Cash outflow due to purchase of Intangible assets',
 'Net change in cash and cash equivalents',
 'Cash and cash equivalents as at the end of the year',
 'Cash and cash equivalents as at the beginning of the year',
 'Current portion of long term inter-corporate loans',
 'Inter-corporate loans & borrowings_nbfc norms',
 'Inter-corporate loans (Old Sch. VI)_y',
 'Long term inter-corporate loans',
 'Secured inter-corporate loans_old sch',
 'Secured long term inter-corporate loans',
 'Secured short term inter-corporate loans',
 'Short term inter-corporate loans',
 'Unsecured inter-corporate loans_old sch',
 'Unsecured long term inter-corporate loans',
 'Prowess company code',
 'Entity type',
 'Entity type code',
 'Incorporation year',
 'Industry group',
 'Industry group code',
 'NIC name',
 'NIC code',
 'Ownership group code',
 'Ownership group',
 'Age group',
 'NSE symbol',
 'Head office address',
 'Total Shares_percent_Shares held',
 'Promoters_percent',
 'Indian Promoters_percent',
 'Foreign Promoters_percent',
 'Nonpromoters_percent',
 'NonpromoterInstitutions_percent',
 'Nonpromoter Noninstitutions_percent',
 'BVCommonStock',
 'Office',
 'NoFamilyControl',
 'PBOA_calc',
 'ROA_calc',
 'ln_totalassets',
 'Book value of common stock',
 'TobinQ_Debt1',
 'ln_TobinQ_Debt1',
 'TobinQ_longborrowincl2',
 'TobinQ_longborrowexcl3',
 'ln_TobinQ_longborrowincl2',
 'ln_TobinQ_longborrowexcl3',
 'TobinQ_BVPS',
 'BookLeverage',
 'Debt_TotalAssets',
 'RD to Assets',
 'ln_rdtoassets',
 'ln_marcap',
 'FirmAge',
 'lnage',
 'govtdummy',
 'findummy',
 'promoterholding20',
 'promoterholding25',
 'promoterholding30',
 'promoterholding40',
 'promoterholding50',
 'FamilyOwnedFamilyCeoChair20',
 'FamilyOwnedFamilyCeoChair25',
 'FamilyOwnedFamilyCeoChair30',
 'FamilyOwnedFamilyCeoChair40',
 'FamilyOwnedFamilyCeoChair50',
 'FamilyOwnedFamilyChair20',
 'FamilyOwnedFamilyChair25',
 'FamilyOwnedFamilyChair30',
 'FamilyOwnedFamilyChair40',
 'FamilyOwnedFamilyChair50',
 'FamilyOwnedFamilyManaged20',
 'FamilyOwnedFamilyManaged25',
 'FamilyOwnedFamilyManaged30',
 'FamilyOwnedFamilyManaged40',
 'FamilyOwnedFamilyManaged50']

In [104]:
firm = firm.replace([np.inf, -np.inf], np.nan)
firm.describe()

,FirmID,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio,Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables_old,Subscribed preference capital,Paid up preference capital_net of forfeited preference capital_old,Paid up preference capital_net of forfeited preference capital,Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or outflow from investing activities,Cash inflow due to sale of fixed assets,Cash outflow due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash outflow due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings_nbfc norms,Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans_old sch,Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans_old sch,Unsecured long term inter-corporate loans,Prowess company code,Entity type code,Incorporation year,Industry group code,Ownership group code,Total Shares_percent_Shares held,Promoters_percent,Indian Promoters_percent,Foreign Promoters_percent,Nonpromoters_percent,NonpromoterInstitutions_percent,Nonpromoter Noninstitutions_percent,BVCommonStock,NoFamilyControl,PBOA_calc,ROA_calc,ln_totalassets,Book value of common stock,TobinQ_Debt1,ln_TobinQ_Debt1,TobinQ_longborrowincl2,TobinQ_longborrowexcl3,ln_TobinQ_longborrowincl2,ln_TobinQ_longborrowexcl3,TobinQ_BVPS,BookLeverage,Debt_TotalAssets,RD to Assets,ln_rdtoassets,ln_marcap,FirmAge,lnage,govtdummy,findummy,promoterholding20,promoterholding25,promoterholding30,promoterholding40,promoterholding50,FamilyOwnedFamilyCeoChair20,FamilyOwnedFamilyCeoChair25,FamilyOwnedFamilyCeoChair30,FamilyOwnedFamilyCeoChair40,FamilyOwnedFamilyCeoChair50,FamilyOwnedFamilyChair20,FamilyOwnedFamilyChair25,FamilyOwnedFamilyChair30,FamilyOwnedFamilyChair40,FamilyOwnedFamilyChair50,FamilyOwnedFamilyManaged20,FamilyOwnedFamilyManaged25,FamilyOwnedFamilyManaged30,FamilyOwnedFamilyManaged40,FamilyOwnedFamilyManaged50
count,28909.000000,28909,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.0,28909.0,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,26129.000000,26129.000000,28909.000000,28909.000000,28909.000000,28909.0,28909.0,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,16716.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.0,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,26129.000000,26129.000000,26129.000000,26129.000000,26129.000000,26129.000000,26129.000000,2.539200e+04,27360.000000,2.736000e+04,27323.000000,2.736100e+04,2.736000e+04,27360.000000,25650.000000,1.701300e+04,1.697000e+04,2.510800e+04,2.606400e+04,2314.000000,2603.000000,2603.000000,2.357000e+03,2.312300e+04,2.708600e+04,8774.000000,7847.000000,21490.000000,23984.000000,28605.000000,2.860500e+04,2.866600e+04,28675.000000,26607.000000,28608.000000,2.653100e+04,17412.000000,23654.000000,15.000000,823.000000,15225.000000,15092.000000,15232.000000,210.000000,122.000000,4982.000000,1865.000000,406.000000,340.000000,127.000000,2233.000000,4472.000000,1648.000000,28696.000000,2.869600e+04,28652.000000,2.869600e+04,2.869600e+04,27843.0,27566.000000,26965.000000,17682.000000,27843.000000,27101.000000,27843.000000,2.860500e+04,28909.000000,27360.000000,27360.000000,27360.000000,2.890900e+04,27360.000000,27357.000000,27360.000000,27360.000000,27356.000000,27356.000000,2.736000e+04,27360.000000,27360.000000,27360.000000,8715.000000,28632.000000,28652.000000,28652.000000,28909.000000,28909.0,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.000000,28909.00000,28909.000000
mean,1380.263447,2016-06-20 07:07:19.959873792,8.933446,2016.223598,2.122505,1.066346,0.124234,0.723235,2.196582,0.771213,6.736864,3.249369,0.366445,5.684078,0.769795,1.426788,2.479574,4.257290,1.296309,1.622920,0.230660,0.585908,4.236259,1.670310,0.366976,1.750182,0.546473,8.987520,1.187005,0.173315,0.278731,0.148484,0.485070,0.236199,0.763801,0.097202,0.216784,0.200214,2.363693,0.259023,0.923173,0.193209,0.175655,0.102807,0.616071,0.064101,0.309488,0.062889,0.069529,0.037391,1.800858,0.192278,0.848974,0.175034,0.081739,0.046121,0.697015,0.078029,0.330970,0.068324,0.028227,0.016786,5.496281,0.607826,2.269155,0.483385,0.081739,0.046121,2.546300,0.275496,1.054793,0.217477,0.184614,0.110444,7.315749,0.829851,2.753572,0.606476,0.449860,0.252844,0.592584,0.064306,0.128092,0.025686,0.015255,0.009734,0.589782,0.063966,0.128022,0.025674,0.015220,0.009699,0.003736,0.000336,0.002352,0.000398,0.0,0.0,0.592238,0.068714,0.134871,0.026444,0.004531,0.002782,0.799682,0.279048,0.244457,0.121900,0.448995,0.196409,0.179183,0.098032,1.040377,0.092732,1.750562,0.328410,14.568266,0.0,0.0,1.750182,0.186178,1.750182,0.186178,0.755163,0.158823,0.755163,0.158823,0.190550,0.064101,0.829851,0.317357,0.339118,0.283126,0.028095,0.437602,0.919885,0.891684,0.580783,0.311929,0.370754,0.583406,0.433046,0.532748,0.442643,0.051821,0.502780,0.538956,0.657788,0.305049,0.181513,0.260151,0.0,0.220742,0.655764,0.761340,0.566980,0.201014,0.185727,0.557501,0.408944,0.517539,0.442080,0.001005,0.492403,0.413127,0.637713,0.177936,0.155064,0.408001,0.016696,0.043097,0.043808,0.386280,0.123022,0.047291,0.002476,0.219314,0.529342,0.090112,0.009391,0.557477,0.009952,0.118955,0.290259,0.030022,0.467563,0.309864,0.286930,0.072756,0.092897,0.136490,0.470512,0.175708,0.266461,0.343772,0.186228,1.040377,0.073498,1.040377,0.099591,0.390218,0.390218,0.073498,3.405319e+04,2955.238030,1.188849e+04,2.968437,1.357654e+05,2.974891e+03,4794.117836,1.616725,1.526656e+04,1.286139e+04,3.044007e+04,4.547885e+03,1562.740925,1478.102958,1478.102958,1.636884e+08,4.829223e+03,3.606299e+03,408.905117,1446.270205,2294.957417,540.412471,146.257224,2.889736e+08,7.846130e+04,0.638269,3.282749,0.742946,-3.271351e+03,170.771359,-2203.046779,42.993333,-750.676428,61.016942,1302.392322,1229.445429,1954.961905,8377.181148,1703.151987,1477.423003,5264.092857,1888.300588,2983.479528,1365.561576,1283.129405,1451.973604,188697.910963,1.020310e+10,1981.790242,1.013274e+14,1.954598e+10,100.0,54.619642,49.135623,10.044624,45.594634,12.400345,33.523965,2.556593e+10,0.499879,0.124101,0.023805,9.162641,2.529708e+10,1.824924,0.042395,1.576037,1.551578,-0.297812,-0.348168,4.090507e+05,0.296517,0.384574,0.002986,-6.093919,8.511022,34.420704,3.329495,0.055969,0.0,0.915839,0.898613,0.867550,0.773462,0.626864,0.234321,0.230413,0.223840,0.204504,0.170293,0.389221,0.382857,0.372479,0.337577,0.275900,0.400671,0.393026,0.381265,0.34446,0.282057
min,0.000000,2006-03-31 00:00:00,1.000000,2006.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.506849,-0.832485,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.611111,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.396000e+02,-731315.000000,-4.391500e+05,-1457.140000,0.000000e+00,-1.215089e+06,-439096.000000,0.000000,0.000000e+00,-1.000000e-01,0.000000e+00,1.000000e-01,0.000000,0.000000,0.000000,0.000000e+00,-1.000000e-01,-9.135181e+05,0.000000,-40.600000,0.000000,-270542.000000,-3294.970000,3.463060e+05,0.000000e+00,-50.000000,-0.000000,-515.210000,-1.436250e+06,-636.900000,-427200.000000,-8.700000,-170135.000000,-216530.000000,-62175.400000,-29065.300000,0.000000,0.000000,0.100000,0.000000,0.100000,0.000000,0.000000,0.000000,0.100000,0.000000,11.000000,1.020301e+10,1863.000000,1.010111e+14,1.010000e+10,100.0,0.000000,0.000000,0.000000,0.410000,0.000000,0.070000,-9.597946e+11,0.000000,-33.200000,-103.608696,-2.302585,-9.597946e+11,0.000000,-5.613093,0.000000,0.000000,-7.113712,-7.113712,-8.873902e+07,0.000000,0.000000,0.000000,-14.974653,0.277632,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000

In [105]:
firm.loc[ firm["AvgTenureInYearsinCompTotal"] < 0]

,FirmID,Symbol,AsOnDate,TotDirCount,AsOnYear,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,PercentBusyDir,Busy_dummy,HasCeoMD,HasChairman,HasPromoterOnBoard,HasDualityChairmanMD,IsFamilyManaged,HasFamilyChairman,HasFamilyChairmanAndCEO,CountFirstTermDir,CountFirstTermIndepDir,PercentFirstTermIndepDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsinCompTotal,AvgTenureInYearsinCompIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,CountMBA,PercentMBA,CountIndepMBA,PercentIndepMBA,CountRookieIndepMBA,PercentRookieIndepMBA,CountPhD,PercentPhD,CountIndepPhD,PercentIndepPhD,CountRookieIndepPhD,PercentRookieIndepPhD,CountFinanceXP,PercentFinanceXP,CountIndepFinanceXP,PercentIndepFinanceXP,CountRookieIndepFinanceXP,PercentRookieIndepFinanceXP,CountTechXP,PercentTechXP,CountIndepTechXP,PercentIndepTechXP,CountRookieIndepTechXP,PercentRookieIndepTechXP,CountFinanceSkill,PercentFinanceSkill,CountIndepFinanceSkill,PercentIndepFinanceSkill,CountRookieIndepFinanceSkill,PercentRookieIndepFinanceSkill,CountTechSkill,PercentTechSkill,CountIndepTechSkill,PercentIndepTechSkill,CountRookieIndepTechSkill,PercentRookieIndepTechSkill,CountRelatedIndustryXP,PercentRelatedIndustryXP,CountIndepRelatedIndustryXP,PercentIndepRelatedIndustryXP,CountRookieIndepRelatedIndustryXP,PercentRookieIndepRelatedIndustryXP,CountExecXP,PercentExecXP,CountIndepExecXP,PercentIndepExecXP,CountRookieIndepExecXP,PercentRookieIndepExecXP,CountPublicExecXP,PercentPublicExecXP,CountIndepPublicExecXP,PercentIndepPublicExecXP,CountRookieIndepPublicExecXP,PercentRookieIndepPublicExecXP,CountPrivateExecXP,PercentPrivateExecXP,CountIndepPrivateExecXP,PercentIndepPrivateExecXP,CountRookieIndepPrivateExecXP,PercentRookieIndepPrivateExecXP,CountCeoMDChairXP,PercentCeoMDChairXP,CountIndepCeoMDChairXP,PercentIndepCeoMDChairXP,CountRookieIndepCeoMDChairXP,PercentRookieIndepCeoMDChairXP,CountRookieAppoint,CountRookieIndepAppoint,CountNonRookieAppoint,CountNonRookieIndepAppoint,RookieAppointDummy,RookieIndepAppointDummy,NonRookieAppointDummy,NonRookieIndepAppointDummy,TotalDirCess,TotalRookieIndepDirCess,TotalDirAppoint,TotalRookieIndepDirAppoint,UniqueSkills,CountUniqueSkills,CountRetiringTermLimit,PercentRetiringTermLimit,TermLimitRetireesPcodeList,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,ZeroYearPCodeList,FirstYearPCodeList,TwoYearPCodeList,ThreeYearPCodeList,PCodeList,ZeroYearIndepPCodeList,FirstYearIndepPCodeList,TwoYearIndepPCodeList,ThreeYearIndepPCodeList,IndepPCodeList,BoardAbsenceMean,Academic_mean,Company Business_mean,combined_sustainability_mean,combined_entrepreneurial_mean,combined_compensation_mean,combined_conglomerate_experience_mean,combined_hr_mean,combined_technology_mean,combined_finance_accounting_mean,combined_governance_mean,combined_government_policy_mean,combined_international_mean,combined_leadership_mean,combined_legal_mean,combined_marketing_mean,combined_risk_management_mean,combined_scientific_mean,combined_strategic_planning_mean,combined_manufacturing_supply_chain_mean,combined_leadership_outside_board_mean,skill_committee_sustainability_mean,skill_committee_entrepreneurial_mean,skill_committee_compensation_mean,skill_committee_conglomerate_experience_mean,skill_committee_hr_mean,skill_committee_technology_mean,skill_committee_finance_accounting_mean,skill_committee_governance_mean,skill_committee_government_policy_mean,skill_committee_international_mean,skill_committee_leadership_mean,skill_committee_legal_mean,skill_committee_marketing_mean,skill_committee_risk_management_mean,skill_committee_scientific_mean,skill_committee_strategic_planning_mean,skill_committee_manufacturing_supply_chain_mean,skill_committee_leadership_outside_board_mean,board_consumer discretionary_mean,board_research & development_mean,board_legal/compliance_mean,board_utilities_mean,board_healthcare_mean,board_fast moving consumer goods_mean,board_risk management_mean,board_economics_mean,board_supply chain management_mean,board_diversified_mean,board_personal values_mean,board_finance_mean,board_diversity_mean,board_telecommunication_mean,board_leadership/management_mean,board_energy_mean,board_industrials_mean,board_human resources_mean,board_services_mean,board_corporate governance_mean,board_accounts/audit/taxation_mean,board_operations_mean,board_financial services_mean,board_commodities_mean,board_corporate social responsibility_mean,board_strategy_mean,board_international business_mean,board_information technology_mean,board_marketing_mean,board_public policy_mean,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio,Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables_old,Subscribed preference capital,Paid up preference capital_net of forfeited preference capital_old,Paid up preference capital_net of forfeited preference capital,Paid up preference shares,Total other receivables,Net cash flow from operating activities,Research development expenses,Inter-corporate loans (Old Sch. VI)_x,Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Net cash inflow or outflow from investing activities,Cash inflow due to sale of fixed assets,Cash outflow due to purchase of fixed assets,Cash inflow due to sale of Intangible assets,Cash outflow due to purchase of Intangible assets,Net change in cash and cash equivalents,Cash and cash equivalents as at the end of the year,Cash and cash equivalents as at the beginning of the year,Current portion of long term inter-corporate loans,Inter-corporate loans & borrowings_nbfc norms,Inter-corporate loans (Old Sch. VI)_y,Long term inter-corporate loans,Secured inter-corporate loans_old sch,Secured long term inter-corporate loans,Secured short term inter-corporate loans,Short term inter-corporate loans,Unsecured inter-corporate loans_old sch,Unsecured long term inter-corporate loans,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares_percent_Shares held,Promoters_percent,Indian Promoters_percent,Foreign Promoters_percent,Nonpromoters_percent,NonpromoterInstitutions_percent,Nonpromoter Noninstitutions_percent,BVCommonStock,Office,NoFamilyControl,PBOA_calc,ROA_calc,ln_totalassets,Book value of common stock,TobinQ_Debt1,ln_TobinQ_Debt1,TobinQ_longborrowincl2,TobinQ_longborrowexcl3,ln_TobinQ_longborrowincl2,ln_TobinQ_longborrowexcl3,TobinQ_BVPS,BookLeverage,Debt_TotalAssets,RD to Assets,ln_rdtoassets,ln_marcap,FirmAge,lnage,govtdummy,findummy,promoterholding20,promoterholding25,promoterholding30,promoterholding40,promoterholding50,FamilyOwnedFamilyCeoChair20,FamilyOwnedFamilyCeoChair25,FamilyOwnedFamilyCeoChair30,FamilyOwnedFamilyCeoChair40,FamilyOwnedFamilyCeoChair50,FamilyOwnedFamilyChair20,FamilyOwnedFamilyChair25,FamilyOwnedFamilyChair30,FamilyOwnedFamilyChair40,FamilyOwnedFamilyChair50,FamilyOwnedFamilyManaged20,FamilyOwnedFamilyManaged25,FamilyOwnedFamilyManaged30,FamilyOwnedFamilyManaged40,FamilyOwnedFamilyManaged50
2141,214,ASIANELEC,2006-03-31,2,2006,0.693147,0,0.000000,0,88.0,0,0,2,0,0.000000,2,0,0,0,2,0,2,0.0,1,0,0,0,0,0,0,0,2,0,0.000000,0,0,-6.506849,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0,0,0,2,1.000000,0,0.000000,0,0.0,1,0.500000,0,0.000000,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0.500000,0,0.000000,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,2,0,0,0,1,0,NaN,NaN,2,0,"{corporate social responsibility, accounts/aud...",13,0,0.0,[],0,0.000000,0,0.000000,0,0.0,0,0.0,[],[],[],[],"[P00000310, P00003700]",[],[],[],[],[],NaN,0.500000,0.000000,0.500000,0.500000,0.500000,0.000000,0.500000,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.500000,0.000000,0.500000,0.000000,0.500000,1.000000,0.500000,0.500000,0.0,0.000000,0.0,0.000000,0.500000,1.000000,0.500000,0.000000,0.000000,0.500000,0.500000,0.000000,0.500000,0.0,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,0.500000,0.000000,0.500000,0.500000,0.0,0.0,0.000000,0.500000,0.00,0.000000,0.500000,0.0,0.500000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asian Electronics Ltd.,1252.3,251.5,410.4,8.31,3479.4,-69.7,187.2,1.13,NaN,NaN,1588.5,320.8,NaN,NaN,NaN,NaN,NaN,-301.6,0.6,156.1,99.7,64.1,153.41,8.942472e+06,4543.67,5.00,3.31,0.78,-179.4,NaN,-130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22793.0,Public Ltd.,1.020302e+10,1964.0,Other electronics,1.010140e+14,Manufacture of electronic components,2610,2.010200e+10,Private (Indian),Between 1951 and 1971,ASIANELEC,"D-11, Road No.28, Wagle Indl. Estate, Thane M...",100.0,43.13,43.13,0.0,56.86,6.81,50.06,1.371865e+09,NaN,1,0.117951,0.072283,8.154615,1.371865e+09,1.762422,0.566689,1.305877,1.305877,0.266875,0.266875,-394279.647770,0.092200,0.456544,0.000172,-8.665441,8.421490,42.0,3.737670,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2142,214,ASIANELEC,2007-03-31,4,2007,1.386294,0,0.000000,0,76.25,0,0,4,0,0.000000,4,0,0,0,4,0,4,0.0,1,0,0,0,0,0,0,0,4,0,0.000000,0,0,-4.063014,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0,0,0,3,0.750000,0,0.000000,0,0.0,1,0.250000,0,0.000000,0,0.0,2,0.500000,0,0.0,0,0.0,1,0.250000,0,0.0,0,0.0,2,0.500000,0,0.000000,0,0.0,1,0.250000,0,0.0,0,0.0,2,0.500000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0,4,0,0,0,1,0,0.0,0.0,2,0,"{information technology, research & developmen...",19,0,0.0,[],0,0.000000,0,0.000000,0,0.0,0,0.0,[],[],[],[],"[P00002475, P00000310, P00013015, P00003700]",[],[],[],[],[],NaN,0.250000,0.500000,0.250000,0.500000,0.250000,0.000000,0.500000,1.000000,1.000000,0.750000,0.750000,1.000000,0.500000,0.500000,0.250000,0.500000,0.000000,0.500000,0.500000,0.500000,0.250000,0.0,0.000000,0.0,0.250000,0.750000,1.000000,0.500000,0.250000,0.000000,0.500000,0.500000,0.250000,0.500000,0.0,0.500000,0.250000,0.500000,0.500000,0.250000,0.500000,0.000000,0.500000,0.000000,0.500000,0.250000,0.0,0.0,0.250000,0.500000,0.00,0.000000,0.500000,0.0,0.250000,0.250000,0.0,0.500000,0.500000,0.000000,0.000000,0.250000,0.250000,0.500000,0.000000,0.250000,0.250000,0.250000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,Asian Electronics Ltd.,3651.6,666.3,1077.0,13.72,6207.5,650.4,739.2,0.47,NaN,NaN,1650.2,625.2,NaN,NaN,NaN,NaN,NaN,-1388.3,1.4,NaN,74.7,64.2,238.02,1.391747e+07,6453.53,-1.83,1.95,0.84,-348.3,0.1,-378.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22793.0,Public Ltd.,1.020302e+10,1964.0,Other electronics,1.010140e+14,Manufacture of electronic components,2610,2.010200e+10,Private (Indian),Between 1951 and 1971,ASIANELEC,"D-11, Road No.28, Wagle Indl. Estate, Thane M...",100.0,33.67,33.67,NaN,66.33,25.22,41.11,3.312637e+09,NaN,1,0.173500,0.107338,8.733514,3.312637e+09,1.305474,0.266566,1.039634,1.039634,0.038869,0.038869,-533648.654758,0.100717,0.265840,0.000226,-8.397041,8.772383,43.0,3.761200,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2143,214,ASIANELEC,2008-03-31,6,2008,1.791759,0,0.000000,0,75.666667,1,1,5,0,0.000000,6,0,1,0,5,0,5,0.0,1,0,0,0,0,0,0,0,6,0,0.000000,3,1,-3.722831,0.000000,0.000000,0.000000,0.166667,0.833333,0.166667,0.833333,0,0,0,4,0.666667,0,0.000000,0,0.0,1,0.166667,0,0.000000,0,0.0,2,0.333333,0,0.0,0,0.0,1,0.166667,0,0.0,0,0.0,3,0.500000,0,0.000000,0,0.0,2,0.333333,0,0.0,0,0.0,4,0.666667,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,4,0,1,0,1,0,0.0,0.0,2,0,"{information technology, research & developmen...",21,0,0.0,[],3,0.500000,3,0.500000,0,0.0,0,0.0,[],[P00026404],[P00026404],[P00026404],"[P00002475, P00016306, P00000310, P00026404, P...",[],[],[],[],[],NaN,0.166667,0.666667,0.333333,0.500000,0.166667,0.000000,0.500000,1.000000,1.000000,0.666667,0.666667,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.500000,0.666667,0.500000,0.333333,0.0,0.000000,0.0,0.166667,0.666667,1.000000,0.500000,0.333333,0.166667,0.500000,0.500000,0.500000,0.500000,0.0,0.500000,0.333333,0.500000,0.500000,0.333333,0.500000,0.000000,0.333333,0.000000,0.500000,0.166667,0.0,0.0,0.166667,0.500000,0.00,0.000000,0.500000,0.0,0.166667,0.333333,0.0,0.500000,0.500000,0.166667,0.000000,0.166667,0.333333,0.500000,0.166667,0.333333,0.500000,0.333333,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,Asian Electronics Ltd.,2328.8,-1541.1,780.6,-24.03,7199.5,598.6,353.5,0.98,NaN,NaN,2080.2,659.5,NaN,NaN,NaN,NaN,51.9,483.9,7.1,NaN,71.2,0.0,71.17,2.988494e+07,5948.60,-2.95,2.80,0.75,-271.3,250.1,-115.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22793.0,Public Ltd.,1.020302e+10,1964.0,Other electronics,1.010140e+14,Manufacture of electronic components,2610,2.010200e+10,Private (Indian),Between 1951 and 1971,ASIANELEC,"D-11, Road No.28, Wagle Indl. Estate, Thane M...",100.0,33.49,33.49,NaN,66.51,26.66,39.85,2.126911e+09,NaN,1,0.108424,-0.214057,8.881767,2.126911e+09,1.115189,0.109023,0.826252,0.826252,-0.190856,-0.190856,-295423.059432,0.091604,0.288937,0.000986,-6.921672,8.690911,44.0,3.784190,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2144,214,ASIANELEC,2009-03-31,5,2009,1.609438,0,0.000000,0,70.75,2,1,3,0,0.000000,5,0,2,0,3,0,2,0.0,1,0,0,0,0,0,0,0,5,0,0.000000,4,1,-3.810959,0.000000,0.000000,0.000000,0.400000,0.600000,0.400000,0.600000,0,0,0,4,0.800000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.0,1,0.200000,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.400000,0,0.000000,0,0.0,1,0.200000,0,0.0,0,0.0,3,0.600000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0,3,0,1,0,1,0,3.0,0.0,2,0,"{information technology, corporate social resp...",18,0,0.0,[],4,0.800000,4,0.800000,0,0.0,0,0.0,"[P00117867, P00110508]","[P00117867, P00110508]","[P00117867, P00110508]","[P00117867, P00110508]","[P00002475, P00117867, P00016306, P00003700, P...",[],[],[],[],[],NaN,0.000000,0.600000,0.200000,0.400000,0.000000,0.000000,0.200000,0.600000,0.400000,0.400000,0.400000,0.600000,0.400000,0.400000,0.400000,0.400000,0.000000,0.400000,0.400000,0.600000,0.200000,0.0,0.000000,0.0,0.200000,0.400000,0.400000,0.400000,0.200000,0.000000,0.400000,0.400000,0.400000,0.400000,0.0,0.400000,0.200000,0.600000,0.400000,0.200000,0.400000,0.000000,0.200000,0.000000,0.400000,0.000000,0.0,0.0,0.200000,0.400000,0.00,0.000000,0.400000,0.0,0.200000,0.200000,0.0,0.400000,0.400000,0.000000,0.000000,0.200000,0.200000,0.400000,0.000000,0.200000,0.400000,0.200000,3.0,0.000000,3.0,0.500000,0.0,0.0,0.000000,Asian Electronics Ltd.,2194.4,50.3,484.6,-0.26,8123.5,261.3,13.6,1.10,NaN,NaN,2388.5,1243.8,NaN,NaN,NaN,NaN,412.1,-254.2,2.4,NaN,NaN,NaN,72.93,2.988494e+07,594.71,2.58,0.27,0.20,208.6,177.8,-99.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22793.0,Public Ltd.,1.020302e+10,1964.0,Other electronics,1.010140e+14,Manufacture of electronic components,2610,2.010200e+10,Private (Indian),Between 1951 and 1971,ASIANELEC,"D-11, Road No.28, Wagle Indl. Estate, Thane M...",100.0,32.15,32.15,NaN,67.85,5.22,62.63,2.179509e+09,NaN,1,0.059654,0.006192,9.002516,2.179509e+09,0.367232,-1.001761,0.073209,0.073209,-2.614442,-2.614442,-268295.715850,0.153111,0.294024,0.000295,-8.127048,6.388074,45.0,3.806662,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2145,214,ASIANELEC,2010-03-31,3,2010,1.098612,0,0.000000,0,74.0,1,1,2,0,0.000000,3,0,1,0,2,0,1,0.0,1,0,0,0,0,0,0,0,3,0,0.000000,1,1,-0.512329,0.000000,0.000000,0.000000,0.333333,0.666667,0.333333,0.666667,0,0,0,0,0.000000,0,0.000000,0,0.0,0,0.000000,0,0.000000,0,0.0,1,0.333333,0,0.0,0,0.0,1,0.333333,0,0.0,0,0.0,1,0.333333,0,0.000000,0,0.0,1,0.333333,0,0.0,0,0.0,1,0.333333,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,0,2,0,1,0,1,0,4.0,0.0,2,0,"{information technology, leadership/management...",9,0,0.0,[],1,0.333333,1,0.333333,0,0.0,0,0.0,[P00110508],[P00110508],[P00110508],[P00110508],"[P00006999, P00023334, P00110508]",[],[],[],[],[],NaN,0.000000,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.666667,0.666667,0.333333,0.333333,0.666667,0.666667,0.333333,0.666667,0.333333,0.333333,0.333333,0.333333,0.666667,0.000000,0.0,0.000000,0.0,0.000000,0.666667,0.666667,0.333333,0.333333,0.333333,0.333333,0.333333,0.666667,0.333333,0.0,0.333333,0.000000,0.333333,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.333333,0.000000,0.0,0.0,0.000000,0.333333,0.00,0.000000,0.333333,0.0,0.000000,0.000000,0.0,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.333333,0.333333,0.000000,0.333333,4.0,0.000000,4.0,0.800000,0.0,0.0,0.000000,Asian Electronics Ltd.,2299.7,29.4,422.7,0.48,7060.4,364.7,20.4,0.58,NaN,NaN,1336.6,1341.4,NaN,NaN,NaN,NaN,0.8,1949.2,0.3,56.6,NaN,NaN,74.42,3.071828e+07,877.01,2.33,0.38,0.41,-597.2,5.4,-8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22793.0,Public Ltd.,1.020302e+10,1964.0,Other electronics,1.010140e+14,Manufacture of electronic components,2610,2.010200e+10,Private (Indian),Between 1951 and 1971,ASIANELEC,"D-11, Road No.28, Wagle Indl. Estate, Thane M...",100.0,NaN,NaN,NaN,100.00,0.33,99.67,2.286054e+09,NaN,1,0.059869,0.004164,8.862257,2.286054e+09,0.313525,-1.159877,0.124215,0.124215,-2.085739,-2.085739,-323784.238419,0.189989,0.189309,0.000042,-10.066230,6.776518,46.0,3.828641,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [106]:
firm.to_pickle(rf"{output_folder_path}\Main_Firm_No Loc_Fin_Calc.pkl")
firm.to_csv(rf"{output_folder_path}\Main_Firm_No Loc_Fin_Calc v210625.csv")