# Director Skill Sets Table 7 - Deaths only

In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import mpl_toolkits as mplot3d
%matplotlib inline
import seaborn as sns

import scipy.stats as stats
from scipy.stats.mstats import winsorize
from scipy.spatial.distance import cdist


from sklearn.neighbors import NearestNeighbors

import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
import_folder_path = rf"../../../../[IN USE] Rookie Directors/[4] FF3 CAR/car_output4"
output_folder_path = "analysis_outputs"
# pca_input_folder_path = rf"..\..\..\[IN USE] Rookie Directors\[1.5] Director Skills PCA\director_skills_pca"
supporting_folder_path = "supporting_datafiles"

In [3]:
dirFirm = pd.read_pickle(rf"{import_folder_path}/Director Level_FF3_CAR.pkl")
dirFirm = dirFirm.loc[ dirFirm["date_source"] == "Date of Demise"].reset_index(drop = True)

# pca = pd.read_pickle(rf"{pca_input_folder_path}\Main_Director_COMPLETE_PCA.pkl")

# pca_col = [
#     "Person Code", "AsOnDate", "Symbol",
#     "SkillsetIndex", "SkillsetGeneralistDummy",
#     "PC1_FactorScore", "PC1_FactorScore_Standardised"
# ]

# pca2 = pca[pca_col].copy()
# dirFirm = dirFirm0.merge(pca2, on = ["Person Code", "AsOnDate", "Symbol"], how = "left")

In [4]:
dirFirm

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210
0,23,20MICRONS,20 MICRONS LTD.,2010-03-31,2010,INE144J01027,P00027669,LATE MR.,VISHNU,RAJARAM,VARSHNEY,1947-04-11,M,NaN,NaN,NaN,<NA>,<NA>,POST GRADUATE: M.E.-ELECTRICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.VISHNU VARSHNEY HOLDS BACHELOR'S DEGREE OF ...,NaT,2009-07-29,U,2000-04-10,2009-07-29,2009-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,120.0,0.0,0.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3032.0,0.0,0.0,3032.0,3397.0,0.0,0.0,3397.0,3395,"((20MICRONS, U),)","{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,78,0.000000,9.306849,9.301370,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,{},POST GRADUATE: M.E.-ELECTRICAL,0,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{20MICRONS},0,1,1,0,1,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Date of Demise,2009-07-29,11.0,12.60,-0.017161,0.008824,-1.187185,-1.178360,0.280266,-0.219265,-0.017647,0.005552,0.012183,0.009481,0.149680,0.127689,2.883363e-04,-0.040906,0.031116,0.005558,-0.005077,-0.018884,0.007822,0.012183,0.011318,0.181844,0.165033,1.844490e-06,-0.036358,0.032253,-0.004294,-0.021468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,126,20MICRONS,20 MICRONS LTD.,2022-03-31,2022,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, EXECUTIVE DIRECTOR, PROMOTER-DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,2021-06-09,N,1988-03-29,2021-06-09,2021-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,70.0,8768.0,0.0,2992.0,11760.0,8768.0,0.0,3357.0,12125.0,8768.0,0.0,2992.0,11760.0,8768.0,0.0,3357.0,12125.0,12117,"((20MICRONS, U), (20MICRONS, N))","{(20MICRONS, N)}","{(20MICRONS, N)}","((20MICRONS, U),)","((20MICRONS, U),)",1,0,0,1,1,0,0,1,0,0,1,1,0,0,1,1,N,0,1,0,1,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,1,0,79,0.000000,33.219178,33.197260,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,2.010104e+10,11.0,20 Microns Ltd.,0,0,"{strategy, international business, finance, in...",POST GRADUATE: M.SC.-CHEMISTRY,0,0,{08},{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'operations', 'legal/...",1,1,{20MICRONS},11,1,1,1,1,0,1,1,False,False,False,False,False,True,True,True,False,True,False,True,True,True,False,True,True,0,False,False,False,False,True,True,True,False,False,False,False,False,False,False,True,False,True,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,NaN,NaN,Date of Demise,2021-06-09,11.0,62.65,-0.050758,0.009187,-0.781018,-0.771830,-0.013827,0.574967,-0.012722,0.012962,0.005616,0.002648,0.226438,0.206432,1.442831e-06,0.019264,0.032283,-0.045076,-0.067948,-0.013204,0.012573,0.005820,0.003541,0.246655,0.231175,5.148205e-09,0.019494,0.031831,-0.046729,-0.070715,-0.013624,0.012502,0.006303,0.004055,0.252174,0.239426,4.255265e-11,0.019202,0.030779,-0.048621,-0.074279,-0.014345,0.012616,0.006013,0.004464,0.248136,0.237186,1.014764e-12,0.021426,0.032394,-0.047478,-0.073063,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,424,3PLAND,3P LAND HOLDINGS LTD.,2010-03-31,2010,INE105C01023,P00022755,LATE MR.,SHAHRUKH,MINOCHER,CONTRACTOR,1931-03-19,M,NaN,NaN,NaN,<NA>,<NA>,"GRADUATE: GRADUATE,A.T.A.,INDIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR.CONTRACTOR HAS BEEN ASSOCIATED WITH THE COM...,NaT,2009-06-14,U,1990-12-31,2009-06-14,2009-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,75.0,0.0,0.0,6375.0,0.0,0.0,6375.0,6740.0,0.0,0.0,6740.0,6375.0,0.0,0.0,6375.0,6740.0,0.0,0.0,6740.0,6735,"((3PLAND, U),)","{(3PLAND, U)}","{(3PLAND, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,94,0.000000,18.465753,18.452055,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,3PLAND,64191,Public Ltd.,M P Jatia Group,2.010104e+10,183396.0,3P Land Holdings Ltd.,0,1,{},"GRADUATE: GRADUATE,A.T.A.,INDIA",0,0,{64191},{64191},{64191},{64191},{64},{64},1,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{3PLAND},0,1,1,0,1,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Date of Demise,2009-06-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,459,3PLAND,3P LAND HOLDINGS LTD.,2015-03-31,2015,INE105C01023,P00065870,LATE MS.,POONAM,NaN,JATIA,NaT,F,NaN,NaN,NO,PROMOTER-DIRECTOR,NO,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaT,2014-12-23,N,2014-09-15,2014-12-23,NaT,NaT,1,0.0,1.0,1.0,1,0.0,0.0,0.0,0.0,0.0,99.0,0.0,0.0,0.0,0.0,0.0,0.0,99.0,99.0,0.0,0.0,0.0,0.0,0.0,0.0,99.0,99.0,267,(),"{(3PLAND, N)}","{(3PLAND, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1,<NA>,0.000000,0.271233,0.731507,1,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,3PLAND,64191,Public Ltd.,M P Jatia Group,2.010104e+10,183396.0,3P Land Holdings Ltd.,0,1,{},,0,0,{},{64191},{64191},{64191},{},{64},0,0,0,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.0,4.0,0.333333,Date of Demise,2014-12-23,183396.0,10.40,0.000000,0.021966,-0.426120,-0.404154,-0.152997,-0.691279,-0.034120,0.006030,0.009853,-0.012442,0.044787,0.020083,1.486581e-01,-0.022056,-0.081209,-0.214709,-0.318633,-0.032356,0.003969,0.007143,-0.008552,0.027074,0.007082,2.592112e-01,-0.023174,-0.084097,-0.218122,-0.316671,-0.032625,0.004530,0.005529,-0.007328,0.019062,0.002342,3.343746e-01,-0.019863,-0.082707,-0.219750,-0.315539,-0.032428,0.003937,0.003346,-0.005669,0.010256,-0.004158,5.461230e-01,-0.017709,-0.082096,-0.219482,-0.313737,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,1233,AARTIDRUGS,AARTI DRUGS LTD.,2022-03-31,2022,INE767A01016,P00005474,LATE MR.,RAMDAS,MANEKLAL,GANDHI,1933-03-14,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,FINANCE,HEALTHCARE,LEADER...",SOLICITOR,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,HE IS L.L.M. FROM MUMBAI UNIVERSITY. HE IS AN ...,NaT,2021-07-16,Y,2005-12-31,2021-07-16,2021-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,107.0,0.0,2282.0,3029.0,0.0,5311.0,2282.0,3394.0,0.0,5676.0,2282.0,3029.0,0.0,5311.0,2282.0,3394.0,0.0,5676.0,13278,"((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...",5,2,0,7,5,2,0,7,0,3,0,3,0,3,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,92,9.298630,15.550685,36.378082,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,AARTIDRUGS,2100,Public Ltd.,Alchemie Group,2.010103e+10,3990.0,Aarti Drugs Ltd.,0,0,"{strategy, finance, legal/compliance, corporat...","POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",1,0,"{2100, 20299, 20, 46691, 21002}","{20299, 46691, 2100}","{20299, 46691, 2100}","{2100, 20299, 20, 46691, 21002}","{20, 46, 21}","{20, 46, 21}",0,0,1,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'strategy', 'legal/co...",0,1,"{AARTIDRUGS, UNICHEMLAB, PIDILITIND, AARTIIND,...",6,5,5,0,1,0,1,1,False,False,False,False,False,False,True,True,False,False,True,True,False,False,False,True,False,1,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,6.0,1.0,0.833333,Date of Demise,2021-07-16,3990.0,730.65,0.018896,0.009245,0.316611,0.325856,0.003376,0.564257,-0.014844,0.008144,0.002629,0.002879,0.132478,0.110042,8.723116e-04,0.004606,-0.025435,-0.055652,-0.153805,-0.015232,0.009891,0.004385,0.003099,0.144461,0.126881,4.326799e-05,0.003140,-0.025749,-0.058699,-0.160480,-0.014632,0.010992,0.004299,0.002307,0.138304,0.123616,8.367564e-06,0.001408,-0.028103,-0.061461,-0.161486,-0.012238,0.012575,0.006608,0.003290,0.124710,0.111963,4.613534e-06,-0.009226,-0.036602,-0.073541,-0.179789,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [5]:
# dirFirm data wrangling if any:
dirFirm["Year of Study"] = [x.year for x in dirFirm["Date of Study"]]

dirFirm = dirFirm.drop_duplicates(subset = ["Person Code", "Company", "Date of Study"]).reset_index(drop = True)

dirFirm["ln_dirage"] = np.log(dirFirm["Age"] + 1).astype("float")
dirFirm["ln_directorships"] = np.log(dirFirm["CompCountOtherPastTotalAB"] + 1).astype("float")

In [6]:
dirFirm.describe()

,index,AsOnDate,AsOnYear,Date of Birth,Tenure Valid till,Date of Demise,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,Ownership group code,Prowess company code,govtdummy,findummy,IsMBA,IsPhD,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,HasTechSkill,HasFinanceSkill,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,Manufacturing_NIC_not used,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships
count,1223.000000,1223,1223.000000,1094,26,1223,1223,1223,1162,1,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.0,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1094.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.000000,1223.000000,1223.0,1223.000000,1223.0,1223.000000,1.213000e+03,1213.000000,1223.00000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.000000,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.000000,1223.0,1223.000000,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.00000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.00000,1223.000000,1223.000000,1223.0,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,629.000000,629.000000,629.000000,1223,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,8.040000e+02,784.000000,784.000000,784.000000,784.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,8.030000e+02,783.000000,783.000000,783.000000,783.000000,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000,7.990000e+02,779.000000,779.000000,779.000000,779.000000,794.000000,794.000000,794.000000,794.000000,794.000000,794.000000,7.940000e+02,774.000000,774.000000,774.000000,774.000000,1223.000000,32.000000,1223.000000,32.000000,1223.000000,32.000000,1223.000000,32.000000,1223.000000,1094.000000,1223.000000
mean,126805.076043,2016-07-07 18:55:02.698282752,2016.271464,1941-03-18 12:40:48.263254144,2026-03-16 08:18:27.692307712,2016-01-08 06:29:43.810302720,2000-09-15 08:40:25.511038592,2016-01-08 06:29:43.810302720,2015-08-05 08:25:36.660929536,2015-03-31 00:00:00,1.0,0.002453,0.052330,1.004088,0.021259,0.0,0.0,0.0,102.787408,118.158626,75.986917,3886.174162,693.854456,665.143908,5245.172527,3978.113655,853.821750,760.973835,5592.909240,3903.437449,696.575634,665.587081,5265.600164,3995.376942,857.172527,761.465249,5614.014718,6607.614064,1.401472,0.234669,0.057236,1.693377,1.401472,0.234669,0.057236,1.693377,0.538839,0.945217,0.390842,1.874898,0.538839,0.945217,0.390842,1.874898,0.469338,0.530662,0.110384,0.889616,0.058054,0.156991,0.022077,0.029436,0.076043,0.171709,0.103843,0.136549,0.139820,0.039248,0.040065,0.092396,0.027800,0.058054,0.052330,0.411284,0.478332,0.031889,83.840951,2.348418,15.380862,18.103052,0.238757,0.121832,0.0,0.0,0.032706,0.017989,0.072772,0.043336,0.110384,0.058054,0.053148,0.0,0.520850,0.208504,1.0,0.053148,0.0,0.469338,1.986056e+10,166599.180544,0.02453,0.103843,0.128373,0.053966,0.184791,0.062142,0.950940,0.004906,0.006541,0.001635,0.023712,0.023712,0.0,0.023712,0.0,0.065413,0.321341,2.278823,2.277187,2.179886,0.054783,0.831562,0.053966,0.581357,0.950940,0.619787,0.029436,0.023712,0.151267,0.0,0.029436,0.0,0.022895,0.0,0.349959,0.072772,0.889616,0.205233,0.834015,0.524121,0.226492,0.174980,0.237122,0.061325,0.238757,0.050695,0.234669,0.187244,0.163532,0.125102,0.295176,0.278005,0.118561,0.118561,0.032706,0.0,0.173344,0.159444,0.404742,0.160262,0.649223,0.659853,0.147997,0.047424,0.045789,0.007359,0.176615,0.003271,0.080131,0.051513,0.11202,0.044971,0.125102,0.006541,0.106296,0.013083,0.143908,0.02453,0.086672,0.026165,0.0,0.023712,0.076860,0.017171,0.025348,0.187244,0.001635,0.015536,0.058872,0.072772,0.056419,0.017989,5.972973,2.052464,0.651074,2016-01-08 06:29:43.810302720,163350.498756,275.736443,0.000496,0.025524,0.007010,0.032534,0.034020,0.076947,-0.023387,0.010207,0.005683,0.002041,0.176448,0.155149,7.639269e-02,-0.001463,-0.044992,-0.060274,-0.168396,-0.023610,0.010262,0.006207,0.002294,0.173544,0.156562,6.078763e-02,-0.002440,-0.047939,-0.063012,-0.168280,-0.023697,0.010404,0.006124,0.002512,0.171285,0.157159,5.095774e-02,-0.003139,-0.049303,-0.064364,-0.168719,-0.023766,0.010333,0.006156,0.002667,0.169670,0.157578,4.341338e-02,-0.002790,-0.049232,-0.065206,-0.168809,0.026165,118.156250,0.026165,148.156250,0.026165,178.156250,0.026165,207.218750,2015.527392,4.430834,0.674110
min,23.000000,2006-03-31 00:00:00,2006.000000,1911-11-11 00:00:00,2025-03-27 00:00:00,2006-01-02 00:00:00,1940-08-23 00:00:00,2006-01-02 00:00:00,2006-03-31 00:00:00,2015-03-31 00:00:00,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.000000,-158.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-158.000000,0.000000,-158.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.0,0.000000,0.008219,0.115068,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,0.000000,1.010100e+10,11.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2006-01-02 00:00:00,11.000000,0.100000,-0.200000,0.007905,-6.381449,-6.311735,-4.176493,-3.583618,-0.047053,-0.010444,-1.189216,-0.220981,0.002542,-0.023254,2.770209e-37,-0.428166,-0.519040,-0.655598,-3.463362,-0.043825,-0.007550,-0.787783,-0.085610,0.000646,-0.019888,3.459331e-45,-0.398771,-0.510181,-0.644050,-3.919775,-0.042015,-0.007658,-0.669731,-0.070299,0.001132,-0.015894,5.453677e-52,-0.421028,-0.509802,-0.645290,-4.298828,-0.040535,-0.008242,-0.623359,-0.059885,0.000134,-0.014427,9.213257e-61,-0.412520,-0.511551,-0.647247,-3.753564,0.000000,61.000000,0.000000,91.000000,0.000000,121.000000,0.000000,151.000000,2006.000000,3.610918,0.000000
25%,65035.500000,2012-03-31 00:00:00,2012.000000,1933-03-02 18:00:00,2025-08-13 00:00:00,2012-02-19 00:00:00,1992-02-28 12:00:00,2012-02-19 00:00:00,2012-03-31 00:00:00,2015-03-31 00:00:00,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1578.000000,0.000000,0.000000,0.000000,1934.500000,0.000000,0.000000,0.000000,1605.000000,0.000000,0.000000,0.000000,1957.500000,2653.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.0,0.000000,5.363014,7.269863,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,0.000000,2.010102e+10,82760.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.400000,2012-02-19 00:00:00,82982.000000,22.030000,-0.015966,0.014990,-0.513780,-0.498866,-0.382941,-0.430896,-0.029842,0.006261,0.002953,-0.001638,0.069771,0.045713,1.724925e-07,-0.035328,-0.088013,-0.150997,-0.261414,-0.029787,0.006535,0.003243,-0.001160,0.068800,0.049665,3.067249e-09,-0.036014,-0.089746,-0.150694,-0.261612,-0.029874,0.006844,0.003100,-0.000906,0.072033,0.056215,4.902637e-11,-0.036138,-0.089134,-0.150315,-0.259166,-0.029771,0.007005,0.003028,-0.000430,0.072049,0.058536,7.891205e-13,-0.035338,-0.089194,-0.148991,-0.258384,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2012.000000,4.343805,0.000000
50%,126163.000000,2016-03-31 00:00:00,2016.000000,1939-12-20 00:00:00,2025-12-31 12:00:00,2016-01-31 00:00:00,2004-01-30 00:00:00,2016-01-31 00:00:00,2015-03-31 00:00:00,2015-03-31 00:00:00,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,2171.000000,0.000000,0.000000,3939.000000,2252.000000,0.000000,0.000000,4265.000000,2197.000000,0.000000,0.000000,3979.000000,2282.000000,0.000000,0.000000,4302.000000,5590.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,85.0,0.000000,11.786301,15.315068,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,1.0,0.000000,0.0,0.000000,2.010103e+10,141201.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.714286,2016-01-31 00:00:00,138282.000000,66.650000,0.000000,0.019319,0.097026,0.113686,0.061231,0.089029,-0.025207,0.010276,0.007193,0.002395,0.149583,0.127589,2.901818e-04,-0.004722,-0.053172,-0.102376,-0.196013,-0.025458,0.010245,0.007344,0.002359,0.145367,0.127806,4.016321e-05,-0.005135,-0.052548,-0.102540,-0.199615,-0.025322,0.010365,0.007186,0.002577,0.145464,0.130898,4.110193e-06,-0.004280,-0.054130,-0.103277,-0.197063,-0.025322,0.010259,0.007048,0.002500,0.141010,0.128500,7.057264e-07,-0.004395,-0.054185,-0.104730,-0.199543,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2016.000000,4.454347,0.693147
75%,187787.500000,2021-03-31 00:00:00,2021.000000,1948-10-14 00:00:00,2026-09-27 12:00:00,2020-08-08 00:00:00,2009-09-27 00:00:00,2020-08-08 00:00:00,2020-03-31 00:00:00,2015-03-31 00:00:00,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,7.000000,170.000000,32.000000,6431.000000,962.000000,15.000000,7906.000000,6610.000000,1293.000000,365.000000,8271.000000,6487.500000,966.000000,15.000000,7955.500000,6617.500000,1302.500000,365.000000,8320.500000,9534.000000,2.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,92.0,3.568493,22.795890,26.120548,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,1.0,0.000000,0.0,1.000000,2.010104e+10,241535.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.000000,2.000000,3.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,3.000000,1.000000,2020-08-08 00:00:00,237919.000000,204.150000,0.012390,0.026974,0.542179,0.565457,0.526194,0.589564,-0.017622,0.013777,0.011219,0.006279,0.254967,0.235699,3.799736e-02,0.031610,-0.016003,-0.054830,-0.130650,-0.018098,0.013801,0.011221,0.006196,0.252094,0.236726,1.517098e-02,0.030955,-0.015762,-0.053970,-0.127855,-0.018264,0.013540,0.010961,0.006180,0.250967,0.238199,4.235132e-03,0.030956,-0.016255,-0.055247,-0.127471,-0.018440,0.013375,0.011124,0.006092,0.250018,0.239096,1.476035e-03,0.031088,-0.017053,-0.054598,-0.129483,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2020.000000,4.532599,1.098612

# PSM

## Verifying and removing those rows with no control data points

In [7]:
# Sample constraints ---> govtdummy==0 & findummy==0 & asonyear>2012
dirFirm.columns.to_list()

['index',
 'Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Date of Demise',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'TenureInYearsTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsZeroYear',
 'IsZeroYearIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Ownership group code',
 'Prowess company code',
 'CompanyName',
 'govtdummy',
 'findummy',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllPastDirectNIC_2Digit',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'SkillsInBriefProfile',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills_gai',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'Academic',
 'Outside Board',
 'Company Business',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Manufacturing_NIC_not used',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'skill_committee_sustainability',
 'combined_entrepreneurial',
 'skill_committee_entrepreneurial',
 'combined_compensation',
 'skill_committee_compensation',
 'combined_conglomerate_experience',
 'skill_committee_conglomerate_experience',
 'combined_hr',
 'skill_committee_hr',
 'combined_technology',
 'skill_committee_technology',
 'combined_finance_accounting',
 'skill_committee_finance_accounting',
 'combined_governance',
 'skill_committee_governance',
 'combined_government_policy',
 'skill_committee_government_policy',
 'combined_international',
 'skill_committee_international',
 'combined_leadership',
 'skill_committee_leadership',
 'combined_legal',
 'skill_committee_legal',
 'combined_marketing',
 'skill_committee_marketing',
 'combined_risk_management',
 'skill_committee_risk_management',
 'combined_scientific',
 'skill_committee_scientific',
 'combined_strategic_planning',
 'skill_committee_strategic_planning',
 'combined_manufacturing_supply_chain',
 'skill_committee_manufacturing_supply_chain',
 'skill_committee_leadership_outside_board',
 'combined_leadership_outside_board',
 'board_corporate governance',
 'board_international business',
 'board_industrials',
 'board_utilities',
 'board_finance',
 'board_telecommunication',
 'board_accounts/audit/taxation',
 'board_public policy',
 'board_risk management',
 'board_research & development',
 'board_legal/compliance',
 'board_services',
 'board_marketing',
 'board_healthcare',
 'board_strategy',
 'board_commodities',
 'board_operations',
 'board_diversity',
 'board_diversified',
 'board_corporate social responsibility',
 'board_human resources',
 'board_fast moving consumer goods',
 'board_economics',
 'board_leadership/management',
 'board_energy',
 'board_financial services',
 'board_information technology',
 'board_personal values',
 'board_consumer discretionary',
 'board_supply chain management',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'date_source',
 'Date of Study',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_SMB',
 'OLS120_HML',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_SMB',
 'OLS150_HML',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_SMB',
 'OLS180_HML',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11',
 'OLS210_intercept',
 'OLS210_RMRF',
 'OLS210_SMB',
 'OLS210_HML',
 'OLS210_r_squared',
 'OLS210_adjusted_r_squared',
 'OLS210_f_p_value',
 '210CAR3',
 '210CAR5',
 '210CAR7',
 '210CAR11',
 'insufficient_data_dummy_120',
 'na_trading_days_120',
 'insufficient_data_dummy_150',
 'na_trading_days_150',
 'insufficient_data_dummy_180',
 'na_trading_days_180',
 'insufficient_data_dummy_210',
 'na_trading_days_210',
 'Year of Study',
 'ln_dirage',
 'ln_directorships']

In [8]:
dirFirm["IsDualityChairmanMD"] = dirFirm["IsDualityChairmanMD"].astype(int)


# dirFirm["NIC_2digit"] = dirFirm["NIC code"].dropna().apply(lambda x: x[0:2])
# dirFirm["NIC_2digit"] = dirFirm["NIC_2digit"]

psmSample = dirFirm.loc[ (dirFirm["Year of Study"] >= 2013)].copy()
# \
# & (dirFirm["govtdummy"] == 0) & (dirFirm["findummy"] == 0) ].copy()
#.dropna(subset = controlVars).dropna(subset = dependentVar).copy()

psmSample["DummySum"] = psmSample["IsRookie"] + psmSample["IsNonRookie"]
psmSample["DummySumIndep"] = psmSample["IsRookieIndep"] + psmSample["IsNonRookieIndep"]

psmSampleAll = psmSample.loc[ psmSample["DummySum"] == 1 ].reset_index(drop = True)
#psmSampleAll = psmSampleAll.loc[ ~psmSampleAll.duplicated(subset = ["AsOnDate", "Symbol", "Appointment Date"], keep = False)]

psmSampleIndep = psmSample.loc[ psmSample["DummySumIndep"] == 1 ].reset_index(drop = True)
#psmSampleIndep = psmSampleIndep.loc[ ~psmSampleIndep.duplicated(subset = ["AsOnDate", "Symbol", "Appointment Date"], keep = False)]

## CAR windsorization

In [9]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

from scipy.stats.mstats import winsorize

def winsorize_output(sample, variable, limits = [0, 0]):
    sample[f"nonwinsorised_{variable}"] = sample[variable]
    sample[f"winsorised_{variable}"] = winsorize(np.array(sample[f"nonwinsorised_{variable}"]), limits = limits, inclusive = [False, False])
    sample[[f"nonwinsorised_{variable}", f"winsorised_{variable}"]].describe()
    print(sample[[f"winsorised_{variable}", f"nonwinsorised_{variable}"]].describe())
    print("\n\nTop values and their count: ", (sample[f"nonwinsorised_{variable}"].value_counts().sort_index().tail(n=10)))
    print("\n\n")
    
    # Graphs
    fig, axes = plt.subplots(1, 2, figsize = (12, 6))
    sns.kdeplot(data = sample[f"nonwinsorised_{variable}"].replace([np.inf, -np.inf], np.nan), ax = axes[0])
    axes[0].set_title(f'Nonwinsorised {variable}')
    sns.kdeplot(data = sample[f"winsorised_{variable}"].replace([np.inf, -np.inf], np.nan), ax = axes[1])
    axes[1].set_title(f'Winsorized {variable}')
    plt.tight_layout()
    plt.show()

    sample[variable] = sample[f"winsorised_{variable}"]
    return sample[variable]

# for car in carCol:
#     psmSampleIndep[car] = winsorize_output(psmSampleIndep, car, [0.01, 0.01])

In [10]:
# dirFirm2 = dirFirm.copy()
# psmSampleIndep2 = psmSampleIndep.copy()

# listCol = [
#     "FirstYearPCodeList", "TwoYearPCodeList", "ThreeYearPCodeList", "PCodeList",
#     "FirstYearIndepPCodeList", "TwoYearIndepPCodeList", "ThreeYearIndepPCodeList", "IndepPCodeList",
#     "OtherFirstYearIndepPCode", "OtherTwoYearIndepPCode", "OtherThreeYearIndepPCode", "TotalIndepPCode",
#     "OtherFirstYearPCode", "OtherTwoYearPCode", "OtherThreeYearPCode", "TotalPCode",
#     "OtherFirstYearPCodeIndepExcl","OtherTwoYearPCodeIndepExcl", "OtherThreeYearPCodeIndepExcl", "TotalPCodeIndepExcl",
#     "OtherFirstYearPCodeExcl", "OtherTwoYearPCodeExcl", "OtherThreeYearPCodeExcl", "TotalPCodeExcl"
# ]

# dirFirm2 = dirFirm2.drop(listCol, axis = 1)
# psmSampleIndep2 = psmSampleIndep2.drop(listCol, axis = 1)


# dirFirm2.to_csv("Main_Firm_PSM Ready_no filter v040425.csv")
# psmSampleIndep2.to_csv("Main_Firm_PSM Ready_filter-Indep_gov_fin v040425.csv")


# # # psmSampleAll --> 2101 rows 
# # psmSampleIndep --> 1561 rows

## PSM --> RookieAppoints as Treatment, NonRookieAppoints as Control

In [11]:
def LogitReg(sample, endog_var, exog_var):
    
    # Logit Regression
    endog = sample[endog_var]
    exog = sample[exog_var]
    
    scaler = StandardScaler()
    exog_standardised = pd.DataFrame(scaler.fit_transform(exog), columns=exog.columns)

    exog_standardised = sm.add_constant(exog_standardised)
    
    log_reg = sm.Logit(endog, exog_standardised).fit()

    propensityScores = log_reg.predict(exog_standardised)
    
    return propensityScores

In [12]:
def MeanDiffTtest(sample, endog_var, exog_var, car, depVar, dirFirm):

    sample[car] = winsorize(sample[car], limits = [0.01, 0.01])
    if depVar != None:
        dirFirm = dirFirm.rename( {depVar:f"{depVar}_2"}, axis = 1)
    
        colsAdd = []
        for i in range(-1, 4):
            if i != 0:
                colsAdd.append(f"AsOnYear_T+{i}")
                colsAdd.append(f"{depVar}T+{i}")
                if i>0 :
                    colsAdd.append(depVar+f"(T+{i}) - (T-1)")
    
        newFrame= pd.DataFrame(columns = colsAdd, data = 0, index = sample.index, dtype = "float")
        sample = pd.concat([sample, newFrame], axis = 1)
        sample = sample.copy()
        
        for i in range(-1, 4):
            if i != 0:
                sample.loc[:, f"AsOnYear_T+{i}"] = sample["AsOnYear"] + i
    
        for i in range(-1, 4):
            if i != 0:
                sample.loc[:, f"{depVar}T+{i}"] = sample.merge(dirFirm[["Symbol", "AsOnYear", f"{depVar}_2"]].copy(), left_on = ["Symbol", f"AsOnYear_T+{i}"],
                                                              right_on = ["Symbol", "AsOnYear"], how = "left")[f"{depVar}_2"]
        
        for i in range(1, 4):
            if i != 0:
                sample.loc[:, depVar+f"(T+{i}) - (T-1)"] = sample[f"{depVar}T+{i}"] - sample[f"{depVar}T+-1"]
    
            
        sample = sample.copy()
    
    group1 = sample.loc[ sample[endog_var] == 1].copy()
    group2 = sample.loc[ sample[endog_var] == 0].copy()
    
    t_stat, p_value = stats.ttest_ind(group1[car], group2[car], equal_var=False)  # Welch’s t-test (default)

    print("\n")
    print(car, ":")
    print("\n")
    print("T Statistic:", t_stat, " P Value:",p_value)
    print("Treated Mean:", group1[car].mean(), " Control Mean:", group2[car].mean(), " Diff:", group1[car].mean() - group2[car].mean())
    print("Treated Median:", group1[car].median(), " Control Median:", group2[car].median(), " Diff:", group1[car].median() - group2[car].median())
    print("Treated N:", len(group1[car]), "; Control N:", len(group2[car]))
    print("[treated unique = ", len(group1.loc[ :, ["Person Code", "Symbol", "AsOnDate"]].drop_duplicates()), "]",\
          "[control unique = ", len(group2.loc[ :, ["Person Code", "Symbol", "AsOnDate"]].drop_duplicates()), "]"
         )
    print("\n")

    # -----------------------------------------------------------------------------------------------------------------
    
    if exog_var != None:
        print("━"*120)
        print(f'{"Matching Variable":<40} {"Treatment Firms":<20} {"Control Firms":<20} {"Test of Diff (p value)":<20}')
        print(f'{" ":<40} {"N = " + str(len(group1[car])):<20} {"N = " + str(len(group2[car])):<20}')
        print("-"*120)

        for var in exog_var:
            treatMean = group1[var].mean()
            controlMean = group2[var].mean()
            p_value = stats.ttest_ind(group1[var], group2[var], equal_var=False)[1]
            print(f'{var:<40} {treatMean:<20.4f} {controlMean:<20.4f} {p_value:<20.4f}')
    
        print("━"*120, "\n")
    
    # -----------------------------------------------------------------------------------------------------------------


    if depVar != None:
        print(depVar, " across years:\n")
        for i in range(1,4):
            sample = sample.dropna(subset = [depVar+f'(T+{i}) - (T-1)'])
    
        group1 = sample.loc[ sample[endog_var] == 1].copy()
        group2 = sample.loc[ sample[endog_var] == 0].copy()

        print("━"*150, "\n")
        print(f'{depVar:<40}{" ":<20}{"Treatment":<20}{"Control":<20}{"Difference":<20}{"Test of Diff":<20}{"Test of Diff"}')
        print(f'{" ":<120}{"(t stat)":<20}{"(p value)":<20}')
    
        print("─"*150, "\n")
    
        for i in range(1,4):
            t_stat2, p_value2 = stats.ttest_ind(group1[depVar+f'(T+{i}) - (T-1)'], group2[depVar+f'(T+{i}) - (T-1)'], equal_var=False)  # Welch’s t-test (default)
            
            treatedMean = group1[depVar+f'(T+{i}) - (T-1)'].mean()
            controlMean = group2[depVar+f'(T+{i}) - (T-1)'].mean()
            diffMean = treatedMean - controlMean
    
            treatedMedian = group1[depVar+f'(T+{i}) - (T-1)'].median()
            controlMedian = group2[depVar+f'(T+{i}) - (T-1)'].median()
            diffMedian = treatedMedian - controlMedian
    
            print(f'{"Year_T+" + str(i) +" - Year_T-1":<40}{"<MEAN>":<20}{treatedMean:<20.4f}{controlMean:<20.4f}{diffMean:<20.4f}{t_stat2:<20.4f}{p_value2:<20.10f}')
    
            label1 = "Treated N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
            label2 = "Control N: " + str(len(group2[depVar+f'(T+{i}) - (T-1)']))
            
            print(f'{label1 + " "*5 + label2:<40}{"<MEDIAN>":<20}{treatedMedian:<20.4f}{controlMedian:<20.4f}{diffMedian:<20.4f}')
            
            print("-"*150, "\n")
            
        print("━"*150, "\n")

    return

In [13]:
def OneSampleTtest(sample, endog_var, exog_var, car, depVar, dirFirm):

    # if depVar != None:
    #     dirFirm = dirFirm.rename( {depVar:f"{depVar}_2"}, axis = 1)
    
    #     colsAdd = []
    #     for i in range(-1, 4):
    #         if i != 0:
    #             colsAdd.append(f"AsOnYear_T+{i}")
    #             colsAdd.append(f"{depVar}T+{i}")
    #             if i>0 :
    #                 colsAdd.append(depVar+f"(T+{i}) - (T-1)")
    
    #     newFrame= pd.DataFrame(columns = colsAdd, data = 0, index = sample.index, dtype = "int")
    #     sample = pd.concat([sample, newFrame], axis = 1)
    #     sample = sample.copy()
        
    #     for i in range(-1, 4):
    #         if i != 0:
    #             sample.loc[:, f"AsOnYear_T+{i}"] = sample["AsOnYear"] + i
    
    #     for i in range(-1, 4):
    #         if i != 0:
    #             sample.loc[:, f"{depVar}T+{i}"] = sample.merge(dirFirm[["Symbol", "AsOnYear", f"{depVar}_2"]].copy(), left_on = ["Symbol", f"AsOnYear_T+{i}"],
    #                                                           right_on = ["Symbol", "AsOnYear"], how = "left")[f"{depVar}_2"]
        
    #     for i in range(1, 4):
    #         if i != 0:
    #             sample.loc[:, depVar+f"(T+{i}) - (T-1)"] = sample[f"{depVar}T+{i}"] - sample[f"{depVar}T+-1"]
    
            
    #     sample = sample.copy()
    sample[car] = winsorize(sample[car], limits = [0.01, 0.01])
    group1 = sample.copy()
    
    t_stat, p_value = stats.ttest_1samp(group1[car], 0)  # Welch’s t-test (default)
    
    print("\n")
    print(car, ":")
    print("\n")
    print("T Statistic:", t_stat, " P Value:",p_value)
    print("Mean:", group1[car].mean())
    print("Median:", group1[car].median())
    print("N:", len(group1[car]))

    print("\n")

    # -----------------------------------------------------------------------------------------------------------------




    # if exog_var != None:
    #     print("━"*120)
    #     print(f'{"Matching Variable":<40} {"Treatment Firms":<20} {"Control Firms":<20} {"Test of Diff (p value)":<20}')
    #     print(f'{" ":<40} {"N = " + str(len(group1[car])):<20} {"N = " + str(len(group2[car])):<20}')
    #     print("-"*120)

    #     for var in exog_var:
    #         treatMean = group1[var].mean()
    #         controlMean = group2[var].mean()
    #         p_value = stats.ttest_ind(group1[var], group2[var], equal_var=False)[1]
    #         print(f'{var:<40} {treatMean:<20.4f} {controlMean:<20.4f} {p_value:<20.4f}')
    
    #     print("━"*120, "\n")
    
    # -----------------------------------------------------------------------------------------------------------------


    # if depVar != None:
    #     print(depVar, " across years:\n")
    #     for i in range(1,4):
    #         sample = sample.dropna(subset = [depVar+f'(T+{i}) - (T-1)'])
    
    #     group1 = sample.loc[ sample[endog_var] == 1].copy()
    #     group2 = sample.loc[ sample[endog_var] == 0].copy()

    #     print("━"*150, "\n")
    #     print(f'{depVar:<40}{" ":<20}{"Treatment Firms":<20}{"Control Firms":<20}{"Difference":<20}{"Test of Diff":<20}{"Test of Diff"}')
    #     print(f'{" ":<120}{"(t stat)":<20}{"(p value)":<20}')
    
    #     print("─"*150, "\n")
    
    #     for i in range(1,4):
    #         t_stat2, p_value2 = stats.ttest_ind(group1[depVar+f'(T+{i}) - (T-1)'], group2[depVar+f'(T+{i}) - (T-1)'], equal_var=False)  # Welch’s t-test (default)
            
    #         treatedMean = group1[depVar+f'(T+{i}) - (T-1)'].mean()
    #         controlMean = group2[depVar+f'(T+{i}) - (T-1)'].mean()
    #         diffMean = treatedMean - controlMean
    
    #         treatedMedian = group1[depVar+f'(T+{i}) - (T-1)'].median()
    #         controlMedian = group2[depVar+f'(T+{i}) - (T-1)'].median()
    #         diffMedian = treatedMedian - controlMedian
    
    #         print(f'{"Year_T+" + str(i) +" - Year_T-1":<40}{"<MEAN>":<20}{treatedMean:<20.4f}{controlMean:<20.4f}{diffMean:<20.4f}{t_stat2:<20.4f}{p_value2:<20.10f}')
    
    #         label1 = "Treated N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
    #         label2 = "Control N: " + str(len(group1[depVar+f'(T+{i}) - (T-1)']))
            
    #         print(f'{label1 + " "*5 + label2:<40}{"<MEDIAN>":<20}{treatedMedian:<20.4f}{controlMedian:<20.4f}{diffMedian:<20.4f}')
            
    #         print("-"*150, "\n")
            
    #print("━"*150, "\n")

    return

In [14]:
def PsmReplac(sample, endog_var, exog_var, car, depVar, dirFirm):

    # Logit Regression
    sample.loc[:, "propensityScore"] = LogitReg(sample, endog_var, exog_var)

    treated = sample.loc[ sample[endog_var] == 1].copy()
    control = sample.loc[ sample[endog_var] == 0].copy()

    # Nearest Neighbours
    nn = NearestNeighbors(n_neighbors = 1, metric = "euclidean")
    nn.fit(control[["propensityScore"]])

    distances, indices = nn.kneighbors(treated[["propensityScore"]])
    
    matchedControl = control.iloc[indices.flatten()].copy()
    
    matched = pd.concat([treated, matchedControl])
    matched.reset_index(drop=True, inplace=True)

    MeanDiffTtest(matched, endog_var, exog_var, car, depVar, dirFirm)

    return

In [15]:
# Func PSM non replacement
def PsmNonReplac(sample, endog_var, exog_var, car, depVar, dirFirm):

    # Logit Regression
    sample.loc[:, "propensityScore"] = LogitReg(sample, endog_var, exog_var)

    # Separate treated and control groups
    treated = sample[sample[endog_var] == 1].copy()
    control = sample[sample[endog_var] == 0].copy()
    
    # Compute pairwise distances (absolute difference in propensity scores)
    dist_matrix = cdist(treated[['propensityScore']], control[['propensityScore']], metric='euclidean')
    
    # Match without replacement
    treated_indices = []
    matched_indices = []
    used_control_indices = set()
    
    for i in range(len(treated)):
        if len(used_control_indices) >= len(control):  # Stop if no controls left
            print("Warning: Not enough control units to match all treated units.")
            break
        
        # Get nearest control unit index that hasn't been used
        match_idx = np.argmin(dist_matrix[i])
        
        while match_idx in used_control_indices:  # Ensure it's not already matched
            dist_matrix[i, match_idx] = np.inf  # Temporarily set distance to infinity

            if np.all(dist_matrix[i] == np.inf):  # If all controls are exhausted
                print(f"No available control for treated unit {i}, skipping.")
                match_idx = None
                break
            
            match_idx = np.argmin(dist_matrix[i])
        
        used_control_indices.add(match_idx)
        matched_indices.append(match_idx)
        treated_indices.append(i)
    
    # Retrieve matched units
    matched_control = control.iloc[matched_indices].copy()
    matched_treated = treated.iloc[treated_indices].copy()
    
    # Combine matched treated and control units
    matched_data = pd.concat([matched_treated.reset_index(drop=True), matched_control.reset_index(drop=True)])
    
    # Reset index
    matched_data.reset_index(drop=True, inplace=True)


    # Mean difference and T Test
    MeanDiffTtest(matched_data, endog_var, exog_var, car, depVar, dirFirm)

    return

In [16]:
psmSampleIndep

,index,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Date of Demise,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Ownership group code,Prowess company code,CompanyName,govtdummy,findummy,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllPastDirectNIC_2Digit,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,SkillsInBriefProfile,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Manufacturing_NIC_not used,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,date_source,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships,DummySum,DummySumIndep
0,1233,AARTIDRUGS,AARTI DRUGS LTD.,2022-03-31,2022,INE767A01016,P00005474,LATE MR.,RAMDAS,MANEKLAL,GANDHI,1933-03-14,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,FINANCE,HEALTHCARE,LEADER...",SOLICITOR,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,HE IS L.L.M. FROM MUMBAI UNIVERSITY. HE IS AN ...,NaT,2021-07-16,Y,2005-12-31,2021-07-16,2021-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,107.0,0.0,2282.0,3029.0,0.0,5311.0,2282.0,3394.0,0.0,5676.0,2282.0,3029.0,0.0,5311.0,2282.0,3394.0,0.0,5676.0,13278,"((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...",5,2,0,7,5,2,0,7,0,3,0,3,0,3,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,92,9.298630,15.550685,36.378082,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,AARTIDRUGS,2100,Public Ltd.,Alchemie Group,2.010103e+10,3990.0,Aarti Drugs Ltd.,0,0,"{strategy, finance, legal/compliance, corporat...","POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",1,0,"{2100, 20299, 20, 46691, 21002}","{20299, 46691, 2100}","{20299, 46691, 2100}","{2100, 20299, 20, 46691, 21002}","{20, 46, 21}","{20, 46, 21}",0,0,1,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'strategy', 'legal/co...",0,1,"{AARTIDRUGS, UNICHEMLAB, PIDILITIND, AARTIIND,...",6,5,5,0,1,0,1,1,False,False,False,False,False,False,True,True,False,False,True,True,False,False,False,True,False,1,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,6.0,1.0,0.833333,Date of Demise,2021-07-16,3990.0,730.65,0.018896,0.009245,0.316611,0.325856,0.003376,0.564257,-0.014844,0.008144,0.002629,0.002879,0.132478,0.110042,8.723116e-04,0.004606,-0.025435,-0.055652,-0.153805,-0.015232,0.009891,0.004385,0.003099,0.144461,0.126881,4.326799e-05,0.003140,-0.025749,-0.058699,-0.160480,-0.014632,0.010992,0.004299,0.002307,0.138304,0.123616,8.367564e-06,0.001408,-0.028103,-0.061461,-0.161486,-0.012238,0.012575,0.006608,0.003290,0.124710,0.111963,4.613534e-06,-0.009226,-0.036602,-0.073541,-0.179789,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2021,4.532599,2.079442,1,1
1,1481,AARTIIND,AARTI INDUSTRIES LTD.,2019-03-31,2019,INE769A01020,P00085909,LATE MR.,RADHESHYAM,SOBHRAJ,ROHRA,1956-04-12,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.TECH.-CHEMICAL,INDIAN INSTITUTE OF...",POST GRADUATE: P.G.DIPLOMA-MANAGEMENT COMPUTER...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR. ROHRA IS BACHELOR IN TECHNOLOGY (CHEMICAL ...,NaT,2018-09-28,Y,2017-12-21,2018-09-28,2018-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,0.0,0.0,0.0,0.0,281.0,0.0,281.0,0.0,0.0,0.0,0.0,0.0,281.0,0.0,281.0,281,"((AARTIIND, Y),)","{(AARTIIND, Y)}","{(AARTIIND, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,69,0.769863,0.769863,0.769863,1,1,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,1,AARTIIND,20299,Public Ltd.,Alchemie Group,2.010103e+10,3998.0,Aarti Industries Ltd.,0,0,{},"GRADUATE: B.TECH.-CHEMICAL,INDIAN INSTITUTE OF...",0,0,{20299},{20299},{20299},{20299},{20},{20},0,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,{AARTIIND},0,1,1,0,1,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1,False,True,False,False,True,True,True,False,False,True,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.0,5.0,0.375000,Date of Demise,2018-09-28,3998.0,290.55,-0.022014,0.019001,-1.494719,-1.475718,-2.956178,-1.437585,-0.021878,0.010700,0.003338,0.000766,0.139673,0.117423,5.509774e-04,-0.039164,-0.054104,-0.069426,-0.187143,-0.022138,0.007353,0.003061,0.000132,0.077994,0.059048,7.748489e-03,-0.048096,-0.065604,-0.089707,-0.230684,-0.021298,0.009546,0.003167,-0.000932,0.088514,0.072977,9.578746e-04,-0.047559,-0.060016,-0.077983,-0.211884,-0.021581,0.008977,0.003622,-0.001736,0.072541,0.059034,1.401824e-03,-0.047246,-0.059475,-0.078709,-0.218055,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2018,4.248495,0.000000,1,1
2,1522,AARTIIND,AARTI INDUSTRIES LTD.,2022-03-31,2022,INE769A01020,P00005474,LATE MR.,RAMDAS,MANEKLAL,GANDHI,1933-03-14,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,FINANCE,HEALTHCARE,LEADER...",SOLICITOR,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,HE IS L.L.M. FROM MUMBAI UNIVERSITY. HE IS AN ...,NaT,2021-07-16,Y,1990-01-29,2021-07-16,2021-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,107.0,0.0,8097.0,3029.0,0.0,11126.0,8097.0,3394.0,0.0,11491.0,8097.0,3029.0,0.0,11126.0,8097.0,3394.0,0.0,11491.0,13278,"((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","{(AARTIIND, Y), (VINYLINDIA, Y), (AARTIDRUGS, Y)}","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...","((AARTIDRUGS, U), (PIDILITIND, Y), (VINYLINDIA...",5,2,0,7,5,2,0,7,0,3,0,3,0,3,0,3,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,92,9.298630,31.482192,36.378082,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,AARTIIND,20299,Public Ltd.,Alchemie Group,2.010103e+10,3998.0,Aarti Industries Ltd.,0,0,"{strategy, finance, legal/compliance, corporat...","POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI",1,0,"{2100, 20299, 20, 46691, 21002}","{20299, 46691, 2100}","{20299, 46691, 2100}","{2100, 20299, 20, 46691, 21002}","{20, 46, 21}","{20, 46, 21}",0,0,1,0,0,0,0,0,0,0,0,{},{},{},"{'corporate governance', 'strategy', 'legal/co...",0,1,"{AARTIDRUGS, UNICHEMLAB, PIDILITIND, AARTIIND,...",6,5,5,0,1,0,1,1,False,False,False,False,False,False,True,True,False,False,True,True,False,False,False,True,False,1,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,7.0,1.0,0.857143,Date of Demise,2021-07-16,3998.0,856.95,0.002926,0.009245,0.316611,0.325856,0.003376,0.564257,-0.012627,0.006998,0.007996,0.004616,0.235897,0.216136,7.204323e-07,-0.028421,-0.023911,-0.039931,-0.117265,-0.011842,0.007986,0.008414,0.003834,0.228487,0.212634,2.827606e-08,-0.031368,-0.027427,-0.043715,-0.120129,-0.012202,0.008103,0.008349,0.003692,0.235954,0.222930,2.723893e-10,-0.030199,-0.026406,-0.042655,-0.118662,-0.012362,0.008157,0.008490,0.003831,0.233875,0.222718,6.830957e-12,-0.029934,-0.025927,-0.042446,-0.119002,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2021,4.532599,2.079442,1,1
3,2275,ABBOTINDIA,ABBOTT INDIA LTD.,2018-03-31,2018,INE358A01014,P00004272,LATE MR.,RANJAN,MOHANLAL,KAPUR,1942-11-25,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: GRADUATE,AMERICAN ASSOCIATION OF ADV...","POST GRADUATE: M.A.-ENGLISH,ST.STEPHEN'S COLLE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,CO.EXECUTIVE,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,MR KAPUR IS AN EX-CITIBANKER. HE IS A VETERAN ...,NaT,2018-01-27,Y,2006-09-18,2018-01-27,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,302.0,0.0,2021.0,1763.0,0.0,3784.0,2021.0,2128.0,0.0,4149.0,2021.0,1763.0,0.0,3784.0,2021.0,2128.0,0.0,4149.0,6307,"((HITECHCORP, Y), (ABBOTINDIA, Y), (MIRCELECTR...","{(PIDILITIND, Y), (ABBOTINDIA, Y)}","{(PIDILITIND, Y), (ABBOTINDIA, Y)}","((HITECHCORP, Y), (MIRCELECTR, Y), (HITECHCORP...","((HITECHCORP, Y), (MIRCELECTR, Y), (HITECHCORP...",5,2,0,7,5,2,0,7,0,2,0,2,0,2,0,2,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,82,5.830137,11.367123,17.279452,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,ABBOTINDIA,21002,Public Ltd.,Private (Foreign),2.020200e+10,121704.0,Abbott India Ltd.,0,0,{},"GRADUATE: GRADUATE,AMERICAN ASSOCIATION OF ADV...",0,0,"{26401, 22208, 20, 64191, 21002}","{20, 21002}","{20, 21002}","{26401, 22208, 20, 64191, 21002}","{20, 21, 26, 64, 22}","{20, 21, 26, 64, 22}",1,0,1,0,0,0,0,0,0,0,0,{},{},{},set(),0,0,"{HDFCBANK, ABBOTINDIA, MIRCELECTR, PIDILITIND,...",0,5,5,0,1,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,1,False,False,False,False,False,True,True,False,True,False,False,False,True,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Date of Demise,2018-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2018,4.418841,2.079442,1,1
4,3409,ADANIGREEN,ADANI GREEN ENERGY LTD.,2024-03-31,2024,INE364U01010,P00052996,LATE DR.(MS.),POORNIMA,GOVIND,ADVANI,1960-07-29,F,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMBAI","DOCTORATE: PH.D.-LAW,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,C...",ADVOCATE,DEMISE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"DR, POORNIMA ADVANI IS ENGAGED IN PRACTICE OF ...",NaT,2023-04-01,Y,2019-08-07,2023-04-01,2023-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,968.0,0.0,968.0,0.0,1333.0,0.0,1333.0,0.0,968.0,0.0,968.0,0.0,1333.0,0.0,1333.0,1697,"((ADANIGREEN, Y),)","{(ADANIGREEN, Y)}","{(ADANIGREEN, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,64,3.652055,3.652055,4.649315,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ADANIGREEN,46529,Public Ltd.,Adani Group,2.010102e+10,527121.0,Adani Green Energy Ltd.,0,0,"{strategy, economics, corporate social respons...","POST GRADUATE: LL.M.,UNIVERSITY OF MUMBAI,MUMB...",1,1,{46529},{46529},{46529},{46529},{46},{46},0,0,1,0,0,0,0,0,0,0,0,{},{},{services},"{'corporate governance', 'services', 'corporat...",1,1,{ADANIGREEN},14,1,1,0,1,1,0,1,True,False,False,False,False,True,True,True,False,True,True,True,True,True,False,True,False,0,False,False,False,False,False,True,True,False,True,False,False,True,True,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,0,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,8.0,0.0,1.000000,Date of Demise,2023-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2023,4.174387,0.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

# CAR Plots

### Total Sample

In [17]:
test = psmSampleIndep.copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Year of Study"]].plot(kind = "scatter", x="Year of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

In [18]:
test.describe()

,index,AsOnDate,AsOnYear,Date of Birth,Tenure Valid till,Date of Demise,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,Ownership group code,Prowess company code,govtdummy,findummy,IsMBA,IsPhD,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,HasTechSkill,HasFinanceSkill,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,Manufacturing_NIC_not used,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships,DummySum,DummySumIndep
count,541.000000,541,541.000000,461,15,541,541,541,516,0,541.0,541.000000,541.000000,541.000000,541.000000,541.0,541.0,541.0,541.0,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.0,541.000000,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.000000,541.000000,541.0,541.0,541.0,541.000000,541.0,541.000000,541.0,541.000000,461.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.000000,541.0,541.000000,541.0,541.0,5.380000e+02,538.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.000000,541.0,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.0,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.0,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,386.000000,386.000000,386.000000,541,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,3.610000e+02,349.000000,349.000000,349.000000,349.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,3.610000e+02,349.000000,349.000000,349.000000,349.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,3.610000e+02,349.000000,349.000000,349.000000,349.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,3.600000e+02,348.000000,348.000000,348.000000,348.000000,541.000000,19.000000,541.000000,19.000000,541.000000,19.000000,541.000000,19.000000,541.000000,461.000000,541.000000,541.0,541.0
mean,129124.077634,2018-10-05 11:26:43.696857600,2018.515712,1942-07-03 08:16:39.566160512,2026-03-10 09:36:00,2018-04-10 09:10:58.780036864,2006-06-21 05:19:24.510166400,2018-04-10 09:10:58.780036864,2017-10-04 10:39:04.186046720,NaT,1.0,0.003697,0.049908,1.005545,0.022181,0.0,0.0,0.0,0.0,258.299445,0.0,2434.787431,1514.532348,9.027726,3958.347505,2434.787431,1867.345656,9.027726,4311.160813,2454.177449,1520.683919,9.027726,3983.889094,2454.177449,1874.920518,9.027726,4338.125693,5416.310536,2.133087,0.438078,0.085028,2.656192,2.133087,0.438078,0.085028,2.656192,0.003697,1.944547,0.053604,2.001848,0.003697,1.944547,0.053604,2.001848,1.0,0.0,0.127542,0.872458,0.0,0.042514,0.020333,0.025878,0.020333,0.064695,0.0,0.001848,0.001848,0.001848,0.0,0.0,0.0,0.127542,0.0,0.872458,0.0,0.029575,82.544469,5.136769,11.885276,14.839207,0.269871,0.269871,0.0,0.0,0.038817,0.038817,0.094270,0.094270,0.127542,0.127542,0.059150,0.0,0.432532,0.234750,1.0,0.059150,0.0,1.0,1.986606e+10,178095.890335,0.024030,0.109057,0.168207,0.083179,0.231054,0.090573,0.955638,0.005545,0.005545,0.0,0.009242,0.009242,0.0,0.009242,0.0,0.086876,0.378928,2.924214,2.731978,2.593346,0.011091,0.842884,0.083179,0.733826,0.955638,0.597043,0.038817,0.035120,0.147874,0.0,0.036969,0.0,0.011091,0.0,0.377079,0.094270,0.881701,0.273567,0.881701,0.604436,0.314233,0.238447,0.299445,0.099815,0.256932,0.059150,0.288355,0.243993,0.231054,0.184843,0.301294,0.280961,0.171904,0.171904,0.005545,0.0,0.214418,0.208872,0.393715,0.192237,0.817006,0.826248,0.205176,0.057301,0.064695,0.014787,0.240296,0.005545,0.103512,0.088725,0.160813,0.062847,0.184843,0.007394,0.125693,0.016636,0.192237,0.031423,0.110906,0.044362,0.0,0.035120,0.114603,0.027726,0.036969,0.243993,0.001848,0.024030,0.083179,0.094270,0.059150,0.025878,5.955959,2.178756,0.626262,2018-04-10 09:10:58.780036864,170197.781163,292.353657,0.000342,0.024937,0.048898,0.073835,0.034222,0.147462,-0.023768,0.010327,0.006956,0.002179,0.161200,0.139507,8.592985e-02,-0.004388,-0.050470,-0.102229,-0.200800,-0.023885,0.010165,0.006893,0.002292,0.156838,0.139513,6.966301e-02,-0.004184,-0.050175,-0.101725,-0.199630,-0.023986,0.010327,0.006694,0.002267,0.152801,0.138361,6.007374e-02,-0.004163,-0.050244,-0.101834,-0.199343,-0.024085,0.010297,0.006674,0.002389,0.149870,0.137490,4.814913e-02,-0.003899,-0.050220,-0.102861,-0.200640,0.035120,116.894737,0.035120,146.894737,0.035120,176.894737,0.035120,206.894737,2017.785582,4.418738,0.954696,1.0,1.0
min,1233.000000,2013-03-31 00:00:00,2013.000000,1920-05-17 00:00:00,2025-03-27 00:00:00,2013-01-01 00:00:00,1955-08-27 00:00:00,2013-01-01 00:00:00,2012-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,-158.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-158.000000,0.000000,-158.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,31.000000,76.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,49.0,0.024658,0.084932,0.208219,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,1.010100e+10,1120.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,2013-01-01 00:00:00,3990.000000,0.100000,-0.080851,0.007905,-2.708078,-2.694947,-3.199046,-3.583618,-0.047053,-0.010444,-0.012804,-0.018154,0.002542,-0.023254,1.157006e-19,-0.232415,-0.272763,-0.410391,-0.609713,-0.043825,-0.007550,-0.011276,-0.014020,0.000646,-0.019888,9.634225e-24,-0.223836,-0.287026,-0.409436,-0.629275,-0.042015,-0.007658,-0.008629,-0.012993,0.001737,-0.015278,1.751110e-27,-0.222225,-0.280351,-0.419055,-0.623555,-0.040535,-0.008242,-0.009009,-0.016136,0.000134,-0.014427,4.627187e-32,-0.221390,-0.278929,-0.412941,-0.633076,0.000000,61.000000,0.000000,91.000000,0.000000,121.000000,0.000000,151.000000,2013.000000,3.912023,0.000000,1.0,1.0
25%,65520.000000,2015-03-31 00:00:00,2015.000000,1935-08-09 00:00:00,2025-08-31 12:00:00,2015-03-24 00:00:00,2001-12-10 00:00:00,2015-03-24 00:00:00,2014-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,94.000000,0.0,0.000000,335.000000,0.000000,1333.000000,0.000000,700.000000,0.000000,1684.000000,0.000000,343.000000,0.000000,1346.000000,0.000000,708.000000,0.000000,1699.000000,2439.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.000000,76.0,1.939726,4.654795,6.682192,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,2.010102e+10,92968.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.250000,1.000000,0.400000,2015-03-24 00:00:00,86604.000000,23.750000,-0.015593,0.014979,-0.391011,-0.367519,-0.403890,-0.353677,-0.029833,0.006312,0.002747,-0.001970,0.060066,0.035757,7.838897e-07,-0.040410,-0.087213,-0.150228,-0.264455,-0.030174,0.006561,0.003173,-0.001670,0.063904,0.044669,2.956407e-08,-0.037534,-0.087395,-0.149562,-0.261685,-0.030326,0.007005,0.002784,-0.001442,0.062792,0.046817,1.547185e-09,-0.038824,-0.088173,-0.146836,-0.256942,-0.030573,0.006999,0.002917,-0.001029,0.062287,0.048631,7.498300e-11,-0.038413,-0.087478,-0.148371,-0.255147,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2015.000000,4.343805,0.000000,1.0,1.0
50%,127116.000000,2018-03-31 00:00:00,2018.000000,1941-08-04 00:00:00,2025-11-25 00:00:00,2018-03-18 00:00:00,2008-01-30 00:00:00,2018-03-18 00:00:00,2018-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,184.000000,0.0,1256.000000,1054.000000,0.000000,2958.000000,1256.000000,1419.000000,0.000000,3323.000000,1256.000000,1061.000000,0.000000,2969.000000,1256.000000,1426.000000,0.000000,3334.000000,4897.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.000000,83.0,3.906849,9.134247,13.416438,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,2.010103e+10,153595.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.666667,2018-03-18 00:00:00,145617.000000,70.650000,-0.001106,0.019213,0.136023,0.161152,0.057557,0.119912,-0.025077,0.010681,0.006984,0.002502,0.137497,0.115191,6.334641e-04,-0.009207,-0.054308,-0.104649,-0.198495,-0.025469,0.010321,0.007364,0.002595,0.130953,0.113096,1.298316e-04,-0.009601,-0.053013,-0.102097,-0.199998,-0.025259,0.010601,0.006718,0.002239,0.129367,0.114526,2.011616e-05,-0.010089,-0.054958,-0.102047,-0.196202,-0.025377,0.010422,0.006684,0.002117,0.124587,0.111838,4.678955e-06,-0.008871,-0.054320,-0.101965,-0.201375,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2018.000000,4.430817,0.693147,1.0,1.0
75%,191316.000000,2022-03-31 00:00:00,2022.000000,1949-01-01 00:00:00,2026-08-28 00:00:00,2021-04-28 00:00:00,2014-04-16 00:00:00,2021-04-28 00:00:00,2021-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,289.000000,0.0,3532.000000,2297.000000,0.000000,5611.000000,3532.000000,2662.000000,0.000000,5976.000000,3571.000000,2297.000000,0.000000,5614.000000,3571.000000,2662.000000,0.000000,5979.000000,7443.000000,3.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,3.000000,0.000000,2.000000,0.000000,2.000000,0.000000,2.000000,0.000000,2.000000,1.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.000000,89.0,7.293151,16.380822,20.391781,1.000000,1.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,1.0,0.000000,0.0,1.0,2.010104e+10,247607.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.000000,4.000000,3.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,3.000000,0.875000,2021-04-28 00:00:00,243438.000000,207.300000,0.010204,0.027224,0.501197,0.528945,0.489542,0.705914,-0.016309,0.014302,0.011079,0.006101,0.234754,0.214964,6.531108e-02,0.023723,-0.020028,-0.059944,-0.135575,-0.016055,0.014046,0.010717,0.006203,0.228006,0.212143,2.154910e-02,0.025704,-0.017344,-0.059214,-0.131453,-0.016091,0.013786,0.010274,0.006201,0.220436,0.207148,9.543853e-03,0.024491,-0.018358,-0.058777,-0.132623,-0.016359,0.013625,0.010634,0.006257,0.215551,0.204127,4.068869e-03,0.023297,-0.018265,-0.056981,-0.133217,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2021.000000,4.499810,1.386294,1.0,1.0

### RID

In [19]:
test = psmSampleIndep.loc[ psmSampleIndep["IsRookieIndep"] == 1 ].copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Year of Study"]].plot(kind = "scatter", x="Year of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

In [20]:
test.describe()

,index,AsOnDate,AsOnYear,Date of Birth,Tenure Valid till,Date of Demise,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,Ownership group code,Prowess company code,govtdummy,findummy,IsMBA,IsPhD,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,HasTechSkill,HasFinanceSkill,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,Manufacturing_NIC_not used,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships,DummySum,DummySumIndep
count,69.000000,69,69.000000,36,2,69,69,69,58,0,69.0,69.0,69.000000,69.0,69.000000,69.0,69.0,69.0,69.0,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.0,69.000000,69.0,69.000000,69.0,69.000000,69.0,69.000000,69.0,69.0,69.0,69.0,69.0,69.0,69.000000,69.0,69.000000,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.000000,36.0,69.000000,69.000000,69.000000,69.0,69.0,69.0,69.0,69.000000,69.000000,69.000000,69.000000,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,69.0,6.900000e+01,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.0,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.0,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.0,69.000000,69.000000,69.0,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,55.000000,55.000000,55.000000,69,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,4.300000e+01,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,4.300000e+01,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,4.300000e+01,43.000000,43.000000,43.000000,43.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,4.200000e+01,42.000000,42.000000,42.000000,42.000000,69.0,0.0,69.0,0.0,69.0,0.0,69.0,0.0,69.000000,36.000000,69.000000,69.0,69.0
mean,117315.434783,2019-04-26 18:46:57.391304448,2019.072464,1953-12-28 10:40:00,2027-05-11 12:00:00,2018-10-19 07:18:15.652173824,2017-05-25 00:41:44.347826176,2018-10-19 07:18:15.652173824,2018-10-06 01:14:28.965517312,NaT,1.0,0.0,0.159420,1.0,0.130435,0.0,0.0,0.0,0.0,174.144928,0.0,7.144928,190.449275,1.985507,199.579710,7.144928,503.144928,1.985507,512.275362,7.144928,190.449275,1.985507,199.579710,7.144928,503.144928,1.985507,512.275362,531.217391,0.028986,0.0,0.014493,0.043478,0.028986,0.0,0.014493,0.043478,0.0,1.086957,0.0,1.086957,0.0,1.086957,0.0,1.086957,1.0,0.0,1.0,0.0,0.0,0.0,0.014493,0.0,0.014493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.101449,71.027778,1.378479,1.403494,1.455390,1.0,1.0,0.0,0.0,0.304348,0.304348,0.739130,0.739130,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.865776e+10,201978.550725,0.144928,0.173913,0.086957,0.043478,0.202899,0.028986,0.855072,0.014493,0.014493,0.0,0.014493,0.014493,0.0,0.014493,0.0,0.086957,0.318841,2.536232,0.913043,0.913043,0.0,0.608696,0.043478,0.043478,0.855072,0.521739,0.043478,0.043478,0.115942,0.0,0.014493,0.0,0.014493,0.0,0.362319,0.101449,0.753623,0.231884,0.753623,0.550725,0.202899,0.173913,0.217391,0.101449,0.130435,0.028986,0.304348,0.275362,0.188406,0.144928,0.246377,0.231884,0.159420,0.159420,0.0,0.0,0.188406,0.188406,0.231884,0.086957,0.318841,0.347826,0.173913,0.014493,0.0,0.028986,0.217391,0.0,0.086957,0.072464,0.159420,0.057971,0.144928,0.014493,0.086957,0.0,0.188406,0.028986,0.057971,0.014493,0.0,0.043478,0.130435,0.0,0.014493,0.275362,0.014493,0.028986,0.057971,0.101449,0.043478,0.014493,7.163636,2.709091,0.633588,2018-10-19 07:18:15.652173824,202621.395349,155.178140,0.001741,0.023167,-0.005566,0.017601,-0.116760,-0.016160,-0.023036,0.010147,0.007198,0.003094,0.167017,0.145474,7.424006e-02,0.000813,-0.047969,-0.096143,-0.180682,-0.023019,0.009768,0.006653,0.003078,0.163992,0.146814,4.433120e-02,0.000672,-0.047948,-0.095642,-0.181325,-0.023203,0.009438,0.007007,0.003349,0.166172,0.151959,2.929109e-02,0.000957,-0.047555,-0.094922,-0.180316,-0.023365,0.009374,0.007308,0.003278,0.165878,0.153731,2.231108e-02,-0.000648,-0.050860,-0.105754,-0.188796,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2018.231884,4.270518,0.030137,1.0,1.0
min,1481.000000,2013-03-31 00:00:00,2013.000000,1939-11-08 00:00:00,2027-02-11 00:00:00,2013-02-11 00:00:00,2010-11-27 00:00:00,2013-02-11 00:00:00,2012-03-31 00:00:00,NaT,1.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,9.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,31.000000,76.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,49.0,0.024658,0.084932,0.208219,1.0,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.010100e+10,3998.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,2013-02-11 00:00:00,3998.000000,1.350000,-0.080851,0.008472,-1.494719,-1.475718,-2.956178,-1.437585,-0.041951,-0.006743,-0.006732,-0.007180,0.013512,-0.012000,2.577367e-18,-0.081976,-0.201666,-0.304882,-0.444955,-0.038375,-0.005039,-0.011276,-0.007636,0.016249,-0.003965,9.634225e-24,-0.071829,-0.197896,-0.299970,-0.438741,-0.036783,-0.004636,-0.008349,-0.005723,0.013205,-0.003616,1.751110e-27,-0.067650,-0.192150,-0.292956,-0.426287,-0.036646,-0.003512,-0.009009,-0.007255,0.014873,0.000527,4.040190e-30,-0.056826,-0.192125,-0.292602,-0.432312,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2013.000000,3.912023,0.000000,1.0,1.0
25%,65181.000000,2017-03-31 00:00:00,2017.000000,1948-11-24 12:00:00,2027-03-27 18:00:00,2016-12-18 00:00:00,2015-06-24 00:00:00,2016-12-18 00:00:00,2017-03-31 00:00:00,NaT,1.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,80.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,301.000000,0.000000,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,301.000000,0.000000,301.000000,334.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,67.75,0.824658,0.824658,0.915068,1.0,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.010101e+10,82107.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1.000000,0.400000,2016-12-18 00:00:00,79791.500000,24.605000,-0.015256,0.015860,-0.582396,-0.563985,-0.479803,-0.489549,-0.028607,0.006314,0.003530,0.000578,0.056165,0.031755,1.174042e-06,-0.033717,-0.094776,-0.157789,-0.252064,-0.028437,0.006634,0.002743,0.000332,0.060493,0.041188,4.331120e-07,-0.034074,-0.093932,-0.150320,-0.250238,-0.028609,0.006556,0.002755,0.000394,0.069822,0.053967,1.229741e-09,-0.033408,-0.096641,-0.160324,-0.250453,-0.028360,0.006243,0.003800,0.000469,0.071436,0.057914,3.460004e-11,-0.033800,-0.094272,-0.157845,-0.250781,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2016.000000,4.230457,0.000000,1.0,1.0
50%,112023.000000,2019-03-31 00:00:00,2019.000000,1953-11-12 00:00:00,2027-05-11 12:00:00,2018-11-14 00:00:00,2017-09-21 00:00:00,2018-11-14 00:00:00,2019-03-31 00:00:00,NaT,1.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,163.000000,0.0,0.000000,90.000000,0.000000,137.000000,0.000000,455.000000,0.000000,494.000000,0.000000,90.000000,0.000000,137.000000,0.000000,455.000000,0.000000,494.000000,494.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,71.0,1.246575,1.353425,1.353425,1.0,1.0,0.0,0.0,0.000000,0.000000,1.000000,1.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.010103e+10,147825.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2.000000,0.666667,2018-11-14 00:00:00,125758.000000,93.100000,0.001732,0.017832,0.055536,0.076233,-0.022604,-0.210802,-0.024505,0.010168,0.006028,0.002815,0.130767,0.108287,9.722764e-04,-0.010854,-0.051895,-0.100159,-0.187143,-0.023865,0.009435,0.006975,0.003353,0.120576,0.102505,2.974896e-04,-0.013002,-0.049420,-0.109679,-0.204054,-0.024455,0.009104,0.008379,0.003490,0.129367,0.114526,2.011616e-05,-0.012377,-0.051364,-0.107109,-0.202116,-0.024672,0.008828,0.007445,0.002896,0.124088,0.111332,5.588692e-06,-0.010390,-0.056378,-0.108153,-0.195704,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2018.000000,4.276666,0.000000,1.0,1.0
75%,174376.000000,2021-03-31 00:00:00,2021.000000,1957-05-08 06:00:00,2027-06-25 06:00:00,2021-01-27 00:00:00,2019-04-25 00:00:00,2021-01-27 00:00:00,2020-12-29 18:00:00,NaT,1.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,244.000000,0.0,0.000000,339.000000,0.000000,350.000000,0.000000,704.000000,0.000000,715.000000,0.000000,339.000000,0.000000,350.000000,0.000000,704.000000,0.000000,715.000000,756.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,76.0,1.928767,1.958904,2.071233,1.0,1.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.010104e+10,346205.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.000000,4.000000,1.000000,1.000000,0.0,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,4.000000,0.894444,2021-01-27 00:00:00,360841.500000,253.300000,0.015083,0.022599,0.340954,0.375225,0.406831,0.378056,-0.017249,0.013797,0.010591,0.005199,0.229585,0.209660,8.180185e-02,0.025100,-0.033326,-0.065893,-0.150835,-0.016066,0.013131,0.009788,0.005638,0.198386,0.181915,2.747938e-02,0.025626,-0.026935,-0.055844,-0.147220,-0.017165,0.013149,0.010358,0.005940,0.229779,0.216650,5.185351e-03,0.026703,-0.028611,-0.057522,-0.139307,-0.017273,0.012924,0.011075,0.006950,0.221540,0.210203,1.577286e-03,0.020427,-0.027571,-0.061528,-0.140295,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2021.000000,4.343805,0.000000,1.0,1.0
max,254292.000000,2024-03-31 00:00:00,2024.000000,1976-03-07 00:00:00,2027-08-09 00:00:00,2023-12-12 00:00:00,2022-08-10 00:00:00,2023-12-12 00:00:00,2023-03-31 00:00:00,NaT,1.0,0.0,1.000000,1.0,1.000000,0.0,0.0,0.0,0.0,684.000000,0.0,490.000000,718.000000,137.000000,718.000000,490.000000,1083.000000,137.000000,1083.000000,490.000000,718.000000,137.000000,718.000000,490.000000,1083.000000,137.000000,1083.000000,1082.000000,1.000000,0.0,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0,2.000000,0.0,2.000000,0.0,2.000000,0.0,2.000000,1.0,0.0,1.0,0.0,0.0,0.0,1.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000,85.0,2.967123,2.967123,2.964384,1.0,1.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.020200e+10,644325.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0,1.000000,0.0,1.000000,1.000000,12.000000,2.000000,2.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.000000,17.000000,1.000000,2023-12-12 00:00:00,644325.000000,600.150000,0.071429,0.068131,1.494895,1.519807,1.136704,2.873384,-0.006004,0.027576,0.025881,0.012323,0.518059,0.505595,6.628243e-01,0.140327,0.192421,0.390927,0.241004,-0.006908,0.027936,0.024174,0.012867,0.528961,0.519282,4.936341e-01,0.143986,0.196503,0.397258,0.242966,-0.007969,0.027315,0.024078,0.012586,0.514830,0.506560,5.037387e-01,0.145636,0.197898,0.391601,0.239608,-0.007802,0.027490,0.023854,0.012138,0.492070,0.484673,3.772974e-01,0.135469,0.187549,0.214782,0.172870,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,2023.000000,4.454347,0.693147,1.0,1.0

In [21]:
test.loc[ test["120CAR5"] >= 0.75]

Empty DataFrame
Columns: [index, Symbol, Company, AsOnDate, AsOnYear, ISIN, Person Code, Director Salutation, Director First Name, Director Middle Name, Director Surname, Date of Birth, Gender, Nationality, Member of Civil Services, Promoter Director (Yes/No), Position on Board, Independent (Yes/No), Education1, Education2, Education3, Education4, Education5, Education6, Education7, Education8, Education9, Education10, Skills/Competencies, Occupation, Cessation Reason, Other Directorship 1, Other Directorship 2, Other Directorship 3, Other Directorship 4, Other Directorship 5, Other Directorship 6, Other Directorship 7, Other Directorship 8, Other Directorship 9, Other Directorship 10, Other Directorship 11, Other Directorship 12, Other Directorship 13, Other Directorship 14, Other Directorship 15, Brief Profile, Tenure Valid till, Date of Demise, Indep, Appointment Date, Cessation Date, PrevLastServed, NextServed, CessationDummy, ReappointDummy, TermStartDummy, TermNumber, AppointDummy, CumOpBalUnc, CumOpBalIndep, CumOpBalNonIndep, CumCloBalUnc, CumCloBalIndep, CumCloBalNonIndep, TermOpBalUnc, TermOpBalIndep, TermOpBalNonIndep, TermOpBalTotal, TermCloBalUnc, TermCloBalIndep, TermCloBalNonIndep, TermCloBalTotal, CompOpBalUnc, CompOpBalIndep, CompOpBalNonIndep, CompOpBalTotal, CompCloBalUnc, CompCloBalIndep, CompCloBalNonIndep, CompCloBalTotal, CloBalTotalXP, AllPastDirect, CurrDirectA, CurrDirectAB, PastSiezedDirectA, PastSiezedDirectAB, CountOtherPastUnclearA, CountOtherPastIndepA, CountOtherPastNonIndepA, CompCountOtherPastTotalA, CountOtherPastUnclearAB, CountOtherPastIndepAB, CountOtherPastNonIndepAB, CompCountOtherPastTotalAB, CountCurrUnclearA, CountCurrIndepA, CountCurrNonIndepA, CompCountCurrTotalA, CountCurrUnclearAB, ...]
Index: []

### Non RID

In [22]:
test = psmSampleIndep.loc[ psmSampleIndep["IsRookieIndep"] == 0 ].copy()

carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# for car in carCol:
#     test[car] = winsorize(test[car].values, limits = [0.01, 0.01]).data
#     test[[car, "Year of Study"]].plot(kind = "scatter", x="Year of Study", y=car, xticks = np.arange(2012, 2025, step = 1), yticks = np.arange(-2, 2.25, step = 0.25))

In [23]:
test.describe()

,index,AsOnDate,AsOnYear,Date of Birth,Tenure Valid till,Date of Demise,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,TenureInYearsTotal,IsFirstTerm,IsFirstTermIndep,IsZeroYear,IsZeroYearIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,Ownership group code,Prowess company code,govtdummy,findummy,IsMBA,IsPhD,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,HasTechSkill,HasFinanceSkill,NumSkills_gai,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,Academic,Outside Board,Company Business,Manufacturing_NIC_not used,combined_sustainability,skill_committee_sustainability,combined_entrepreneurial,skill_committee_entrepreneurial,combined_compensation,skill_committee_compensation,combined_conglomerate_experience,skill_committee_conglomerate_experience,combined_hr,skill_committee_hr,combined_technology,skill_committee_technology,combined_finance_accounting,skill_committee_finance_accounting,combined_governance,skill_committee_governance,combined_government_policy,skill_committee_government_policy,combined_international,skill_committee_international,combined_leadership,skill_committee_leadership,combined_legal,skill_committee_legal,combined_marketing,skill_committee_marketing,combined_risk_management,skill_committee_risk_management,combined_scientific,skill_committee_scientific,combined_strategic_planning,skill_committee_strategic_planning,combined_manufacturing_supply_chain,skill_committee_manufacturing_supply_chain,skill_committee_leadership_outside_board,combined_leadership_outside_board,board_corporate governance,board_international business,board_industrials,board_utilities,board_finance,board_telecommunication,board_accounts/audit/taxation,board_public policy,board_risk management,board_research & development,board_legal/compliance,board_services,board_marketing,board_healthcare,board_strategy,board_commodities,board_operations,board_diversity,board_diversified,board_corporate social responsibility,board_human resources,board_fast moving consumer goods,board_economics,board_leadership/management,board_energy,board_financial services,board_information technology,board_personal values,board_consumer discretionary,board_supply chain management,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,Date of Study,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_SMB,OLS210_HML,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210,Year of Study,ln_dirage,ln_directorships,DummySum,DummySumIndep
count,472.000000,472,472.000000,425,13,472,472,472,458,0,472.0,472.000000,472.000000,472.000000,472.000000,472.0,472.0,472.0,472.0,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.0,472.0,472.0,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.000000,472.000000,472.0,472.0,472.0,472.0,472.0,472.0,472.0,472.000000,425.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.0,472.0,472.0,472.0,472.0,472.0,472.0,472.000000,472.0,472.000000,472.000000,472.0,472.000000,472.0,472.0,4.690000e+02,469.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.000000,472.0,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.0,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,472.0,472.000000,472.000000,472.000000,472.000000,472.000000,331.000000,331.000000,331.000000,472,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,3.180000e+02,306.000000,306.000000,306.000000,306.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,3.180000e+02,306.000000,306.000000,306.000000,306.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,3.180000e+02,306.000000,306.000000,306.000000,306.000000,318.000000,318.000000,318.000000,318.000000,318.000000,318.000000,3.180000e+02,306.000000,306.000000,306.000000,306.000000,472.000000,19.000000,472.000000,19.000000,472.000000,19.000000,472.000000,19.000000,472.000000,425.000000,472.000000,472.0,472.0
mean,130850.341102,2018-09-05 18:09:09.152542464,2018.434322,1941-07-12 21:51:14.823529472,2026-01-03 16:36:55.384615424,2018-03-13 07:49:49.830508544,2004-11-14 19:40:40.677966080,2018-03-13 07:49:49.830508544,2017-08-19 00:25:09.170305792,NaT,1.0,0.004237,0.033898,1.006356,0.006356,0.0,0.0,0.0,0.0,270.601695,0.0,2789.675847,1708.095339,10.057203,4507.828390,2789.675847,2066.773305,10.057203,4866.506356,2811.900424,1715.146186,10.057203,4537.103814,2811.900424,2075.455508,10.057203,4897.413136,6130.444915,2.440678,0.502119,0.095339,3.038136,2.440678,0.502119,0.095339,3.038136,0.004237,2.069915,0.061441,2.135593,0.004237,2.069915,0.061441,2.135593,1.0,0.0,0.0,1.0,0.0,0.048729,0.021186,0.029661,0.021186,0.074153,0.0,0.002119,0.002119,0.002119,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.019068,83.52,5.686179,13.417570,16.795739,0.163136,0.163136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.067797,0.0,0.495763,0.269068,1.0,0.067797,0.0,1.0,2.004383e+10,174582.236674,0.006356,0.099576,0.180085,0.088983,0.235169,0.099576,0.970339,0.004237,0.004237,0.0,0.008475,0.008475,0.0,0.008475,0.0,0.086864,0.387712,2.980932,2.997881,2.838983,0.012712,0.877119,0.088983,0.834746,0.970339,0.608051,0.038136,0.033898,0.152542,0.0,0.040254,0.0,0.010593,0.0,0.379237,0.093220,0.900424,0.279661,0.900424,0.612288,0.330508,0.247881,0.311441,0.099576,0.275424,0.063559,0.286017,0.239407,0.237288,0.190678,0.309322,0.288136,0.173729,0.173729,0.006356,0.0,0.218220,0.211864,0.417373,0.207627,0.889831,0.896186,0.209746,0.063559,0.074153,0.012712,0.243644,0.006356,0.105932,0.091102,0.161017,0.063559,0.190678,0.006356,0.131356,0.019068,0.192797,0.031780,0.118644,0.048729,0.0,0.033898,0.112288,0.031780,0.040254,0.239407,0.0,0.023305,0.086864,0.093220,0.061441,0.027542,5.755287,2.090634,0.625045,2018-03-13 07:49:49.830508544,165813.455975,310.902547,0.000153,0.025176,0.056263,0.081439,0.054638,0.169586,-0.023866,0.010352,0.006923,0.002055,0.160414,0.138700,8.751055e-02,-0.005119,-0.050821,-0.103085,-0.203627,-0.024002,0.010218,0.006925,0.002186,0.155871,0.138526,7.308838e-02,-0.004866,-0.050487,-0.102580,-0.202202,-0.024092,0.010447,0.006652,0.002121,0.150993,0.136522,6.423617e-02,-0.004883,-0.050622,-0.102805,-0.202017,-0.024180,0.010418,0.006590,0.002272,0.147756,0.135345,5.156171e-02,-0.004345,-0.050132,-0.102464,-0.202265,0.040254,116.894737,0.040254,146.894737,0.040254,176.894737,0.040254,206.894737,2017.720339,4.431293,1.089854,1.0,1.0
min,1233.000000,2013-03-31 00:00:00,2013.000000,1920-05-17 00:00:00,2025-03-27 00:00:00,2013-01-01 00:00:00,1955-08-27 00:00:00,2013-01-01 00:00:00,2012-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,-158.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-158.000000,0.000000,-158.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,94.000000,1096.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,57.0,0.032877,0.257534,3.002740,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,1.010100e+10,1120.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,2013-01-01 00:00:00,3990.000000,0.100000,-0.069425,0.007905,-2.708078,-2.694947,-3.199046,-3.583618,-0.047053,-0.010444,-0.012804,-0.018154,0.002542,-0.023254,1.157006e-19,-0.232415,-0.272763,-0.410391,-0.609713,-0.043825,-0.007550,-0.008106,-0.014020,0.000646,-0.019888,4.536452e-22,-0.223836,-0.287026,-0.409436,-0.629275,-0.042015,-0.007658,-0.008629,-0.012993,0.001737,-0.015278,1.008718e-26,-0.222225,-0.280351,-0.419055,-0.623555,-0.040535,-0.008242,-0.007796,-0.016136,0.000134,-0.014427,4.627187e-32,-0.221390,-0.278929,-0.412941,-0.633076,0.000000,61.000000,0.000000,91.000000,0.000000,121.000000,0.000000,151.000000,2013.000000,4.060443,0.000000,1.0,1.0
25%,66015.750000,2015-03-31 00:00:00,2015.000000,1935-01-31 00:00:00,2025-08-12 00:00:00,2015-01-27 00:00:00,2001-01-31 00:00:00,2015-01-27 00:00:00,2014-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,100.000000,0.0,0.000000,602.500000,0.000000,1966.000000,0.000000,967.500000,0.000000,2308.750000,0.000000,615.500000,0.000000,2001.750000,0.000000,980.500000,0.000000,2338.500000,3125.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,77.0,2.686301,6.406849,8.561644,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,2.010102e+10,93902.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.400000,2015-01-27 00:00:00,87441.250000,23.437500,-0.015561,0.014856,-0.391011,-0.367519,-0.357214,-0.338756,-0.029948,0.006381,0.002647,-0.002336,0.060969,0.036683,7.698579e-07,-0.042022,-0.085850,-0.147169,-0.266253,-0.030418,0.006577,0.003200,-0.001810,0.064044,0.044812,2.859806e-08,-0.038009,-0.084843,-0.149024,-0.262159,-0.030568,0.007093,0.002796,-0.001733,0.062102,0.046116,1.548629e-09,-0.039002,-0.086367,-0.146685,-0.258299,-0.030707,0.007086,0.002840,-0.001106,0.060395,0.046712,1.027913e-10,-0.038471,-0.085830,-0.147390,-0.256864,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2015.000000,4.356709,0.693147,1.0,1.0
50%,132393.500000,2018-03-31 00:00:00,2018.000000,1940-11-01 00:00:00,2025-10-11 00:00:00,2018-01-03 12:00:00,2006-10-28 12:00:00,2018-01-03 12:00:00,2017-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,192.000000,0.0,1729.000000,1400.500000,0.000000,3611.000000,1729.000000,1765.500000,0.000000,3976.000000,1739.500000,1403.000000,0.000000,3628.000000,1739.500000,1768.000000,0.000000,3993.000000,5354.000000,1.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,84.0,4.843836,10.939726,14.668493,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,1.0,0.000000,0.0,1.0,2.010103e+10,153595.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,2.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.666667,2018-01-03 12:00:00,146644.500000,69.525000,-0.001858,0.019637,0.150372,0.176689,0.061327,0.142455,-0.025240,0.010813,0.007164,0.002450,0.137612,0.115309,6.288053e-04,-0.008382,-0.054458,-0.104786,-0.198893,-0.025626,0.010387,0.007385,0.002114,0.132646,0.114824,1.140644e-04,-0.007752,-0.053143,-0.102026,-0.199821,-0.025495,0.010811,0.006713,0.002053,0.129473,0.114634,1.992198e-05,-0.009827,-0.055194,-0.101763,-0.196011,-0.025516,0.010645,0.006601,0.002040,0.124587,0.111838,4.678955e-06,-0.008327,-0.054320,-0.100458,-0.201375,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2017.500000,4.442651,1.098612,1.0,1.0
75%,194522.000000,2022-03-31 00:00:00,2022.000000,1948-01-26 00:00:00,2026-02-07 00:00:00,2021-04-29 06:00:00,2011-07-24 00:00:00,2021-04-29 06:00:00,2021-03-31 00:00:00,NaT,1.0,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,295.000000,0.0,3928.000000,2519.000000,0.000000,6051.250000,3928.000000,2884.000000,0.000000,6416.250000,3933.750000,2519.000000,0.000000,6099.500000,3933.750000,2884.000000,0.000000,6464.500000,8011.750000,3.000000,0.000000,0.000000,4.000000,3.000000,0.000000,0.000000,4.000000,0.000000,3.000000,0.000000,3.000000,0.000000,3.000000,0.000000,3.000000,1.0,0.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,90.0,7.901370,17.710959,21.950000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.000000,1.000000,1.0,0.000000,0.0,1.0,2.010104e+10,246615.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.000000,4.000000,4.000000,4.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,0.875000,2021-04-29 06:00:00,240178.500000,201.537500,0.009721,0.027278,0.516660,0.535459,0.521746,0.708520,-0.016276,0.014324,0.011135,0.006116,0.235000,0.215215,6.214486e-02,0.023709,-0.019911,-0.059645,-0.133814,-0.016099,0.014140,0.010788,0.006222,0.228367,0.212511,2.133426e-02,0.025411,-0.017042,-0.059411,-0.131415,-0.015961,0.013841,0.010268,0.006200,0.220427,0.207139,1.013478e-02,0.024118,-0.016439,-0.059950,-0.132418,-0.016315,0.013707,0.010489,0.006252,0.213112,0.201653,4.941398e-03,0.023863,-0.017247,-0.057156,-0.130409,0.000000,120.000000,0.000000,150.000000,0.000000,180.000000,0.000000,210.000000,2021.000000,4.510860,1.609438,1.0,1.0

In [24]:
test.loc[ test["180CAR11"] >= 2]

Empty DataFrame
Columns: [index, Symbol, Company, AsOnDate, AsOnYear, ISIN, Person Code, Director Salutation, Director First Name, Director Middle Name, Director Surname, Date of Birth, Gender, Nationality, Member of Civil Services, Promoter Director (Yes/No), Position on Board, Independent (Yes/No), Education1, Education2, Education3, Education4, Education5, Education6, Education7, Education8, Education9, Education10, Skills/Competencies, Occupation, Cessation Reason, Other Directorship 1, Other Directorship 2, Other Directorship 3, Other Directorship 4, Other Directorship 5, Other Directorship 6, Other Directorship 7, Other Directorship 8, Other Directorship 9, Other Directorship 10, Other Directorship 11, Other Directorship 12, Other Directorship 13, Other Directorship 14, Other Directorship 15, Brief Profile, Tenure Valid till, Date of Demise, Indep, Appointment Date, Cessation Date, PrevLastServed, NextServed, CessationDummy, ReappointDummy, TermStartDummy, TermNumber, AppointDummy, CumOpBalUnc, CumOpBalIndep, CumOpBalNonIndep, CumCloBalUnc, CumCloBalIndep, CumCloBalNonIndep, TermOpBalUnc, TermOpBalIndep, TermOpBalNonIndep, TermOpBalTotal, TermCloBalUnc, TermCloBalIndep, TermCloBalNonIndep, TermCloBalTotal, CompOpBalUnc, CompOpBalIndep, CompOpBalNonIndep, CompOpBalTotal, CompCloBalUnc, CompCloBalIndep, CompCloBalNonIndep, CompCloBalTotal, CloBalTotalXP, AllPastDirect, CurrDirectA, CurrDirectAB, PastSiezedDirectA, PastSiezedDirectAB, CountOtherPastUnclearA, CountOtherPastIndepA, CountOtherPastNonIndepA, CompCountOtherPastTotalA, CountOtherPastUnclearAB, CountOtherPastIndepAB, CountOtherPastNonIndepAB, CompCountOtherPastTotalAB, CountCurrUnclearA, CountCurrIndepA, CountCurrNonIndepA, CompCountCurrTotalA, CountCurrUnclearAB, ...]
Index: []

## Panel A: Whole Sample

### Mean Difference

In [25]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    sample = psmSampleIndep.dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

120CAR3 :


T Statistic: 0.714465046576091  P Value: 0.47796349755139733
Treated Mean: 0.0008128487747067279  Control Mean: -0.0050723384351284  Diff: 0.0058851872098351285
Treated Median: -0.010853815251621338  Control Median: -0.00838220539344278  Diff: -0.0024716098581785573
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




120CAR5 :


T Statistic: 0.2349002878226609  P Value: 0.8152122161930472
Treated Mean: -0.047968923798573176  Control Mean: -0.050865574579479954  Diff: 0.0028966507809067774
Treated Median: -0.05189541851544589  Control Median: -0.05445832937658813  Diff: 0.0025629108611422355
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




120CAR7 :


T Statistic: -0.04623451566144807  P Value: 0.9632915949930251
Treated Mean: -0.10492600027212991  Control Mean: -0.10431791416962292  Diff: -0.0006080861025069828
Treated Median: -0.10015870060148074  Control Median: -0.10478584942433283  Diff: 0.00462714882285209
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




120CAR11 :


T Statistic: 1.0431860191483466  P Value: 0.3013760657230634
Treated Mean: -0.18509768377788544  Control Mean: -0.20394387830451513  Diff: 0.018846194526629695
Treated Median: -0.18714333005703315  Control Median: -0.19889250483520055  Diff: 0.011749174778167393
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




150CAR3 :


T Statistic: 0.680252611559497  P Value: 0.499193535384174
Treated Mean: 0.000672063978742147  Control Mean: -0.004797990080087276  Diff: 0.0054700540588294225
Treated Median: -0.01300173139770034  Control Median: -0.007751910194949047  Diff: -0.005249821202751293
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




150CAR5 :


T Statistic: 0.1956435712786419  P Value: 0.8456525873907843
Treated Mean: -0.04797723611964681  Control Mean: -0.05034515990190334  Diff: 0.0023679237822565244
Treated Median: -0.04942031473103427  Control Median: -0.053142575158994274  Diff: 0.0037222604279600058
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




150CAR7 :


T Statistic: -0.08151956603683268  P Value: 0.9353244188089425
Treated Mean: -0.10482438410469454  Control Mean: -0.10376860294754778  Diff: -0.0010557811571467596
Treated Median: -0.1096788487055117  Control Median: -0.10202643269861833  Diff: -0.00765241600689337
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




150CAR11 :


T Statistic: 0.9006930542118268  P Value: 0.3716499104368507
Treated Mean: -0.1861682724927829  Control Mean: -0.2023516818002554  Diff: 0.0161834093074725
Treated Median: -0.2040542789754996  Control Median: -0.1998206115452249  Diff: -0.004233667430274701
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




180CAR3 :


T Statistic: 0.7244143107527065  P Value: 0.4718497579047203
Treated Mean: 0.0009574209807704251  Control Mean: -0.004775672871129748  Diff: 0.0057330938519001735
Treated Median: -0.012376825383872248  Control Median: -0.009827450683522802  Diff: -0.002549374700349445
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




180CAR5 :


T Statistic: 0.24613774474323055  P Value: 0.806541420733701
Treated Mean: -0.047571953297257434  Control Mean: -0.050525794490305684  Diff: 0.0029538411930482497
Treated Median: -0.0513643698033798  Control Median: -0.055193985088161514  Diff: 0.0038296152847817136
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




180CAR7 :


T Statistic: 0.004714256528597939  P Value: 0.9962555828497871
Treated Mean: -0.1039955450221366  Control Mean: -0.10405657740186909  Diff: 6.10323797324841e-05
Treated Median: -0.10710927827290793  Control Median: -0.10176255085524541  Diff: -0.005346727417662525
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




180CAR11 :


T Statistic: 0.9569494198891838  P Value: 0.3427672911187851
Treated Mean: -0.18485828637681687  Control Mean: -0.20218946708752894  Diff: 0.017331180710712074
Treated Median: -0.20211572242187342  Control Median: -0.19601090747230648  Diff: -0.006104814949566939
Treated N: 43 ; Control N: 306
[treated unique =  43 ] [control unique =  306 ]




210CAR3 :


T Statistic: 0.4726487165005048  P Value: 0.6383206020824033
Treated Mean: -0.0006482417472691088  Control Mean: -0.004231027336440316  Diff: 0.003582785589171207
Treated Median: -0.010390301388900269  Control Median: -0.008327423715484977  Diff: -0.0020628776734152917
Treated N: 42 ; Control N: 306
[treated unique =  42 ] [control unique =  306 ]




210CAR5 :


T Statistic: -0.05716310735174195  P Value: 0.9546344568462666
Treated Mean: -0.05086042379723153  Control Mean: -0.050209881833785504  Diff: -0.0006505419634460288
Treated Median: -0.056378409921424094  Control Median: -0.05432033779479372  Diff: -0.002058072126630374
Treated N: 42 ; Control N: 306
[treated unique =  42 ] [control unique =  306 ]




210CAR7 :


T Statistic: -0.38257356251713875  P Value: 0.7034957194077196
Treated Mean: -0.10816891550157504  Control Mean: -0.10352672079944857  Diff: -0.00464219470212647
Treated Median: -0.10815297827274646  Control Median: -0.1004581482992645  Diff: -0.007694829973481962
Treated N: 42 ; Control N: 306
[treated unique =  42 ] [control unique =  306 ]




210CAR11 :


T Statistic: 0.6963751258650576  P Value: 0.4890856303383072
Treated Mean: -0.19061142067281153  Control Mean: -0.2024032202719768  Diff: 0.011791799599165265
Treated Median: -0.19570382158312039  Control Median: -0.2013750170492592  Diff: 0.005671195466138812
Treated N: 42 ; Control N: 306
[treated unique =  42 ] [control unique =  306 ]

In [26]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)

### One Sample T Test

In [27]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:

    sample1 = psmSampleIndep.loc[psmSampleIndep["IsIndep"] == 1].copy()
    print("All Independent Directors:")
    sample = sample1.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors:")
    sample = sample1.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors:")
    sample = sample2.dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

All Independent Directors:


120CAR3 :


T Statistic: -1.5855615702773922  P Value: 0.11374703037853341
Mean: -0.00434722940927479
Median: -0.009206811264595202
N: 349


Rookie Independent Directors:


120CAR3 :


T Statistic: 0.1056189870187427  P Value: 0.9163874950865101
Mean: 0.0008128487747067279
Median: -0.010853815251621338
N: 43


Non Rookie Independent Directors:


120CAR3 :


T Statistic: -1.727423571304705  P Value: 0.08510394782152088
Mean: -0.0050723384351284
Median: -0.00838220539344278
N: 306


All Independent Directors:


120CAR5 :


T Statistic: -13.615938576233605  P Value: 3.8588785221917465e-34
Mean: -0.05050868064372353
Median: -0.05430782118126312
N: 349


Rookie Independent Directors:


120CAR5 :


T Statistic: -4.101145799468911  P Value: 0.00018446924088054984
Mean: -0.047968923798573176
Median: -0.05189541851544589
N: 43


Non Rookie Independent Directors:


120CAR5 :


T Statistic: -13.071770503558566  P Value: 2.6178555170972504e-31
Mean: -0.05091817589940908
Median: -0.05445832937658813
N: 306


All Independent Directors:


120CAR7 :


T Statistic: -24.00896823597037  P Value: 8.041143162659223e-76
Mean: -0.10439283595302636
Median: -0.10464907321239925
N: 349


Rookie Independent Directors:


120CAR7 :


T Statistic: -5.652909661823504  P Value: 1.2521419279036048e-06
Mean: -0.09614326395536431
Median: -0.10015870060148074
N: 43


Non Rookie Independent Directors:


120CAR7 :


T Statistic: -22.46365438414088  P Value: 1.2718231813876518e-66
Mean: -0.10437760266969309
Median: -0.10478584942433283
N: 306


All Independent Directors:


120CAR11 :


T Statistic: -32.920615844181285  P Value: 6.366660971681254e-109
Mean: -0.20162185433705074
Median: -0.19849523125319
N: 349


Rookie Independent Directors:


120CAR11 :


T Statistic: -9.569602836215052  P Value: 4.103291762198119e-12
Mean: -0.18068214191831777
Median: -0.18714333005703315
N: 43


Non Rookie Independent Directors:


120CAR11 :


T Statistic: -31.1527740797838  P Value: 9.078846148578011e-97
Mean: -0.20407986694459113
Median: -0.19889250483520055
N: 306


All Independent Directors:

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

150CAR3 :


T Statistic: -1.5353916915791532  P Value: 0.12559628806922088
Mean: -0.004124029264816028
Median: -0.009601135127140545
N: 349


Rookie Independent Directors:


150CAR3 :


T Statistic: 0.08950855946063238  P Value: 0.9291032338398529
Mean: 0.000672063978742147
Median: -0.01300173139770034
N: 43


Non Rookie Independent Directors:


150CAR3 :


T Statistic: -1.6668796813174922  P Value: 0.09656482498944365
Mean: -0.004797990080087276
Median: -0.007751910194949047
N: 306


All Independent Directors:


150CAR5 :


T Statistic: -13.67982592382972  P Value: 2.1802426860323858e-34
Mean: -0.05005340998030726
Median: -0.053012940625008914
N: 349


Rookie Independent Directors:


150CAR5 :


T Statistic: -4.174090502426945  P Value: 0.0001472490110983894
Mean: -0.04794819275989428
Median: -0.04942031473103427
N: 43


Non Rookie Independent Directors:


150CAR5 :


T Statistic: -13.08638121243236  P Value: 2.3145686858538325e-31
Mean: -0.050378086843260464
Median: -0.053142575158994274
N: 306


All Independent Directors:


150CAR7 :


T Statistic: -24.05577332595178  P Value: 5.264137613863291e-76
Mean: -0.10389868486662315
Median: -0.1020973472242181
N: 349


Rookie Independent Directors:


150CAR7 :


T Statistic: -5.6071069400171245  P Value: 1.456476873993648e-06
Mean: -0.0956419809314343
Median: -0.1096788487055117
N: 43


Non Rookie Independent Directors:


150CAR7 :


T Statistic: -22.48451633381163  P Value: 1.0656452521772603e-66
Mean: -0.10384932932092518
Median: -0.10202643269861833
N: 306


All Independent Directors:


150CAR11 :


T Statistic: -33.08167127177807  P Value: 1.7556280501574562e-109
Mean: -0.20035773738701382
Median: -0.19999825807109736
N: 349


Rookie Independent Directors:


150CAR11 :


T Statistic: -9.544325213378867  P Value: 4.431178260718244e-12
Mean: -0.18132477831587007
Median: -0.2040542789754996
N: 43


Non Rookie Independent Directors:


150CAR11 :


T Statistic: -31.270335172950166  P Value: 3.781672312069382e-97
Mean: -0.20248711227788982
Median: -0.1998206115452249
N: 306


All Independent Directors:


180CAR3 :


T Statistic: -1.5189069070963774  P Value: 0.12969388629444603
Mean: -0.004069303141526003
Median: -0.010089014739904423
N: 349


Rookie Independent Directors:


180CAR3 :


T Statistic: 0.1298587986931024  P Value: 0.8972980903694319
Mean: 0.0009574209807704251
Median: -0.012376825383872248
N: 43


Non Rookie Independent Directors:


180CAR3 :


T Statistic: -1.6601457396843098  P Value: 0.0979128476287865
Mean: -0.004775672871129748
Median: -0.009827450683522802
N: 306


All Independent Directors:


180CAR5 :


T Statistic: -13.709768273011147  P Value: 1.667930788451737e-34
Mean: -0.05016185417139143
Median: -0.05495799773098434
N: 349


Rookie Independent Directors:


180CAR5 :


T Statistic: -4.182243184235144  P Value: 0.00014357492384615687
Mean: -0.04755525596028733
Median: -0.0513643698033798
N: 43

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

Non Rookie Independent Directors:


180CAR5 :


T Statistic: -13.117922434285159  P Value: 1.7740813975268901e-31
Mean: -0.05056395179284319
Median: -0.055193985088161514
N: 306


All Independent Directors:


180CAR7 :


T Statistic: -24.014234487679094  P Value: 7.666756872737055e-76
Mean: -0.10404905765307686
Median: -0.10204708585025246
N: 349


Rookie Independent Directors:


180CAR7 :


T Statistic: -5.596737721907461  P Value: 1.5071602919272952e-06
Mean: -0.09492213881488903
Median: -0.10710927827290793
N: 43


Non Rookie Independent Directors:


180CAR7 :


T Statistic: -22.4433081717587  P Value: 1.5113292114603649e-66
Mean: -0.10411624846243417
Median: -0.10176255085524541
N: 306


All Independent Directors:


180CAR11 :


T Statistic: -32.97217987216286  P Value: 4.2134055684913637e-109
Mean: -0.20005410671342977
Median: -0.19620205825635054
N: 349


Rookie Independent Directors:


180CAR11 :


T Statistic: -9.487674681904982  P Value: 5.265848915320099e-12
Mean: -0.18031612888974155
Median: -0.20211572242187342
N: 43


Non Rookie Independent Directors:


180CAR11 :


T Statistic: -31.260481518523875  P Value: 4.0694400153810853e-97
Mean: -0.20236502732699946
Median: -0.19601090747230648
N: 306


All Independent Directors:


210CAR3 :


T Statistic: -1.4375829231262682  P Value: 0.1514535756039123
Mean: -0.003798622179126549
Median: -0.008871169164034107
N: 348


Rookie Independent Directors:


210CAR3 :


T Statistic: -0.09228496915438934  P Value: 0.9269210862396562
Mean: -0.0006482417472691088
Median: -0.010390301388900269
N: 42


Non Rookie Independent Directors:


210CAR3 :


T Statistic: -1.4849450758146996  P Value: 0.1385911564706697
Mean: -0.004231027336440316
Median: -0.008327423715484977
N: 306


All Independent Directors:


210CAR5 :


T Statistic: -13.984691040909413  P Value: 1.4781688213373825e-35
Mean: -0.05028839551902899
Median: -0.05432033779479372
N: 348


Rookie Independent Directors:


210CAR5 :


T Statistic: -4.7447382412633905  P Value: 2.5394407507837185e-05
Mean: -0.05086042379723153
Median: -0.056378409921424094
N: 42


Non Rookie Independent Directors:


210CAR5 :


T Statistic: -13.183157870796183  P Value: 1.0229675837409335e-31
Mean: -0.050259330911923014
Median: -0.05432033779479372
N: 306


All Independent Directors:


210CAR7 :


T Statistic: -24.51549049575723  P Value: 9.997532003314347e-78
Mean: -0.10408698567729141
Median: -0.10196523507039207
N: 348


Rookie Independent Directors:


210CAR7 :


T Statistic: -8.40846532119041  P Value: 1.8337104799494282e-10
Mean: -0.10575367372083051
Median: -0.10815297827274646
N: 42


Non Rookie Independent Directors:


210CAR7 :


T Statistic: -22.675450080732663  P Value: 2.1155740286338095e-67
Mean: -0.10360525148981746
Median: -0.1004581482992645
N: 306


All Independent Directors:


210CAR11 :


T Statistic: -33.721846452871354  P Value: 1.527646301513865e-111
Mean: -0.20098007204449134
Median: -0.2013750170492592
N: 348


Rookie Independent Directors:


210CAR11 :


T Statistic: -11.403872352810131  P Value: 2.7065175750457767e-14
Mean: -0.1887962041023854
Median: -0.19570382158312039
N: 42


Non Rookie Independent Directors:


210CAR11 :


T Statistic: -31.548599115335723  P Value: 4.790816330822035e-98
Mean: -0.2024961347872032
Median: -0.2013750170492592
N: 306

/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
/home/leshleon/projects/Rookie Directors Project/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:867: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

## Panel B: Unique skills dummy

### Mean Difference: RID vs NRID

In [ ]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    print("No unique skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

### Mean Difference: within RID/NRID: WIP

In [ ]:
# carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
#           "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
#           "180CAR3", "180CAR5", "180CAR7", "180CAR11",
#           "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

# exog_var = None
# depVar = None
# controlVars = None

# for car in carCol:
#     print("No unique skills:")
#     sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
#     MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

#     print("At least one unique skill:")
#     sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
#     MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

### One Sample T Test

In [ ]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

for car in carCol:
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors\nNo unique skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = sample1.loc[sample1["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors\nNo unique skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] == 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("At least one unique skill:")
    sample = sample2.loc[sample2["NumSkills_gai"] != 0].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

In [ ]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)

## Panel C: Number of Skills

### Mean Difference

In [ ]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

num_skills_median = psmSampleIndep.drop_duplicates(subset = ["AsOnDate", "Person Code"])["NumSkills_gai"].median()
for car in carCol:
    print("Less than median no. skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = psmSampleIndep.loc[psmSampleIndep["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    MeanDiffTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

### One Sample T Test

In [ ]:
carCol = ["120CAR3", "120CAR5", "120CAR7", "120CAR11", 
          "150CAR3", "150CAR5", "150CAR7", "150CAR11", 
          "180CAR3", "180CAR5", "180CAR7", "180CAR11",
          "210CAR3", "210CAR5", "210CAR7", "210CAR11"]

exog_var = None
depVar = None
controlVars = None

num_skills_median = psmSampleIndep.drop_duplicates(subset = ["AsOnDate", "Person Code"])["NumSkills_gai"].median()
for car in carCol:
    sample1 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 1].copy()
    print("Rookie Independent Directors\nLess than median no. skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = sample1.loc[sample1["NumSkills_gai"] < num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    sample2 = psmSampleIndep.loc[psmSampleIndep["IsRookieIndep"] == 0].copy()
    print("Non Rookie Independent Directors\nLess than median no. skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

    print("Greater than median no. skills:")
    sample = sample2.loc[sample2["NumSkills_gai"] > num_skills_median].dropna(subset = car).reset_index(drop=True).copy()
    OneSampleTtest(sample, "IsRookieIndep", exog_var, car, depVar, dirFirm)

In [ ]:
### PSM without replacement
# PsmNonReplac(psmSampleIndep, "RookieIndepAppointDummy", controlVars, "ln_TobinQ_longborrowincl2", dirFirm)